TRADE_SKILLS_DATA["skills"]["Mining"] = {
    {
        ["id"] = 2657,
        ["min_skill"] = 1,
        ["name"] = {
            ["Chinese"] = "熔炼铜锭",
            ["English"] = "Smelt Copper",
            ["French"] = "Fonte du cuivre",
            ["German"] = "Kupfer verhütten",
            ["Korean"] = "구리 제련",
            ["Mexican"] = "Fundir cobre",
            ["Portuguese"] = "Fundir Cobre",
            ["Russian"] = "Выплавка меди",
            ["Spanish"] = "Cobre fundido",
            ["Taiwanese"] = "熔煉銅錠",
        },
        ["phase"] = 1,
        ["special_action"] = "auto learned",
    },
    {
        ["id"] = 2658,
        ["min_skill"] = 75,
        ["name"] = {
            ["Chinese"] = "熔炼银锭",
            ["English"] = "Smelt Silver",
            ["French"] = "Fonte de l'argent",
            ["German"] = "Silber verhütten",
            ["Korean"] = "은 제련",
            ["Mexican"] = "Fundir plata",
            ["Portuguese"] = "Fundir Prata",
            ["Russian"] = "Выплавка серебра",
            ["Spanish"] = "Palata fundida",
            ["Taiwanese"] = "熔煉銀錠",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 200,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 2659,
        ["min_skill"] = 65,
        ["name"] = {
            ["Chinese"] = "熔炼青铜",
            ["English"] = "Smelt Bronze",
            ["French"] = "Fonte du bronze",
            ["German"] = "Bronze verhütten",
            ["Korean"] = "청동 제련",
            ["Mexican"] = "Fundir bronce",
            ["Portuguese"] = "Fundir Bronze",
            ["Russian"] = "Выплавка бронзы",
            ["Spanish"] = "Bronce fundido",
            ["Taiwanese"] = "熔煉青銅",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 200,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 3304,
        ["min_skill"] = 65,
        ["name"] = {
            ["Chinese"] = "熔炼锡锭",
            ["English"] = "Smelt Tin",
            ["French"] = "Fonte de l'étain",
            ["German"] = "Zinn verhütten",
            ["Korean"] = "주석 제련",
            ["Mexican"] = "Fundir estaño",
            ["Portuguese"] = "Fundir Estanho",
            ["Russian"] = "Выплавка олова",
            ["Spanish"] = "Chapa fundida",
            ["Taiwanese"] = "熔煉錫錠",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 50,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 3307,
        ["min_skill"] = 125,
        ["name"] = {
            ["Chinese"] = "熔炼铁锭",
            ["English"] = "Smelt Iron",
            ["French"] = "Fonte du fer",
            ["German"] = "Eisen verhütten",
            ["Korean"] = "철 제련",
            ["Mexican"] = "Fundir hierro",
            ["Portuguese"] = "Fundir Ferro",
            ["Russian"] = "Выплавка железа",
            ["Spanish"] = "Hierro fundido",
            ["Taiwanese"] = "熔煉鐵錠",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 500,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 3308,
        ["min_skill"] = 155,
        ["name"] = {
            ["Chinese"] = "熔炼金锭",
            ["English"] = "Smelt Gold",
            ["French"] = "Fonte de l'or",
            ["German"] = "Gold verhütten",
            ["Korean"] = "금 제련",
            ["Mexican"] = "Fundir oro",
            ["Portuguese"] = "Fundir Ouro",
            ["Russian"] = "Выплавка золота",
            ["Spanish"] = "Oro fundido",
            ["Taiwanese"] = "熔煉金錠",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 2500,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 3569,
        ["min_skill"] = 165,
        ["name"] = {
            ["Chinese"] = "熔炼钢锭",
            ["English"] = "Smelt Steel",
            ["French"] = "Fonte de l'acier",
            ["German"] = "Stahl verhütten",
            ["Korean"] = "강철 제련",
            ["Mexican"] = "Fundir acero",
            ["Portuguese"] = "Fundir Aço",
            ["Russian"] = "Выплавка стали",
            ["Spanish"] = "Acero fundido",
            ["Taiwanese"] = "熔煉鋼錠",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 2500,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 10097,
        ["min_skill"] = 175,
        ["name"] = {
            ["Chinese"] = "熔炼秘银",
            ["English"] = "Smelt Mithril",
            ["French"] = "Fonte du mithril",
            ["German"] = "Mithril verhütten",
            ["Korean"] = "미스릴 제련",
            ["Mexican"] = "Fundir mitril",
            ["Portuguese"] = "Fundir Mithril",
            ["Russian"] = "Выплавка мифрила",
            ["Spanish"] = "Mitril fundido",
            ["Taiwanese"] = "熔煉祕銀",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 5000,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 10098,
        ["min_skill"] = 230,
        ["name"] = {
            ["Chinese"] = "熔炼真银",
            ["English"] = "Smelt Truesilver",
            ["French"] = "Fonte du vrai-argent",
            ["German"] = "Echtsilber verhütten",
            ["Korean"] = "진은 제련",
            ["Mexican"] = "Fundir veraplata",
            ["Portuguese"] = "Fundir Veraprata",
            ["Russian"] = "Выплавка истинного серебра",
            ["Spanish"] = "Veraplata fundida",
            ["Taiwanese"] = "熔煉真銀",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 10000,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 14891,
        ["min_skill"] = 230,
        ["name"] = {
            ["Chinese"] = "熔炼黑铁",
            ["English"] = "Smelt Dark Iron",
            ["French"] = "Fonte du sombrefer",
            ["German"] = "Dunkeleisen verhütten",
            ["Korean"] = "검은무쇠 제련",
            ["Mexican"] = "Fundir hierro negro",
            ["Portuguese"] = "Fundir Ferro Negro",
            ["Russian"] = "Выплавка черного железа",
            ["Spanish"] = "Hierro negro fundido",
            ["Taiwanese"] = "熔煉黑鐵",
        },
        ["phase"] = 1,
        ["quests"] = {
            4083,
        },
        ["special_action"] = "talk to npc after quest",
    },
    {
        ["id"] = 16153,
        ["min_skill"] = 250,
        ["name"] = {
            ["Chinese"] = "熔炼瑟银",
            ["English"] = "Smelt Thorium",
            ["French"] = "Fonte du thorium",
            ["German"] = "Thorium verhütten",
            ["Korean"] = "토륨 제련",
            ["Mexican"] = "Fundir torio",
            ["Portuguese"] = "Fundir Tório",
            ["Russian"] = "Выплавка тория",
            ["Spanish"] = "Torio fundido",
            ["Taiwanese"] = "熔煉瑟銀",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 20000,
            ["sources"] = {
                1681,
                1701,
                3001,
                3137,
                3175,
                3357,
                3555,
                4254,
                4598,
                5392,
                5513,
                6297,
                8128,
            },
        },
    },
    {
        ["id"] = 22967,
        ["min_skill"] = 300,
        ["name"] = {
            ["Chinese"] = "熔炼源质",
            ["English"] = "Smelt Elementium",
            ["French"] = "Fonte de l'élémentium",
            ["German"] = "Elementium verhütten",
            ["Korean"] = "엘레멘티움 제련",
            ["Mexican"] = "Fundir elementium",
            ["Portuguese"] = "Fundir Elemêntio",
            ["Russian"] = "Выплавка элементия",
            ["Spanish"] = "Elementium fundido",
            ["Taiwanese"] = "熔煉源質",
        },
        ["phase"] = 3,
        ["special_action"] = "talk to Kirix",
        ["trainers"] = {
            ["price"] = 0,
            ["sources"] = {
                14401,
            },
        },
    },
}
