TRADE_SKILLS_DATA["levels"]["Blacksmithing"] = {
    {
        ["id"] = 2018,
        ["max_skill"] = 75,
        ["min_skill"] = 0,
        ["min_xp_level"] = 5,
        ["name"] = {
            ["Chinese"] = "锻造 (初级)",
            ["English"] = "Blacksmithing (Apprentice)",
            ["French"] = "Forge (Apprenti)",
            ["German"] = "Schmiedekunst (Lehrling)",
            ["Korean"] = "대장기술 (초급)",
            ["Mexican"] = "Herrería (Aprendiz)",
            ["Portuguese"] = "Ferraria (Aprendiz)",
            ["Russian"] = "Кузнечное дело (Ученик)",
            ["Spanish"] = "Herrería (Aprendiz)",
            ["Taiwanese"] = "鍛造 (學徒)",
        },
        ["phase"] = 1,
        ["rank"] = 1,
        ["trainers"] = {
            ["price"] = 10,
            ["sources"] = {
                514,
                957,
                1241,
                3174,
                3557,
                4605,
                6299,
                10266,
                10277,
                10278,
            },
        },
    },
    {
        ["id"] = 3100,
        ["max_skill"] = 150,
        ["min_skill"] = 50,
        ["min_xp_level"] = 10,
        ["name"] = {
            ["Chinese"] = "锻造 (中级)",
            ["English"] = "Blacksmithing (Journeyman)",
            ["French"] = "Forge (Compagnon)",
            ["German"] = "Schmiedekunst (Geselle)",
            ["Korean"] = "대장기술 (수습)",
            ["Mexican"] = "Herrería (Oficial)",
            ["Portuguese"] = "Ferraria (Profissional)",
            ["Russian"] = "Кузнечное дело (Подмастерье)",
            ["Spanish"] = "Herrería (Oficial)",
            ["Taiwanese"] = "鍛造 (熟練工)",
        },
        ["phase"] = 1,
        ["rank"] = 2,
        ["trainers"] = {
            ["price"] = 500,
            ["sources"] = {
                1383,
                2998,
                3136,
                3478,
                4596,
                5511,
                10276,
            },
        },
    },
    {
        ["id"] = 3538,
        ["max_skill"] = 225,
        ["min_skill"] = 125,
        ["min_xp_level"] = 20,
        ["name"] = {
            ["Chinese"] = "锻造 (高级)",
            ["English"] = "Blacksmithing (Expert)",
            ["French"] = "Forge (Expert)",
            ["German"] = "Schmiedekunst (Experte)",
            ["Korean"] = "대장기술 (숙련)",
            ["Mexican"] = "Herrería (Experto)",
            ["Portuguese"] = "Ferraria (Perito)",
            ["Russian"] = "Кузнечное дело (Умелец)",
            ["Spanish"] = "Herrería (Experto)",
            ["Taiwanese"] = "鍛造 (專家)",
        },
        ["phase"] = 1,
        ["rank"] = 3,
        ["trainers"] = {
            ["price"] = 5000,
            ["sources"] = {
                3355,
                4258,
            },
        },
    },
    {
        ["id"] = 9785,
        ["max_skill"] = 300,
        ["min_skill"] = 200,
        ["min_xp_level"] = 35,
        ["name"] = {
            ["Chinese"] = "锻造 (大师级)",
            ["English"] = "Blacksmithing (Artisan)",
            ["French"] = "Forge (Artisan)",
            ["German"] = "Schmiedekunst (Fachmann)",
            ["Korean"] = "대장기술 (전문)",
            ["Mexican"] = "Herrería (Artesano)",
            ["Portuguese"] = "Ferraria (Artifice)",
            ["Russian"] = "Кузнечное дело (Мастеровой)",
            ["Spanish"] = "Herrería (Artesano)",
            ["Taiwanese"] = "鍛造 (大工匠)",
        },
        ["phase"] = 1,
        ["rank"] = 4,
        ["trainers"] = {
            ["price"] = 50000,
            ["sources"] = {
                2836,
            },
        },
    },
}
