TRADE_SKILLS_DATA["specialisations"]["Blacksmithing"] = {
    {
        ["id"] = 9787,
        ["min_skill"] = 200,
        ["name"] = {
            ["Chinese"] = "武器锻造师",
            ["English"] = "Weaponsmith",
            ["French"] = "Fabricant d'armes",
            ["German"] = "Waffenschmied",
            ["Korean"] = "무기제작",
            ["Mexican"] = "Forjador de armas",
            ["Portuguese"] = "Forja de Armas",
            ["Russian"] = "Оружейник",
            ["Spanish"] = "Forjador de armas",
            ["Taiwanese"] = "護甲鍛造師",
        },
        ["phase"] = 1,
        ["quests"] = {
            5284,
        },
    },
    {
        ["id"] = 9788,
        ["min_skill"] = 200,
        ["name"] = {
            ["Chinese"] = "护甲锻造师",
            ["English"] = "Armorsmith",
            ["French"] = "Fabricant d'armures",
            ["German"] = "Rüstungsschmied",
            ["Korean"] = "방어구제작",
            ["Mexican"] = "Forjador de armaduras",
            ["Portuguese"] = "Ferreiro de Armaduras",
            ["Russian"] = "Бронник",
            ["Spanish"] = "Forjador de armaduras",
            ["Taiwanese"] = "武器鑄造",
        },
        ["phase"] = 1,
        ["quests"] = {
            5283,
        },
    },
    {
        ["id"] = 17039,
        ["min_skill"] = 250,
        ["name"] = {
            ["Chinese"] = "铸剑大师",
            ["English"] = "Master Swordsmith",
            ["French"] = "Maître Fabricant d'épées",
            ["German"] = "Schwertschmiedemeister",
            ["Korean"] = "검 제작의 대가",
            ["Mexican"] = "Maestro forjador de espadas",
            ["Portuguese"] = "Mestre Armeiro (Espada)",
            ["Russian"] = "Мастер ковки клинков",
            ["Spanish"] = "Maestro invocador",
            ["Taiwanese"] = "鑄劍大師",
        },
        ["phase"] = 1,
        ["quests"] = {
            5307,
        },
        ["specialisation"] = 9787,
    },
    {
        ["id"] = 17040,
        ["min_skill"] = 250,
        ["name"] = {
            ["Chinese"] = "铸锤大师",
            ["English"] = "Master Hammersmith",
            ["French"] = "Maître Fabricant de marteaux",
            ["German"] = "Hammerschmiedemeister",
            ["Korean"] = "망치 제작의 대가",
            ["Mexican"] = "Maestro forjador de martillos",
            ["Portuguese"] = "Mestre Armeiro (Martelo)",
            ["Russian"] = "Мастер школы Молота",
            ["Spanish"] = "Maestro forjador de martillos",
            ["Taiwanese"] = "鑄錘大師",
        },
        ["phase"] = 1,
        ["quests"] = {
            5305,
        },
        ["specialisation"] = 9787,
    },
    {
        ["id"] = 17041,
        ["min_skill"] = 250,
        ["name"] = {
            ["Chinese"] = "铸斧大师",
            ["English"] = "Master Axesmith",
            ["French"] = "Maître fabricant de haches",
            ["German"] = "Axtschmiedemeister",
            ["Korean"] = "도끼 제작의 대가",
            ["Mexican"] = "Maestro forjador de hachas",
            ["Portuguese"] = "Mestre Armeiro (Machado)",
            ["Russian"] = "Мастер школы топора",
            ["Spanish"] = "Maestro forjador de hachas",
            ["Taiwanese"] = "鑄斧大師",
        },
        ["phase"] = 1,
        ["quests"] = {
            5306,
        },
        ["specialisation"] = 9787,
    },
}
