TRADE_SKILLS_DATA["items"]["Alchemy"] = {
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 21,
                ["min_xp_level"] = 6,
            },
        },
        ["id"] = 2553,
        ["name"] = {
            ["Chinese"] = "配方：初级敏捷药剂",
            ["English"] = "Recipe: Elixir of Minor Agility",
            ["French"] = "Recette : Elixir d'Agilité mineure",
            ["German"] = "Rezept: Elixier der schwachen Beweglichkeit",
            ["Korean"] = "조제법: 최하급 민첩의 비약",
            ["Mexican"] = "Receta: elixir de agilidad menor",
            ["Portuguese"] = "Receita: Elixir de Agilidade Menor",
            ["Russian"] = "Рецепт: слабый эликсир ловкости",
            ["Spanish"] = "Receta: elixir de agilidad menor",
            ["Taiwanese"] = "配方：初級敏捷藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 21,
                ["min_xp_level"] = 6,
            },
        },
        ["id"] = 2555,
        ["name"] = {
            ["Chinese"] = "配方：迅捷药水",
            ["English"] = "Recipe: Swiftness Potion",
            ["French"] = "Recette : Potion de Rapidité",
            ["German"] = "Rezept: Hurtigkeitstrank",
            ["Korean"] = "조제법: 신속의 물약",
            ["Mexican"] = "Receta: poción de presteza",
            ["Portuguese"] = "Receita: Poção de Rapidez",
            ["Russian"] = "Рецепт: зелье скорости",
            ["Spanish"] = "Receta: poción de velocidad",
            ["Taiwanese"] = "配方：迅捷藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 30,
                ["min_xp_level"] = 15,
            },
        },
        ["id"] = 3393,
        ["name"] = {
            ["Chinese"] = "配方：初级抗魔药水",
            ["English"] = "Recipe: Minor Magic Resistance Potion",
            ["French"] = "Recette : Potion de résistance à la magie mineure",
            ["German"] = "Rezept: Schwacher Magiewiderstandstrank",
            ["Korean"] = "조제법: 최하급 마법 저항 물약",
            ["Mexican"] = "Receta: poción de resistencia a la magia menor",
            ["Portuguese"] = "Receita: Poção Menor de Resistência à Magia",
            ["Russian"] = "Рецепт: cлабый эликсир сопротивления магии",
            ["Spanish"] = "Receta: poción de resistencia a la magia menor",
            ["Taiwanese"] = "配方：初級抗魔藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 30,
                ["min_xp_level"] = 15,
            },
        },
        ["id"] = 3394,
        ["name"] = {
            ["Chinese"] = "配方：抗毒药剂",
            ["English"] = "Recipe: Elixir of Poison Resistance",
            ["French"] = "Recette : Elixir de résistance au poison",
            ["German"] = "Rezept: Elixier des Giftwiderstands",
            ["Korean"] = "조제법: 독 저항의 비약",
            ["Mexican"] = "Receta: Elixir de resistencia al veneno",
            ["Portuguese"] = "Receita: Elixir de Resistência a Veneno",
            ["Russian"] = "Рецепт: эликсир сопротивления яду",
            ["Spanish"] = "Receta: elixir de resistencia al envenenamiento",
            ["Taiwanese"] = "配方：抗毒藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "common",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 55,
                ["min_xp_level"] = 40,
            },
        },
        ["id"] = 3395,
        ["name"] = {
            ["Chinese"] = "配方：有限无敌药水",
            ["English"] = "Recipe: Limited Invulnerability Potion",
            ["French"] = "Recette : Potion d'invulnérabilité limitée",
            ["German"] = "Rezept: Begrenzter Unverwundbarkeitstrank",
            ["Korean"] = "조제법: 제한된 무적 물약",
            ["Mexican"] = "Receta: poción de invulnerabilidad limitada",
            ["Portuguese"] = "Receita: Poção de Invulnerabilidade Limitada",
            ["Russian"] = "Рецепт: слабое зелье неуязвимости",
            ["Spanish"] = "Receta: poción de invulnerabilidad limitada",
            ["Taiwanese"] = "配方：有限無敵藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 35,
                ["min_xp_level"] = 20,
            },
        },
        ["id"] = 3396,
        ["name"] = {
            ["Chinese"] = "配方：次级敏捷药剂",
            ["English"] = "Recipe: Elixir of Lesser Agility",
            ["French"] = "Recette : Elixir d'Agilité inférieur",
            ["German"] = "Rezept: Elixier der geringen Beweglichkeit",
            ["Korean"] = "조제법: 하급 민첩의 비약",
            ["Mexican"] = "Receta: elixir de agilidad inferior",
            ["Portuguese"] = "Receita: Elixir de Agilidade Inferior",
            ["Russian"] = "Рецепт: эликсир ловкости I ступени",
            ["Spanish"] = "Receta: elixir de agilidad inferior",
            ["Taiwanese"] = "配方：次級敏捷藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "common",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 41,
                ["min_xp_level"] = 10,
            },
        },
        ["id"] = 3830,
        ["name"] = {
            ["Chinese"] = "配方：强力坚韧药剂",
            ["English"] = "Recipe: Elixir of Fortitude",
            ["French"] = "Recette : Elixir de Robustesse",
            ["German"] = "Rezept: Elixier der Seelenstärke",
            ["Korean"] = "조제법: 인내의 비약",
            ["Mexican"] = "Receta: elixir de entereza",
            ["Portuguese"] = "Receita: Elixir de Fortitude",
            ["Russian"] = "Рецепт: эликсир стойкости",
            ["Spanish"] = "Receta: elixir de entereza",
            ["Taiwanese"] = "配方：堅韌藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "common",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 45,
                ["min_xp_level"] = 30,
            },
        },
        ["id"] = 3831,
        ["name"] = {
            ["Chinese"] = "配方：超强巨魔之血药水",
            ["English"] = "Recipe: Mighty Troll's Blood Potion",
            ["French"] = "Recette : Potion de sang de troll hargneux",
            ["German"] = "Rezept: Mächtiger Trollbluttrank",
            ["Korean"] = "조제법: 강력한 재생의 물약",
            ["Mexican"] = "Receta: Poción de sangre de trol poderosa",
            ["Portuguese"] = "Receita: Poção Potente de Sangue de Troll",
            ["Russian"] = "Рецепт: мощное зелье тролльей крови",
            ["Spanish"] = "Receta: poción de sangre de trol poderosa",
            ["Taiwanese"] = "配方：超強食人妖之血藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 45,
                ["min_xp_level"] = 30,
            },
        },
        ["id"] = 3832,
        ["name"] = {
            ["Chinese"] = "配方：侦测次级隐形药剂",
            ["English"] = "Recipe: Elixir of Detect Lesser Invisibility",
            ["French"] = "Recette : Elixir de Détection d'Invisibilité inférieure",
            ["German"] = "Rezept: Elixier der Entdeckung geringer Unsichtbarkeit",
            ["Korean"] = "조제법: 하급 투명체 감지의 비약",
            ["Mexican"] = "Receta: elixir de detección de invisibilidad inferior",
            ["Portuguese"] = "Receita: Elixir de Detectar Invisibilidade Inferior",
            ["Russian"] = "Рецепт: эликсир обнаружения простой невидимости",
            ["Spanish"] = "Receta: elixir de detección de invisibilidad inferior",
            ["Taiwanese"] = "配方：偵測次級隱形藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 4597,
        ["name"] = {
            ["Chinese"] = "配方：褪色的治疗药水",
            ["English"] = "Recipe: Discolored Healing Potion",
            ["French"] = "Recette : Potion de soins décolorée",
            ["German"] = "Rezept: Verfärbter Heiltrank",
            ["Korean"] = "조제법: 빛바랜 치유 물약",
            ["Mexican"] = "Receta: poción de sanación descolorida",
            ["Portuguese"] = "Receita: Poção Descolorida de Cura",
            ["Russian"] = "Рецепт: бесцветное лечебное зелье",
            ["Spanish"] = "Receta: poción curativa descolorida",
            ["Taiwanese"] = "配方：透明治療藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            429,
        },
    },
    {
        ["id"] = 4624,
        ["name"] = {
            ["Chinese"] = "配方：次级石盾药水",
            ["English"] = "Recipe: Lesser Stoneshield Potion",
            ["French"] = "Recette : Potion de Bouclier de pierre inférieure",
            ["German"] = "Rezept: Geringer Steinschildtrank",
            ["Korean"] = "조제법: 하급 돌방패 물약",
            ["Mexican"] = "Receta: poción de escudo de piedra inferior",
            ["Portuguese"] = "Receita: Poção de Escudopétreo Inferior",
            ["Russian"] = "Рецепт: простое зелье каменного щита",
            ["Spanish"] = "Receta: poción de escudo de piedra inferior",
            ["Taiwanese"] = "配方：次級石盾藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["quests"] = {
            715,
        },
    },
    {
        ["id"] = 5640,
        ["name"] = {
            ["Chinese"] = "配方：怒气药水",
            ["English"] = "Recipe: Rage Potion",
            ["French"] = "Recette : Potion de rage",
            ["German"] = "Rezept: Wuttrank",
            ["Korean"] = "조제법: 분노의 물약",
            ["Mexican"] = "Receta: poción de ira",
            ["Portuguese"] = "Receita: Poção de Raiva",
            ["Russian"] = "Рецепт: зелье ярости",
            ["Spanish"] = "Receta: poción de ira",
            ["Taiwanese"] = "配方：怒氣藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 100,
            ["sources"] = {
                1669,
                1685,
                3335,
                3499,
            },
        },
    },
    {
        ["id"] = 5642,
        ["name"] = {
            ["Chinese"] = "配方：自由行动药剂",
            ["English"] = "Recipe: Free Action Potion",
            ["French"] = "Recette : Potion de libre action",
            ["German"] = "Rezept: Trank der freien Aktion",
            ["Korean"] = "조제법: 자유 의지의 물약",
            ["Mexican"] = "Receta: poción de acción libre",
            ["Portuguese"] = "Receita: Poção de Ação Desimpedida",
            ["Russian"] = "Рецепт: зелье свободы действий",
            ["Spanish"] = "Receta: poción de acción libre",
            ["Taiwanese"] = "配方：自由行動藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1800,
            ["sources"] = {
                3348,
                4226,
                5178,
            },
        },
    },
    {
        ["id"] = 5643,
        ["name"] = {
            ["Chinese"] = "配方：暴怒药水",
            ["English"] = "Recipe: Great Rage Potion",
            ["French"] = "Recette  : Potion de Grande rage",
            ["German"] = "Rezept: Großer Wuttrank",
            ["Korean"] = "조제법: 상급 분노의 물약",
            ["Mexican"] = "Receta: poción de gran ira",
            ["Portuguese"] = "Receita: Poção Grandiosa de Raiva",
            ["Russian"] = "Рецепт: сильнодействующее зелье ярости",
            ["Spanish"] = "Receta: gran poción de ira",
            ["Taiwanese"] = "配方：暴怒藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 2000,
            ["sources"] = {
                3335,
                4226,
            },
        },
    },
    {
        ["id"] = 6053,
        ["name"] = {
            ["Chinese"] = "配方：神圣防护药水",
            ["English"] = "Recipe: Holy Protection Potion",
            ["French"] = "Recette : Potion de protection contre le Sacré",
            ["German"] = "Rezept: Heiligschutztrank",
            ["Korean"] = "조제법: 신성 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra lo Sagrado",
            ["Portuguese"] = "Receita: Poção de Proteção contra o Sagrado",
            ["Russian"] = "Рецепт: зелье священной защиты",
            ["Spanish"] = "Receta: poción de protección Sagrada",
            ["Taiwanese"] = "配方：神聖防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 800,
            ["sources"] = {
                1685,
                3134,
                3490,
            },
        },
    },
    {
        ["id"] = 6054,
        ["name"] = {
            ["Chinese"] = "配方：暗影防护药水",
            ["English"] = "Recipe: Shadow Protection Potion",
            ["French"] = "Recette : Potion de protection contre l'Ombre",
            ["German"] = "Rezept: Schattenschutztrank",
            ["Korean"] = "조제법: 암흑 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra las Sombras",
            ["Portuguese"] = "Receita: Poção de Proteção contra a Sombra",
            ["Russian"] = "Рецепт: зелье защиты от темной магии",
            ["Spanish"] = "Receta: poción de protección de las Sombras",
            ["Taiwanese"] = "配方：暗影防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 900,
            ["sources"] = {
                2393,
                3956,
            },
        },
    },
    {
        ["id"] = 6055,
        ["name"] = {
            ["Chinese"] = "配方：火焰防护药水",
            ["English"] = "Recipe: Fire Protection Potion",
            ["French"] = "Recette : Potion de protection contre le Feu",
            ["German"] = "Rezept: Feuerschutztrank",
            ["Korean"] = "조제법: 화염 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra el Fuego",
            ["Portuguese"] = "Receita: Poção de Proteção contra o Fogo",
            ["Russian"] = "Рецепт: зелье защиты от огня",
            ["Spanish"] = "Receta: poción de protección de Fuego",
            ["Taiwanese"] = "配方：火焰防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1500,
            ["sources"] = {
                2380,
                4083,
            },
        },
    },
    {
        ["id"] = 6056,
        ["name"] = {
            ["Chinese"] = "配方：冰霜防护药水",
            ["English"] = "Recipe: Frost Protection Potion",
            ["French"] = "Recette : Potion de protection contre le Givre",
            ["German"] = "Rezept: Frostschutztrank",
            ["Korean"] = "조제법: 냉기 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra la Escarcha",
            ["Portuguese"] = "Receita: Poção de Proteção contra o Gelo",
            ["Russian"] = "Рецепт: зелье защиты от магии льда",
            ["Spanish"] = "Receta: poción de Protección de Escarcha",
            ["Taiwanese"] = "配方：冰霜防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 2000,
            ["sources"] = {
                2812,
                2848,
            },
        },
    },
    {
        ["id"] = 6057,
        ["name"] = {
            ["Chinese"] = "配方：自然防护药水",
            ["English"] = "Recipe: Nature Protection Potion",
            ["French"] = "Recette : Potion de protection contre la Nature",
            ["German"] = "Rezept: Naturschutztrank",
            ["Korean"] = "조제법: 자연 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra la Naturaleza",
            ["Portuguese"] = "Receita: Poção de Proteção contra a Natureza",
            ["Russian"] = "Рецепт: зелье защиты от сил природы",
            ["Spanish"] = "Receta: poción de protección de Naturaleza",
            ["Taiwanese"] = "配方：自然防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 2000,
            ["sources"] = {
                2848,
                5594,
                8157,
                8158,
            },
        },
    },
    {
        ["id"] = 6068,
        ["name"] = {
            ["Chinese"] = "配方：暗影之油",
            ["English"] = "Recipe: Shadow Oil",
            ["French"] = "Recette : Huile des ténèbres",
            ["German"] = "Rezept: Schattenöl",
            ["Korean"] = "조제법: 암흑 오일",
            ["Mexican"] = "Receta: aceite de las Sombras",
            ["Portuguese"] = "Receita: Óleo de Sombra",
            ["Russian"] = "Рецепт: масло Тьмы",
            ["Spanish"] = "Receta: aceite de las Sombras",
            ["Taiwanese"] = "配方：暗影之油",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1500,
            ["sources"] = {
                2481,
                4878,
            },
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 35,
                ["min_xp_level"] = 20,
            },
        },
        ["id"] = 6211,
        ["name"] = {
            ["Chinese"] = "配方：食人魔力量药剂",
            ["English"] = "Recipe: Elixir of Ogre's Strength",
            ["French"] = "Recette : Elixir de Force d'ogre",
            ["German"] = "Rezept: Elixier der Ogerstärke",
            ["Korean"] = "조제법: 오우거 힘의 비약",
            ["Mexican"] = "Receta: elixir de fuerza de ogro",
            ["Portuguese"] = "Receita: Elixir de Força do Ogro",
            ["Russian"] = "Рецепт: эликсир силы огра",
            ["Spanish"] = "Receta: elixir de fuerza de ogro",
            ["Taiwanese"] = "配方：巨魔力量藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "common",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 26,
                ["min_xp_level"] = 10,
            },
        },
        ["id"] = 6663,
        ["name"] = {
            ["Chinese"] = "配方：增长药剂",
            ["English"] = "Recipe: Elixir of Giant Growth",
            ["French"] = "Recette : Elixir de Taille de géant",
            ["German"] = "Rezept: Elixier des Riesenwuchses",
            ["Korean"] = "조제법: 성장의 비약",
            ["Mexican"] = "Receta: elixir de crecimiento gigante",
            ["Portuguese"] = "Receita: Elixir de Crescimento Gigantesco",
            ["Russian"] = "Рецепт: эликсир увеличения",
            ["Spanish"] = "Receta: elixir de crecimiento gigante",
            ["Taiwanese"] = "配方：增長藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 50,
                ["min_xp_level"] = 35,
            },
        },
        ["id"] = 9293,
        ["name"] = {
            ["Chinese"] = "配方：抗魔药水",
            ["English"] = "Recipe: Magic Resistance Potion",
            ["French"] = "Recette : Potion de résistance à la magie",
            ["German"] = "Rezept: Magiewiderstandstrank",
            ["Korean"] = "조제법: 마법 저항 물약",
            ["Mexican"] = "Receta: poción de resistencia a la magia",
            ["Portuguese"] = "Receita: Poção de Resistência à Magia",
            ["Russian"] = "Рецепт: зелье защиты от магии",
            ["Spanish"] = "Receta: poción de resistencia a la magia",
            ["Taiwanese"] = "配方：抗魔藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 52,
                ["min_xp_level"] = 36,
            },
        },
        ["id"] = 9294,
        ["name"] = {
            ["Chinese"] = "配方：野葡萄药水",
            ["English"] = "Recipe: Wildvine Potion",
            ["French"] = "Recette : Potion de sauvageonne",
            ["German"] = "Rezept: Wildrankentrank",
            ["Korean"] = "조제법: 야생덩굴 물약",
            ["Mexican"] = "Receta: poción de atriplex salvaje",
            ["Portuguese"] = "Receita: Poção de Vinha Selvagem",
            ["Russian"] = "Рецепт: зелье из дикой лозы",
            ["Spanish"] = "Receta: poción de atriplex salvaje",
            ["Taiwanese"] = "配方：野葡萄藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 55,
                ["min_xp_level"] = 40,
            },
        },
        ["id"] = 9295,
        ["name"] = {
            ["Chinese"] = "配方：隐形药水",
            ["English"] = "Recipe: Invisibility Potion",
            ["French"] = "Recette : Potion d'invisibilité",
            ["German"] = "Rezept: Unsichtbarkeitstrank",
            ["Korean"] = "조제법: 투명 물약",
            ["Mexican"] = "Receta: poción de invisibilidad",
            ["Portuguese"] = "Receita: Poção de Invisibilidade",
            ["Russian"] = "Рецепт: зелье невидимости",
            ["Spanish"] = "Receta: poción de invisibilidad",
            ["Taiwanese"] = "配方：隱形藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                1783,
                1791,
            },
        },
        ["id"] = 9296,
        ["name"] = {
            ["Chinese"] = "配方：阿尔萨斯的礼物",
            ["English"] = "Recipe: Gift of Arthas",
            ["French"] = "Recette : Don d'Arthas",
            ["German"] = "Rezept: Arthas' Gabe",
            ["Korean"] = "조제법: 아서스의 선물",
            ["Mexican"] = "Receta: ofrenda de Arthas",
            ["Portuguese"] = "Receita: Dádiva de Arthas",
            ["Russian"] = "Рецепт: эликсир \"Дар Артаса\"",
            ["Spanish"] = "Receta: obsequio de Arthas",
            ["Taiwanese"] = "配方：阿薩斯的禮物",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 40,
            },
        },
        ["id"] = 9297,
        ["name"] = {
            ["Chinese"] = "配方：梦境药剂",
            ["English"] = "Recipe: Elixir of Dream Vision",
            ["French"] = "Recette : Elixir de Vision de rêve",
            ["German"] = "Rezept: Elixier der Traumvision",
            ["Korean"] = "조제법: 몽상의 비약",
            ["Mexican"] = "Receta: elixir de visión onírica",
            ["Portuguese"] = "Receita: Elixir de Visão de Sonhos",
            ["Russian"] = "Рецепт: эликсир Снозрения",
            ["Spanish"] = "Receta: elixir de visión de ensueño",
            ["Taiwanese"] = "配方：夢境藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 55,
                ["min_xp_level"] = 40,
            },
        },
        ["id"] = 9298,
        ["name"] = {
            ["Chinese"] = "配方：巨人药剂",
            ["English"] = "Recipe: Elixir of Giants",
            ["French"] = "Recette : Elixir des géants",
            ["German"] = "Rezept: Elixier der Riesen",
            ["Korean"] = "조제법: 거인의 비약",
            ["Mexican"] = "Receta: elixir de gigantes",
            ["Portuguese"] = "Receita: Elixir de Gigantes",
            ["Russian"] = "Рецепт: эликсир великанов",
            ["Spanish"] = "Receta: elixir de gigantes",
            ["Taiwanese"] = "配方：巨人藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 9300,
        ["name"] = {
            ["Chinese"] = "配方：屠魔药剂",
            ["English"] = "Recipe: Elixir of Demonslaying",
            ["French"] = "Recette : Elixir de Tueur de démons",
            ["German"] = "Rezept: Elixier des Dämonentötens",
            ["Korean"] = "조제법: 악마 사냥 전문화의 비약",
            ["Mexican"] = "Receta: elixir de matanza de demonios",
            ["Portuguese"] = "Receita: Elixir de Demonicídio",
            ["Russian"] = "Рецепт: эликсир истребления демонов",
            ["Spanish"] = "Receta: elixir de matanza de demonios",
            ["Taiwanese"] = "配方：屠魔藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 10000,
            ["sources"] = {
                8177,
                8178,
            },
        },
    },
    {
        ["id"] = 9301,
        ["name"] = {
            ["Chinese"] = "配方：暗影之力药剂",
            ["English"] = "Recipe: Elixir of Shadow Power",
            ["French"] = "Recette : Elixir de Puissance de l'ombre",
            ["German"] = "Rezept: Elixier der Schattenmacht",
            ["Korean"] = "조제법: 암흑 강화의 비약",
            ["Mexican"] = "Receta: elixir de poder de las Sombras",
            ["Portuguese"] = "Receita: Elixir de Poder Sombrio",
            ["Russian"] = "Рецепт: эликсир силы тьмы",
            ["Spanish"] = "Receta: elixir de poder de las Sombras",
            ["Taiwanese"] = "配方：暗影之力藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["vendors"] = {
            ["price"] = 10000,
            ["sources"] = {
                1313,
                4610,
            },
        },
    },
    {
        ["id"] = 9302,
        ["name"] = {
            ["Chinese"] = "配方：幻象染料",
            ["English"] = "Recipe: Ghost Dye",
            ["French"] = "Recette : Teinture fantôme",
            ["German"] = "Rezept: Geisterfarbstoff",
            ["Korean"] = "조제법: 유령 염료",
            ["Mexican"] = "Receta: tinte fantasmal",
            ["Portuguese"] = "Receita: Pigmento Fantasma",
            ["Russian"] = "Рецепт: призрачная краска",
            ["Spanish"] = "Receta: tinte fantasmal",
            ["Taiwanese"] = "配方：幻象染料",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 9000,
            ["sources"] = {
                8157,
                8158,
            },
        },
    },
    {
        ["id"] = 9303,
        ["name"] = {
            ["Chinese"] = "配方：点金石",
            ["English"] = "Recipe: Philosopher's Stone",
            ["French"] = "Recette : Pierre philosophale",
            ["German"] = "Rezept: Stein der Weisen",
            ["Korean"] = "조제법: 연금술사의 돌",
            ["Mexican"] = "Receta: piedra filosofal",
            ["Portuguese"] = "Receita: Pedra Filosofal",
            ["Russian"] = "Рецепт: философский камень",
            ["Spanish"] = "Receta: piedra de filósofo",
            ["Taiwanese"] = "配方：點金石",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 8000,
            ["sources"] = {
                5594,
            },
        },
    },
    {
        ["id"] = 9304,
        ["name"] = {
            ["Chinese"] = "配方：点铁成金",
            ["English"] = "Recipe: Transmute Iron to Gold",
            ["French"] = "Recette : Transmutation du fer en or",
            ["German"] = "Rezept: Eisen in Gold transmutieren",
            ["Korean"] = "조제법: 철을 금으로 변환",
            ["Mexican"] = "Receta: transmutar hierro a oro",
            ["Portuguese"] = "Receita: Transmutar Ferro em Ouro",
            ["Russian"] = "Рецепт: трансмутация железа в золото",
            ["Spanish"] = "Receta: transmutar hierro a oro",
            ["Taiwanese"] = "配方：點鐵成金",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 8000,
            ["sources"] = {
                5594,
            },
        },
    },
    {
        ["id"] = 9305,
        ["name"] = {
            ["Chinese"] = "配方：点化秘银",
            ["English"] = "Recipe: Transmute Mithril to Truesilver",
            ["French"] = "Recette : Transmutation du mithril en vrai-argent",
            ["German"] = "Rezept: Mithril in Echtsilber transmutieren",
            ["Korean"] = "조제법: 미스릴을 진은으로 변환",
            ["Mexican"] = "Receta: transmutar mitril a veraplata",
            ["Portuguese"] = "Receita: Transmutar Mithril em Veraprata",
            ["Russian"] = "Рецепт: трансмутация мифрила в истинное серебро",
            ["Spanish"] = "Receta: transmutar mitril a veraplata",
            ["Taiwanese"] = "配方：點化祕銀",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 8000,
            ["sources"] = {
                5594,
            },
        },
    },
    {
        ["id"] = 10644,
        ["name"] = {
            ["Chinese"] = "配方：地精火箭燃油",
            ["English"] = "Recipe: Goblin Rocket Fuel",
            ["French"] = "Recette : Carburant de fusée des gobelins",
            ["German"] = "Rezept: Goblin-Raketentreibstoff",
            ["Korean"] = "조제법: 고블린 로켓 연료",
            ["Mexican"] = "Receta: combustible de cohete goblin",
            ["Portuguese"] = "Receita: Combustível de Foguete Goblínico",
            ["Russian"] = "Рецепт: гоблинское ракетное топливо",
            ["Spanish"] = "Receta: combustible de cohete goblin",
            ["Taiwanese"] = "配方：哥布林火箭燃油",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["special_action"] = "made goblin engineer 205",
    },
    {
        ["id"] = 12958,
        ["name"] = {
            ["Chinese"] = "配方：合成奥金",
            ["English"] = "Recipe: Transmute Arcanite",
            ["French"] = "Recette : Transmutation d'arcanite",
            ["German"] = "Rezept: Arkanit transmutieren",
            ["Korean"] = "조제법: 아케이나이트로 변환",
            ["Mexican"] = "Receta: transmutar arcanita",
            ["Portuguese"] = "Receita: Transmutar Arcanita",
            ["Russian"] = "Рецепт: трансмутация арканита",
            ["Spanish"] = "Receta: transmutar arcanita",
            ["Taiwanese"] = "配方：合成奧金",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 50000,
            ["sources"] = {
                5594,
            },
        },
    },
    {
        ["drops"] = {
            ["sources"] = {
                7027,
            },
        },
        ["id"] = 13476,
        ["name"] = {
            ["Chinese"] = "配方：特效怒气药水",
            ["English"] = "Recipe: Mighty Rage Potion",
            ["French"] = "Recette : Potion de rage puissante",
            ["German"] = "Rezept: Mächtiger Wuttrank",
            ["Korean"] = "조제법: 강력한 분노의 물약",
            ["Mexican"] = "Receta: poción de ira poderosa",
            ["Portuguese"] = "Receita: Poção Potente de Raiva",
            ["Russian"] = "Рецепт: мощное зелье ярости",
            ["Spanish"] = "Receta: poción de ira poderosa",
            ["Taiwanese"] = "配方：強效怒氣藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 13477,
        ["name"] = {
            ["Chinese"] = "配方：超级法力药水",
            ["English"] = "Recipe: Superior Mana Potion",
            ["French"] = "Recette : Potion de mana excellente",
            ["German"] = "Rezept: Überragender Manatrank",
            ["Korean"] = "조제법: 최상급 마나 물약",
            ["Mexican"] = "Receta: poción de maná excelente",
            ["Portuguese"] = "Receita: Poção Superior de Mana",
            ["Russian"] = "Рецепт: мощное зелье маны",
            ["Spanish"] = "Receta: poción de maná excelente",
            ["Taiwanese"] = "配方：超級法力藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 12000,
            ["sources"] = {
                4226,
                4610,
            },
        },
    },
    {
        ["id"] = 13478,
        ["name"] = {
            ["Chinese"] = "配方：超强防御药剂",
            ["English"] = "Recipe: Elixir of Superior Defense",
            ["French"] = "Recette : Elixir de Défense excellente",
            ["German"] = "Rezept: Elixier der überragenden Verteidigung",
            ["Korean"] = "조제법: 최상급 방어의 비약",
            ["Mexican"] = "Receta: elixir de defensa excelente",
            ["Portuguese"] = "Receita: Elixir de Defesa Superior",
            ["Russian"] = "Рецепт: мощный эликсир защиты",
            ["Spanish"] = "Receta: elixir de defensa excelente",
            ["Taiwanese"] = "配方：超強防禦藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 13000,
            ["sources"] = {
                3348,
                5178,
            },
        },
    },
    {
        ["drops"] = {
            ["sources"] = {
                9449,
                9450,
                9451,
                9452,
                15162,
            },
        },
        ["id"] = 13479,
        ["name"] = {
            ["Chinese"] = "配方：先知药剂",
            ["English"] = "Recipe: Elixir of the Sages",
            ["French"] = "Recette : Elixir des Sages",
            ["German"] = "Rezept: Elixier der Weisen",
            ["Korean"] = "조제법: 현인의 비약",
            ["Mexican"] = "Receta: elixir de los sabios",
            ["Portuguese"] = "Receita: Elixir dos Sábios",
            ["Russian"] = "Рецепт: эликсир мудрецов",
            ["Spanish"] = "Receta: elixir de los sabios",
            ["Taiwanese"] = "配方：先知藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 13480,
        ["name"] = {
            ["Chinese"] = "配方：特效治疗药水",
            ["English"] = "Recipe: Major Healing Potion",
            ["French"] = "Recette : Potion de Soins majeure",
            ["German"] = "Rezept: Erheblicher Heiltrank",
            ["Korean"] = "조제법: 일급 치유 물약",
            ["Mexican"] = "Receta: poción de sanación sublime",
            ["Portuguese"] = "Receita: Poção Elevada de Cura",
            ["Russian"] = "Рецепт: сильнейшее лечебное зелье",
            ["Spanish"] = "Receta: poción de curación sublime",
            ["Taiwanese"] = "配方：極效治療藥水",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 15000,
            ["sources"] = {
                11188,
            },
        },
    },
    {
        ["id"] = 13481,
        ["name"] = {
            ["Chinese"] = "配方：蛮力药剂",
            ["English"] = "Recipe: Elixir of Brute Force",
            ["French"] = "Recette : Elixir de Force de brute",
            ["German"] = "Rezept: Elixier der rohen Gewalt",
            ["Korean"] = "조제법: 야수 힘의 비약",
            ["Mexican"] = "Receta: elixir de fuerza bruta",
            ["Portuguese"] = "Receita: Elixir da Força Bruta",
            ["Russian"] = "Рецепт: эликсир грубой силы",
            ["Spanish"] = "Receta: elixir de potencia bruta",
            ["Taiwanese"] = "配方：蠻力藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            5150,
        },
    },
    {
        ["id"] = 13482,
        ["name"] = {
            ["Chinese"] = "配方：点气成火",
            ["English"] = "Recipe: Transmute Air to Fire",
            ["French"] = "Recette : Transmutation de l'Air en Feu",
            ["German"] = "Rezept: Luft zu Feuer transmutieren",
            ["Korean"] = "조제법: 바람을 불로 변환",
            ["Mexican"] = "Receta: transmutar aire en fuego",
            ["Portuguese"] = "Receita: Transmutar Ar em Fogo",
            ["Russian"] = "Рецепт: трансмутация воздуха в огонь",
            ["Spanish"] = "Receta: transmutar aire a fuego",
            ["Taiwanese"] = "配方：點氣成火",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["reputation"] = {
            ["faction_id"] = 529,
            ["level_id"] = 6,
        },
        ["vendors"] = {
            ["price"] = 15000,
            ["sources"] = {
                10856,
                10857,
                11536,
            },
        },
    },
    {
        ["id"] = 13483,
        ["name"] = {
            ["Chinese"] = "配方：点火成土",
            ["English"] = "Recipe: Transmute Fire to Earth",
            ["French"] = "Recette : Transmutation du Feu en Terre",
            ["German"] = "Rezept: Feuer zu Erde transmutieren",
            ["Korean"] = "조제법: 불을 대지로 변환",
            ["Mexican"] = "Receta: transmutar fuego a tierra",
            ["Portuguese"] = "Receita: Transmutar Fogo em Terra",
            ["Russian"] = "Рецепт: трансмутация огня в землю",
            ["Spanish"] = "Receta: transmutar fuego a tierra",
            ["Taiwanese"] = "配方：點火成土",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["vendors"] = {
            ["price"] = 15000,
            ["sources"] = {
                9499,
            },
        },
    },
    {
        ["id"] = 13484,
        ["name"] = {
            ["Chinese"] = "配方：转土成水",
            ["English"] = "Recipe: Transmute Earth to Water",
            ["French"] = "Recette : Transmutation de la Terre en Eau",
            ["German"] = "Rezept: Erde zu Wasser transmutieren",
            ["Korean"] = "조제법: 대지를 물로 변환",
            ["Mexican"] = "Receta: transmutar tierra a agua",
            ["Portuguese"] = "Receita: Transmutar Terra em Água",
            ["Russian"] = "Рецепт: трансмутация земли в воду",
            ["Spanish"] = "Receta: transmutar tierra a agua",
            ["Taiwanese"] = "配方：轉土成水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["reputation"] = {
            ["faction_id"] = 576,
            ["level_id"] = 5,
        },
        ["vendors"] = {
            ["price"] = 15000,
            ["sources"] = {
                11557,
            },
        },
    },
    {
        ["id"] = 13485,
        ["name"] = {
            ["Chinese"] = "配方：点水成气",
            ["English"] = "Recipe: Transmute Water to Air",
            ["French"] = "Recette : Transmutation de l'Eau en Air",
            ["German"] = "Rezept: Wasser zu Luft transmutieren",
            ["Korean"] = "조제법: 물을 바람으로 변환",
            ["Mexican"] = "Receta: transmutar agua a aire",
            ["Portuguese"] = "Receita: Transmutar Água em Ar",
            ["Russian"] = "Рецепт: трансмутация воды в воздух",
            ["Spanish"] = "Receta: transmutar agua a aire",
            ["Taiwanese"] = "配方：點水成氣",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["vendors"] = {
            ["price"] = 15000,
            ["sources"] = {
                11278,
            },
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 50,
            },
        },
        ["id"] = 13486,
        ["name"] = {
            ["Chinese"] = "配方：死灵化水",
            ["English"] = "Recipe: Transmute Undeath to Water",
            ["French"] = "Recette : Transmutation du Non-mort en Eau",
            ["German"] = "Rezept: Untod zu Wasser transmutieren",
            ["Korean"] = "조제법: 불사를 물로 변환",
            ["Mexican"] = "Receta: transmutar no-muerto a agua",
            ["Portuguese"] = "Receita: Transmutar Morte-viva em Água",
            ["Russian"] = "Рецепт: трансмутация нежити в воду",
            ["Spanish"] = "Receta: transmutar inerte a agua",
            ["Taiwanese"] = "配方：死靈化水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 50,
            },
        },
        ["id"] = 13487,
        ["name"] = {
            ["Chinese"] = "配方：水转死灵",
            ["English"] = "Recipe: Transmute Water to Undeath",
            ["French"] = "Recette : Transmutation de l'Eau en Non-mort",
            ["German"] = "Rezept: Wasser zu Untod transmutieren",
            ["Korean"] = "조제법: 물을 불사로 변환",
            ["Mexican"] = "Receta: transmutar agua a no-muerto",
            ["Portuguese"] = "Receita: Transmutar Água em Morte-viva",
            ["Russian"] = "Рецепт: трансмутация воды в нежить",
            ["Spanish"] = "Receta: transmutar agua a inerte",
            ["Taiwanese"] = "配方：水轉死靈",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 50,
            },
        },
        ["id"] = 13488,
        ["name"] = {
            ["Chinese"] = "配方：生命归土",
            ["English"] = "Recipe: Transmute Life to Earth",
            ["French"] = "Recette : Transmutation de la Vie en Terre",
            ["German"] = "Rezept: Leben in Erde transmutieren",
            ["Korean"] = "조제법: 생명을 대지로 변환",
            ["Mexican"] = "Receta: transmutar vida a tierra",
            ["Portuguese"] = "Receita: Transmutar Vida em Terra",
            ["Russian"] = "Рецепт: трансмутация жизни в землю",
            ["Spanish"] = "Receta: transmutar vida a tierra",
            ["Taiwanese"] = "配方：生命歸土",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 50,
            },
        },
        ["id"] = 13489,
        ["name"] = {
            ["Chinese"] = "配方：土转生命",
            ["English"] = "Recipe: Transmute Earth to Life",
            ["French"] = "Recette : Transmutation de la Terre en Vie",
            ["German"] = "Rezept: Erde in Leben transmutieren",
            ["Korean"] = "조제법: 대지를 생명으로 변환",
            ["Mexican"] = "Receta: transmutar tierra a vida",
            ["Portuguese"] = "Receita: Transmutar Terra em Vida",
            ["Russian"] = "Рецепт: трансмутация земли в жизнь",
            ["Spanish"] = "Receta: transmutar tierra a vida",
            ["Taiwanese"] = "配方：土轉生命",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 50,
            },
        },
        ["id"] = 13490,
        ["name"] = {
            ["Chinese"] = "配方：强效石盾药水",
            ["English"] = "Recipe: Greater Stoneshield Potion",
            ["French"] = "Recette : Potion de Bouclier de pierre supérieure",
            ["German"] = "Rezept: Großer Steinschildtrank",
            ["Korean"] = "조제법: 상급 돌방패 물약",
            ["Mexican"] = "Receta: poción de escudo de piedra superior",
            ["Portuguese"] = "Receita: Poção de Escudopétreo Maior",
            ["Russian"] = "Рецепт: сильное зелье каменного щита",
            ["Spanish"] = "Receta: poción de escudo de piedra superior",
            ["Taiwanese"] = "配方：強效石盾藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                6201,
                7106,
            },
        },
        ["id"] = 13491,
        ["name"] = {
            ["Chinese"] = "配方：猫鼬药剂",
            ["English"] = "Recipe: Elixir of the Mongoose",
            ["French"] = "Recette : Elixir de la Mangouste",
            ["German"] = "Rezept: Elixier des Mungos",
            ["Korean"] = "조제법: 살쾡이의 비약",
            ["Mexican"] = "Receta: elixir de la mangosta",
            ["Portuguese"] = "Receita: Elixir do Mangusto",
            ["Russian"] = "Рецепт: эликсир мангуста",
            ["Spanish"] = "Receta: elixir de la mangosta",
            ["Taiwanese"] = "配方：貓鼬藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 50,
            },
        },
        ["id"] = 13492,
        ["name"] = {
            ["Chinese"] = "配方：净化药水",
            ["English"] = "Recipe: Purification Potion",
            ["French"] = "Recette : Potion de Purification",
            ["German"] = "Rezept: Läuterungstrank",
            ["Korean"] = "조제법: 정화 물약",
            ["Mexican"] = "Receta: poción de purificación",
            ["Portuguese"] = "Receita: Poção de Purificação",
            ["Russian"] = "Рецепт: зелье очищения",
            ["Spanish"] = "Receta: poción de purificación",
            ["Taiwanese"] = "配方：淨化藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 52,
            },
        },
        ["id"] = 13493,
        ["name"] = {
            ["Chinese"] = "配方：强效奥法药剂",
            ["English"] = "Recipe: Greater Arcane Elixir",
            ["French"] = "Recette : Elixir des arcanes supérieur",
            ["German"] = "Rezept: Großes Arkanelixier",
            ["Korean"] = "조제법: 상급 신비의 비약",
            ["Mexican"] = "Receta: elixir Arcano superior",
            ["Portuguese"] = "Receita: Elixir Arcano Maior",
            ["Russian"] = "Рецепт: сильный чародейский эликсир",
            ["Spanish"] = "Receta: elixir arcano superior",
            ["Taiwanese"] = "配方：強效祕法藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                9262,
                9264,
            },
        },
        ["id"] = 13494,
        ["name"] = {
            ["Chinese"] = "配方：强效火焰防护药水",
            ["English"] = "Recipe: Greater Fire Protection Potion",
            ["French"] = "Recette : Potion de protection contre le Feu supérieure",
            ["German"] = "Rezept: Großer Feuerschutztrank",
            ["Korean"] = "조제법: 상급 화염 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra el Fuego superior",
            ["Portuguese"] = "Receita: Poção Maior de Proteção contra o Fogo",
            ["Russian"] = "Рецепт: сильное зелье защиты от огня",
            ["Spanish"] = "Receta: poción de protección de Fuego superior",
            ["Taiwanese"] = "配方：強效火焰防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                7428,
            },
        },
        ["id"] = 13495,
        ["name"] = {
            ["Chinese"] = "配方：强效冰霜防护药水",
            ["English"] = "Recipe: Greater Frost Protection Potion",
            ["French"] = "Recette : Potion de protection contre le Givre supérieure",
            ["German"] = "Rezept: Großer Frostschutztrank",
            ["Korean"] = "조제법: 상급 냉기 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra la Escarcha superior",
            ["Portuguese"] = "Receita: Poção Maior de Proteção contra o Gelo",
            ["Russian"] = "Рецепт: сильное зелье защиты от магии льда",
            ["Spanish"] = "Receta: poción de protección de Escarcha superior",
            ["Taiwanese"] = "配方：強效冰霜防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                1812,
                1813,
            },
        },
        ["id"] = 13496,
        ["name"] = {
            ["Chinese"] = "配方：强效自然防护药水",
            ["English"] = "Recipe: Greater Nature Protection Potion",
            ["French"] = "Recette : Potion de protection contre la Nature supérieure",
            ["German"] = "Rezept: Großer Naturschutztrank",
            ["Korean"] = "조제법: 상급 자연 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra la Naturaleza superior",
            ["Portuguese"] = "Receita: Poção Maior de Proteção contra a Natureza",
            ["Russian"] = "Рецепт: сильное зелье защиты от сил природы",
            ["Spanish"] = "Receta: poción de protección de Naturaleza superior",
            ["Taiwanese"] = "配方：強效自然防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                7437,
            },
        },
        ["id"] = 13497,
        ["name"] = {
            ["Chinese"] = "配方：强效奥术防护药水",
            ["English"] = "Recipe: Greater Arcane Protection Potion",
            ["French"] = "Recette : Potion de protection contre les Arcanes supérieure",
            ["German"] = "Rezept: Großer Arkanschutztrank",
            ["Korean"] = "조제법: 상급 비전 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra lo Arcano superior",
            ["Portuguese"] = "Receita: Poção Maior de Proteção contra o Arcano",
            ["Russian"] = "Рецепт: сильное зелье защиты от тайной магии",
            ["Spanish"] = "Receta: poción de protección Arcana superior",
            ["Taiwanese"] = "配方：強效祕法防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                8546,
                8550,
            },
        },
        ["id"] = 13499,
        ["name"] = {
            ["Chinese"] = "配方：强效暗影防护药水",
            ["English"] = "Recipe: Greater Shadow Protection Potion",
            ["French"] = "Recette : Potion de protection contre l'Ombre supérieure",
            ["German"] = "Rezept: Großer Schattenschutztrank",
            ["Korean"] = "조제법: 상급 암흑 보호 물약",
            ["Mexican"] = "Receta: poción de Protección contra las Sombras superior",
            ["Portuguese"] = "Receita: Poção Maior de Proteção contra a Sombra",
            ["Russian"] = "Рецепт: сильное зелье защиты от темной магии",
            ["Spanish"] = "Receta: poción de protección de las Sombras superior",
            ["Taiwanese"] = "配方：強效暗影防護藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                1853,
            },
        },
        ["id"] = 13501,
        ["name"] = {
            ["Chinese"] = "配方：特效法力药水",
            ["English"] = "Recipe: Major Mana Potion",
            ["French"] = "Recette : Potion de mana majeure",
            ["German"] = "Rezept: Erheblicher Manatrank",
            ["Korean"] = "조제법: 일급 마나 물약",
            ["Mexican"] = "Receta: poción de maná sublime",
            ["Portuguese"] = "Receita: Poção Elevada de Mana",
            ["Russian"] = "Рецепт: сильнейшее зелье маны",
            ["Spanish"] = "Receta: poción de maná sublime",
            ["Taiwanese"] = "配方：極效法力藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["vendors"] = {
            ["price"] = 30000,
            ["sources"] = {
                11278,
            },
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 55,
            },
        },
        ["id"] = 13518,
        ["name"] = {
            ["Chinese"] = "配方：化石合剂",
            ["English"] = "Recipe: Flask of Petrification",
            ["French"] = "Recette : Flacon de pétrification",
            ["German"] = "Rezept: Fläschchen der Versteinerung",
            ["Korean"] = "조제법: 석화의 영약",
            ["Mexican"] = "Receta: Frasco de petrificación",
            ["Portuguese"] = "Receita: Frasco de Petrificação",
            ["Russian"] = "Рецепт: настой окаменения",
            ["Spanish"] = "Receta: frasco de petrificación",
            ["Taiwanese"] = "配方：石化精煉藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                10363,
            },
        },
        ["id"] = 13519,
        ["name"] = {
            ["Chinese"] = "配方：泰坦合剂",
            ["English"] = "Recipe: Flask of the Titans",
            ["French"] = "Recette : Flacon des Titans",
            ["German"] = "Rezept: Fläschchen der Titanen",
            ["Korean"] = "조제법: 티탄의 영약",
            ["Mexican"] = "Receta: frasco de los titanes",
            ["Portuguese"] = "Receita: Frasco dos Titãs",
            ["Russian"] = "Рецепт: настой титанов",
            ["Spanish"] = "Receta: frasco de los Titanes",
            ["Taiwanese"] = "配方：泰坦精煉藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                10813,
            },
        },
        ["id"] = 13520,
        ["name"] = {
            ["Chinese"] = "配方：精炼智慧合剂",
            ["English"] = "Recipe: Flask of Distilled Wisdom",
            ["French"] = "Recette : Flacon de sagesse distillée",
            ["German"] = "Rezept: Fläschchen mit destillierter Weisheit",
            ["Korean"] = "조제법: 순수한 지혜의 영약",
            ["Mexican"] = "Receta: frasco de sabiduría destilada",
            ["Portuguese"] = "Receita: Frasco de Sabedoria Destilada",
            ["Russian"] = "Рецепт: настой Концентрированной мудрости",
            ["Spanish"] = "Receta: frasco de sabiduría destilada",
            ["Taiwanese"] = "配方：智慧精煉藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                10508,
            },
        },
        ["id"] = 13521,
        ["name"] = {
            ["Chinese"] = "配方：超级能量合剂",
            ["English"] = "Recipe: Flask of Supreme Power",
            ["French"] = "Recette : Flacon de pouvoir suprême",
            ["German"] = "Rezept: Fläschchen mit oberster Macht",
            ["Korean"] = "조제법: 강력한 마력의 영약",
            ["Mexican"] = "Receta: frasco de poder supremo",
            ["Portuguese"] = "Receita: Frasco de Poder Supremo",
            ["Russian"] = "Рецепт: настой великой силы",
            ["Spanish"] = "Receta: frasco de poder supremo",
            ["Taiwanese"] = "配方：超級能量精煉藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                10339,
            },
        },
        ["id"] = 13522,
        ["name"] = {
            ["Chinese"] = "配方：多重抗性合剂",
            ["English"] = "Recipe: Flask of Chromatic Resistance",
            ["French"] = "Recette : Flacon de résistance chromatique",
            ["German"] = "Rezept: Fläschchen mit chromatischem Widerstand",
            ["Korean"] = "조제법: 마력 저항의 영약",
            ["Mexican"] = "Receta: frasco de resistencia cromática",
            ["Portuguese"] = "Receita: Frasco de Resistência Cromática",
            ["Russian"] = "Рецепт: настой всецветного сопротивления",
            ["Spanish"] = "Receta: frasco de resistencia cromática",
            ["Taiwanese"] = "配方：多重抗性精煉藥水",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 14634,
        ["name"] = {
            ["Chinese"] = "配方：冰霜之油",
            ["English"] = "Recipe: Frost Oil",
            ["French"] = "Recette : Huile glaciale",
            ["German"] = "Rezept: Frostöl",
            ["Korean"] = "조제법: 냉기 오일",
            ["Mexican"] = "Receta: aceite de Escarcha",
            ["Portuguese"] = "Receita: Óleo Gélido",
            ["Russian"] = "Рецепт: масло льда",
            ["Spanish"] = "Receta: aceite escarchado",
            ["Taiwanese"] = "配方：冰霜之油",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["vendors"] = {
            ["price"] = 2500,
            ["sources"] = {
                2480,
            },
        },
    },
    {
        ["holiday"] = 141,
        ["id"] = 17709,
        ["name"] = {
            ["Chinese"] = "配方：冰霜之力药剂",
            ["English"] = "Recipe: Elixir of Frost Power",
            ["French"] = "Recette : Elixir de Puissance du givre",
            ["German"] = "Rezept: Elixier der Frostmacht",
            ["Korean"] = "조제법: 냉기 강화의 비약",
            ["Mexican"] = "Receta: elixir de poder de Escarcha",
            ["Portuguese"] = "Receita: Elixir de Poder Gélido",
            ["Russian"] = "Рецепт: эликсир Силы льда",
            ["Spanish"] = "Receta: elixir de poder de Escarcha",
            ["Taiwanese"] = "配方：冰霜之力藥劑",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["quests"] = {
            8769,
        },
    },
    {
        ["drops"] = {
            ["sources"] = {
                11982,
                11988,
                12056,
                12057,
                12118,
                12259,
                12264,
            },
        },
        ["id"] = 18257,
        ["name"] = {
            ["Chinese"] = "配方：特效活力药水",
            ["English"] = "Recipe: Major Rejuvenation Potion",
            ["French"] = "Recette : Potion de régénération majeure",
            ["German"] = "Rezept: Erheblicher Verjüngungstrank",
            ["Korean"] = "조제법: 일급 회복 물약",
            ["Mexican"] = "Receta: poción de rejuvenecimiento sublime",
            ["Portuguese"] = "Receita: Poção Elevada de Rejuvenescimento",
            ["Russian"] = "Рецепт: сильнейшее зелье омоложения",
            ["Spanish"] = "Receta: poción rejuvenecedora sublime",
            ["Taiwanese"] = "配方：極效活力藥水",
        },
        ["phase"] = 1,
        ["quality"] = "rare",
    },
    {
        ["id"] = 20011,
        ["name"] = {
            ["Chinese"] = "配方：魔血药水",
            ["English"] = "Recipe: Mageblood Potion",
            ["French"] = "Recette : Potion Magesang",
            ["German"] = "Rezept: Magierbluttrank",
            ["Korean"] = "조제법: 마력의 물약",
            ["Mexican"] = "Receta: Poción de sangre de mago",
            ["Portuguese"] = "Receita: Poção de Sangue de Mago",
            ["Russian"] = "Рецепт: зелье крови волшебника",
            ["Spanish"] = "Receta: poción de sangre de mago",
            ["Taiwanese"] = "配方：魔血藥水",
        },
        ["phase"] = 4,
        ["quality"] = "common",
        ["reputation"] = {
            ["faction_id"] = 270,
            ["level_id"] = 7,
        },
        ["vendors"] = {
            ["price"] = 50000,
            ["sources"] = {
                14921,
            },
        },
    },
    {
        ["id"] = 20012,
        ["name"] = {
            ["Chinese"] = "配方：强效昏睡药水",
            ["English"] = "Recipe: Greater Dreamless Sleep",
            ["French"] = "Recette : Sommeil sans rêve supérieur",
            ["German"] = "Rezept: Großer Trank des traumlosen Schlafs",
            ["Korean"] = "조제법: 상급 숙면의 물약",
            ["Mexican"] = "Receta: Letargo sin sueños superior",
            ["Portuguese"] = "Receita: Sonho sem Sonhos Maior",
            ["Russian"] = "Рецепт: сильное зелье спокойного сна",
            ["Spanish"] = "Receta: letargo sin sueños superior",
            ["Taiwanese"] = "配方：強效昏睡藥水",
        },
        ["phase"] = 4,
        ["quality"] = "common",
        ["reputation"] = {
            ["faction_id"] = 270,
            ["level_id"] = 5,
        },
        ["vendors"] = {
            ["price"] = 50000,
            ["sources"] = {
                14921,
            },
        },
    },
    {
        ["id"] = 20013,
        ["name"] = {
            ["Chinese"] = "配方：活力行动药水",
            ["English"] = "Recipe: Living Action Potion",
            ["French"] = "Recette : Potion de vive action",
            ["German"] = "Rezept: Trank der lebhaften Aktion",
            ["Korean"] = "조제법: 자유 행동의 물약",
            ["Mexican"] = "Receta: poción de acción viva",
            ["Portuguese"] = "Receita: Poção de Ação Vivaz",
            ["Russian"] = "Рецепт: зелье неудержимости",
            ["Spanish"] = "Receta: poción de acción viva",
            ["Taiwanese"] = "配方：活力行動藥水",
        },
        ["phase"] = 4,
        ["quality"] = "common",
        ["reputation"] = {
            ["faction_id"] = 270,
            ["level_id"] = 8,
        },
        ["vendors"] = {
            ["price"] = 50000,
            ["sources"] = {
                14921,
            },
        },
    },
    {
        ["id"] = 20014,
        ["name"] = {
            ["Chinese"] = "配方：特效巨魔之血药水",
            ["English"] = "Recipe: Major Troll's Blood Potion",
            ["French"] = "Recette : Potion de sang de troll majeure",
            ["German"] = "Rezept: Erheblicher Trollbluttrank",
            ["Korean"] = "조제법: 일급 재생의 물약",
            ["Mexican"] = "Receta: Poción de sangre de trol sublime",
            ["Portuguese"] = "Receita: Poção Elevada de Sangue de Troll",
            ["Russian"] = "Рецепт: сильнейшее зелье тролльей крови",
            ["Spanish"] = "Receta: poción de sangre de trol sublime",
            ["Taiwanese"] = "配方：極效食人妖之血藥水",
        },
        ["phase"] = 4,
        ["quality"] = "common",
        ["reputation"] = {
            ["faction_id"] = 270,
            ["level_id"] = 6,
        },
        ["vendors"] = {
            ["price"] = 50000,
            ["sources"] = {
                14921,
            },
        },
    },
    {
        ["id"] = 20761,
        ["name"] = {
            ["Chinese"] = "配方：转化元素火焰",
            ["English"] = "Recipe: Transmute Elemental Fire",
            ["French"] = "Recette : Transmutation du feu élémentaire",
            ["German"] = "Rezept: Elementarfeuer transmutieren",
            ["Korean"] = "조제법: 자연의 불꽃으로 변환",
            ["Mexican"] = "Receta: transmutar fuego elemental",
            ["Portuguese"] = "Receita: Transmutar Fogo Elemental",
            ["Russian"] = "Рецепт: трансмутация первородного огня",
            ["Spanish"] = "Receta: transmutar Fuego elemental",
            ["Taiwanese"] = "配方：轉化元素火焰",
        },
        ["phase"] = 5,
        ["quality"] = "common",
        ["reputation"] = {
            ["faction_id"] = 59,
            ["level_id"] = 5,
        },
        ["vendors"] = {
            ["price"] = 120000,
            ["sources"] = {
                12944,
            },
        },
    },
    {
        ["drops"] = {
            ["sources"] = {
                5844,
                5846,
                8637,
            },
        },
        ["id"] = 21547,
        ["name"] = {
            ["Chinese"] = "配方：强效火力药剂",
            ["English"] = "Recipe: Elixir of Greater Firepower",
            ["French"] = "Recette : Elixir de maîtrise du feu supérieure",
            ["German"] = "Rezept: Elixier der großen Feuermacht",
            ["Korean"] = "조제법: 상급 화염 강화의 비약",
            ["Mexican"] = "Receta: elixir de poder de Fuego superior",
            ["Portuguese"] = "Receita: Elixir de Poder de Fogo Maior",
            ["Russian"] = "Рецепт: сильный эликсир огневой мощи",
            ["Spanish"] = "Receta: elixir de poder de Fuego superior",
            ["Taiwanese"] = "配方：強效火力藥劑",
        },
        ["phase"] = 5,
        ["quality"] = "uncommon",
    },
}
