TRADE_SKILLS_DATA["levels"]["Alchemy"] =
    {
        {
            ["id"] = 2259,
            ["max_skill"] = 75,
            ["min_skill"] = 0,
            ["min_xp_level"] = 5,
            ["name"] = {
                ["Chinese"] = "炼金术 (初级)",
                ["English"] = "Alchemy (Apprentice)",
                ["French"] = "Alchimie (Apprenti)",
                ["German"] = "Alchimie (Lehrling)",
                ["Korean"] = "연금술 (초급)",
                ["Mexican"] = "Alquimia (Aprendiz)",
                ["Portuguese"] = "Alquimia (Aprendiz)",
                ["Russian"] = "Алхимия (Ученик)",
                ["Spanish"] = "Alquimia (Aprendiz)",
                ["Taiwanese"] = "煉金術 (學徒)",
            },
            ["rank"] = 1,
            ["trainers"] = {
                ["price"] = 10,
                ["sources"] = {
                    1215,
                    1246,
                    1470,
                    2132,
                    3184,
                    3603,
                    5500,
                    11041,
                    11044,
                    11046,
                    11047,
                },
            },
        },
        {
            ["id"] = 3101,
            ["max_skill"] = 150,
            ["min_skill"] = 50,
            ["min_xp_level"] = 10,
            ["name"] = {
                ["Chinese"] = "炼金术 (中级)",
                ["English"] = "Alchemy (Journeyman)",
                ["French"] = "Alchimie (Compagnon)",
                ["German"] = "Alchimie (Geselle)",
                ["Korean"] = "연금술 (수습)",
                ["Mexican"] = "Alquimia (Oficial)",
                ["Portuguese"] = "Alquimia (Profissional)",
                ["Russian"] = "Алхимия (Подмастерье)",
                ["Spanish"] = "Alquimia (Oficial)",
                ["Taiwanese"] = "煉金術 (熟練工)",
            },
            ["rank"] = 2,
            ["trainers"] = {
                ["price"] = 500,
                ["sources"] = {
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4609,
                    4900,
                    5177,
                    5499,
                    11042,
                },
            },
        },
        {
            ["id"] = 3464,
            ["max_skill"] = 225,
            ["min_skill"] = 125,
            ["min_xp_level"] = 20,
            ["name"] = {
                ["Chinese"] = "炼金术 (高级)",
                ["English"] = "Alchemy (Expert)",
                ["French"] = "Alchimie (Expert)",
                ["German"] = "Alchimie (Experte)",
                ["Korean"] = "연금술 (숙련)",
                ["Mexican"] = "Alquimia (Experto)",
                ["Portuguese"] = "Alquimia (Perito)",
                ["Russian"] = "Алхимия (Умелец)",
                ["Spanish"] = "Alquimia (Experto)",
                ["Taiwanese"] = "煉金術 (專家)",
            },
            ["rank"] = 3,
            ["trainers"] = {
                ["price"] = 5000,
                ["sources"] = {
                    4160,
                    4611,
                },
            },
        },
        {
            ["id"] = 11611,
            ["max_skill"] = 300,
            ["min_skill"] = 200,
            ["min_xp_level"] = 35,
            ["name"] = {
                ["Chinese"] = "炼金术 (大师级)",
                ["English"] = "Alchemy (Artisan)",
                ["French"] = "Alchimie (Artisan)",
                ["German"] = "Alchimie (Fachmann)",
                ["Korean"] = "연금술 (전문)",
                ["Mexican"] = "Alquimia (Artesano)",
                ["Portuguese"] = "Alquimia (Artifice)",
                ["Russian"] = "Алхимия (Мастеровой)",
                ["Spanish"] = "Alquimia (Artesano)",
                ["Taiwanese"] = "煉金術 (大工匠)",
            },
            ["rank"] = 4,
            ["trainers"] = {
                ["price"] = 50000,
                ["sources"] = {
                    1386,
                    7948,
                },
            },
        },
    }
