TRADE_SKILLS_DATA["skills"]["Alchemy"] =
    {
        {
            ["id"] = 2329,
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "狮王之力药剂",
                ["English"] = "Elixir of Lion's Strength",
                ["French"] = "Elixir de force du lion",
                ["German"] = "Elixier der Löwenstärke",
                ["Korean"] = "사자의 힘 비약",
                ["Mexican"] = "Elixir de fuerza de león",
                ["Portuguese"] = "Elixir de Força de Leão",
                ["Russian"] = "Эликсир Львиной силы",
                ["Spanish"] = "Elixir de fuerza de león",
                ["Taiwanese"] = "獅王之力藥劑",
            },
            ["special_action"] = "auto learned",
        },
        {
            ["id"] = 2330,
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "初级治疗药水",
                ["English"] = "Minor Healing Potion",
                ["French"] = "Potion de soins mineure",
                ["German"] = "Schwacher Heiltrank",
                ["Korean"] = "최하급 치유 물약",
                ["Mexican"] = "Poción de sanación menor",
                ["Portuguese"] = "Poção Menor de Cura",
                ["Russian"] = "Слабое лечебное зелье",
                ["Spanish"] = "Poción menor de curación",
                ["Taiwanese"] = "初級治療藥水",
            },
            ["special_action"] = "auto learned",
        },
        {
            ["id"] = 2331,
            ["min_skill"] = 25,
            ["name"] = {
                ["Chinese"] = "初级法力药水",
                ["English"] = "Minor Mana Potion",
                ["French"] = "Potion de mana mineure",
                ["German"] = "Schwacher Manatrank",
                ["Korean"] = "최하급 마나 물약",
                ["Mexican"] = "Poción de maná menor",
                ["Portuguese"] = "Poção Menor de Mana",
                ["Russian"] = "Слабое зелье маны",
                ["Spanish"] = "Poción menor de maná",
                ["Taiwanese"] = "初級法力藥水",
            },
            ["trainers"] = {
                ["price"] = 100,
                ["sources"] = {
                    1215,
                    1246,
                    1386,
                    1470,
                    2132,
                    2391,
                    2837,
                    3184,
                    3347,
                    3603,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    5500,
                    7948,
                    11041,
                    11042,
                    11044,
                    11046,
                    11047,
                },
            },
        },
        {
            ["id"] = 2332,
            ["min_skill"] = 40,
            ["name"] = {
                ["Chinese"] = "初级活力药水",
                ["English"] = "Minor Rejuvenation Potion",
                ["French"] = "Potion de régénération mineure",
                ["German"] = "Schwacher Verjüngungstrank",
                ["Korean"] = "최하급 회복 물약",
                ["Mexican"] = "Poción de Rejuvenecimiento menor",
                ["Portuguese"] = "Poção Menor de Rejuvenescimento",
                ["Russian"] = "Слабое зелье омоложения",
                ["Spanish"] = "Poción menor de rejuvenecimiento",
                ["Taiwanese"] = "初級活力藥水",
            },
            ["trainers"] = {
                ["price"] = 150,
                ["sources"] = {
                    1215,
                    1246,
                    1386,
                    1470,
                    2132,
                    2391,
                    2837,
                    3184,
                    3347,
                    3603,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    5500,
                    7948,
                    11041,
                    11042,
                    11044,
                    11046,
                    11047,
                },
            },
        },
        {
            ["id"] = 2333,
            ["items"] = {
                3396,
            },
            ["min_skill"] = 140,
            ["name"] = {
                ["Chinese"] = "次级敏捷药剂",
                ["English"] = "Elixir of Lesser Agility",
                ["French"] = "Elixir d'Agilité inférieure",
                ["German"] = "Elixier der geringen Beweglichkeit",
                ["Korean"] = "하급 민첩의 비약",
                ["Mexican"] = "Elixir de agilidad inferior",
                ["Portuguese"] = "Elixir de Agilidade Inferior",
                ["Russian"] = "Эликсир ловкости I ступени",
                ["Spanish"] = "Elixir de agilidad inferior",
                ["Taiwanese"] = "次級敏捷藥劑",
            },
        },
        {
            ["id"] = 2334,
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "初级坚韧药剂",
                ["English"] = "Elixir of Minor Fortitude",
                ["French"] = "Elixir de Robustesse mineure",
                ["German"] = "Elixier der schwachen Seelenstärke",
                ["Korean"] = "최하급 인내의 비약",
                ["Mexican"] = "Elixir de entereza menor",
                ["Portuguese"] = "Elixir de Fortitude Menor",
                ["Russian"] = "Слабый эликсир стойкости",
                ["Spanish"] = "Elixir de entereza menor",
                ["Taiwanese"] = "初級堅韌藥劑",
            },
            ["trainers"] = {
                ["price"] = 250,
                ["sources"] = {
                    1215,
                    1246,
                    1386,
                    1470,
                    2132,
                    2391,
                    2837,
                    3184,
                    3347,
                    3603,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    5500,
                    7948,
                    11041,
                    11042,
                    11044,
                    11046,
                    11047,
                },
            },
        },
        {
            ["id"] = 2335,
            ["items"] = {
                2555,
            },
            ["min_skill"] = 60,
            ["name"] = {
                ["Chinese"] = "迅捷药水",
                ["English"] = "Swiftness Potion",
                ["French"] = "Potion de Rapidité",
                ["German"] = "Hurtigkeitstrank",
                ["Korean"] = "신속의 물약",
                ["Mexican"] = "Poción de presteza",
                ["Portuguese"] = "Poção de Rapidez",
                ["Russian"] = "Зелье скорости",
                ["Spanish"] = "Poción de rapidez",
                ["Taiwanese"] = "迅捷藥水",
            },
        },
        {
            ["id"] = 2337,
            ["min_skill"] = 55,
            ["name"] = {
                ["Chinese"] = "次级治疗药水",
                ["English"] = "Lesser Healing Potion",
                ["French"] = "Potion de soins inférieure",
                ["German"] = "Geringer Heiltrank",
                ["Korean"] = "하급 치유 물약",
                ["Mexican"] = "Poción de sanación inferior",
                ["Portuguese"] = "Poção Inferior de Cura",
                ["Russian"] = "Простое лечебное зелье",
                ["Spanish"] = "Poción inferior de curación",
                ["Taiwanese"] = "次級治療藥水",
            },
            ["trainers"] = {
                ["price"] = 1000,
                ["sources"] = {
                    1215,
                    1246,
                    1470,
                    2132,
                    2391,
                    2837,
                    3009,
                    3184,
                    3347,
                    3603,
                    3964,
                    4609,
                    4900,
                    5177,
                    5499,
                    5500,
                    11041,
                    11042,
                    11044,
                    11046,
                    11047,
                },
            },
        },
        {
            ["id"] = 3170,
            ["min_skill"] = 15,
            ["name"] = {
                ["Chinese"] = "弱效巨魔之血药水",
                ["English"] = "Weak Troll's Blood Potion",
                ["French"] = "Potion de sang de troll faible",
                ["German"] = "Schwacher Trollbluttrank",
                ["Korean"] = "약한 재생의 물약",
                ["Mexican"] = "Poción de sangre de trol débil",
                ["Portuguese"] = "Poção Fraca de Sangue de Troll",
                ["Russian"] = "Слабое зелье тролльей крови",
                ["Spanish"] = "Poción débil de sangre de trol",
                ["Taiwanese"] = "弱效食人妖之血藥水",
            },
            ["trainers"] = {
                ["price"] = 50,
                ["sources"] = {
                    1215,
                    1246,
                    1386,
                    1470,
                    2132,
                    2391,
                    2837,
                    3184,
                    3347,
                    3603,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    5500,
                    7948,
                    11041,
                    11042,
                    11044,
                    11046,
                    11047,
                },
            },
        },
        {
            ["id"] = 3171,
            ["min_skill"] = 90,
            ["name"] = {
                ["Chinese"] = "智慧药剂",
                ["English"] = "Elixir of Wisdom",
                ["French"] = "Elixir de Sagesse",
                ["German"] = "Elixier der Weisheit",
                ["Korean"] = "지혜의 비약",
                ["Mexican"] = "Elixir de sabiduría",
                ["Portuguese"] = "Elixir de Sabedoria",
                ["Russian"] = "Эликсир Мудрости",
                ["Spanish"] = "Elixir de sabiduría",
                ["Taiwanese"] = "智慧藥劑",
            },
            ["trainers"] = {
                ["price"] = 500,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 3172,
            ["items"] = {
                3393,
            },
            ["min_skill"] = 110,
            ["name"] = {
                ["Chinese"] = "初级抗魔药水",
                ["English"] = "Minor Magic Resistance Potion",
                ["French"] = "Potion de résistance à la magie mineure",
                ["German"] = "Schwacher Magiewiderstandstrank",
                ["Korean"] = "최하급 마법 저항 물약",
                ["Mexican"] = "Poción de resistencia a la magia menor",
                ["Portuguese"] = "Poção Menor de Resistência à Magia",
                ["Russian"] = "Слабое зелье защиты от магии",
                ["Spanish"] = "Poción menor de resistencia a la magia",
                ["Taiwanese"] = "初級抗魔藥水",
            },
        },
        {
            ["id"] = 3173,
            ["min_skill"] = 120,
            ["name"] = {
                ["Chinese"] = "次级法力药水",
                ["English"] = "Lesser Mana Potion",
                ["French"] = "Potion de mana inférieure",
                ["German"] = "Geringer Manatrank",
                ["Korean"] = "하급 마나 물약",
                ["Mexican"] = "Poción de maná inferior",
                ["Portuguese"] = "Poção Inferior de Mana",
                ["Russian"] = "Простое зелье маны",
                ["Spanish"] = "Poción inferior de maná",
                ["Taiwanese"] = "次級法力藥水",
            },
            ["trainers"] = {
                ["price"] = 150,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 3174,
            ["items"] = {
                3394,
            },
            ["min_skill"] = 120,
            ["name"] = {
                ["Chinese"] = "抗毒药剂",
                ["English"] = "Elixir of Poison Resistance",
                ["French"] = "Elixir de résistance au poison",
                ["German"] = "Elixier des Giftwiderstands",
                ["Korean"] = "독 저항의 비약",
                ["Mexican"] = "Elixir de resistencia al veneno",
                ["Portuguese"] = "Elixir de Resistência a Veneno",
                ["Russian"] = "Эликсир сопротивления яду",
                ["Spanish"] = "Elixir de resistencia al veneno",
                ["Taiwanese"] = "抗毒藥劑",
            },
        },
        {
            ["id"] = 3175,
            ["items"] = {
                3395,
            },
            ["min_skill"] = 250,
            ["name"] = {
                ["Chinese"] = "有限无敌药水",
                ["English"] = "Limited Invulnerability Potion",
                ["French"] = "Potion d'invulnérabilité limitée",
                ["German"] = "Begrenzter Unverwundbarkeitstrank",
                ["Korean"] = "제한된 무적 물약",
                ["Mexican"] = "Poción de invulnerabilidad limitada",
                ["Portuguese"] = "Poção de Invulnerabilidade Limitada",
                ["Russian"] = "Слабое зелье неуязвимости",
                ["Spanish"] = "Poción limitada de invulnerabilidad",
                ["Taiwanese"] = "有限無敵藥水",
            },
        },
        {
            ["id"] = 3176,
            ["min_skill"] = 125,
            ["name"] = {
                ["Chinese"] = "强力巨魔之血药水",
                ["English"] = "Strong Troll's Blood Potion",
                ["French"] = "Potion de sang de troll forte",
                ["German"] = "Starker Trollbluttrank",
                ["Korean"] = "강한 재생의 물약",
                ["Mexican"] = "Poción de sangre de trol fuerte",
                ["Portuguese"] = "Poção Forte de Sangue de Troll",
                ["Russian"] = "Крепкое зелье тролльей крови",
                ["Spanish"] = "Poción fuerte de sangre de trol",
                ["Taiwanese"] = "強力食人妖之血藥水",
            },
            ["trainers"] = {
                ["price"] = 1500,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 3177,
            ["min_skill"] = 130,
            ["name"] = {
                ["Chinese"] = "防御药剂",
                ["English"] = "Elixir of Defense",
                ["French"] = "Elixir de Défense",
                ["German"] = "Elixier der Verteidigung",
                ["Korean"] = "방어의 비약",
                ["Mexican"] = "Elixir de defensa",
                ["Portuguese"] = "Elixir de Defesa",
                ["Russian"] = "Эликсир защиты",
                ["Spanish"] = "Elixir de defensa",
                ["Taiwanese"] = "防禦藥劑",
            },
            ["trainers"] = {
                ["price"] = 2000,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 3188,
            ["items"] = {
                6211,
            },
            ["min_skill"] = 150,
            ["name"] = {
                ["Chinese"] = "食人魔力量药剂",
                ["English"] = "Elixir of Ogre's Strength",
                ["French"] = "Elixir de Force d'ogre",
                ["German"] = "Elixier der Ogerstärke",
                ["Korean"] = "오우거의 힘 비약",
                ["Mexican"] = "Elixir de fuerza de ogro",
                ["Portuguese"] = "Elixir de Força do Ogro",
                ["Russian"] = "Эликсир Силы огра",
                ["Spanish"] = "Elixir de fuerza de ogro",
                ["Taiwanese"] = "巨魔力量藥劑",
            },
        },
        {
            ["id"] = 3230,
            ["items"] = {
                2553,
            },
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "初级敏捷药剂",
                ["English"] = "Elixir of Minor Agility",
                ["French"] = "Elixir d'Agilité mineure",
                ["German"] = "Elixier der schwachen Beweglichkeit",
                ["Korean"] = "최하급 민첩의 비약",
                ["Mexican"] = "Elixir de agilidad menor",
                ["Portuguese"] = "Elixir de Agilidade Menor",
                ["Russian"] = "Эликсир ловкости II ступени",
                ["Spanish"] = "Elixir de agilidad menor",
                ["Taiwanese"] = "初級敏捷藥劑",
            },
        },
        {
            ["id"] = 3447,
            ["min_skill"] = 110,
            ["name"] = {
                ["Chinese"] = "治疗药水",
                ["English"] = "Healing Potion",
                ["French"] = "Potion de soins",
                ["German"] = "Heiltrank",
                ["Korean"] = "치유 물약",
                ["Mexican"] = "Poción de sanación",
                ["Portuguese"] = "Poção de Cura",
                ["Russian"] = "Лечебное зелье",
                ["Spanish"] = "Poción de curación",
                ["Taiwanese"] = "治療藥水",
            },
            ["trainers"] = {
                ["price"] = 4000,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 3448,
            ["min_skill"] = 165,
            ["name"] = {
                ["Chinese"] = "次级隐形药水",
                ["English"] = "Lesser Invisibility Potion",
                ["French"] = "Potion d'Invisibilité inférieure",
                ["German"] = "Geringer Unsichtbarkeitstrank",
                ["Korean"] = "하급 투명 물약",
                ["Mexican"] = "Poción de invisibilidad inferior",
                ["Portuguese"] = "Poção Inferior de Invisibilidade",
                ["Russian"] = "Зелье простой невидимости",
                ["Spanish"] = "Poción inferior de invisibilidad",
                ["Taiwanese"] = "次級隱形藥水",
            },
            ["trainers"] = {
                ["price"] = 4500,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 3449,
            ["items"] = {
                6068,
            },
            ["min_skill"] = 165,
            ["name"] = {
                ["Chinese"] = "暗影之油",
                ["English"] = "Shadow Oil",
                ["French"] = "Huile des ténèbres",
                ["German"] = "Schattenöl",
                ["Korean"] = "암흑 오일",
                ["Mexican"] = "Aceite de las Sombras",
                ["Portuguese"] = "Óleo de Sombra",
                ["Russian"] = "Масло Тьмы",
                ["Spanish"] = "Aceite de las Sombras",
                ["Taiwanese"] = "暗影之油",
            },
        },
        {
            ["id"] = 3450,
            ["items"] = {
                3830,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "坚韧药剂",
                ["English"] = "Elixir of Fortitude",
                ["French"] = "Elixir de Robustesse",
                ["German"] = "Elixier der Seelenstärke",
                ["Korean"] = "인내의 비약",
                ["Mexican"] = "Elixir de entereza",
                ["Portuguese"] = "Elixir de Fortitude",
                ["Russian"] = "Эликсир стойкости",
                ["Spanish"] = "Elixir de la entereza",
                ["Taiwanese"] = "堅韌藥劑",
            },
            ["trainers"] = {
                ["price"] = 5400,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 3451,
            ["items"] = {
                3831,
            },
            ["min_skill"] = 180,
            ["name"] = {
                ["Chinese"] = "超强巨魔之血药水",
                ["English"] = "Mighty Troll's Blood Potion",
                ["French"] = "Potion de sang de troll hargneux",
                ["German"] = "Mächtiger Trollbluttrank",
                ["Korean"] = "강력한 재생의 물약",
                ["Mexican"] = "Poción de sangre de trol poderosa",
                ["Portuguese"] = "Poção Potente de Sangue de Troll",
                ["Russian"] = "Мощное зелье тролльей крови",
                ["Spanish"] = "Poción de sangre de trol poderoso",
                ["Taiwanese"] = "超強食人妖之血藥水",
            },
        },
        {
            ["id"] = 3452,
            ["min_skill"] = 160,
            ["name"] = {
                ["Chinese"] = "法力药水",
                ["English"] = "Mana Potion",
                ["French"] = "Potion de mana",
                ["German"] = "Manatrank",
                ["Korean"] = "마나 물약",
                ["Mexican"] = "Poción de maná",
                ["Portuguese"] = "Poção de Mana",
                ["Russian"] = "Зелье маны",
                ["Spanish"] = "Poción de maná",
                ["Taiwanese"] = "法力藥水",
            },
            ["trainers"] = {
                ["price"] = 4500,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 3453,
            ["items"] = {
                3832,
            },
            ["min_skill"] = 195,
            ["name"] = {
                ["Chinese"] = "侦测次级隐形药剂",
                ["English"] = "Elixir of Detect Lesser Invisibility",
                ["French"] = "Elixir de Détection de l'invisibilité inférieure",
                ["German"] = "Elixier der Entd. geringer Unsichtbarkeit",
                ["Korean"] = "하급 투명체 감지의 비약",
                ["Mexican"] = "Elixir de detección de invisibilidad inferior",
                ["Portuguese"] = "Elixir de Detectar Invisibilidade Inferior",
                ["Russian"] = "Эликсир обнаружения простой невидимости",
                ["Spanish"] = "Elixir de detección de invisibilidad inferior",
                ["Taiwanese"] = "偵測次級隱形藥劑",
            },
        },
        {
            ["id"] = 3454,
            ["items"] = {
                14634,
            },
            ["min_skill"] = 200,
            ["name"] = {
                ["Chinese"] = "冰霜之油",
                ["English"] = "Frost Oil",
                ["French"] = "Huile glaciale",
                ["German"] = "Frostöl",
                ["Korean"] = "냉기 오일",
                ["Mexican"] = "Aceite de Escarcha",
                ["Portuguese"] = "Óleo Gélido",
                ["Russian"] = "Масло льда",
                ["Spanish"] = "Aceite de Escarcha",
                ["Taiwanese"] = "冰霜之油",
            },
        },
        {
            ["id"] = 4508,
            ["items"] = {
                4597,
            },
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "透明治疗药水",
                ["English"] = "Discolored Healing Potion",
                ["French"] = "Potion de soins décolorée",
                ["German"] = "Verfärbter Heiltrank",
                ["Korean"] = "빛바랜 치유 물약",
                ["Mexican"] = "Poción de sanación descolorida",
                ["Portuguese"] = "Poção Descolorida de Cura",
                ["Russian"] = "Бесцветное лечебное зелье",
                ["Spanish"] = "Poción descolorida de curación",
                ["Taiwanese"] = "透明治療藥水",
            },
        },
        {
            ["id"] = 4942,
            ["items"] = {
                4624,
            },
            ["min_skill"] = 215,
            ["name"] = {
                ["Chinese"] = "次级石盾药水",
                ["English"] = "Lesser Stoneshield Potion",
                ["French"] = "Potion de Bouclier de pierre inférieure",
                ["German"] = "Geringer Steinschildtrank",
                ["Korean"] = "하급 돌방패 물약",
                ["Mexican"] = "Poción de escudo de piedra inferior",
                ["Portuguese"] = "Poção Inferior de Escudopétreo",
                ["Russian"] = "Простое зелье каменного щита",
                ["Spanish"] = "Poción inferior de petrescudo",
                ["Taiwanese"] = "次級石盾藥水",
            },
        },
        {
            ["id"] = 6617,
            ["items"] = {
                5640,
            },
            ["min_skill"] = 60,
            ["name"] = {
                ["Chinese"] = "怒气药水",
                ["English"] = "Rage Potion",
                ["French"] = "Potion de Rage",
                ["German"] = "Wuttrank",
                ["Korean"] = "분노 물약",
                ["Mexican"] = "Poción de ira",
                ["Portuguese"] = "Poção de Raiva",
                ["Russian"] = "Зелье ярости",
                ["Spanish"] = "Poción de cólera",
                ["Taiwanese"] = "怒氣藥水",
            },
        },
        {
            ["id"] = 6618,
            ["items"] = {
                5643,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "暴怒药水",
                ["English"] = "Great Rage Potion",
                ["French"] = "Potion de Grande rage",
                ["German"] = "Großer Wuttrank",
                ["Korean"] = "상급 분노의 물약",
                ["Mexican"] = "Poción de gran ira",
                ["Portuguese"] = "Poção Grande de Raiva",
                ["Russian"] = "Сильнодействующее зелье ярости",
                ["Spanish"] = "Poción de gran furia",
                ["Taiwanese"] = "暴怒藥水",
            },
        },
        {
            ["id"] = 6624,
            ["items"] = {
                5642,
            },
            ["min_skill"] = 150,
            ["name"] = {
                ["Chinese"] = "自由行动药剂",
                ["English"] = "Free Action Potion",
                ["French"] = "Potion de libre action",
                ["German"] = "Trank der freien Aktion",
                ["Korean"] = "자유 의지의 물약",
                ["Mexican"] = "Poción de acción libre",
                ["Portuguese"] = "Poção de Ação Desimpedida",
                ["Russian"] = "Зелье свободы действий",
                ["Spanish"] = "Poción de acción libre",
                ["Taiwanese"] = "自由行動藥劑",
            },
        },
        {
            ["id"] = 7179,
            ["min_skill"] = 90,
            ["name"] = {
                ["Chinese"] = "水下呼吸药剂",
                ["English"] = "Elixir of Water Breathing",
                ["French"] = "Elixir de Respiration aquatique",
                ["German"] = "Elixier der Wasseratmung",
                ["Korean"] = "수중 호흡의 비약",
                ["Mexican"] = "Elixir de respiración acuática",
                ["Portuguese"] = "Elixir de Respiração Aquática",
                ["Russian"] = "Эликсир водного дыхания",
                ["Spanish"] = "Elixir de respiración acuática",
                ["Taiwanese"] = "水下呼吸藥劑",
            },
            ["trainers"] = {
                ["price"] = 450,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 7181,
            ["min_skill"] = 155,
            ["name"] = {
                ["Chinese"] = "强效治疗药水",
                ["English"] = "Greater Healing Potion",
                ["French"] = "Potion de soins supérieure",
                ["German"] = "Großer Heiltrank",
                ["Korean"] = "상급 치유 물약",
                ["Mexican"] = "Poción de sanación superior",
                ["Portuguese"] = "Poção Maior de Cura",
                ["Russian"] = "Сильное лечебное зелье",
                ["Spanish"] = "Poción superior de curación",
                ["Taiwanese"] = "強效治療藥水",
            },
            ["trainers"] = {
                ["price"] = 4500,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 7183,
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "初级防御药剂",
                ["English"] = "Elixir of Minor Defense",
                ["French"] = "Elixir de défense mineure",
                ["German"] = "Elixier der schwachen Verteidigung",
                ["Korean"] = "최하급 방어의 비약",
                ["Mexican"] = "Elixir de defensa menor",
                ["Portuguese"] = "Elixir de Defesa Menor",
                ["Russian"] = "Слабый эликсир защиты",
                ["Spanish"] = "Elixir de defensa menor",
                ["Taiwanese"] = "初級防禦藥劑",
            },
            ["special_action"] = "auto learned",
        },
        {
            ["id"] = 7255,
            ["items"] = {
                6053,
            },
            ["min_skill"] = 100,
            ["name"] = {
                ["Chinese"] = "神圣防护药水",
                ["English"] = "Holy Protection Potion",
                ["French"] = "Potion de protection contre le Sacré",
                ["German"] = "Heiligschutztrank",
                ["Korean"] = "신성 보호 물약",
                ["Mexican"] = "Poción de Protección contra lo Sagrado",
                ["Portuguese"] = "Poção de Proteção contra o Sagrado",
                ["Russian"] = "Зелье священной защиты",
                ["Spanish"] = "Poción de protección Sagrada",
                ["Taiwanese"] = "神聖防護藥水",
            },
        },
        {
            ["id"] = 7256,
            ["items"] = {
                6054,
            },
            ["min_skill"] = 135,
            ["name"] = {
                ["Chinese"] = "暗影防护药水",
                ["English"] = "Shadow Protection Potion",
                ["French"] = "Potion de protection contre l'Ombre",
                ["German"] = "Schattenschutztrank",
                ["Korean"] = "암흑 보호 물약",
                ["Mexican"] = "Poción de Protección contra las Sombras",
                ["Portuguese"] = "Poção de Proteção contra a Sombra",
                ["Russian"] = "Зелье защиты от темной магии",
                ["Spanish"] = "Poción de protección de las Sombras",
                ["Taiwanese"] = "暗影防護藥水",
            },
        },
        {
            ["id"] = 7257,
            ["items"] = {
                6055,
            },
            ["min_skill"] = 165,
            ["name"] = {
                ["Chinese"] = "火焰防护药水",
                ["English"] = "Fire Protection Potion",
                ["French"] = "Potion de protection contre le Feu",
                ["German"] = "Feuerschutztrank",
                ["Korean"] = "화염 보호 물약",
                ["Mexican"] = "Poción de Protección contra el Fuego",
                ["Portuguese"] = "Poção de Proteção contra o Fogo",
                ["Russian"] = "Зелье Огненной защиты",
                ["Spanish"] = "Poción de Protección al Fuego",
                ["Taiwanese"] = "火焰防護藥水",
            },
        },
        {
            ["id"] = 7258,
            ["items"] = {
                6056,
            },
            ["min_skill"] = 190,
            ["name"] = {
                ["Chinese"] = "冰霜防护药水",
                ["English"] = "Frost Protection Potion",
                ["French"] = "Potion de protection contre le Givre",
                ["German"] = "Frostschutztrank",
                ["Korean"] = "냉기 보호 물약",
                ["Mexican"] = "Poción de Protección contra la Escarcha",
                ["Portuguese"] = "Poção de Proteção contra o Gelo",
                ["Russian"] = "Зелье защиты от магии льда",
                ["Spanish"] = "Poción de Protección a la Escarcha",
                ["Taiwanese"] = "冰霜防護藥水",
            },
        },
        {
            ["id"] = 7259,
            ["items"] = {
                6057,
            },
            ["min_skill"] = 190,
            ["name"] = {
                ["Chinese"] = "自然防护药水",
                ["English"] = "Nature Protection Potion",
                ["French"] = "Potion de protection contre la Nature",
                ["German"] = "Naturschutztrank",
                ["Korean"] = "자연 보호 물약",
                ["Mexican"] = "Poción de Protección contra la Naturaleza",
                ["Portuguese"] = "Poção de Proteção contra a Natureza",
                ["Russian"] = "Зелье Природной защиты",
                ["Spanish"] = "Poción de protección de la naturaleza",
                ["Taiwanese"] = "自然防護藥水",
            },
        },
        {
            ["id"] = 7836,
            ["min_skill"] = 80,
            ["name"] = {
                ["Chinese"] = "黑口鱼油",
                ["English"] = "Blackmouth Oil",
                ["French"] = "Huile de bouche-noire",
                ["German"] = "Schwarzmaulöl",
                ["Korean"] = "아귀 오일",
                ["Mexican"] = "Aceite de bocanegra",
                ["Portuguese"] = "Óleo de Bocanera",
                ["Russian"] = "Масло черноротика",
                ["Spanish"] = "Aceite de bocanegra",
                ["Taiwanese"] = "黑口魚油",
            },
            ["trainers"] = {
                ["price"] = 250,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 7837,
            ["min_skill"] = 130,
            ["name"] = {
                ["Chinese"] = "火焰之油",
                ["English"] = "Fire Oil",
                ["French"] = "Huile de feu",
                ["German"] = "Feueröl",
                ["Korean"] = "화염 오일",
                ["Mexican"] = "Aceite de Fuego",
                ["Portuguese"] = "Óleo ígneo",
                ["Russian"] = "Зажигательное масло",
                ["Spanish"] = "Aceite de Fuego",
                ["Taiwanese"] = "火焰之油",
            },
            ["trainers"] = {
                ["price"] = 1000,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 7841,
            ["min_skill"] = 100,
            ["name"] = {
                ["Chinese"] = "速游药水",
                ["English"] = "Swim Speed Potion",
                ["French"] = "Potion de Nage rapide",
                ["German"] = "Schwimmtempotrank",
                ["Korean"] = "신속한 수영 물약",
                ["Mexican"] = "Poción de velocidad de nado",
                ["Portuguese"] = "Poção de Velocidade de Nado",
                ["Russian"] = "Зелье быстрого плавания",
                ["Spanish"] = "Poción de velocidad de nado",
                ["Taiwanese"] = "速遊藥水",
            },
            ["trainers"] = {
                ["price"] = 1000,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 7845,
            ["min_skill"] = 140,
            ["name"] = {
                ["Chinese"] = "火力药剂",
                ["English"] = "Elixir of Firepower",
                ["French"] = "Elixir de Maîtrise du feu",
                ["German"] = "Elixier der Feuermacht",
                ["Korean"] = "화염 강화의 비약",
                ["Mexican"] = "Elixir de poder de Fuego",
                ["Portuguese"] = "Elixir de Poder de Fogo",
                ["Russian"] = "Эликсир огневой мощи",
                ["Spanish"] = "Elixir de poder de Fuego",
                ["Taiwanese"] = "火力藥劑",
            },
            ["trainers"] = {
                ["price"] = 3000,
                ["sources"] = {
                    1386,
                    2391,
                    2837,
                    3009,
                    3347,
                    3964,
                    4160,
                    4609,
                    4611,
                    4900,
                    5177,
                    5499,
                    7948,
                    11042,
                },
            },
        },
        {
            ["id"] = 8240,
            ["items"] = {
                6663,
            },
            ["min_skill"] = 90,
            ["name"] = {
                ["Chinese"] = "增长药剂",
                ["English"] = "Elixir of Giant Growth",
                ["French"] = "Elixir de Taille de géant",
                ["German"] = "Elixier des Riesenwuchses",
                ["Korean"] = "성장의 비약",
                ["Mexican"] = "Elixir de crecimiento gigante",
                ["Portuguese"] = "Elixir de Crescimento Gigantesco",
                ["Russian"] = "Эликсир Увеличения",
                ["Spanish"] = "Elixir de crecimiento gigante",
                ["Taiwanese"] = "增長藥劑",
            },
        },
        {
            ["id"] = 11448,
            ["min_skill"] = 205,
            ["name"] = {
                ["Chinese"] = "强效法力药水",
                ["English"] = "Greater Mana Potion",
                ["French"] = "Potion de mana supérieure",
                ["German"] = "Großer Manatrank",
                ["Korean"] = "상급 마나 물약",
                ["Mexican"] = "Poción de maná superior",
                ["Portuguese"] = "Poção Maior de Mana",
                ["Russian"] = "Сильное зелье маны",
                ["Spanish"] = "Poción superior de maná",
                ["Taiwanese"] = "強效法力藥水",
            },
            ["trainers"] = {
                ["price"] = 8100,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 11449,
            ["min_skill"] = 185,
            ["name"] = {
                ["Chinese"] = "敏捷药剂",
                ["English"] = "Elixir of Agility",
                ["French"] = "Elixir d'Agilité",
                ["German"] = "Elixier der Beweglichkeit",
                ["Korean"] = "민첩의 비약",
                ["Mexican"] = "Elixir de agilidad",
                ["Portuguese"] = "Elixir de Agilidade",
                ["Russian"] = "Эликсир Ловкости",
                ["Spanish"] = "Elixir de agilidad",
                ["Taiwanese"] = "敏捷藥劑",
            },
            ["trainers"] = {
                ["price"] = 5850,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 11450,
            ["min_skill"] = 195,
            ["name"] = {
                ["Chinese"] = "强效防御药剂",
                ["English"] = "Elixir of Greater Defense",
                ["French"] = "Elixir de défense supérieure",
                ["German"] = "Elixier der großen Verteidigung",
                ["Korean"] = "상급 방어의 비약",
                ["Mexican"] = "Elixir de defensa superior",
                ["Portuguese"] = "Elixir de Defesa Maior",
                ["Russian"] = "Сильный эликсир защиты",
                ["Spanish"] = "Elixir de defensa superior",
                ["Taiwanese"] = "強效防禦藥劑",
            },
            ["trainers"] = {
                ["price"] = 6750,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 11451,
            ["min_skill"] = 205,
            ["name"] = {
                ["Chinese"] = "献祭之油",
                ["English"] = "Oil of Immolation",
                ["French"] = "Huile d'immolation",
                ["German"] = "Öl des Feuerbrandes",
                ["Korean"] = "제물의 오일",
                ["Mexican"] = "Aceite de inmolación",
                ["Portuguese"] = "Óleo de Imolação",
                ["Russian"] = "Воспламеняющая смесь",
                ["Spanish"] = "Aceite de inmolación",
                ["Taiwanese"] = "獻祭之油",
            },
            ["trainers"] = {
                ["price"] = 7200,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 11452,
            ["min_skill"] = 210,
            ["name"] = {
                ["Chinese"] = "滋补药剂",
                ["English"] = "Restorative Potion",
                ["French"] = "Potion de Restauration",
                ["German"] = "Regenerationstrank",
                ["Korean"] = "복원의 물약",
                ["Mexican"] = "Poción restauradora",
                ["Portuguese"] = "Poção de Restauração",
                ["Russian"] = "Приводящее в сознание зелье",
                ["Spanish"] = "Poción restauradora",
                ["Taiwanese"] = "滋補藥水",
            },
            ["quests"] = {
                2203,
                2501,
            },
        },
        {
            ["id"] = 11453,
            ["items"] = {
                9293,
            },
            ["min_skill"] = 210,
            ["name"] = {
                ["Chinese"] = "抗魔药水",
                ["English"] = "Magic Resistance Potion",
                ["French"] = "Potion de résistance à la magie",
                ["German"] = "Magiewiderstandtrank",
                ["Korean"] = "마법 저항 물약",
                ["Mexican"] = "Poción de resistencia a la magia",
                ["Portuguese"] = "Poção de Resistência à Magia",
                ["Russian"] = "Зелье защиты от магии",
                ["Spanish"] = "Poción de resistencia a la magia",
                ["Taiwanese"] = "抗魔藥水",
            },
        },
        {
            ["id"] = 11456,
            ["items"] = {
                10644,
            },
            ["min_skill"] = 210,
            ["name"] = {
                ["Chinese"] = "地精火箭燃油",
                ["English"] = "Goblin Rocket Fuel",
                ["French"] = "Carburant de fusée gobelin",
                ["German"] = "Goblin-Raketentreibstoff",
                ["Korean"] = "고블린 로켓 연료",
                ["Mexican"] = "Combustible de cohete goblin",
                ["Portuguese"] = "Combustível de Foguete Goblínico",
                ["Russian"] = "Гоблинское ракетное топливо",
                ["Spanish"] = "Gasolina de cohete goblin",
                ["Taiwanese"] = "哥布林火箭燃油",
            },
        },
        {
            ["id"] = 11457,
            ["min_skill"] = 215,
            ["name"] = {
                ["Chinese"] = "超强治疗药水",
                ["English"] = "Superior Healing Potion",
                ["French"] = "Potion de soins excellente",
                ["German"] = "Überragender Heiltrank",
                ["Korean"] = "최상급 치유 물약",
                ["Mexican"] = "Poción de sanación excelente",
                ["Portuguese"] = "Poção Superior de Cura",
                ["Russian"] = "Мощное лечебное зелье",
                ["Spanish"] = "Poción excelente de curación",
                ["Taiwanese"] = "超強治療藥水",
            },
            ["trainers"] = {
                ["price"] = 9000,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 11458,
            ["items"] = {
                9294,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "野葡萄药水",
                ["English"] = "Wildvine Potion",
                ["French"] = "Potion de sauvageonne",
                ["German"] = "Wildrankentrank",
                ["Korean"] = "야생덩굴 물약",
                ["Mexican"] = "Poción de atriplex salvaje",
                ["Portuguese"] = "Poção de Vinha Selvagem",
                ["Russian"] = "Виноградное зелье",
                ["Spanish"] = "Poción de atriplex salvaje",
                ["Taiwanese"] = "野葡萄藥水",
            },
        },
        {
            ["id"] = 11459,
            ["items"] = {
                9303,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "点金石",
                ["English"] = "Philosophers' Stone",
                ["French"] = "Pierre philosophale",
                ["German"] = "Stein der Weisen",
                ["Korean"] = "연금술사의 돌",
                ["Mexican"] = "Piedra filosofal",
                ["Portuguese"] = "Pedra Filosofal",
                ["Russian"] = "Философский камень",
                ["Spanish"] = "Piedra del filósofo",
                ["Taiwanese"] = "點金石",
            },
        },
        {
            ["id"] = 11460,
            ["min_skill"] = 230,
            ["name"] = {
                ["Chinese"] = "侦测亡灵药剂",
                ["English"] = "Elixir of Detect Undead",
                ["French"] = "Elixir de Détection des morts-vivants",
                ["German"] = "Elixier der Untotenentdeckung",
                ["Korean"] = "언데드 감지의 비약",
                ["Mexican"] = "Elixir de detección de no-muertos",
                ["Portuguese"] = "Elixir de Detecção de Mortos-vivos",
                ["Russian"] = "Эликсир обнаружения Нежити",
                ["Spanish"] = "Elixir de detección de no-muertos",
                ["Taiwanese"] = "偵測不死生物藥劑",
            },
            ["trainers"] = {
                ["price"] = 4500,
                ["sources"] = {
                    1386,
                    7948,
                },
            },
        },
        {
            ["id"] = 11461,
            ["min_skill"] = 235,
            ["name"] = {
                ["Chinese"] = "奥法药剂",
                ["English"] = "Arcane Elixir",
                ["French"] = "Elixir des arcanes",
                ["German"] = "Arkanes Elixier",
                ["Korean"] = "신비의 비약",
                ["Mexican"] = "Elixir Arcano",
                ["Portuguese"] = "Elixir Arcano",
                ["Russian"] = "Чародейский эликсир",
                ["Spanish"] = "Elixir Arcano",
                ["Taiwanese"] = "祕法藥劑",
            },
            ["trainers"] = {
                ["price"] = 9000,
                ["sources"] = {
                    1386,
                    7948,
                },
            },
        },
        {
            ["id"] = 11464,
            ["items"] = {
                9295,
            },
            ["min_skill"] = 235,
            ["name"] = {
                ["Chinese"] = "隐形药水",
                ["English"] = "Invisibility Potion",
                ["French"] = "Potion d'invisibilité",
                ["German"] = "Unsichtbarkeitstrank",
                ["Korean"] = "투명 물약",
                ["Mexican"] = "Poción de invisibilidad",
                ["Portuguese"] = "Poção de Invisibilidade",
                ["Russian"] = "Зелье невидимости",
                ["Spanish"] = "Poción de invisibilidad",
                ["Taiwanese"] = "隱形藥水",
            },
        },
        {
            ["id"] = 11465,
            ["min_skill"] = 235,
            ["name"] = {
                ["Chinese"] = "强效聪颖药剂",
                ["English"] = "Elixir of Greater Intellect",
                ["French"] = "Elixir d'Intelligence supérieure",
                ["German"] = "Elixier der großen Intelligenz",
                ["Korean"] = "상급 지능의 비약",
                ["Mexican"] = "Elixir de intelecto superior",
                ["Portuguese"] = "Elixir de Intelecto Maior",
                ["Russian"] = "Сильный эликсир интеллекта",
                ["Spanish"] = "Elixir de intelecto superior",
                ["Taiwanese"] = "強效聰穎藥劑",
            },
            ["trainers"] = {
                ["price"] = 10800,
                ["sources"] = {
                    1386,
                    7948,
                },
            },
        },
        {
            ["id"] = 11466,
            ["items"] = {
                9296,
            },
            ["min_skill"] = 240,
            ["name"] = {
                ["Chinese"] = "阿尔萨斯的礼物",
                ["English"] = "Gift of Arthas",
                ["French"] = "Don d'Arthas",
                ["German"] = "Arthas' Gabe",
                ["Korean"] = "아서스의 선물",
                ["Mexican"] = "Ofrenda de Arthas",
                ["Portuguese"] = "Dádiva de Arthas",
                ["Russian"] = "Дар Артаса",
                ["Spanish"] = "Regalo de Arthas",
                ["Taiwanese"] = "阿薩斯的賜福",
            },
        },
        {
            ["id"] = 11467,
            ["min_skill"] = 240,
            ["name"] = {
                ["Chinese"] = "强效敏捷药剂",
                ["English"] = "Elixir of Greater Agility",
                ["French"] = "Elixir d'Agilité supérieure",
                ["German"] = "Elixier der großen Beweglichkeit",
                ["Korean"] = "상급 민첩의 비약",
                ["Mexican"] = "Elixir de agilidad superior",
                ["Portuguese"] = "Elixir de Agilidade Maior",
                ["Russian"] = "Сильный эликсир ловкости",
                ["Spanish"] = "Elixir de agilidad superior",
                ["Taiwanese"] = "強效敏捷藥劑",
            },
            ["trainers"] = {
                ["price"] = 10800,
                ["sources"] = {
                    1386,
                    7948,
                },
            },
        },
        {
            ["id"] = 11468,
            ["items"] = {
                9297,
            },
            ["min_skill"] = 240,
            ["name"] = {
                ["Chinese"] = "梦境药剂",
                ["English"] = "Elixir of Dream Vision",
                ["French"] = "Elixir de Vision de rêve",
                ["German"] = "Elixier der Traumvision",
                ["Korean"] = "몽상의 비약",
                ["Mexican"] = "Elixir de Visión onírica",
                ["Portuguese"] = "Elixir de Visão de Sonhos",
                ["Russian"] = "Эликсир Снозрения",
                ["Spanish"] = "Elixir de visión onírica",
                ["Taiwanese"] = "夢境藥劑",
            },
        },
        {
            ["id"] = 11472,
            ["items"] = {
                9298,
            },
            ["min_skill"] = 245,
            ["name"] = {
                ["Chinese"] = "巨人药剂",
                ["English"] = "Elixir of Giants",
                ["French"] = "Elixir des géants",
                ["German"] = "Elixier der Riesen",
                ["Korean"] = "거인의 비약",
                ["Mexican"] = "Elixir de gigantes",
                ["Portuguese"] = "Elixir de Gigantes",
                ["Russian"] = "Эликсир Великанов",
                ["Spanish"] = "Elixir de gigantes",
                ["Taiwanese"] = "巨人藥劑",
            },
        },
        {
            ["id"] = 11473,
            ["items"] = {
                9302,
            },
            ["min_skill"] = 245,
            ["name"] = {
                ["Chinese"] = "幻象染料",
                ["English"] = "Ghost Dye",
                ["French"] = "Teinture fantôme",
                ["German"] = "Geisterfarbstoff",
                ["Korean"] = "유령 염료",
                ["Mexican"] = "Tinte fantasmal",
                ["Portuguese"] = "Pigmento Fantasma",
                ["Russian"] = "Призрачная краска",
                ["Spanish"] = "Tintura fantasmal",
                ["Taiwanese"] = "幻象染料",
            },
        },
        {
            ["id"] = 11476,
            ["items"] = {
                9301,
            },
            ["min_skill"] = 250,
            ["name"] = {
                ["Chinese"] = "暗影之力药剂",
                ["English"] = "Elixir of Shadow Power",
                ["French"] = "Elixir de Puissance de l'ombre",
                ["German"] = "Elixier der Schattenmacht",
                ["Korean"] = "암흑 강화의 비약",
                ["Mexican"] = "Elixir de poder de las Sombras",
                ["Portuguese"] = "Elixir de Poder Sombrio",
                ["Russian"] = "Эликсир силы тьмы",
                ["Spanish"] = "Elixir de poder de las sombras",
                ["Taiwanese"] = "暗影之力藥劑",
            },
        },
        {
            ["id"] = 11477,
            ["items"] = {
                9300,
            },
            ["min_skill"] = 250,
            ["name"] = {
                ["Chinese"] = "屠魔药剂",
                ["English"] = "Elixir of Demonslaying",
                ["French"] = "Elixir de Tueur de démons",
                ["German"] = "Elixier des Dämonentötens",
                ["Korean"] = "악마 사냥 전문화의 비약",
                ["Mexican"] = "Elixir de matanza de demonios",
                ["Portuguese"] = "Elixir de Demonicídio",
                ["Russian"] = "Эликсир убийства демонов",
                ["Spanish"] = "Elixir de matanza de demonios",
                ["Taiwanese"] = "屠魔藥劑",
            },
        },
        {
            ["id"] = 11478,
            ["min_skill"] = 250,
            ["name"] = {
                ["Chinese"] = "侦测恶魔药剂",
                ["English"] = "Elixir of Detect Demon",
                ["French"] = "Elixir de Détection des démons",
                ["German"] = "Elixier der Dämonenentdeckung",
                ["Korean"] = "악마 감지의 비약",
                ["Mexican"] = "Elixir de detección de demonios",
                ["Portuguese"] = "Elixir de Detecção de Demônios",
                ["Russian"] = "Эликсир обнаружения демонов",
                ["Spanish"] = "Elixir de detección de demonios",
                ["Taiwanese"] = "偵測惡魔藥劑",
            },
            ["trainers"] = {
                ["price"] = 12600,
                ["sources"] = {
                    1386,
                    7948,
                },
            },
        },
        {
            ["id"] = 11479,
            ["items"] = {
                9304,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "点铁成金",
                ["English"] = "Transmute: Iron to Gold",
                ["French"] = "Transmutation : Fer en Or",
                ["German"] = "Transmutieren: Eisen in Gold",
                ["Korean"] = "변환식: 철을 금으로",
                ["Mexican"] = "Transmutar: hierro a oro",
                ["Portuguese"] = "Transmutar: Ferro em Ouro",
                ["Russian"] = "Трансмутация железа в золото",
                ["Spanish"] = "Transmutar: hierro a oro",
                ["Taiwanese"] = "點鐵成金",
            },
        },
        {
            ["id"] = 11480,
            ["items"] = {
                9305,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "转化秘银",
                ["English"] = "Transmute: Mithril to Truesilver",
                ["French"] = "Transmutation de mithril en vrai-argent",
                ["German"] = "Transmutieren: Mithril in Echtsilber",
                ["Korean"] = "변환식: 미스릴을 진은으로",
                ["Mexican"] = "Transmutar: mitril a veraplata",
                ["Portuguese"] = "Transmutar: Mithril em Veraprata",
                ["Russian"] = "Трансмутация мифрила в истинное серебро",
                ["Spanish"] = "Transmutar: mitril a veraplata",
                ["Taiwanese"] = "轉化秘銀",
            },
        },
        {
            ["id"] = 12609,
            ["min_skill"] = 200,
            ["name"] = {
                ["Chinese"] = "猫眼药剂",
                ["English"] = "Catseye Elixir",
                ["French"] = "Elixir d'oeil de chat",
                ["German"] = "Katzenaugenelixier",
                ["Korean"] = "고양이눈 비약",
                ["Mexican"] = "Elixir de ojo de gato",
                ["Portuguese"] = "Elixir Olho de Gato",
                ["Russian"] = "Эликсир \"Кошачий глаз\"",
                ["Spanish"] = "Elixir Ojodegato",
                ["Taiwanese"] = "貓眼藥劑",
            },
            ["trainers"] = {
                ["price"] = 7200,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 15833,
            ["min_skill"] = 230,
            ["name"] = {
                ["Chinese"] = "昏睡药水",
                ["English"] = "Dreamless Sleep Potion",
                ["French"] = "Potion de sommeil sans rêve",
                ["German"] = "Trank des traumlosen Schlafs",
                ["Korean"] = "숙면의 물약",
                ["Mexican"] = "Poción de letargo sin sueños",
                ["Portuguese"] = "Poção do Sono sem Sonhos",
                ["Russian"] = "Зелье спокойного сна",
                ["Spanish"] = "Poción de letargo sin sueños",
                ["Taiwanese"] = "昏睡藥水",
            },
            ["trainers"] = {
                ["price"] = 9000,
                ["sources"] = {
                    1386,
                    7948,
                },
            },
        },
        {
            ["id"] = 17187,
            ["items"] = {
                12958,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：奥金",
                ["English"] = "Transmute: Arcanite",
                ["French"] = "Transmutation d'arcanite",
                ["German"] = "Transmutieren: Arkanit",
                ["Korean"] = "변환식: 아케이나이트",
                ["Mexican"] = "Transmutar: arcanita",
                ["Portuguese"] = "Transmutar: Arcanita",
                ["Russian"] = "Трансмутация: арканит",
                ["Spanish"] = "Transmutar: arcanita",
                ["Taiwanese"] = "轉化：奧金",
            },
        },
        {
            ["id"] = 17551,
            ["min_skill"] = 250,
            ["name"] = {
                ["Chinese"] = "石鳞鱼油",
                ["English"] = "Stonescale Oil",
                ["French"] = "Huile de pierre-écaille",
                ["German"] = "Steinschuppenöl",
                ["Korean"] = "돌비늘 오일",
                ["Mexican"] = "Aceite de escama pétrea",
                ["Portuguese"] = "Óleo de Petrescama",
                ["Russian"] = "Масло каменного угря",
                ["Spanish"] = "Aceite de escamas de piedra",
                ["Taiwanese"] = "石鱗魚油",
            },
            ["trainers"] = {
                ["price"] = 13500,
                ["sources"] = {
                    1386,
                    7948,
                },
            },
        },
        {
            ["id"] = 17552,
            ["items"] = {
                13476,
            },
            ["min_skill"] = 255,
            ["name"] = {
                ["Chinese"] = "强效怒气药水",
                ["English"] = "Mighty Rage Potion",
                ["French"] = "Potion de rage puissante",
                ["German"] = "Mächtiger Wuttrank",
                ["Korean"] = "강력한 분노의 물약",
                ["Mexican"] = "Poción de ira poderosa",
                ["Portuguese"] = "Poção Potente de Raiva",
                ["Russian"] = "Мощное зелье ярости",
                ["Spanish"] = "Poción de furia poderosa",
                ["Taiwanese"] = "強效怒氣藥水",
            },
        },
        {
            ["id"] = 17553,
            ["items"] = {
                13477,
            },
            ["min_skill"] = 260,
            ["name"] = {
                ["Chinese"] = "超强法力药水",
                ["English"] = "Superior Mana Potion",
                ["French"] = "Potion de mana excellente",
                ["German"] = "Überragender Manatrank",
                ["Korean"] = "최상급 마나 물약",
                ["Mexican"] = "Poción de maná excelente",
                ["Portuguese"] = "Poção Superior de Mana",
                ["Russian"] = "Мощное зелье маны",
                ["Spanish"] = "Poción excelente de maná",
                ["Taiwanese"] = "超強法力藥水",
            },
        },
        {
            ["id"] = 17554,
            ["items"] = {
                13478,
            },
            ["min_skill"] = 265,
            ["name"] = {
                ["Chinese"] = "超强防御药剂",
                ["English"] = "Elixir of Superior Defense",
                ["French"] = "Elixir de défense excellente",
                ["German"] = "Elixier der überragenden Verteidigung",
                ["Korean"] = "최상급 방어의 비약",
                ["Mexican"] = "Elixir de defensa excelente",
                ["Portuguese"] = "Elixir de Defesa Superior",
                ["Russian"] = "Мощный эликсир защиты",
                ["Spanish"] = "Elixir de defensa superior",
                ["Taiwanese"] = "超強防禦藥劑",
            },
        },
        {
            ["id"] = 17555,
            ["items"] = {
                13479,
            },
            ["min_skill"] = 270,
            ["name"] = {
                ["Chinese"] = "先知药剂",
                ["English"] = "Elixir of the Sages",
                ["French"] = "Elixir des Sages",
                ["German"] = "Elixier der Weisen",
                ["Korean"] = "현인의 비약",
                ["Mexican"] = "Elixir de los sabios",
                ["Portuguese"] = "Elixir dos Sábios",
                ["Russian"] = "Эликсир Мудреца",
                ["Spanish"] = "Elixir de los sabios",
                ["Taiwanese"] = "先知藥劑",
            },
        },
        {
            ["id"] = 17556,
            ["items"] = {
                13480,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "特效治疗药水",
                ["English"] = "Major Healing Potion",
                ["French"] = "Potion de soins majeure",
                ["German"] = "Erheblicher Heiltrank",
                ["Korean"] = "일급 치유 물약",
                ["Mexican"] = "Poción de sanación sublime",
                ["Portuguese"] = "Poção Elevada de Cura",
                ["Russian"] = "Сильнейшее лечебное зелье",
                ["Spanish"] = "poción sublime de curación",
                ["Taiwanese"] = "極效治療藥水",
            },
        },
        {
            ["id"] = 17557,
            ["items"] = {
                13481,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "蛮力药剂",
                ["English"] = "Elixir of Brute Force",
                ["French"] = "Elixir de Force de brute",
                ["German"] = "Elixier der rohen Gewalt",
                ["Korean"] = "야수 힘의 비약",
                ["Mexican"] = "Elixir de fuerza bruta",
                ["Portuguese"] = "Elixir da Força Bruta",
                ["Russian"] = "Эликсир Грубой силы",
                ["Spanish"] = "Elixir de fuerza bruta",
                ["Taiwanese"] = "蠻力藥劑",
            },
        },
        {
            ["id"] = 17559,
            ["items"] = {
                13482,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：点气成火",
                ["English"] = "Transmute: Air to Fire",
                ["French"] = "Transmutation de l'Air en Feu",
                ["German"] = "Transmutieren: Luft zu Feuer",
                ["Korean"] = "변환식: 바람을 불로",
                ["Mexican"] = "Transmutar: aire en fuego",
                ["Portuguese"] = "Transmutar: Ar em Fogo",
                ["Russian"] = "Трансмутация: воздух в огонь",
                ["Spanish"] = "Transmutar: aire en fuego",
                ["Taiwanese"] = "轉化：點氣成火",
            },
        },
        {
            ["id"] = 17560,
            ["items"] = {
                13483,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：点火成土",
                ["English"] = "Transmute: Fire to Earth",
                ["French"] = "Transmutation du Feu en Terre",
                ["German"] = "Transmutieren: Feuer zu Erde",
                ["Korean"] = "변환식: 불을 대지로",
                ["Mexican"] = "Transmutar: fuego a tierra",
                ["Portuguese"] = "Transmutar: Fogo em Terra",
                ["Russian"] = "Трансмутация: огонь в землю",
                ["Spanish"] = "Transmutar: fuego a tierra",
                ["Taiwanese"] = "轉化：點火成土",
            },
        },
        {
            ["id"] = 17561,
            ["items"] = {
                13484,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：转土成水",
                ["English"] = "Transmute: Earth to Water",
                ["French"] = "Transmutation de la Terre en Eau",
                ["German"] = "Transmutieren: Erde zu Wasser",
                ["Korean"] = "변환식: 대지를 물로",
                ["Mexican"] = "Transmutar: tierra a agua",
                ["Portuguese"] = "Transmutar: Terra em Água",
                ["Russian"] = "Трансмутация: земля в воду",
                ["Spanish"] = "Transmutar: tierra a agua",
                ["Taiwanese"] = "轉化：轉土成水",
            },
        },
        {
            ["id"] = 17562,
            ["items"] = {
                13485,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：点水成气",
                ["English"] = "Transmute: Water to Air",
                ["French"] = "Transmutation de l'Eau en Air",
                ["German"] = "Transmutieren: Wasser zu Luft",
                ["Korean"] = "변환식: 물을 바람으로",
                ["Mexican"] = "Transmutar: agua a aire",
                ["Portuguese"] = "Transmutar: Água em Ar",
                ["Russian"] = "Трансмутация: вода в воздух",
                ["Spanish"] = "Transmutar: agua a aire",
                ["Taiwanese"] = "轉化：點水成氣",
            },
        },
        {
            ["id"] = 17563,
            ["items"] = {
                13486,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：死灵化水",
                ["English"] = "Transmute: Undeath to Water",
                ["French"] = "Transmutation du Non-mort en Eau",
                ["German"] = "Transmutieren: Untod zu Wasser",
                ["Korean"] = "변환식: 불사를 물로",
                ["Mexican"] = "Transmutar: no-muerte a agua",
                ["Portuguese"] = "Transmutar: Morte-viva em Água",
                ["Russian"] = "Трансмутация: нежитие в воду",
                ["Spanish"] = "Transmutar: no-muerte a agua",
                ["Taiwanese"] = "轉化：死靈化水",
            },
        },
        {
            ["id"] = 17564,
            ["items"] = {
                13487,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：水转死灵",
                ["English"] = "Transmute: Water to Undeath",
                ["French"] = "Transmutation de l'Eau en Non-mort",
                ["German"] = "Transmutieren: Wasser zu Untod",
                ["Korean"] = "변환식: 물을 불사로",
                ["Mexican"] = "Transmutar: agua a no-muerte",
                ["Portuguese"] = "Transmutar: Água em Morte-viva",
                ["Russian"] = "Трансмутация: вода в нежитие",
                ["Spanish"] = "Transmutar: agua a no-muerte",
                ["Taiwanese"] = "轉化：水轉死靈",
            },
        },
        {
            ["id"] = 17565,
            ["items"] = {
                13488,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：生命归土",
                ["English"] = "Transmute: Life to Earth",
                ["French"] = "Transmutation de la Vie en Terre",
                ["German"] = "Transmutieren: Leben zu Erde",
                ["Korean"] = "변환식: 생명을 대지로",
                ["Mexican"] = "Transmutar: vida a tierra",
                ["Portuguese"] = "Transmutar: Vida em Terra",
                ["Russian"] = "Трансмутация: жизнь в землю",
                ["Spanish"] = "Transmutar: vida a tierra",
                ["Taiwanese"] = "轉化：生命歸土",
            },
        },
        {
            ["id"] = 17566,
            ["items"] = {
                13489,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "转化：土转生命",
                ["English"] = "Transmute: Earth to Life",
                ["French"] = "Transmutation de la Terre en Vie",
                ["German"] = "Transmutieren: Erde zu Leben",
                ["Korean"] = "변환식: 대지를 생명으로",
                ["Mexican"] = "Transmutar: tierra a vida",
                ["Portuguese"] = "Transmutar: Terra em Vida",
                ["Russian"] = "Трансмутация: земля в жизнь",
                ["Spanish"] = "Transmutar: tierra a vida",
                ["Taiwanese"] = "轉化：土轉生命",
            },
        },
        {
            ["id"] = 17570,
            ["items"] = {
                13490,
            },
            ["min_skill"] = 280,
            ["name"] = {
                ["Chinese"] = "强效石盾药水",
                ["English"] = "Greater Stoneshield Potion",
                ["French"] = "Potion de Bouclier de pierre supérieure",
                ["German"] = "Großer Steinschildtrank",
                ["Korean"] = "상급 돌방패 물약",
                ["Mexican"] = "Poción de escudo de piedra superior",
                ["Portuguese"] = "Poção Maior de Escudopétreo",
                ["Russian"] = "Сильное зелье каменного щита",
                ["Spanish"] = "Poción petrescudo superior",
                ["Taiwanese"] = "強效石盾藥水",
            },
        },
        {
            ["id"] = 17571,
            ["items"] = {
                13491,
            },
            ["min_skill"] = 280,
            ["name"] = {
                ["Chinese"] = "猫鼬药剂",
                ["English"] = "Elixir of the Mongoose",
                ["French"] = "Elixir de la Mangouste",
                ["German"] = "Elixier des Mungos",
                ["Korean"] = "살쾡이의 비약",
                ["Mexican"] = "Elixir de la mangosta",
                ["Portuguese"] = "Elixir do Mangusto",
                ["Russian"] = "Эликсир Мангуста",
                ["Spanish"] = "Elixir de la mangosta",
                ["Taiwanese"] = "貓鼬藥劑",
            },
        },
        {
            ["id"] = 17572,
            ["items"] = {
                13492,
            },
            ["min_skill"] = 285,
            ["name"] = {
                ["Chinese"] = "净化药水",
                ["English"] = "Purification Potion",
                ["French"] = "Potion de purification",
                ["German"] = "Läuterungstrank",
                ["Korean"] = "정화 물약",
                ["Mexican"] = "Poción de purificación",
                ["Portuguese"] = "Poção de Purificação",
                ["Russian"] = "Зелье Очищения",
                ["Spanish"] = "Poción de purificación",
                ["Taiwanese"] = "淨化藥水",
            },
        },
        {
            ["id"] = 17573,
            ["items"] = {
                13493,
            },
            ["min_skill"] = 285,
            ["name"] = {
                ["Chinese"] = "强效奥法药剂",
                ["English"] = "Greater Arcane Elixir",
                ["French"] = "Elixir des arcanes supérieur",
                ["German"] = "Großes Arkanelixier",
                ["Korean"] = "상급 신비의 비약",
                ["Mexican"] = "Elixir Arcano superior",
                ["Portuguese"] = "Elixir Arcano Maior",
                ["Russian"] = "Сильный чародейский эликсир",
                ["Spanish"] = "Elixir superior Arcano",
                ["Taiwanese"] = "強效祕法藥劑",
            },
        },
        {
            ["id"] = 17574,
            ["items"] = {
                13494,
            },
            ["min_skill"] = 290,
            ["name"] = {
                ["Chinese"] = "强效火焰防护药水",
                ["English"] = "Greater Fire Protection Potion",
                ["French"] = "Potion de Protection contre le Feu supérieure",
                ["German"] = "Großer Feuerschutztrank",
                ["Korean"] = "상급 화염 보호 물약",
                ["Mexican"] = "Poción de Protección contra el Fuego superior",
                ["Portuguese"] = "Poção Maior de Proteção contra o Fogo",
                ["Russian"] = "Сильное зелье защиты от огня",
                ["Spanish"] = "Poción superior de protección de Fuego",
                ["Taiwanese"] = "強效火焰防護藥水",
            },
        },
        {
            ["id"] = 17575,
            ["items"] = {
                13495,
            },
            ["min_skill"] = 290,
            ["name"] = {
                ["Chinese"] = "强效冰霜防护药水",
                ["English"] = "Greater Frost Protection Potion",
                ["French"] = "Potion de protection contre le Givre supérieure",
                ["German"] = "Großer Frostschutztrank",
                ["Korean"] = "상급 냉기 보호 물약",
                ["Mexican"] = "Poción de Protección contra la Escarcha superior",
                ["Portuguese"] = "Poção Maior de Proteção contra o Gelo",
                ["Russian"] = "Сильное зелье защиты от магии льда",
                ["Spanish"] = "Poción superior de protección a la Escarcha",
                ["Taiwanese"] = "強效冰霜防護藥水",
            },
        },
        {
            ["id"] = 17576,
            ["items"] = {
                13496,
            },
            ["min_skill"] = 290,
            ["name"] = {
                ["Chinese"] = "强效自然防护药水",
                ["English"] = "Greater Nature Protection Potion",
                ["French"] = "Potion de protection contre la Nature supérieure",
                ["German"] = "Großer Naturschutztrank",
                ["Korean"] = "상급 자연 보호 물약",
                ["Mexican"] = "Poción de Protección contra la Naturaleza superior",
                ["Portuguese"] = "Poção Maior de Proteção contra a Natureza",
                ["Russian"] = "Великая таинственная субстанция",
                ["Spanish"] = "Poción superior de protección a la Naturaleza",
                ["Taiwanese"] = "強效自然防護藥水",
            },
        },
        {
            ["id"] = 17577,
            ["items"] = {
                13497,
            },
            ["min_skill"] = 290,
            ["name"] = {
                ["Chinese"] = "强效奥术防护药水",
                ["English"] = "Greater Arcane Protection Potion",
                ["French"] = "Potion de protection contre les Arcanes supérieure",
                ["German"] = "Großer Arkanschutztrank",
                ["Korean"] = "상급 비전 보호 물약",
                ["Mexican"] = "Poción de Protección contra lo Arcano superior",
                ["Portuguese"] = "Poção Maior de Proteção contra o Arcano",
                ["Russian"] = "Сильный чародейский эликсир",
                ["Spanish"] = "Poción superior de protección Arcana",
                ["Taiwanese"] = "強效祕法防護藥水",
            },
        },
        {
            ["id"] = 17578,
            ["items"] = {
                13499,
            },
            ["min_skill"] = 290,
            ["name"] = {
                ["Chinese"] = "强效暗影防护药水",
                ["English"] = "Greater Shadow Protection Potion",
                ["French"] = "Potion de protection contre l'Ombre supérieure",
                ["German"] = "Großer Schattenschutztrank",
                ["Korean"] = "상급 암흑 보호 물약",
                ["Mexican"] = "Poción de Protección contra las Sombras superior",
                ["Portuguese"] = "Poção Maior de Proteção contra a Sombra",
                ["Russian"] = "Великая таинственная субстанция",
                ["Spanish"] = "Poción superior de protección a las Sombras",
                ["Taiwanese"] = "強效暗影防護藥水",
            },
        },
        {
            ["id"] = 17580,
            ["items"] = {
                13501,
            },
            ["min_skill"] = 295,
            ["name"] = {
                ["Chinese"] = "特效法力药水",
                ["English"] = "Major Mana Potion",
                ["French"] = "Potion de mana majeure",
                ["German"] = "Erheblicher Manatrank",
                ["Korean"] = "일급 마나 물약",
                ["Mexican"] = "Poción de maná sublime",
                ["Portuguese"] = "Poção Elevada de Mana",
                ["Russian"] = "Сильнейшее зелье маны",
                ["Spanish"] = "poción sublime de maná",
                ["Taiwanese"] = "極效法力藥水",
            },
        },
        {
            ["id"] = 17634,
            ["items"] = {
                13518,
            },
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "化石合剂",
                ["English"] = "Flask of Petrification",
                ["French"] = "Flacon de pétrification",
                ["German"] = "Fläschchen der Versteinerung",
                ["Korean"] = "석화의 영약",
                ["Mexican"] = "Frasco de petrificación",
                ["Portuguese"] = "Frasco de Petrificação",
                ["Russian"] = "Склянка Оцепенения",
                ["Spanish"] = "Frasco de petrificación",
                ["Taiwanese"] = "石化精煉藥水",
            },
        },
        {
            ["id"] = 17635,
            ["items"] = {
                13519,
            },
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "泰坦合剂",
                ["English"] = "Flask of the Titans",
                ["French"] = "Flacon des Titans",
                ["German"] = "Fläschchen der Titanen",
                ["Korean"] = "티탄의 영약",
                ["Mexican"] = "Frasco de los titanes",
                ["Portuguese"] = "Frasco dos Titãs",
                ["Russian"] = "Склянка Титанов",
                ["Spanish"] = "Frasco de los titanes",
                ["Taiwanese"] = "泰坦精煉藥水",
            },
        },
        {
            ["id"] = 17636,
            ["items"] = {
                13520,
            },
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "精炼智慧合剂",
                ["English"] = "Flask of Distilled Wisdom",
                ["French"] = "Flacon de sagesse distillée",
                ["German"] = "Fläschchen mit destillierter Weisheit",
                ["Korean"] = "순수한 지혜의 영약",
                ["Mexican"] = "Frasco de sabiduría destilada",
                ["Portuguese"] = "Frasco de Sabedoria Destilada",
                ["Russian"] = "Склянка Концентрированной мудрости",
                ["Spanish"] = "Frasco de sabiduría destilada",
                ["Taiwanese"] = "智慧精煉藥水",
            },
        },
        {
            ["id"] = 17637,
            ["items"] = {
                13521,
            },
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "超级能量合剂",
                ["English"] = "Flask of Supreme Power",
                ["French"] = "Flacon de pouvoir suprême",
                ["German"] = "Fläschchen mit oberster Macht",
                ["Korean"] = "강력한 마력의 영약",
                ["Mexican"] = "Frasco de poder supremo",
                ["Portuguese"] = "Frasco de Poder Supremo",
                ["Russian"] = "Склянка Великой силы",
                ["Spanish"] = "Frasco de poder supremo",
                ["Taiwanese"] = "超級能量精煉藥水",
            },
        },
        {
            ["id"] = 17638,
            ["items"] = {
                13522,
            },
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "多重抗性合剂",
                ["English"] = "Flask of Chromatic Resistance",
                ["French"] = "Flacon de résistance chromatique",
                ["German"] = "Fläschchen mit chromatischem Widerstand",
                ["Korean"] = "마력 저항의 영약",
                ["Mexican"] = "Frasco de resistencia cromática",
                ["Portuguese"] = "Frasco de Resistência Cromática",
                ["Russian"] = "Склянка Разноцветной устойчивости",
                ["Spanish"] = "Frasco de resistencia cromática",
                ["Taiwanese"] = "多重抗性精煉藥水",
            },
        },
        {
            ["id"] = 21923,
            ["items"] = {
                17709,
            },
            ["min_skill"] = 190,
            ["name"] = {
                ["Chinese"] = "冰霜之力药剂",
                ["English"] = "Elixir of Frost Power",
                ["French"] = "Elixir de Puissance du givre",
                ["German"] = "Elixier der Frostmacht",
                ["Korean"] = "냉기 강화의 비약",
                ["Mexican"] = "Elixir de poder de Escarcha",
                ["Portuguese"] = "Elixir de Poder Gélido",
                ["Russian"] = "Эликсир Силы льда",
                ["Spanish"] = "Elixir de poder de Escarcha",
                ["Taiwanese"] = "冰霜之力藥劑",
            },
        },
        {
            ["id"] = 22732,
            ["items"] = {
                18257,
            },
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "特效活力药水",
                ["English"] = "Major Rejuvenation Potion",
                ["French"] = "Potion de régénération majeure",
                ["German"] = "Erheblicher Verjüngungstrank",
                ["Korean"] = "일급 회복 물약",
                ["Mexican"] = "Poción de rejuvenecimiento sublime",
                ["Portuguese"] = "Poção Elevada de Rejuvenescimento",
                ["Russian"] = "Сильнейшее зелье омоложения",
                ["Spanish"] = "Poción sublime de rejuvenecimiento",
                ["Taiwanese"] = "極效活力藥水",
            },
        },
        {
            ["id"] = 22808,
            ["min_skill"] = 215,
            ["name"] = {
                ["Chinese"] = "强效水下呼吸药剂",
                ["English"] = "Elixir of Greater Water Breathing",
                ["French"] = "Elixir de Respiration aquatique supérieure",
                ["German"] = "Elixier der verbesserten Wasseratmung",
                ["Korean"] = "상급 수중 호흡의 비약",
                ["Mexican"] = "Elixir de respiración acuática superior",
                ["Portuguese"] = "Elixir de Respiração Aquática Maior",
                ["Russian"] = "Сильный эликсир водного дыхания",
                ["Spanish"] = "Elixir de respiración acuática superior",
                ["Taiwanese"] = "強效水下呼吸藥劑",
            },
            ["trainers"] = {
                ["price"] = 9000,
                ["sources"] = {
                    1386,
                    4160,
                    4611,
                    7948,
                },
            },
        },
        {
            ["id"] = 24266,
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "古拉巴什魔精",
                ["English"] = "Gurubashi Mojo Madness",
                ["French"] = "Folie mojo des Gurubashi",
                ["German"] = "Mojowahnsinn der Gurubashi",
                ["Korean"] = "광기의 구루바시 모조",
                ["Mexican"] = "Locura de mojo Gurubashi",
                ["Portuguese"] = "Insânia Mojo Gurubashi",
                ["Russian"] = "Амулет безумия Гурубаши",
                ["Spanish"] = "Locura de mojo Gurubashi",
                ["Taiwanese"] = "古拉巴什魔精",
            },
            ["objects"] = {
                180368,
            },
            ["special_action"] = "inspect tablet madness",
        },
        {
            ["id"] = 24365,
            ["items"] = {
                20011,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "魔血药水",
                ["English"] = "Mageblood Potion",
                ["French"] = "Potion Magesang",
                ["German"] = "Magierbluttrank",
                ["Korean"] = "마력의 물약",
                ["Mexican"] = "Poción de sangre de mago",
                ["Portuguese"] = "Poção de Sangue de Mago",
                ["Russian"] = "Зелье крови волшебника",
                ["Spanish"] = "Poción de sangre de mago",
                ["Taiwanese"] = "魔血藥水",
            },
        },
        {
            ["id"] = 24366,
            ["items"] = {
                20012,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "强效昏睡药水",
                ["English"] = "Greater Dreamless Sleep Potion",
                ["French"] = "Potion de sommeil sans rêve supérieure",
                ["German"] = "Großer Trank des traumlosen Schlafs",
                ["Korean"] = "상급 숙면의 물약",
                ["Mexican"] = "Poción de letargo sin sueños superior",
                ["Portuguese"] = "Poção Maior do Sono sem Sonhos",
                ["Russian"] = "Сильное зелье спокойного сна",
                ["Spanish"] = "Poción superior de letargo sin sueños",
                ["Taiwanese"] = "強效昏睡藥水",
            },
        },
        {
            ["id"] = 24367,
            ["items"] = {
                20013,
            },
            ["min_skill"] = 285,
            ["name"] = {
                ["Chinese"] = "活力行动药水",
                ["English"] = "Living Action Potion",
                ["French"] = "Potion de vive action",
                ["German"] = "Trank der lebhaften Aktion",
                ["Korean"] = "자유 행동의 물약",
                ["Mexican"] = "Poción de acción viva",
                ["Portuguese"] = "Poção de Ação Vivaz",
                ["Russian"] = "Зелье актерства",
                ["Spanish"] = "Poción de acción viviente",
                ["Taiwanese"] = "活力行動藥水",
            },
        },
        {
            ["id"] = 24368,
            ["items"] = {
                20014,
            },
            ["min_skill"] = 290,
            ["name"] = {
                ["Chinese"] = "特效巨魔之血药水",
                ["English"] = "Major Troll's Blood Potion",
                ["French"] = "Potion de sang de troll majeure",
                ["German"] = "Erheblicher Trollbluttrank",
                ["Korean"] = "일급 재생의 물약",
                ["Mexican"] = "Poción de sangre de trol sublime",
                ["Portuguese"] = "Poção Elevada de Sangue de Troll",
                ["Russian"] = "Сильнейшее зелье тролльей крови",
                ["Spanish"] = "Poción sublime de sangre de trol",
                ["Taiwanese"] = "極效食人妖之血藥水",
            },
        },
        {
            ["id"] = 25146,
            ["items"] = {
                20761,
            },
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "转化：元素火焰",
                ["English"] = "Transmute: Elemental Fire",
                ["French"] = "Transmutation : Feu élémentaire",
                ["German"] = "Elementarfeuer transmutieren",
                ["Korean"] = "변환식: 자연의 불꽃",
                ["Mexican"] = "Transmutar: fuego elemental",
                ["Portuguese"] = "Transmutar: Fogo Elemental",
                ["Russian"] = "Трансмутация: первородный огонь",
                ["Spanish"] = "Transmutar: fuego elemental",
                ["Taiwanese"] = "轉化：元素火焰",
            },
        },
        {
            ["id"] = 26277,
            ["items"] = {
                21547,
            },
            ["min_skill"] = 250,
            ["name"] = {
                ["Chinese"] = "强效火力药剂",
                ["English"] = "Elixir of Greater Firepower",
                ["French"] = "Elixir de Maîtrise du feu supérieure",
                ["German"] = "Elixier der großen Feuermacht",
                ["Korean"] = "상급 화염 강화의 비약",
                ["Mexican"] = "Elixir de poder de Fuego superior",
                ["Portuguese"] = "Elixir de Poder de Fogo Maior",
                ["Russian"] = "Сильный эликсир огневой мощи",
                ["Spanish"] = "Elixir de poder de Fuego superior",
                ["Taiwanese"] = "強效火力藥劑",
            },
        },
    }
