TRADE_SKILLS_DATA["skills"]["Poisons"] = {
    {
        ["id"] = 2835,
        ["min_skill"] = 130,
        ["min_xp_level"] = 30,
        ["name"] = {
            ["Chinese"] = "致命毒药",
            ["English"] = "Deadly Poison",
            ["French"] = "Poison mortel",
            ["German"] = "Tödliches Gift",
            ["Korean"] = "맹독",
            ["Mexican"] = "Veneno mortal",
            ["Portuguese"] = "Veneno Mortal",
            ["Russian"] = "Смертельный яд",
            ["Spanish"] = "Veneno mortal",
            ["Taiwanese"] = "致命毒藥",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 10000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 2837,
        ["min_skill"] = 170,
        ["min_xp_level"] = 38,
        ["name"] = {
            ["Chinese"] = "致命毒药 II",
            ["English"] = "Deadly Poison II",
            ["French"] = "Poison mortel II",
            ["German"] = "Tödliches Gift II",
            ["Korean"] = "맹독 II",
            ["Mexican"] = "Veneno mortal II",
            ["Portuguese"] = "Veneno Mortal II",
            ["Russian"] = "Cмертельный яд II",
            ["Spanish"] = "Veneno mortal II",
            ["Taiwanese"] = "致命毒藥 II",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 18000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 3420,
        ["min_skill"] = 1,
        ["min_xp_level"] = 20,
        ["name"] = {
            ["Chinese"] = "致残毒药",
            ["English"] = "Crippling Poison",
            ["French"] = "Poison affaiblissant",
            ["German"] = "Verkrüppelndes Gift",
            ["Korean"] = "신경 마비 독",
            ["Mexican"] = "Veneno entorpecedor",
            ["Portuguese"] = "Veneno Debilitante",
            ["Russian"] = "Калечащий яд",
            ["Spanish"] = "Veneno paralizante",
            ["Taiwanese"] = "致殘毒藥",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 3000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 3421,
        ["min_skill"] = 230,
        ["min_xp_level"] = 50,
        ["name"] = {
            ["Chinese"] = "致残毒药 II",
            ["English"] = "Crippling Poison II",
            ["French"] = "Poison affaiblissant II",
            ["German"] = "Verkrüppelndes Gift II",
            ["Korean"] = "신경 마비 독 II",
            ["Mexican"] = "Veneno entorpecedor II",
            ["Portuguese"] = "Veneno Debilitante II",
            ["Russian"] = "Калечащий яд II",
            ["Spanish"] = "Veneno paralizante II",
            ["Taiwanese"] = "致殘毒藥 II",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 35000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 5763,
        ["min_skill"] = 100,
        ["min_xp_level"] = 24,
        ["name"] = {
            ["Chinese"] = "麻痹毒药",
            ["English"] = "Mind-numbing Poison",
            ["French"] = "Poison de distraction mentale",
            ["German"] = "Gedankenbenebelndes Gift",
            ["Korean"] = "정신 마비 독",
            ["Mexican"] = "Veneno de aturdimiento mental",
            ["Portuguese"] = "Veneno Entorpecente",
            ["Russian"] = "Дурманящий яд",
            ["Spanish"] = "Veneno de aturdimiento mental",
            ["Taiwanese"] = "麻痹毒藥",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 5000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 6510,
        ["min_skill"] = 150,
        ["min_xp_level"] = 34,
        ["name"] = {
            ["Chinese"] = "致盲粉",
            ["English"] = "Blinding Powder",
            ["French"] = "Poudre aveuglante",
            ["German"] = "Blendungspulver",
            ["Korean"] = "실명 가루",
            ["Mexican"] = "Partículas cegadoras",
            ["Portuguese"] = "Pó Cegante",
            ["Russian"] = "Ослепляющий порошок",
            ["Spanish"] = "Polvo cegador",
            ["Taiwanese"] = "致盲粉",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 14000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 8681,
        ["min_skill"] = 1,
        ["min_xp_level"] = 20,
        ["name"] = {
            ["Chinese"] = "速效毒药",
            ["English"] = "Instant Poison",
            ["French"] = "Poison instantané",
            ["German"] = "Sofort wirkendes Gift",
            ["Korean"] = "순간 효과 독",
            ["Mexican"] = "Veneno instantáneo",
            ["Portuguese"] = "Veneno Instantâneo",
            ["Russian"] = "Быстродействующий яд",
            ["Spanish"] = "Veneno instantáneo",
            ["Taiwanese"] = "速效毒藥",
        },
        ["phase"] = 1,
        ["special_action"] = "auto learned",
    },
    {
        ["id"] = 8687,
        ["min_skill"] = 120,
        ["min_xp_level"] = 28,
        ["name"] = {
            ["Chinese"] = "速效毒药 II",
            ["English"] = "Instant Poison II",
            ["French"] = "Poison instantané II",
            ["German"] = "Sofort wirkendes Gift II",
            ["Korean"] = "순간 효과 독 II",
            ["Mexican"] = "Veneno instantáneo II",
            ["Portuguese"] = "Veneno Instantâneo II",
            ["Russian"] = "Быстродействующий яд II",
            ["Spanish"] = "Veneno instantáneo III",
            ["Taiwanese"] = "速效毒藥 II",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 8000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 8691,
        ["min_skill"] = 160,
        ["min_xp_level"] = 36,
        ["name"] = {
            ["Chinese"] = "速效毒药 III",
            ["English"] = "Instant Poison III",
            ["French"] = "Poison instantané III",
            ["German"] = "Sofort wirkendes Gift III",
            ["Korean"] = "순간 효과 독 III",
            ["Mexican"] = "Veneno instantáneo III",
            ["Portuguese"] = "Veneno Instantâneo III",
            ["Russian"] = "Быстродействующий яд III",
            ["Spanish"] = "Veneno instantáneo III",
            ["Taiwanese"] = "速效毒藥 III",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 16000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 8694,
        ["min_skill"] = 170,
        ["min_xp_level"] = 38,
        ["name"] = {
            ["Chinese"] = "麻痹毒药 II",
            ["English"] = "Mind-numbing Poison II",
            ["French"] = "Poison de distraction mentale II",
            ["German"] = "Gedankenbenebelndes Gift II",
            ["Korean"] = "정신 마비 독 II",
            ["Mexican"] = "Veneno de aturdimiento mental II",
            ["Portuguese"] = "Veneno Entorpecente II",
            ["Russian"] = "Дурманящий яд II",
            ["Spanish"] = "Veneno de aturdimiento mental II",
            ["Taiwanese"] = "麻痹毒藥 II",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 18000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 11341,
        ["min_skill"] = 200,
        ["min_xp_level"] = 44,
        ["name"] = {
            ["Chinese"] = "速效毒药 IV",
            ["English"] = "Instant Poison IV",
            ["French"] = "Poison instantané IV",
            ["German"] = "Sofort wirkendes Gift IV",
            ["Korean"] = "순간 효과 독 IV",
            ["Mexican"] = "Veneno instantáneo IV",
            ["Portuguese"] = "Veneno Instantâneo IV",
            ["Russian"] = "Быстродействующий яд IV",
            ["Spanish"] = "Veneno instantáneo IV",
            ["Taiwanese"] = "速效毒藥 IV",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 29000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 11342,
        ["min_skill"] = 240,
        ["min_xp_level"] = 52,
        ["name"] = {
            ["Chinese"] = "速效毒药 V",
            ["English"] = "Instant Poison V",
            ["French"] = "Poison instantané V",
            ["German"] = "Sofort wirkendes Gift V",
            ["Korean"] = "순간 효과 독 V",
            ["Mexican"] = "Veneno instantáneo V",
            ["Portuguese"] = "Veneno Instantâneo V",
            ["Russian"] = "Быстродействующий яд V",
            ["Spanish"] = "Veneno instantáneo V",
            ["Taiwanese"] = "速效毒藥 V",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 46000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 11343,
        ["min_skill"] = 280,
        ["min_xp_level"] = 60,
        ["name"] = {
            ["Chinese"] = "速效毒药 VI",
            ["English"] = "Instant Poison VI",
            ["French"] = "Poison instantané VI",
            ["German"] = "Sofort wirkendes Gift VI",
            ["Korean"] = "순간 효과 독 VI",
            ["Mexican"] = "Veneno instantáneo VI",
            ["Portuguese"] = "Veneno Instantâneo VI",
            ["Russian"] = "Быстродействующий яд VI",
            ["Spanish"] = "Veneno instantáneo VI",
            ["Taiwanese"] = "速效毒藥 VI",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 54000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 11357,
        ["min_skill"] = 210,
        ["min_xp_level"] = 46,
        ["name"] = {
            ["Chinese"] = "致命毒药 III",
            ["English"] = "Deadly Poison III",
            ["French"] = "Poison mortel III",
            ["German"] = "Tödliches Gift III",
            ["Korean"] = "맹독 III",
            ["Mexican"] = "Veneno mortal III",
            ["Portuguese"] = "Veneno Mortal III",
            ["Russian"] = "Смертельный яд III",
            ["Spanish"] = "Veneno mortal III",
            ["Taiwanese"] = "致命毒藥 III",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 31000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 11358,
        ["min_skill"] = 250,
        ["min_xp_level"] = 54,
        ["name"] = {
            ["Chinese"] = "致命毒药 IV",
            ["English"] = "Deadly Poison IV",
            ["French"] = "Poison mortel IV",
            ["German"] = "Tödliches Gift IV",
            ["Korean"] = "맹독 IV",
            ["Mexican"] = "Veneno mortal IV",
            ["Portuguese"] = "Veneno Mortal IV",
            ["Russian"] = "Смертельный яд IV",
            ["Spanish"] = "Veneno mortal IV",
            ["Taiwanese"] = "致命毒藥 IV",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 48000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 11400,
        ["min_skill"] = 240,
        ["min_xp_level"] = 52,
        ["name"] = {
            ["Chinese"] = "麻痹毒药 III",
            ["English"] = "Mind-numbing Poison III",
            ["French"] = "Poison de distraction mentale III",
            ["German"] = "Gedankenbenebelndes Gift III",
            ["Korean"] = "정신 마비 독 III",
            ["Mexican"] = "Veneno de aturdimiento mental III",
            ["Portuguese"] = "Veneno Entorpecente III",
            ["Russian"] = "Дурманящий яд III",
            ["Spanish"] = "Veneno de aturdimiento mental III",
            ["Taiwanese"] = "麻痹毒藥 III",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 46000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 13220,
        ["min_skill"] = 140,
        ["min_xp_level"] = 32,
        ["name"] = {
            ["Chinese"] = "致伤毒药",
            ["English"] = "Wound Poison",
            ["French"] = "Poison douloureux",
            ["German"] = "Wundgift",
            ["Korean"] = "상처 감염 독",
            ["Mexican"] = "Veneno hiriente",
            ["Portuguese"] = "Veneno Ferino",
            ["Russian"] = "Нейтрализующий яд",
            ["Spanish"] = "Envenenar herida",
            ["Taiwanese"] = "致傷毒藥",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 12000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 13228,
        ["min_skill"] = 180,
        ["min_xp_level"] = 40,
        ["name"] = {
            ["Chinese"] = "致伤毒药 II",
            ["English"] = "Wound Poison II",
            ["French"] = "Poison douloureux II",
            ["German"] = "Wundgift II",
            ["Korean"] = "상처 감염 독 II",
            ["Mexican"] = "Veneno hiriente II",
            ["Portuguese"] = "Veneno Ferino II",
            ["Russian"] = "Нейтрализующий яд II",
            ["Spanish"] = "Envenenar herida II",
            ["Taiwanese"] = "致傷毒藥 II",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 20000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 13229,
        ["min_skill"] = 220,
        ["min_xp_level"] = 48,
        ["name"] = {
            ["Chinese"] = "致伤毒药 III",
            ["English"] = "Wound Poison III",
            ["French"] = "Poison douloureux III",
            ["German"] = "Wundgift III",
            ["Korean"] = "상처 감염 독 III",
            ["Mexican"] = "Veneno hiriente III",
            ["Portuguese"] = "Veneno Ferino III",
            ["Russian"] = "Нейтрализующий яд III",
            ["Spanish"] = "Envenenar herida III",
            ["Taiwanese"] = "致傷毒藥 III",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 33000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 13230,
        ["min_skill"] = 260,
        ["min_xp_level"] = 56,
        ["name"] = {
            ["Chinese"] = "致伤毒药 IV",
            ["English"] = "Wound Poison IV",
            ["French"] = "Poison douloureux IV",
            ["German"] = "Wundgift IV",
            ["Korean"] = "상처 감염 독 IV",
            ["Mexican"] = "Veneno hiriente IV",
            ["Portuguese"] = "Veneno Ferino IV",
            ["Russian"] = "Нейтрализующий яд IV",
            ["Spanish"] = "Envenenar herida IV",
            ["Taiwanese"] = "致傷毒藥 IV",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 50000,
            ["sources"] = {
                917,
                918,
                1234,
                1411,
                2130,
                3170,
                3327,
                3328,
                3401,
                3599,
                4163,
                4214,
                4215,
                4582,
                4583,
                4584,
                5165,
                5166,
                5167,
                6707,
                13283,
            },
        },
    },
    {
        ["id"] = 25347,
        ["items"] = {
            21302,
        },
        ["min_skill"] = 300,
        ["min_xp_level"] = 60,
        ["name"] = {
            ["Chinese"] = "致命毒药 V",
            ["English"] = "Deadly Poison V",
            ["French"] = "Poison mortel V",
            ["German"] = "Tödliches Gift V",
            ["Korean"] = "맹독 V",
            ["Mexican"] = "Veneno mortal V",
            ["Portuguese"] = "Veneno Mortal V",
            ["Russian"] = "Смертельный яд V",
            ["Spanish"] = "Veneno mortal V",
            ["Taiwanese"] = "致命毒藥 V",
        },
        ["phase"] = 5,
    },
}
