TRADE_SKILLS_DATA["skills"]["First Aid"] = {
    {
        ["id"] = 3275,
        ["min_skill"] = 1,
        ["name"] = {
            ["Chinese"] = "亚麻绷带",
            ["English"] = "Linen Bandage",
            ["French"] = "Bandage en lin",
            ["German"] = "Leinenverband",
            ["Korean"] = "리넨 붕대",
            ["Mexican"] = "Venda de lino",
            ["Portuguese"] = "Bandagem de Linho",
            ["Russian"] = "Льняные бинты",
            ["Spanish"] = "Vendaje de lino",
            ["Taiwanese"] = "亞麻繃帶",
        },
        ["phase"] = 1,
        ["special_action"] = "auto learned",
    },
    {
        ["id"] = 3276,
        ["min_skill"] = 40,
        ["name"] = {
            ["Chinese"] = "厚亚麻绷带",
            ["English"] = "Heavy Linen Bandage",
            ["French"] = "Bandage épais en lin",
            ["German"] = "Schwerer Leinenverband",
            ["Korean"] = "두꺼운 리넨 붕대",
            ["Mexican"] = "Venda de lino gruesa",
            ["Portuguese"] = "Bandagem Grossa de Linho",
            ["Russian"] = "Плотные льняные бинты",
            ["Spanish"] = "Vendaje pesado de lino",
            ["Taiwanese"] = "厚亞麻繃帶",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 100,
            ["sources"] = {
                2326,
                2327,
                2329,
                2798,
                3181,
                3373,
                4211,
                4591,
                5150,
                5759,
                5939,
                5943,
                6094,
            },
        },
    },
    {
        ["id"] = 3277,
        ["min_skill"] = 80,
        ["name"] = {
            ["Chinese"] = "绒线绷带",
            ["English"] = "Wool Bandage",
            ["French"] = "Bandage en laine",
            ["German"] = "Wollverband",
            ["Korean"] = "양모 붕대",
            ["Mexican"] = "Venda de lana",
            ["Portuguese"] = "Bandagem de Lã",
            ["Russian"] = "Шерстяные бинты",
            ["Spanish"] = "Vendaje de lana",
            ["Taiwanese"] = "絨線繃帶",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 250,
            ["sources"] = {
                2326,
                2327,
                2329,
                2798,
                3181,
                3373,
                4211,
                4591,
                5150,
                5759,
                5939,
                5943,
                6094,
            },
        },
    },
    {
        ["id"] = 3278,
        ["min_skill"] = 115,
        ["name"] = {
            ["Chinese"] = "厚绒线绷带",
            ["English"] = "Heavy Wool Bandage",
            ["French"] = "Bandage épais en laine",
            ["German"] = "Schwerer Wollverband",
            ["Korean"] = "두꺼운 양모 붕대",
            ["Mexican"] = "Venda de lana gruesa",
            ["Portuguese"] = "Bandagem Grossa de Lã",
            ["Russian"] = "Плотные шерстяные бинты",
            ["Spanish"] = "Vendaje pesado de lana",
            ["Taiwanese"] = "厚絨線繃帶",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 1000,
            ["sources"] = {
                2326,
                2327,
                2329,
                2798,
                3181,
                3373,
                4211,
                4591,
                5150,
                5759,
                5939,
                5943,
                6094,
            },
        },
    },
    {
        ["id"] = 7928,
        ["min_skill"] = 150,
        ["name"] = {
            ["Chinese"] = "丝质绷带",
            ["English"] = "Silk Bandage",
            ["French"] = "Bandage en soie",
            ["German"] = "Seidenverband",
            ["Korean"] = "비단 붕대",
            ["Mexican"] = "Venda de seda",
            ["Portuguese"] = "Bandagem de Seda",
            ["Russian"] = "Шелковые бинты",
            ["Spanish"] = "Venda de seda",
            ["Taiwanese"] = "絲質繃帶",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 5000,
            ["sources"] = {
                2326,
                2327,
                2329,
                2798,
                3181,
                3373,
                4211,
                4591,
                5150,
                5759,
                5939,
                5943,
                6094,
            },
        },
    },
    {
        ["id"] = 7929,
        ["items"] = {
            16112,
        },
        ["min_skill"] = 180,
        ["name"] = {
            ["Chinese"] = "厚丝质绷带",
            ["English"] = "Heavy Silk Bandage",
            ["French"] = "Bandage épais en soie",
            ["German"] = "Schwerer Seidenverband",
            ["Korean"] = "두꺼운 비단 붕대",
            ["Mexican"] = "Venda de seda gruesa",
            ["Portuguese"] = "Bandagem Grossa de Seda",
            ["Russian"] = "Плотные шелковые бинты",
            ["Spanish"] = "Vendaje pesado de seda",
            ["Taiwanese"] = "厚絲質繃帶",
        },
        ["phase"] = 1,
    },
    {
        ["id"] = 7934,
        ["min_skill"] = 80,
        ["name"] = {
            ["Chinese"] = "抗毒药剂",
            ["English"] = "Anti-Venom",
            ["French"] = "Anti-venin",
            ["German"] = "Gegengift",
            ["Korean"] = "해독제",
            ["Mexican"] = "Contraveneno",
            ["Portuguese"] = "Antipeçonha",
            ["Russian"] = "Противоядие",
            ["Spanish"] = "Antídoto",
            ["Taiwanese"] = "抗毒藥劑",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 250,
            ["sources"] = {
                2326,
                2327,
                2329,
                2798,
                3181,
                3373,
                4211,
                4591,
                5150,
                5759,
                5939,
                5943,
                6094,
            },
        },
    },
    {
        ["id"] = 7935,
        ["items"] = {
            6454,
        },
        ["min_skill"] = 130,
        ["name"] = {
            ["Chinese"] = "强力抗毒药剂",
            ["English"] = "Strong Anti-Venom",
            ["French"] = "Sérum anti-venin supérieur",
            ["German"] = "Starkes Gegengift",
            ["Korean"] = "강한 해독제",
            ["Mexican"] = "Contraveneno fuerte",
            ["Portuguese"] = "Antipeçonha Forte",
            ["Russian"] = "Мощное противоядие",
            ["Spanish"] = "Antídoto fuerte",
            ["Taiwanese"] = "強力抗毒藥劑",
        },
        ["phase"] = 1,
    },
    {
        ["id"] = 10840,
        ["items"] = {
            16113,
        },
        ["min_skill"] = 210,
        ["name"] = {
            ["Chinese"] = "魔纹绷带",
            ["English"] = "Mageweave Bandage",
            ["French"] = "Bandage en tisse-mage",
            ["German"] = "Magiestoffverband",
            ["Korean"] = "마법 붕대",
            ["Mexican"] = "Venda de tejido mágico",
            ["Portuguese"] = "Bandagem de Magitrama",
            ["Russian"] = "Волшебные бинты",
            ["Spanish"] = "Vendaje de tejido mágico",
            ["Taiwanese"] = "魔紋繃帶",
        },
        ["phase"] = 1,
    },
    {
        ["id"] = 10841,
        ["min_skill"] = 240,
        ["name"] = {
            ["Chinese"] = "厚魔纹绷带",
            ["English"] = "Heavy Mageweave Bandage",
            ["French"] = "Bandage épais en tisse-mage",
            ["German"] = "Schwerer Magiestoffverband",
            ["Korean"] = "두꺼운 마법 붕대",
            ["Mexican"] = "Venda de tejido mágico gruesa",
            ["Portuguese"] = "Bandagem Grossa de Magitrama",
            ["Russian"] = "Плотные волшебные бинты",
            ["Spanish"] = "Vendajes pesados de paño mágico",
            ["Taiwanese"] = "厚魔紋繃帶",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 0,
            ["sources"] = {
                12920,
                12939,
            },
        },
    },
    {
        ["id"] = 18629,
        ["min_skill"] = 260,
        ["name"] = {
            ["Chinese"] = "符文布绷带",
            ["English"] = "Runecloth Bandage",
            ["French"] = "Bandage en étoffe runique",
            ["German"] = "Runenstoffverband",
            ["Korean"] = "룬매듭 붕대",
            ["Mexican"] = "Venda de paño rúnico",
            ["Portuguese"] = "Bandagem de Runatrama",
            ["Russian"] = "Бинты из рунной ткани",
            ["Spanish"] = "Venda de paño rúnico",
            ["Taiwanese"] = "符文布繃帶",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 0,
            ["sources"] = {
                12920,
                12939,
            },
        },
    },
    {
        ["id"] = 18630,
        ["min_skill"] = 290,
        ["name"] = {
            ["Chinese"] = "厚符文布绷带",
            ["English"] = "Heavy Runecloth Bandage",
            ["French"] = "Bandage épais en étoffe runique",
            ["German"] = "Schwerer Runenstoffverband",
            ["Korean"] = "두꺼운 룬매듭 붕대",
            ["Mexican"] = "Venda de paño rúnico gruesa",
            ["Portuguese"] = "Bandagem Grossa de Runatrama",
            ["Russian"] = "Плотные бинты из рунной ткани",
            ["Spanish"] = "Vendaje pesado de paño rúnico",
            ["Taiwanese"] = "厚符文布繃帶",
        },
        ["phase"] = 1,
        ["trainers"] = {
            ["price"] = 0,
            ["sources"] = {
                12920,
                12939,
            },
        },
    },
    {
        ["id"] = 23787,
        ["items"] = {
            19442,
        },
        ["min_skill"] = 300,
        ["name"] = {
            ["Chinese"] = "特效抗毒药剂",
            ["English"] = "Powerful Anti-Venom",
            ["French"] = "Anti-venin puissant",
            ["German"] = "Mächtiges Gegengift",
            ["Korean"] = "강력한 해독제",
            ["Mexican"] = "Contraveneno potente",
            ["Portuguese"] = "Antipeçonha Poderoso",
            ["Russian"] = "Мощное противоядие",
            ["Spanish"] = "Antídoto potente",
            ["Taiwanese"] = "強效抗毒藥劑",
        },
        ["phase"] = 3,
    },
}
