TRADE_SKILLS_DATA["levels"]["Leatherworking"] =
    {
        {
            ["id"] = 2108,
            ["max_skill"] = 75,
            ["min_skill"] = 0,
            ["min_xp_level"] = 5,
            ["name"] = {
                ["Chinese"] = "制皮 (初级)",
                ["English"] = "Leatherworking (Apprentice)",
                ["French"] = "Travail du cuir (Apprenti)",
                ["German"] = "Lederverarbeitung (Lehrling)",
                ["Korean"] = "가죽 세공 (초급)",
                ["Mexican"] = "Peletería (Aprendiz)",
                ["Portuguese"] = "Couraria (Aprendiz)",
                ["Russian"] = "Кожевничество (Ученик)",
                ["Spanish"] = "Peletería (Aprendiz)",
                ["Taiwanese"] = "製皮 (學徒)",
            },
            ["phase"] = 1,
            ["rank"] = 1,
            ["trainers"] = {
                ["price"] = 10,
                ["sources"] = {
                    223,
                    1466,
                    1632,
                    3008,
                    3069,
                    3549,
                    3605,
                    5784,
                    5811,
                    11083,
                    11096,
                },
            },
        },
        {
            ["id"] = 3104,
            ["max_skill"] = 150,
            ["min_skill"] = 50,
            ["min_xp_level"] = 10,
            ["name"] = {
                ["Chinese"] = "制皮 (中级)",
                ["English"] = "Leatherworking (Journeyman)",
                ["French"] = "Travail du cuir (Compagnon)",
                ["German"] = "Lederverarbeitung (Geselle)",
                ["Korean"] = "가죽 세공 (수습)",
                ["Mexican"] = "Peletería (Oficial)",
                ["Portuguese"] = "Couraria (Profissional)",
                ["Russian"] = "Кожевничество (Подмастерье)",
                ["Spanish"] = "Peletería (Oficial)",
                ["Taiwanese"] = "製皮 (熟練工)",
            },
            ["phase"] = 1,
            ["rank"] = 2,
            ["trainers"] = {
                ["price"] = 500,
                ["sources"] = {
                    1385,
                    3365,
                    3703,
                    3967,
                    4588,
                    5127,
                    5564,
                    8153,
                    11081,
                    11084,
                },
            },
        },
        {
            ["id"] = 3811,
            ["max_skill"] = 225,
            ["min_skill"] = 125,
            ["min_xp_level"] = 20,
            ["name"] = {
                ["Chinese"] = "制皮 (高级)",
                ["English"] = "Leatherworking (Expert)",
                ["French"] = "Travail du cuir (Expert)",
                ["German"] = "Lederverarbeitung (Experte)",
                ["Korean"] = "가죽 세공 (숙련)",
                ["Mexican"] = "Peletería (Experto)",
                ["Portuguese"] = "Couraria (Perito)",
                ["Russian"] = "Кожевничество (Умелец)",
                ["Spanish"] = "Peletería (Experto)",
                ["Taiwanese"] = "製皮 (專家)",
            },
            ["phase"] = 1,
            ["rank"] = 3,
            ["trainers"] = {
                ["price"] = 5000,
                ["sources"] = {
                    3007,
                    4212,
                },
            },
        },
        {
            ["id"] = 10662,
            ["max_skill"] = 300,
            ["min_skill"] = 200,
            ["min_xp_level"] = 35,
            ["name"] = {
                ["Chinese"] = "制皮 (大师级)",
                ["English"] = "Leatherworking (Artisan)",
                ["French"] = "Travail du cuir (Artisan)",
                ["German"] = "Lederverarbeitung (Fachmann)",
                ["Korean"] = "가죽 세공 (전문)",
                ["Mexican"] = "Peletería (Artesano)",
                ["Portuguese"] = "Couraria (Artifice)",
                ["Russian"] = "Кожевничество (Мастеровой)",
                ["Spanish"] = "Peletería (Artesano)",
                ["Taiwanese"] = "製皮 (大工匠)",
            },
            ["phase"] = 1,
            ["rank"] = 4,
            ["trainers"] = {
                ["price"] = 50000,
                ["sources"] = {
                    11097,
                    11098,
                },
            },
        },
    }
