TRADE_SKILLS_DATA["levels"]["Herbalism"] =
    {
        {
            ["id"] = 2366,
            ["max_skill"] = 75,
            ["min_skill"] = 0,
            ["min_xp_level"] = 1,
            ["name"] = {
                ["Chinese"] = "草药学 (初级)",
                ["English"] = "Herbalism (Apprentice)",
                ["French"] = "Herboristerie (Apprenti)",
                ["German"] = "Kräuterkunde (Lehrling)",
                ["Korean"] = "약초 채집 (초급)",
                ["Mexican"] = "Botánica (Aprendiz)",
                ["Portuguese"] = "Herborismo (Aprendiz)",
                ["Russian"] = "Травничество (Ученик)",
                ["Spanish"] = "Botánica (Aprendiz)",
                ["Taiwanese"] = "草藥學 (學徒)",
            },
            ["phase"] = 1,
            ["rank"] = 1,
            ["trainers"] = {
                ["price"] = 10,
                ["sources"] = {
                    812,
                    908,
                    1218,
                    1458,
                    1473,
                    2114,
                    2390,
                    2856,
                    3013,
                    3185,
                    3404,
                    3604,
                    3965,
                    4204,
                    4614,
                    4898,
                    5137,
                    5502,
                    5566,
                    8146,
                    12025,
                },
            },
        },
        {
            ["id"] = 2368,
            ["max_skill"] = 150,
            ["min_skill"] = 50,
            ["min_xp_level"] = 1,
            ["name"] = {
                ["Chinese"] = "草药学 (中级)",
                ["English"] = "Herbalism (Journeyman)",
                ["French"] = "Herboristerie (Compagnon)",
                ["German"] = "Kräuterkunde (Geselle)",
                ["Korean"] = "약초 채집 (수습)",
                ["Mexican"] = "Botánica (Oficial)",
                ["Portuguese"] = "Herborismo (Profissional)",
                ["Russian"] = "Травничество (Подмастерье)",
                ["Spanish"] = "Botánica (Oficial)",
                ["Taiwanese"] = "草藥學 (熟練工)",
            },
            ["phase"] = 1,
            ["rank"] = 2,
            ["trainers"] = {
                ["price"] = 500,
                ["sources"] = {
                    812,
                    908,
                    1218,
                    1458,
                    1473,
                    2114,
                    2390,
                    2856,
                    3013,
                    3185,
                    3404,
                    3604,
                    3965,
                    4204,
                    4614,
                    4898,
                    5137,
                    5502,
                    5566,
                    8146,
                    12025,
                },
            },
        },
        {
            ["id"] = 3570,
            ["max_skill"] = 225,
            ["min_skill"] = 125,
            ["min_xp_level"] = 10,
            ["name"] = {
                ["Chinese"] = "草药学 (高级)",
                ["English"] = "Herbalism (Expert)",
                ["French"] = "Herboristerie (Expert)",
                ["German"] = "Kräuterkunde (Experte)",
                ["Korean"] = "약초 채집 (숙련)",
                ["Mexican"] = "Botánica (Experto)",
                ["Portuguese"] = "Herborismo (Perito)",
                ["Russian"] = "Травничество (Умелец)",
                ["Spanish"] = "Botánica (Experto)",
                ["Taiwanese"] = "草藥學 (專家)",
            },
            ["phase"] = 1,
            ["rank"] = 3,
            ["trainers"] = {
                ["price"] = 5000,
                ["sources"] = {
                    812,
                    908,
                    1218,
                    1458,
                    1473,
                    2114,
                    2390,
                    2856,
                    3013,
                    3185,
                    3404,
                    3604,
                    3965,
                    4204,
                    4614,
                    4898,
                    5137,
                    5502,
                    5566,
                    8146,
                    12025,
                },
            },
        },
        {
            ["id"] = 11993,
            ["max_skill"] = 300,
            ["min_skill"] = 200,
            ["min_xp_level"] = 25,
            ["name"] = {
                ["Chinese"] = "草药学 (大师级)",
                ["English"] = "Herbalism (Artisan)",
                ["French"] = "Herboristerie (Artisan)",
                ["German"] = "Kräuterkunde (Fachmann)",
                ["Korean"] = "약초 채집 (전문)",
                ["Mexican"] = "Botánica (Artesano)",
                ["Portuguese"] = "Herborismo (Artifice)",
                ["Russian"] = "Травничество (Мастеровой)",
                ["Spanish"] = "Botánica (Artesano)",
                ["Taiwanese"] = "草藥學 (大工匠)",
            },
            ["phase"] = 1,
            ["rank"] = 4,
            ["trainers"] = {
                ["price"] = 50000,
                ["sources"] = {
                    812,
                    908,
                    1218,
                    1458,
                    1473,
                    2114,
                    2390,
                    2856,
                    3013,
                    3185,
                    3404,
                    3604,
                    3965,
                    4204,
                    4614,
                    4898,
                    5137,
                    5502,
                    5566,
                    8146,
                    12025,
                },
            },
        },
    }
