TRADE_SKILLS_DATA["items"]["Engineering"] = {
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 20,
                ["min_xp_level"] = 5,
            },
        },
        ["id"] = 4408,
        ["name"] = {
            ["Chinese"] = "结构图：机械松鼠",
            ["English"] = "Schematic: Mechanical Squirrel",
            ["French"] = "Schéma : Ecureuil mécanique",
            ["German"] = "Bauplan: Mechanisches Eichhörnchen",
            ["Korean"] = "설계도: 기계 다람쥐",
            ["Mexican"] = "Esquema: ardilla mecánica",
            ["Portuguese"] = "Diagrama: Esquilo Mecânico",
            ["Russian"] = "Чертеж: механическая белка",
            ["Spanish"] = "Esquema: ardilla mecánica",
            ["Taiwanese"] = "結構圖：機械松鼠",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 25,
                ["min_xp_level"] = 10,
            },
        },
        ["id"] = 4409,
        ["name"] = {
            ["Chinese"] = "结构图：小型爆盐炸弹",
            ["English"] = "Schematic: Small Seaforium Charge",
            ["French"] = "Schéma : Petite charge d'hydroglycérine",
            ["German"] = "Bauplan: Kleine Zephyriumladung",
            ["Korean"] = "설계도: 소형 시포리움 폭약",
            ["Mexican"] = "Esquema: carga de seforio pequeña",
            ["Portuguese"] = "Diagrama: Carga Pequena de Cequatrum",
            ["Russian"] = "Чертеж: малый сефориевый заряд",
            ["Spanish"] = "Esquema: carga de seforio pequeña",
            ["Taiwanese"] = "結構圖：小型爆鹽炸彈",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 30,
                ["min_xp_level"] = 15,
            },
        },
        ["id"] = 4410,
        ["name"] = {
            ["Chinese"] = "结构图：暗影护目镜",
            ["English"] = "Schematic: Shadow Goggles",
            ["French"] = "Schéma : Lunettes des ombres",
            ["German"] = "Bauplan: Schattenschutzbrille",
            ["Korean"] = "설계도: 그림자 고글",
            ["Mexican"] = "Esquema: gafas de las Sombras",
            ["Portuguese"] = "Diagrama: Óculos Sombrios",
            ["Russian"] = "Чертеж: теневые очки",
            ["Spanish"] = "Esquema: gafas de las Sombras",
            ["Taiwanese"] = "結構圖：暗影護目鏡",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                7800,
            },
        },
        ["id"] = 4411,
        ["name"] = {
            ["Chinese"] = "结构图：火焰偏斜器",
            ["English"] = "Schematic: Flame Deflector",
            ["French"] = "Schéma : Pare-flammes",
            ["German"] = "Bauplan: Flammendeflektor",
            ["Korean"] = "설계도: 화염 반사장치",
            ["Mexican"] = "Esquema: deflector de llamas",
            ["Portuguese"] = "Diagrama: Defletor de Chamas",
            ["Russian"] = "Чертеж: отражатель пламени",
            ["Spanish"] = "Esquema: deflector de llamas",
            ["Taiwanese"] = "結構圖：火焰偏斜器",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 35,
                ["min_xp_level"] = 20,
            },
        },
        ["id"] = 4412,
        ["name"] = {
            ["Chinese"] = "结构图：夜视步枪",
            ["English"] = "Schematic: Moonsight Rifle",
            ["French"] = "Schéma : Carabine vise-lune",
            ["German"] = "Bauplan: Mondsichtgewehr",
            ["Korean"] = "설계도: 달빛 라이플",
            ["Mexican"] = "Esquema: rifle de vista lunar",
            ["Portuguese"] = "Diagrama: Rifle Miraluna",
            ["Russian"] = "Чертеж: лунная винтовка",
            ["Spanish"] = "Esquema: rifle de vista lunar",
            ["Taiwanese"] = "結構圖：夜視步槍",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                7800,
            },
        },
        ["id"] = 4413,
        ["name"] = {
            ["Chinese"] = "结构图：退化射线",
            ["English"] = "Schematic: Discombobulator Ray",
            ["French"] = "Schéma : Rayon discombobulateur",
            ["German"] = "Bauplan: Diskombobulatorstrahl",
            ["Korean"] = "설계도: 유전자 역결합 광선",
            ["Mexican"] = "Esquema: rayo descombobulador",
            ["Portuguese"] = "Diagrama: Raio Abotocador",
            ["Russian"] = "Чертеж: анти-перенаправляющий луч",
            ["Spanish"] = "Esquema: rayo descombolulador",
            ["Taiwanese"] = "結構圖：退化射線",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 40,
                ["min_xp_level"] = 25,
            },
        },
        ["id"] = 4414,
        ["name"] = {
            ["Chinese"] = "结构图：便携式青铜迫击炮",
            ["English"] = "Schematic: Portable Bronze Mortar",
            ["French"] = "Schéma : Mortier portable en bronze",
            ["German"] = "Bauplan: Tragbarer bronzener Mörser",
            ["Korean"] = "설계도: 휴대용 청동 박격포",
            ["Mexican"] = "Esquema: mortero de bronce portátil",
            ["Portuguese"] = "Diagrama: Morteiro Portátil de Bronze",
            ["Russian"] = "Чертеж: портативный бронзовый миномет",
            ["Spanish"] = "Esquema: mortero de bronce portátil",
            ["Taiwanese"] = "結構圖：可攜式青銅迫擊炮",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 45,
                ["min_xp_level"] = 30,
            },
        },
        ["id"] = 4415,
        ["name"] = {
            ["Chinese"] = "结构图：工匠眼镜",
            ["English"] = "Schematic: Craftsman's Monocle",
            ["French"] = "Schéma : Monocle de l'artisan",
            ["German"] = "Bauplan: Handwerkermonokel",
            ["Korean"] = "설계도: 장인의 단안경",
            ["Mexican"] = "Esquema: monóculo de artesano",
            ["Portuguese"] = "Diagrama: Monóculo do Artífice",
            ["Russian"] = "Чертеж: монокль ремесленника",
            ["Spanish"] = "Esquema: monóculo de artesano",
            ["Taiwanese"] = "結構圖：工匠眼鏡",
        },
        ["phase"] = 1,
        ["quality"] = "rare",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 45,
                ["min_xp_level"] = 30,
            },
        },
        ["id"] = 4416,
        ["name"] = {
            ["Chinese"] = "结构图：地精暗雷",
            ["English"] = "Schematic: Goblin Land Mine",
            ["French"] = "Schéma : Mine gobeline",
            ["German"] = "Bauplan: Goblin-Landmine",
            ["Korean"] = "설계도: 고블린 지뢰",
            ["Mexican"] = "Esquema: mina terrestre goblin",
            ["Portuguese"] = "Diagrama: Mina Terrestre Goblínica",
            ["Russian"] = "Чертеж: гоблинская мина",
            ["Spanish"] = "Esquema: mina terrestre goblin",
            ["Taiwanese"] = "結構圖：哥布林暗雷",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 45,
                ["min_xp_level"] = 30,
            },
        },
        ["id"] = 4417,
        ["name"] = {
            ["Chinese"] = "结构图：大型爆盐炸弹",
            ["English"] = "Schematic: Large Seaforium Charge",
            ["French"] = "Schéma : Grande charge d'hydroglycérine",
            ["German"] = "Bauplan: Große Zephyriumladung",
            ["Korean"] = "설계도: 대형 시포리움 폭약",
            ["Mexican"] = "Esquema: carga de seforio grande",
            ["Portuguese"] = "Diagrama: Carga Grande de Cequatrum",
            ["Russian"] = "Чертеж: большой сефориевый заряд",
            ["Spanish"] = "Esquema: carga de seforio grande",
            ["Taiwanese"] = "結構圖：大型爆鹽炸彈",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 6672,
        ["name"] = {
            ["Chinese"] = "结构图：闪光雷",
            ["English"] = "Schematic: Flash Bomb",
            ["French"] = "Schéma : Bombe éclairante",
            ["German"] = "Bauplan: Blitzstrahlbombe",
            ["Korean"] = "설계도: 섬광탄",
            ["Mexican"] = "Esquema: bomba cegadora",
            ["Portuguese"] = "Diagrama: Bomba de Clarão",
            ["Russian"] = "Чертеж: световая бомба",
            ["Spanish"] = "Esquema: bomba cegadora",
            ["Taiwanese"] = "結構圖：閃光雷",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            1559,
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 25,
                ["min_xp_level"] = 10,
            },
        },
        ["id"] = 6716,
        ["name"] = {
            ["Chinese"] = "结构图：简易投掷炸弹",
            ["English"] = "Schematic: EZ-Thro Dynamite",
            ["French"] = "Schéma : Dynamite Ev-Lan",
            ["German"] = "Bauplan: EZ-Thro-Dynamit",
            ["Korean"] = "설계도: 초보자용 다이너마이트",
            ["Mexican"] = "Esquema: dinamita para tontos",
            ["Portuguese"] = "Diagrama: Dinamite Taca-fácil",
            ["Russian"] = "Чертеж: динамит \"Pro-100-брос\"",
            ["Spanish"] = "Esquema: dinamita EZ-Thro",
            ["Taiwanese"] = "結構圖：簡易投擲炸彈",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                7800,
            },
        },
        ["id"] = 7192,
        ["name"] = {
            ["Chinese"] = "结构图：地精火箭靴",
            ["English"] = "Schematic: Goblin Rocket Boots",
            ["French"] = "Schéma : Bottes-fusées gobelines",
            ["German"] = "Bauplan: Goblin-Raketenstiefel",
            ["Korean"] = "설계도: 고블린 로켓 장화",
            ["Mexican"] = "Esquema: botas cohete goblin",
            ["Portuguese"] = "Diagrama: Botas-foguete Goblínicas",
            ["Russian"] = "Чертеж: гоблинские реактивные сапоги",
            ["Spanish"] = "Esquema: botas cohete goblin",
            ["Taiwanese"] = "結構圖：哥布林火箭靴",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 7560,
        ["name"] = {
            ["Chinese"] = "结构图：侏儒通用遥控器",
            ["English"] = "Schematic: Gnomish Universal Remote",
            ["French"] = "Schéma : Télécommande universelle gnome",
            ["German"] = "Bauplan: Gnomen-Universalfernbedienung",
            ["Korean"] = "설계도: 노움의 만능 원격조종기",
            ["Mexican"] = "Esquema: mando universal gnómico",
            ["Portuguese"] = "Diagrama: Controle Remoto Universal Gnômico",
            ["Russian"] = "Чертеж: универсальный гномский дистанционный пульт",
            ["Spanish"] = "Esquema: mando universal gnómico",
            ["Taiwanese"] = "結構圖：地精通用遙控器",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1200,
            ["sources"] = {
                5175,
                6730,
            },
        },
    },
    {
        ["id"] = 7561,
        ["name"] = {
            ["Chinese"] = "结构图：地精起搏器",
            ["English"] = "Schematic: Goblin Jumper Cables",
            ["French"] = "Schéma : Défibrillateur gobelin",
            ["German"] = "Bauplan: Goblin-Überbrückungskabel",
            ["Korean"] = "설계도: 고블린 점퍼 케이블",
            ["Mexican"] = "Esquema: desfibriladores goblin",
            ["Portuguese"] = "Diagrama: Cabo de Chupeta Goblínico",
            ["Russian"] = "Чертеж: гоблинский кабельный дефибриллятор",
            ["Spanish"] = "Esquema: pinzas de batería goblin",
            ["Taiwanese"] = "結構圖：哥布林起搏器",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 2000,
            ["sources"] = {
                3134,
                3537,
                4086,
                12246,
            },
        },
    },
    {
        ["drops"] = {
            ["sources"] = {
                7800,
            },
        },
        ["id"] = 7742,
        ["name"] = {
            ["Chinese"] = "结构图：侏儒隐形装置",
            ["English"] = "Schematic: Gnomish Cloaking Device",
            ["French"] = "Schéma : Système d'occultation gnome",
            ["German"] = "Bauplan: Gnomisches Verbergungsgerät",
            ["Korean"] = "설계도: 노움 은폐 장치",
            ["Mexican"] = "Esquema: aparato de invisibilidad gnómico",
            ["Portuguese"] = "Diagrama: Dispositivo Ocultador Gnômico",
            ["Russian"] = "Чертеж: маскировочный механизм гномов",
            ["Spanish"] = "Esquema: aparato de invisibilidad gnómico",
            ["Taiwanese"] = "結構圖：地精隱形裝置",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 2400,
            ["sources"] = {
                6777,
            },
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 40,
                ["min_xp_level"] = 25,
            },
        },
        ["id"] = 10601,
        ["name"] = {
            ["Chinese"] = "结构图：增亮护目镜",
            ["English"] = "Schematic: Bright-Eye Goggles",
            ["French"] = "Schéma : Lunettes d'oeil brillant",
            ["German"] = "Bauplan: Hellaugenschutzbrille",
            ["Korean"] = "설계도: 초롱초롱 고글",
            ["Mexican"] = "Esquema: gafas ojo brillante",
            ["Portuguese"] = "Diagrama: Óculos Brilho-do-olhar",
            ["Russian"] = "Чертеж: яркоглазые очки",
            ["Spanish"] = "Esquema: gafas Ojo brillante",
            ["Taiwanese"] = "結構圖：增亮護目鏡",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 10602,
        ["name"] = {
            ["Chinese"] = "结构图：致命瞄准镜",
            ["English"] = "Schematic: Deadly Scope",
            ["French"] = "Schéma : Lunette mortelle",
            ["German"] = "Bauplan: Tödliches Zielfernrohr",
            ["Korean"] = "설계도: 초정밀 조준경",
            ["Mexican"] = "Esquema: mira mortal",
            ["Portuguese"] = "Diagrama: Mira Letal",
            ["Russian"] = "Чертеж: смертоносный прицел",
            ["Spanish"] = "Esquema: mira mortal",
            ["Taiwanese"] = "結構圖：致命瞄準鏡",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 3000,
            ["sources"] = {
                8679,
                9544,
            },
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 50,
                ["min_xp_level"] = 35,
            },
        },
        ["id"] = 10603,
        ["name"] = {
            ["Chinese"] = "结构图：猫眼超级护目镜",
            ["English"] = "Schematic: Catseye Ultra Goggles",
            ["French"] = "Schéma : Lunettes d'oeil de chat",
            ["German"] = "Bauplan: Katzenaugen-Ultraschutzbrille",
            ["Korean"] = "설계도: 고양이눈 고글",
            ["Mexican"] = "Esquema: ultragafas ojo de gato",
            ["Portuguese"] = "Diagrama: Ultra-óculos Olho-de-gato",
            ["Russian"] = "Чертеж: суперочки \"Кошачий глаз\"",
            ["Spanish"] = "Esquema: ultragafas Ojo de gato",
            ["Taiwanese"] = "結構圖：貓眼超級護目鏡",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 50,
                ["min_xp_level"] = 35,
            },
        },
        ["id"] = 10604,
        ["name"] = {
            ["Chinese"] = "结构图：大口径秘银步枪",
            ["English"] = "Schematic: Mithril Heavy-bore Rifle",
            ["French"] = "Schéma : Carabine de gros calibre en mithril",
            ["German"] = "Bauplan: Schwerkalibriges Mithrilgewehr",
            ["Korean"] = "설계도: 미스릴 중구경 라이플",
            ["Mexican"] = "Esquema: rifle de gran calibre de mitril",
            ["Portuguese"] = "Diagrama: Rifle de Mithril de Grosso Calibre",
            ["Russian"] = "Чертеж: мифриловая крупнокалиберная винтовка",
            ["Spanish"] = "Esquema: rifle de gran calibre de mitril",
            ["Taiwanese"] = "結構圖：大口徑祕銀步槍",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 50,
                ["min_xp_level"] = 35,
            },
        },
        ["id"] = 10605,
        ["name"] = {
            ["Chinese"] = "结构图：法术能量护目镜超级版",
            ["English"] = "Schematic: Spellpower Goggles Xtreme",
            ["French"] = "Schéma : Lunettes de fortification des sorts",
            ["German"] = "Bauplan: Zaubermachtschutzbrille Xtrem",
            ["Korean"] = "설계도: 초강력 화력 고글",
            ["Mexican"] = "Esquema: gafas de poder con hechizos Xtremo",
            ["Portuguese"] = "Diagrama: Óculos de Poder Mágico Xtremo",
            ["Russian"] = "Чертеж: экстремальные очки силы заклинаний",
            ["Spanish"] = "Esquema: gafas extremas de hechizo de poder",
            ["Taiwanese"] = "結構圖：法術能量護目鏡超級版",
        },
        ["phase"] = 1,
        ["quality"] = "rare",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 50,
                ["min_xp_level"] = 35,
            },
        },
        ["id"] = 10606,
        ["name"] = {
            ["Chinese"] = "结构图：降落伞披风",
            ["English"] = "Schematic: Parachute Cloak",
            ["French"] = "Schéma : Cape parachute",
            ["German"] = "Bauplan: Fallschirm-Umhang",
            ["Korean"] = "설계도: 낙하산 망토",
            ["Mexican"] = "Esquema: capa paracaídas",
            ["Portuguese"] = "Diagrama: Manto Paraquedas",
            ["Russian"] = "Чертеж: плащ-парашют",
            ["Spanish"] = "Esquema: capa de paracaidista",
            ["Taiwanese"] = "結構圖：降落傘披風",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 10607,
        ["name"] = {
            ["Chinese"] = "结构图：潜水头盔",
            ["English"] = "Schematic: Deepdive Helmet",
            ["French"] = "Schéma : Casque de scaphandrier",
            ["German"] = "Bauplan: Tiefentaucherhelm",
            ["Korean"] = "설계도: 잠수용 헬멧",
            ["Mexican"] = "Esquema: casco de inmersión",
            ["Portuguese"] = "Diagrama: Capacete das Profundezas",
            ["Russian"] = "Чертеж: шлем ныряльщика",
            ["Spanish"] = "Esquema: casco de inmersión",
            ["Taiwanese"] = "結構圖：潛水頭盔",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 3600,
            ["sources"] = {
                8678,
            },
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 55,
                ["min_xp_level"] = 40,
            },
        },
        ["id"] = 10608,
        ["name"] = {
            ["Chinese"] = "结构图：狙击瞄准镜",
            ["English"] = "Schematic: Sniper Scope",
            ["French"] = "Schéma : Lunette de sniper",
            ["German"] = "Bauplan: Heckenschützen-Zielfernrohr",
            ["Korean"] = "설계도: 저격용 조준경",
            ["Mexican"] = "Esquema: mira de francotirador",
            ["Portuguese"] = "Diagrama: Mira de Francoatirador",
            ["Russian"] = "Чертеж: снайперский прицел",
            ["Spanish"] = "Esquema: mira de francotirador",
            ["Taiwanese"] = "結構圖：狙擊瞄準鏡",
        },
        ["phase"] = 1,
        ["quality"] = "rare",
    },
    {
        ["id"] = 10609,
        ["name"] = {
            ["Chinese"] = "结构图：秘银机械幼龙",
            ["English"] = "Schematic: Mithril Mechanical Dragonling",
            ["French"] = "Schéma : Petit dragon mécanique en mithril",
            ["German"] = "Bauplan: Mechanischer Mithrildrachling",
            ["Korean"] = "설계도: 소형 미스릴 기계용",
            ["Mexican"] = "Esquema: dragonizo mecánico de mitril",
            ["Portuguese"] = "Diagrama: Dragonete Mecânico de Mithril",
            ["Russian"] = "Чертеж: мифриловый механический дракончик",
            ["Spanish"] = "Esquema: dragonizo mecánico de mitril",
            ["Taiwanese"] = "結構圖：祕銀機械幼龍",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 4000,
            ["sources"] = {
                2688,
            },
        },
    },
    {
        ["id"] = 11827,
        ["name"] = {
            ["Chinese"] = "结构图：发条娃娃",
            ["English"] = "Schematic: Lil' Smoky",
            ["French"] = "Schéma : Petit fumant",
            ["German"] = "Bauplan: Lil' Smoky",
            ["Korean"] = "설계도: 릴 스모키",
            ["Mexican"] = "Esquema: Humillo",
            ["Portuguese"] = "Diagrama: Fumacinho",
            ["Russian"] = "Чертеж: Крошка Дымок",
            ["Spanish"] = "Esquema: Lil' Humillo",
            ["Taiwanese"] = "結構圖：發條娃娃",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            3645,
        },
        ["special_action"] = "random reward",
    },
    {
        ["id"] = 11828,
        ["name"] = {
            ["Chinese"] = "结构图：炸弹宠物",
            ["English"] = "Schematic: Pet Bombling",
            ["French"] = "Schéma : Bombinette",
            ["German"] = "Bauplan: Winzige wandelnde Bombe",
            ["Korean"] = "설계도: 작은 꼬마 폭탄",
            ["Mexican"] = "Esquema: Bombita",
            ["Portuguese"] = "Diagrama: Bombinha de Estimação",
            ["Russian"] = "Чертеж: зверюшка-бомбист",
            ["Spanish"] = "Esquema: bomba mascota",
            ["Taiwanese"] = "結構圖：炸彈寵物",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            3644,
        },
    },
    {
        ["id"] = 13308,
        ["name"] = {
            ["Chinese"] = "结构图：寒冰偏斜器",
            ["English"] = "Schematic: Ice Deflector",
            ["French"] = "Schéma : Pare-glace",
            ["German"] = "Bauplan: Eisdeflektor",
            ["Korean"] = "설계도: 냉기 반사장치",
            ["Mexican"] = "Esquema: deflector de hielo",
            ["Portuguese"] = "Diagrama: Defletor de Gelo",
            ["Russian"] = "Чертеж: ледяной отражатель",
            ["Spanish"] = "Esquema: deflector de hielo",
            ["Taiwanese"] = "結構圖：寒冰偏斜器",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1800,
            ["sources"] = {
                2684,
            },
        },
    },
    {
        ["id"] = 13309,
        ["name"] = {
            ["Chinese"] = "结构图：精致手工火枪",
            ["English"] = "Schematic: Lovingly Crafted Boomstick",
            ["French"] = "Schéma : Espingole amoureusement construite",
            ["German"] = "Bauplan: Liebevoll hergestelltes Schießeisen",
            ["Korean"] = "설계도: 정성이 가득 담긴 붐스틱",
            ["Mexican"] = "Esquema: bocarda fabricada con amor",
            ["Portuguese"] = "Diagrama: Cano de Atirar Feito com Carinho",
            ["Russian"] = "Чертеж: любовно выделанный громобой",
            ["Spanish"] = "Esquema: trabuco fabricado con amor",
            ["Taiwanese"] = "結構圖：精緻手工火槍",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1000,
            ["sources"] = {
                2682,
                6730,
            },
        },
    },
    {
        ["id"] = 13310,
        ["name"] = {
            ["Chinese"] = "结构图：精确瞄准镜",
            ["English"] = "Schematic: Accurate Scope",
            ["French"] = "Schéma : Lunette de précision",
            ["German"] = "Bauplan: Genaues Zielfernrohr",
            ["Korean"] = "설계도: 정밀한 조준경",
            ["Mexican"] = "Esquema: mira de precisión",
            ["Portuguese"] = "Diagrama: Mira de Precisão",
            ["Russian"] = "Чертеж: точный прицел",
            ["Spanish"] = "Esquema: mira de precisión",
            ["Taiwanese"] = "結構圖：精確瞄準鏡",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 2000,
            ["sources"] = {
                2685,
                12246,
            },
        },
    },
    {
        ["id"] = 13311,
        ["name"] = {
            ["Chinese"] = "结构图：机械幼龙",
            ["English"] = "Schematic: Mechanical Dragonling",
            ["French"] = "Schéma : Petit dragon mécanique",
            ["German"] = "Bauplan: Mechanischer Drachling",
            ["Korean"] = "설계도: 소형 기계용",
            ["Mexican"] = "Esquema: dragonizo mecánico",
            ["Portuguese"] = "Diagrama: Dragonete Mecânico",
            ["Russian"] = "Чертеж: механический дракончик",
            ["Spanish"] = "Esquema: dragonizo mecánico",
            ["Taiwanese"] = "結構圖：機械幼龍",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 10000,
            ["sources"] = {
                2687,
            },
        },
    },
    {
        ["id"] = 14639,
        ["name"] = {
            ["Chinese"] = "结构图：自动净化装置",
            ["English"] = "Schematic: Minor Recombobulator",
            ["French"] = "Schéma : Recombobulateur mineur",
            ["German"] = "Bauplan: Schwacher Rekombobulator",
            ["Korean"] = "설계도: 하급 유전자 역결합기",
            ["Mexican"] = "Esquema: recombobulador menor",
            ["Portuguese"] = "Diagrama: Rebotocador Menor",
            ["Russian"] = "Чертеж: малый атомарный перенаправлятор",
            ["Spanish"] = "Esquema: recombobulador menor",
            ["Taiwanese"] = "結構圖：自動淨化裝置",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1500,
            ["sources"] = {
                2682,
                2683,
            },
        },
    },
    {
        ["id"] = 16041,
        ["name"] = {
            ["Chinese"] = "结构图：瑟银手榴弹",
            ["English"] = "Schematic: Thorium Grenade",
            ["French"] = "Schéma : Grenade en thorium",
            ["German"] = "Bauplan: Thoriumgranate",
            ["Korean"] = "설계도: 토륨 수류탄",
            ["Mexican"] = "Esquema: granada de torio",
            ["Portuguese"] = "Diagrama: Granada de Tório",
            ["Russian"] = "Чертеж: ториевая граната",
            ["Spanish"] = "Esquema: granada de torio",
            ["Taiwanese"] = "結構圖：瑟銀手榴彈",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 12000,
            ["sources"] = {
                3413,
                5175,
            },
        },
    },
    {
        ["id"] = 16042,
        ["name"] = {
            ["Chinese"] = "结构图：瑟银零件",
            ["English"] = "Schematic: Thorium Widget",
            ["French"] = "Schéma : Rouages en thorium",
            ["German"] = "Bauplan: Thoriumapparat",
            ["Korean"] = "설계도: 토륨 부품",
            ["Mexican"] = "Esquema: trasto de torio",
            ["Portuguese"] = "Diagrama: Treco de Tório",
            ["Russian"] = "Чертеж: ториевое устройство",
            ["Spanish"] = "Esquema: trastos wow de torio",
            ["Taiwanese"] = "結構圖：瑟銀零件",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 12000,
            ["sources"] = {
                3413,
                5175,
            },
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 60,
                ["min_xp_level"] = 45,
            },
        },
        ["id"] = 16043,
        ["name"] = {
            ["Chinese"] = "结构图：瑟银火枪",
            ["English"] = "Schematic: Thorium Rifle",
            ["French"] = "Schéma : Carabine en thorium",
            ["German"] = "Bauplan: Thoriumgewehr",
            ["Korean"] = "설계도: 토륨 소총",
            ["Mexican"] = "Esquema: rifle de torio",
            ["Portuguese"] = "Diagrama: Rifle de Tório",
            ["Russian"] = "Чертеж: ториевая винтовка",
            ["Spanish"] = "Esquema: rifle de torio",
            ["Taiwanese"] = "結構圖：瑟銀火槍",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 60,
                ["min_xp_level"] = 45,
            },
        },
        ["id"] = 16044,
        ["name"] = {
            ["Chinese"] = "结构图：仿真机械蛙",
            ["English"] = "Schematic: Lifelike Mechanical Toad",
            ["French"] = "Schéma : Crapaud mécanique",
            ["German"] = "Bauplan: Lebensechte mechanische Kröte",
            ["Korean"] = "설계도: 진짜같은 기계개구리",
            ["Mexican"] = "Esquema: sapo mecánico casi vivo",
            ["Portuguese"] = "Diagrama: Sapo Mecânico Realista",
            ["Russian"] = "Чертеж: механическая жаба",
            ["Spanish"] = "Esquema: sapo mecánico casi vivo",
            ["Taiwanese"] = "結構圖：仿真機械蛙",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                6195,
            },
        },
        ["id"] = 16045,
        ["name"] = {
            ["Chinese"] = "结构图：法术能量护目镜超级改良版",
            ["English"] = "Schematic: Spellpower Goggles Xtreme Plus",
            ["French"] = "Schéma : Lunettes de concentration extrême",
            ["German"] = "Bauplan: Zaubermachtschutzbrille Xtrem Plus",
            ["Korean"] = "설계도: 최신형 주문증폭 고글",
            ["Mexican"] = "Esquema: gafas de poder con hechizos Xtremo Plus",
            ["Portuguese"] = "Diagrama: Óculos de Poder Mágico Xtremo Plus",
            ["Russian"] = "Чертеж: экстремальные-плюс очки силы заклинаний",
            ["Spanish"] = "Esquema: gafas extremas de hechizo de poder plus",
            ["Taiwanese"] = "結構圖：法術能量護目鏡超級改良版",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 16046,
        ["name"] = {
            ["Chinese"] = "结构图：高级活动假人",
            ["English"] = "Schematic: Masterwork Target Dummy",
            ["French"] = "Schéma : Leurre ouvragé",
            ["German"] = "Bauplan: Meisterliche Zielattrappe",
            ["Korean"] = "설계도: 일급 표적 허수아비",
            ["Mexican"] = "Esquema: muñeco-diana magistral",
            ["Portuguese"] = "Diagrama: Boneco-alvo Magistral",
            ["Russian"] = "Чертеж: манекен-мишень искусной работы",
            ["Spanish"] = "Esquema: muñeco-diana magistral",
            ["Taiwanese"] = "結構圖：高級活動假人",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 16000,
            ["sources"] = {
                11185,
            },
        },
    },
    {
        ["id"] = 16047,
        ["name"] = {
            ["Chinese"] = "结构图：瑟银管",
            ["English"] = "Schematic: Thorium Tube",
            ["French"] = "Schéma : Tube en thorium",
            ["German"] = "Bauplan: Thoriumröhre",
            ["Korean"] = "설계도: 토륨관",
            ["Mexican"] = "Esquema: tubo de torio",
            ["Portuguese"] = "Diagrama: Tubo de Tório",
            ["Russian"] = "Чертеж: ториевая труба",
            ["Spanish"] = "Esquema: tubo de torio",
            ["Taiwanese"] = "結構圖：瑟銀管",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 16000,
            ["sources"] = {
                11185,
            },
        },
    },
    {
        ["drops"] = {
            ["sources"] = {
                8897,
            },
        },
        ["id"] = 16048,
        ["name"] = {
            ["Chinese"] = "结构图：黑铁步枪",
            ["English"] = "Schematic: Dark Iron Rifle",
            ["French"] = "Schéma : Carabine en sombrefer",
            ["German"] = "Bauplan: Dunkeleisengewehr",
            ["Korean"] = "설계도: 검은무쇠 소총",
            ["Mexican"] = "Esquema: rifle Hierro Negro",
            ["Portuguese"] = "Diagrama: Rifle de Ferro Negro",
            ["Russian"] = "Чертеж: винтовка из черного железа",
            ["Spanish"] = "Esquema: rifle Hierro Negro",
            ["Taiwanese"] = "結構圖：黑鐵步槍",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                8920,
            },
        },
        ["id"] = 16049,
        ["name"] = {
            ["Chinese"] = "结构图：黑铁炸弹",
            ["English"] = "Schematic: Dark Iron Bomb",
            ["French"] = "Schéma : Bombe en sombrefer",
            ["German"] = "Bauplan: Dunkeleisenbombe",
            ["Korean"] = "설계도: 검은무쇠 폭탄",
            ["Mexican"] = "Esquema: bomba Hierro Negro",
            ["Portuguese"] = "Diagrama: Bomba de Ferro Negro",
            ["Russian"] = "Чертеж: бомба из черного железа",
            ["Spanish"] = "Esquema: bomba Hierro Negro",
            ["Taiwanese"] = "結構圖：黑鐵炸彈",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 16050,
        ["name"] = {
            ["Chinese"] = "结构图：精密奥金转换器",
            ["English"] = "Schematic: Delicate Arcanite Converter",
            ["French"] = "Schéma : Convertisseur d'arcanite délicat",
            ["German"] = "Bauplan: Empfindlicher Arkanitwandler",
            ["Korean"] = "설계도: 정교한 아케이나이트 변환기",
            ["Mexican"] = "Esquema: conversor de arcanita delicado",
            ["Portuguese"] = "Diagrama: Conversor Delicado de Arcanita",
            ["Russian"] = "Чертеж: сверхточный арканитовый преобразователь",
            ["Spanish"] = "Esquema: conversor de arcanita delicado",
            ["Taiwanese"] = "結構圖：精密奧金轉換器",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 20000,
            ["sources"] = {
                11185,
            },
        },
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 50,
            },
        },
        ["id"] = 16051,
        ["name"] = {
            ["Chinese"] = "结构图：瑟银弹",
            ["English"] = "Schematic: Thorium Shells",
            ["French"] = "Schéma : Obus en thorium",
            ["German"] = "Bauplan: Thoriumpatronen",
            ["Korean"] = "설계도: 토륨 탄환",
            ["Mexican"] = "Esquema: proyectiles de torio",
            ["Portuguese"] = "Diagrama: Cartuchos de Tório",
            ["Russian"] = "Чертеж: ториевые патроны",
            ["Spanish"] = "Esquema: proyectiles de torio",
            ["Taiwanese"] = "結構圖：瑟銀彈",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                10426,
            },
        },
        ["id"] = 16052,
        ["name"] = {
            ["Chinese"] = "结构图：语音增强模组",
            ["English"] = "Schematic: Voice Amplification Modulator",
            ["French"] = "Schéma : Modulateur d'amplification vocale",
            ["German"] = "Bauplan: Modularer Stimmenverstärker",
            ["Korean"] = "설계도: 주문 확성기",
            ["Mexican"] = "Esquema: modulador de amplificación de voz",
            ["Portuguese"] = "Diagrama: Modulador de Amplificação de Voz",
            ["Russian"] = "Чертеж: модулирующий усилитель голоса",
            ["Spanish"] = "Esquema: modulador de amplificación de voz",
            ["Taiwanese"] = "結構圖：語音增強模組",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                8900,
            },
        },
        ["id"] = 16053,
        ["name"] = {
            ["Chinese"] = "结构图：高级技师护目镜",
            ["English"] = "Schematic: Master Engineer's Goggles",
            ["French"] = "Schéma : Lunettes de maître ingénieur",
            ["German"] = "Bauplan: Schutzbrille des Meisteringenieurs",
            ["Korean"] = "설계도: 전문 기술자의 고글",
            ["Mexican"] = "Esquema: gafas de maestro ingeniero",
            ["Portuguese"] = "Diagrama: Óculos do Mestre Engenheiro",
            ["Russian"] = "Чертеж: очки старшего инженера",
            ["Spanish"] = "Esquema: gafas de maestro ingeniero",
            ["Taiwanese"] = "結構圖：高級技師護目鏡",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                7437,
            },
        },
        ["id"] = 16054,
        ["name"] = {
            ["Chinese"] = "结构图：奥金幼龙",
            ["English"] = "Schematic: Arcanite Dragonling",
            ["French"] = "Schéma : Petit dragon en arcanite",
            ["German"] = "Bauplan: Arkanitdrachling",
            ["Korean"] = "설계도: 아케이나이트 기계용",
            ["Mexican"] = "Esquema: dragonizo de arcanita",
            ["Portuguese"] = "Diagrama: Dragonete de Arcanita",
            ["Russian"] = "Чертеж: арканитовый дракончик",
            ["Spanish"] = "Esquema: dragonizo de arcanita",
            ["Taiwanese"] = "結構圖：奧金幼龍",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["range"] = {
                ["max_xp_level"] = 63,
                ["min_xp_level"] = 50,
            },
        },
        ["id"] = 16055,
        ["name"] = {
            ["Chinese"] = "结构图：奥术炸弹",
            ["English"] = "Schematic: Arcane Bomb",
            ["French"] = "Schéma : Bombe des arcanes",
            ["German"] = "Bauplan: Arkane Bombe",
            ["Korean"] = "설계도: 신비의 폭탄",
            ["Mexican"] = "Esquema: bomba Arcana",
            ["Portuguese"] = "Diagrama: Bomba Arcana",
            ["Russian"] = "Чертеж: чародейская бомба",
            ["Spanish"] = "Esquema: bomba Arcana",
            ["Taiwanese"] = "結構圖：祕法炸彈",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                8561,
            },
        },
        ["id"] = 16056,
        ["name"] = {
            ["Chinese"] = "结构图：完美的奥金步枪",
            ["English"] = "Schematic: Flawless Arcanite Rifle",
            ["French"] = "Schéma : Carabine en arcanite sans défaut",
            ["German"] = "Bauplan: Fehlerloses Arkanitgewehr",
            ["Korean"] = "설계도: 정교한 아케이나이트 소총",
            ["Mexican"] = "Esquema: rifle de arcanita impecable",
            ["Portuguese"] = "Diagrama: Rifle Impecável de Arcanita",
            ["Russian"] = "Чертеж: отличная арканитовая винтовка",
            ["Spanish"] = "Esquema: rifle de arcanita impecable",
            ["Taiwanese"] = "結構圖：完美的奧金步槍",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["holiday"] = 141,
        ["id"] = 17720,
        ["name"] = {
            ["Chinese"] = "结构图：雪王9000型",
            ["English"] = "Schematic: Snowmaster 9000",
            ["French"] = "Schéma : MaîtreNeige 9000",
            ["German"] = "Bauplan: Schneemeister 9000",
            ["Korean"] = "설계도: 눈뭉치제조기 9000",
            ["Mexican"] = "Esquema: Señor de las nieves 9000",
            ["Portuguese"] = "Diagrama: Mestreneves 9000",
            ["Russian"] = "Чертеж: \"Снегодел-9000\"",
            ["Spanish"] = "Esquema: señor de las nieves 9000",
            ["Taiwanese"] = "結構圖：雪王9000型",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8769,
        },
    },
    {
        ["id"] = 18235,
        ["name"] = {
            ["Chinese"] = "结构图：修理机器人74A型",
            ["English"] = "Schematic: Field Repair Bot 74A",
            ["French"] = "Schéma : Robot réparateur 74A",
            ["German"] = "Bauplan: Feldreparaturbot-74A",
            ["Korean"] = "설계도: 야전수리로봇 74A",
            ["Mexican"] = "Esquema: robot de reparación de campo 74A",
            ["Portuguese"] = "Diagrama: Robô de Reparos em Campo 74A",
            ["Russian"] = "Чертеж: полевой ремонтный робот 74A",
            ["Spanish"] = "Esquema: robot de reparación de campo 74A",
            ["Taiwanese"] = "結構圖：修理機器人74A型",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["special_action"] = "schematic Argelmach",
    },
    {
        ["drops"] = {
            ["sources"] = {
                11982,
                11988,
                12056,
                12057,
                12118,
                12259,
                12264,
            },
        },
        ["id"] = 18290,
        ["name"] = {
            ["Chinese"] = "结构图：比兹尼克247x128精确瞄准镜",
            ["English"] = "Schematic: Biznicks 247x128 Accurascope",
            ["French"] = "Schéma : Hyperviseur Biznicks 247 x 128",
            ["German"] = "Bauplan: Biznicks 247x128 treffsicheres Zielfernrohr",
            ["Korean"] = "설계도: 비즈닉스 247x128 조준경",
            ["Mexican"] = "Esquema: Acurascopio 247x128 de Biznicks",
            ["Portuguese"] = "Diagrama: Precisoscópio 247x128 Biznicks",
            ["Russian"] = "Чертеж: прицел \"Бизникс\" 247x128",
            ["Spanish"] = "Esquema: Acurascopio de 247x128 Biznicks",
            ["Taiwanese"] = "結構圖：比茲尼克247x128精確瞄準鏡",
        },
        ["phase"] = 1,
        ["quality"] = "rare",
    },
    {
        ["drops"] = {
            ["sources"] = {
                11982,
                11988,
                12056,
                12057,
                12118,
                12259,
                12264,
            },
        },
        ["id"] = 18291,
        ["name"] = {
            ["Chinese"] = "结构图：力反馈盾牌",
            ["English"] = "Schematic: Force Reactive Disk",
            ["French"] = "Schéma : Disque de force réactif",
            ["German"] = "Bauplan: Machtreaktive Scheibe",
            ["Korean"] = "설계도: 마력장 원반",
            ["Mexican"] = "Esquema: disco reactivo de fuerza",
            ["Portuguese"] = "Diagrama: Disco de Força Reativa",
            ["Russian"] = "Чертеж: реактивный диск",
            ["Spanish"] = "Esquema: disco reactivo de potencia",
            ["Taiwanese"] = "結構圖：力回饋盾牌",
        },
        ["phase"] = 1,
        ["quality"] = "rare",
    },
    {
        ["drops"] = {
            ["sources"] = {
                11982,
                11988,
                12056,
                12057,
                12118,
                12259,
                12264,
            },
        },
        ["id"] = 18292,
        ["name"] = {
            ["Chinese"] = "结构图：火核狙击步枪",
            ["English"] = "Schematic: Core Marksman Rifle",
            ["French"] = "Schéma : Carabine de tireur d'élite endurci",
            ["German"] = "Bauplan: Kernscharfschützengewehr",
            ["Korean"] = "설계도: 명사수의 라이플",
            ["Mexican"] = "Esquema: rifle de tirador del Núcleo",
            ["Portuguese"] = "Diagrama: Rifle Nuclear de Atirador Perito",
            ["Russian"] = "Чертеж: снайперская винтовка Центра",
            ["Spanish"] = "Esquema: rifle de tirador del Núcleo",
            ["Taiwanese"] = "結構圖：火核狙擊步槍",
        },
        ["phase"] = 1,
        ["quality"] = "rare",
    },
    {
        ["id"] = 18647,
        ["name"] = {
            ["Chinese"] = "结构图：红色焰火",
            ["English"] = "Schematic: Red Firework",
            ["French"] = "Schéma : Fusée rouge",
            ["German"] = "Bauplan: Rotes Feuerwerk",
            ["Korean"] = "설계도: 붉은 폭죽",
            ["Mexican"] = "Esquema: fuegos artificiales rojos",
            ["Portuguese"] = "Diagrama: Fogos de Artifício Vermelhos",
            ["Russian"] = "Чертеж: красная петарда",
            ["Spanish"] = "Esquema: fuego artificial rojo",
            ["Taiwanese"] = "結構圖：紅色煙火",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1800,
            ["sources"] = {
                3413,
            },
        },
    },
    {
        ["id"] = 18648,
        ["name"] = {
            ["Chinese"] = "结构图：绿色焰火",
            ["English"] = "Schematic: Green Firework",
            ["French"] = "Schéma : Fusée verte",
            ["German"] = "Bauplan: Grünes Feuerwerk",
            ["Korean"] = "설계도: 녹색 폭죽",
            ["Mexican"] = "Esquema: fuegos artificiales verdes",
            ["Portuguese"] = "Diagrama: Fogos de Artifício Verdes",
            ["Russian"] = "Чертеж: зеленая петарда",
            ["Spanish"] = "Esquema: fuego artificial verde",
            ["Taiwanese"] = "結構圖：綠色煙火",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1800,
            ["sources"] = {
                2838,
                3495,
            },
        },
    },
    {
        ["id"] = 18649,
        ["name"] = {
            ["Chinese"] = "结构图：蓝色焰火",
            ["English"] = "Schematic: Blue Firework",
            ["French"] = "Schéma : Fusée bleue",
            ["German"] = "Bauplan: Blaues Feuerwerk",
            ["Korean"] = "설계도: 푸른 폭죽",
            ["Mexican"] = "Esquema: fuegos artificiales azules",
            ["Portuguese"] = "Diagrama: Fogos de Artifício Azuis",
            ["Russian"] = "Чертеж: голубая петарда",
            ["Spanish"] = "Esquema: fuego artificial azul",
            ["Taiwanese"] = "結構圖：藍色煙火",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 1800,
            ["sources"] = {
                1304,
                5175,
            },
        },
    },
    {
        ["id"] = 18650,
        ["name"] = {
            ["Chinese"] = "结构图：简易投掷炸弹 II",
            ["English"] = "Schematic: EZ-Thro Dynamite II",
            ["French"] = "Schéma : Dynamite Ev-Lan II",
            ["German"] = "Bauplan: EZ-Thro-Dynamit II",
            ["Korean"] = "설계도: 초보자용 다이너마이트 II",
            ["Mexican"] = "Esquema: dinamita para tontos II",
            ["Portuguese"] = "Diagrama: Dinamite Taca-fácil II",
            ["Russian"] = "Чертеж: динамит \"Pro-100-брос II\"",
            ["Spanish"] = "Esquema: dinamita EZ-Thro 2",
            ["Taiwanese"] = "結構圖：簡易投擲炸彈 II",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 5000,
            ["sources"] = {
                8131,
            },
        },
    },
    {
        ["id"] = 18651,
        ["name"] = {
            ["Chinese"] = "结构图：真银变压器",
            ["English"] = "Schematic: Truesilver Transformer",
            ["French"] = "Schéma : Altérateur de vrai-argent",
            ["German"] = "Bauplan: Echtsilberumwandler",
            ["Korean"] = "설계도: 진은 변환기",
            ["Mexican"] = "Esquema: transformador de veraplata",
            ["Portuguese"] = "Diagrama: Transformador Veraprata",
            ["Russian"] = "Чертеж: преобразователь истинного серебра",
            ["Spanish"] = "Esquema: transformador de veraplata",
            ["Taiwanese"] = "結構圖：真銀變壓器",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 12000,
            ["sources"] = {
                2685,
            },
        },
    },
    {
        ["id"] = 18652,
        ["name"] = {
            ["Chinese"] = "结构图：超低温寒冰偏斜器",
            ["English"] = "Schematic: Gyrofreeze Ice Reflector",
            ["French"] = "Schéma : Réflectoglace gyrogivre",
            ["German"] = "Bauplan: Gyrofrosteisreflektor",
            ["Korean"] = "설계도: 회전냉각식 냉기 반사기",
            ["Mexican"] = "Esquema: reflector de hielo girohielo",
            ["Portuguese"] = "Diagrama: Refletor de Gelo Girogélido",
            ["Russian"] = "Чертеж: гирозамораживающий ледяной отражатель",
            ["Spanish"] = "Esquema: refractor de hielo Girohielo",
            ["Taiwanese"] = "結構圖：寒冰偏斜器",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 12000,
            ["sources"] = {
                11185,
            },
        },
    },
    {
        ["drops"] = {
            ["sources"] = {
                9499,
            },
        },
        ["id"] = 18653,
        ["name"] = {
            ["Chinese"] = "结构图：地精起搏器XL型",
            ["English"] = "Schematic: Goblin Jumper Cables XL",
            ["French"] = "Schéma : Défibrillateur gobelin XL",
            ["German"] = "Bauplan: Goblin-Überbrückungskabel XL",
            ["Korean"] = "설계도: 고블린 점퍼 케이블 XL",
            ["Mexican"] = "Esquema: desfibriladores goblin XL",
            ["Portuguese"] = "Diagrama: Cabo de Chupeta Goblínico XG",
            ["Russian"] = "Чертеж: гоблинский кабельный макси-дефибриллятор",
            ["Spanish"] = "Esquema: pinzas de batería goblin XL",
            ["Taiwanese"] = "結構圖：哥布林起搏器XL型",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                8920,
            },
        },
        ["id"] = 18654,
        ["name"] = {
            ["Chinese"] = "结构图：侏儒报警机器人",
            ["English"] = "Schematic: Gnomish Alarm-O-Bot",
            ["French"] = "Schéma : Robot d'alarme gnome",
            ["German"] = "Bauplan: Gnomischer Alarm-O-Bot",
            ["Korean"] = "설계도: 노움 자동경보기",
            ["Mexican"] = "Esquema: roboalarma gnómico",
            ["Portuguese"] = "Diagrama: Alarmobô Gnômico",
            ["Russian"] = "Чертеж: гномский тревого-бот",
            ["Spanish"] = "Esquema: robot alarma gnómico",
            ["Taiwanese"] = "結構圖：地精報警機器人",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 18655,
        ["name"] = {
            ["Chinese"] = "结构图：强力净化器",
            ["English"] = "Schematic: Major Recombobulator",
            ["French"] = "Schéma : Recombobulateur majeur",
            ["German"] = "Bauplan: Großer Rekombobulator",
            ["Korean"] = "설계도: 상급 유전자 역결합기",
            ["Mexican"] = "Esquema: recombobulador sublime",
            ["Portuguese"] = "Diagrama: Rebotocador Maior",
            ["Russian"] = "Чертеж: большой атомарный перенаправлятор",
            ["Spanish"] = "Esquema: recombobulador sublime",
            ["Taiwanese"] = "結構圖：強力淨化器",
        },
        ["phase"] = 2,
        ["quality"] = "uncommon",
        ["special_action"] = "dm tribute run",
    },
    {
        ["id"] = 18656,
        ["name"] = {
            ["Chinese"] = "结构图：强力爆盐炸弹",
            ["English"] = "Schematic: Powerful Seaforium Charge",
            ["French"] = "Schéma : Puissante charge d'hydroglycérine",
            ["German"] = "Bauplan: Mächtige Zephyriumladung",
            ["Korean"] = "설계도: 강력한 시포리움 폭약",
            ["Mexican"] = "Esquema: carga de seforio potente",
            ["Portuguese"] = "Diagrama: Carga Poderosa de Cequatrum",
            ["Russian"] = "Чертеж: мощный сефориевый заряд",
            ["Spanish"] = "Esquema: carga de seforio potente",
            ["Taiwanese"] = "結構圖：強力爆鹽炸彈",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["vendors"] = {
            ["price"] = 16000,
            ["sources"] = {
                11185,
            },
        },
    },
    {
        ["drops"] = {
            ["sources"] = {
                10264,
            },
        },
        ["id"] = 18657,
        ["name"] = {
            ["Chinese"] = "结构图：高辐射烈焰反射器",
            ["English"] = "Schematic: Hyper-Radiant Flame Reflector",
            ["French"] = "Schéma : Réflectoflamme hyper-radiant",
            ["German"] = "Bauplan: Hyperstrahlender Flammenreflektor",
            ["Korean"] = "설계도: 극고온 화염 반사기",
            ["Mexican"] = "Esquema: reflector de llamas hiperradiante",
            ["Portuguese"] = "Diagrama: Refletor de Chamas Hiper-radiante",
            ["Russian"] = "Чертеж: гипер-излучающий отражатель пламени",
            ["Spanish"] = "Esquema: refractor de llamas hiperradiante",
            ["Taiwanese"] = "結構圖：高輻射烈焰反射器",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                10426,
            },
        },
        ["id"] = 18658,
        ["name"] = {
            ["Chinese"] = "结构图：快速暗影反射器",
            ["English"] = "Schematic: Ultra-Flash Shadow Reflector",
            ["French"] = "Schéma : Réflectombre ultra-flash",
            ["German"] = "Bauplan: Ultrablendender Schattenreflektor",
            ["Korean"] = "설계도: 초광자 암흑 반사기",
            ["Mexican"] = "Esquema: reflector de las Sombras ultradeslumbrante",
            ["Portuguese"] = "Diagrama: Refletor de Sombras Ultrafulgurante",
            ["Russian"] = "Чертеж: ультра-вспышечный отражатель тьмы",
            ["Spanish"] = "Esquema: reflector de sombras ultra-flash",
            ["Taiwanese"] = "結構圖：快速暗影反射器",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["drops"] = {
            ["sources"] = {
                8920,
            },
        },
        ["id"] = 18661,
        ["name"] = {
            ["Chinese"] = "结构图：世界放大器",
            ["English"] = "Schematic: World Enlarger",
            ["French"] = "Schéma : Agrandisseur de monde",
            ["German"] = "Bauplan: Weltvergrößerer",
            ["Korean"] = "설계도: 아제로스 확대기",
            ["Mexican"] = "Esquema: amplificador de mundo",
            ["Portuguese"] = "Diagrama: Aumentador de Mundo",
            ["Russian"] = "Чертеж: увеличитель мира",
            ["Spanish"] = "Esquema: amplificador de mundo",
            ["Taiwanese"] = "結構圖：世界放大器",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
    },
    {
        ["id"] = 19027,
        ["name"] = {
            ["Chinese"] = "结构图：长蛇焰火",
            ["English"] = "Schematic: Snake Burst Firework",
            ["French"] = "Schéma : Feu d'artifice \"Explosion serpentine\"",
            ["German"] = "Bauplan: Schlangenexplosionsfeuerwerk",
            ["Korean"] = "설계도: 뱀꼬리 폭죽",
            ["Mexican"] = "Esquema: fuegos artificiales serpenteantes",
            ["Portuguese"] = "Diagrama: Rojão Rabo-de-cobra",
            ["Russian"] = "Чертеж: петарда \"Змеиное жало\"",
            ["Spanish"] = "Esquema: fuego artificial con forma de serpiente",
            ["Taiwanese"] = "結構圖：長蛇煙火",
        },
        ["phase"] = 1,
        ["quality"] = "common",
        ["special_action"] = "talk to npc after quest",
        ["vendors"] = {
            ["price"] = 5000,
            ["sources"] = {
                14637,
            },
        },
    },
    {
        ["id"] = 20000,
        ["name"] = {
            ["Chinese"] = "结构图：血藤护目镜",
            ["English"] = "Schematic: Bloodvine Goggles",
            ["French"] = "Schéma : Lunettes en vignesang",
            ["German"] = "Bauplan: Blutrebenschutzbrille",
            ["Korean"] = "설계도: 붉은덩굴 고글",
            ["Mexican"] = "Esquema: gafas vid de sangre",
            ["Portuguese"] = "Diagrama: Óculos Vinassangre",
            ["Russian"] = "Чертеж: очки Кровавой Лозы",
            ["Spanish"] = "Esquema: gafas Vid de sangre",
            ["Taiwanese"] = "結構圖：血藤護目鏡",
        },
        ["phase"] = 4,
        ["quality"] = "common",
        ["reputation"] = {
            ["faction_id"] = 270,
            ["level_id"] = 6,
        },
        ["vendors"] = {
            ["price"] = 120000,
            ["sources"] = {
                14921,
            },
        },
    },
    {
        ["id"] = 20001,
        ["name"] = {
            ["Chinese"] = "结构图：血藤透镜",
            ["English"] = "Schematic: Bloodvine Lens",
            ["French"] = "Schéma : Lentille en vignesang",
            ["German"] = "Bauplan: Blutrebenlinse",
            ["Korean"] = "설계도: 붉은덩굴 렌즈",
            ["Mexican"] = "Esquema: lente vid de sangre",
            ["Portuguese"] = "Diagrama: Lente Vinassangre",
            ["Russian"] = "Чертеж: линза Кровавой Лозы",
            ["Spanish"] = "Esquema: lentes Vid de sangre",
            ["Taiwanese"] = "結構圖：血藤透鏡",
        },
        ["phase"] = 4,
        ["quality"] = "common",
        ["reputation"] = {
            ["faction_id"] = 270,
            ["level_id"] = 5,
        },
        ["vendors"] = {
            ["price"] = 50000,
            ["sources"] = {
                14921,
            },
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21724,
        ["name"] = {
            ["Chinese"] = "结构图：小型蓝色烟花",
            ["English"] = "Schematic: Small Blue Rocket",
            ["French"] = "Schéma : Petite comète bleue",
            ["German"] = "Bauplan: Kleine blaue Rakete",
            ["Korean"] = "설계도: 작은 파란색 폭죽",
            ["Mexican"] = "Esquema: cohete azul pequeño",
            ["Portuguese"] = "Diagrama: Foguete Azul Pequeno",
            ["Russian"] = "Чертеж: маленькая синяя ракета",
            ["Spanish"] = "Esquema: cohete azul pequeño",
            ["Taiwanese"] = "結構圖 : 小型藍色煙花",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8876,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21725,
        ["name"] = {
            ["Chinese"] = "结构图：小型绿色烟花",
            ["English"] = "Schematic: Small Green Rocket",
            ["French"] = "Schéma : Petite comète verte",
            ["German"] = "Bauplan: Kleine grüne Rakete",
            ["Korean"] = "설계도: 작은 녹색 폭죽",
            ["Mexican"] = "Esquema: cohete verde pequeño",
            ["Portuguese"] = "Diagrama: Foguete Verde Pequeno",
            ["Russian"] = "Чертеж: маленькая зеленая ракета",
            ["Spanish"] = "Esquema: cohete verde pequeño",
            ["Taiwanese"] = "結構圖 : 小型綠色煙花",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8876,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21726,
        ["name"] = {
            ["Chinese"] = "结构图：小型红色烟花",
            ["English"] = "Schematic: Small Red Rocket",
            ["French"] = "Schéma : Petite comète rouge",
            ["German"] = "Bauplan: Kleine rote Rakete",
            ["Korean"] = "설계도: 작은 빨간색 폭죽",
            ["Mexican"] = "Esquema: cohete rojo pequeño",
            ["Portuguese"] = "Diagrama: Foguete Vermelho Pequeno",
            ["Russian"] = "Чертеж: маленькая красная ракета",
            ["Spanish"] = "Esquema: cohete rojo pequeño",
            ["Taiwanese"] = "結構圖 : 小型紅色煙花",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8876,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21727,
        ["name"] = {
            ["Chinese"] = "结构图：大型蓝色烟花",
            ["English"] = "Schematic: Large Blue Rocket",
            ["French"] = "Schéma : Grande comète bleue",
            ["German"] = "Bauplan: Große blaue Rakete",
            ["Korean"] = "설계도: 큰 파란색 폭죽",
            ["Mexican"] = "Esquema: cohete azul grande",
            ["Portuguese"] = "Diagrama: Foguete Azul Grande",
            ["Russian"] = "Чертеж: большая синяя ракета",
            ["Spanish"] = "Esquema: cohete azul grande",
            ["Taiwanese"] = "結構圖 : 大型藍色煙花",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8879,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21728,
        ["name"] = {
            ["Chinese"] = "结构图：大型绿色烟花",
            ["English"] = "Schematic: Large Green Rocket",
            ["French"] = "Schéma : Grande comète verte",
            ["German"] = "Bauplan: Große grüne Rakete",
            ["Korean"] = "설계도: 큰 녹색 폭죽",
            ["Mexican"] = "Esquema: cohete verde grande",
            ["Portuguese"] = "Diagrama: Foguete Verde Grande",
            ["Russian"] = "Чертеж: большая зеленая ракета",
            ["Spanish"] = "Esquema: cohete verde grande",
            ["Taiwanese"] = "結構圖 : 大型綠色煙花",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8879,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21729,
        ["name"] = {
            ["Chinese"] = "结构图：大型红色烟花",
            ["English"] = "Schematic: Large Red Rocket",
            ["French"] = "Schéma : Grande comète rouge",
            ["German"] = "Bauplan: Große rote Rakete",
            ["Korean"] = "설계도: 큰 빨간색 폭죽",
            ["Mexican"] = "Esquema: cohete rojo grande",
            ["Portuguese"] = "Diagrama: Foguete Vermelho Grande",
            ["Russian"] = "Чертеж: большая красная ракета",
            ["Spanish"] = "Esquema: cohete rojo grande",
            ["Taiwanese"] = "結構圖 : 大型紅色煙花",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8879,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21730,
        ["name"] = {
            ["Chinese"] = "结构图：蓝色烟花束",
            ["English"] = "Schematic: Blue Rocket Cluster",
            ["French"] = "Schéma : Chapelet de comètes bleues",
            ["German"] = "Bauplan: Blaues Raketenbündel",
            ["Korean"] = "설계도: 파란색 연발탄",
            ["Mexican"] = "Esquema: traca de cohetes azules",
            ["Portuguese"] = "Diagrama: Salva de Foguetes Azuis",
            ["Russian"] = "Чертеж: батарея синих фейерверков",
            ["Spanish"] = "Esquema: ristra de cohetes azules",
            ["Taiwanese"] = "結構圖 : 藍色煙花束",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8880,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21731,
        ["name"] = {
            ["Chinese"] = "结构图：绿色烟花束",
            ["English"] = "Schematic: Green Rocket Cluster",
            ["French"] = "Schéma : Chapelet de comètes vertes",
            ["German"] = "Bauplan: Grünes Raketenbündel",
            ["Korean"] = "설계도: 녹색 연발탄",
            ["Mexican"] = "Esquema: traca de cohetes verdes",
            ["Portuguese"] = "Diagrama: Salva de Foguetes Verdes",
            ["Russian"] = "Чертеж: батарея зеленых фейерверков",
            ["Spanish"] = "Esquema: ristra de cohetes verdes",
            ["Taiwanese"] = "結構圖 : 綠色煙花束",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8880,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21732,
        ["name"] = {
            ["Chinese"] = "结构图：红色烟花束",
            ["English"] = "Schematic: Red Rocket Cluster",
            ["French"] = "Schéma : Chapelet de comètes rouges",
            ["German"] = "Bauplan: Rotes Raketenbündel",
            ["Korean"] = "설계도: 빨간색 연발탄",
            ["Mexican"] = "Esquema: traca de cohetes rojos",
            ["Portuguese"] = "Diagrama: Salva de Foguetes Vermelhos",
            ["Russian"] = "Чертеж: батарея красных фейерверков",
            ["Spanish"] = "Esquema: ristra de cohetes rojos",
            ["Taiwanese"] = "結構圖 : 紅色煙花束",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8880,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21733,
        ["name"] = {
            ["Chinese"] = "结构图：大型蓝色烟花束",
            ["English"] = "Schematic: Large Blue Rocket Cluster",
            ["French"] = "Schéma : Chapelet de grandes comètes bleues",
            ["German"] = "Bauplan: Großes blaues Raketenbündel",
            ["Korean"] = "설계도: 큰 파란색 연발탄",
            ["Mexican"] = "Esquema: traca de cohetes azules grandes",
            ["Portuguese"] = "Diagrama: Grande Salva de Foguetes Azuis",
            ["Russian"] = "Чертеж: большая батарея синих фейерверков",
            ["Spanish"] = "Esquema: ristra de cohetes azules grandes",
            ["Taiwanese"] = "結構圖 : 大型藍色煙花束",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8881,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21734,
        ["name"] = {
            ["Chinese"] = "结构图：大型绿色烟花束",
            ["English"] = "Schematic: Large Green Rocket Cluster",
            ["French"] = "Schéma : Chapelet de grandes comètes vertes",
            ["German"] = "Bauplan: Großes grünes Raketenbündel",
            ["Korean"] = "설계도: 큰 녹색 연발탄",
            ["Mexican"] = "Esquema: traca de cohetes verdes grandes",
            ["Portuguese"] = "Diagrama: Grande Salva de Foguetes Verdes",
            ["Russian"] = "Чертеж: большая батарея зеленых фейерверков",
            ["Spanish"] = "Esquema: ristra de cohetes verdes grandes",
            ["Taiwanese"] = "結構圖 : 大型綠色煙花束",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8881,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21735,
        ["name"] = {
            ["Chinese"] = "结构图：大型红色烟花束",
            ["English"] = "Schematic: Large Red Rocket Cluster",
            ["French"] = "Schéma : Chapelet de grandes comètes rouges",
            ["German"] = "Bauplan: Großes rotes Raketenbündel",
            ["Korean"] = "설계도: 큰 빨간색 연발탄",
            ["Mexican"] = "Esquema: traca de cohetes rojos grandes",
            ["Portuguese"] = "Diagrama: Grande Salva de Foguetes Vermelhos",
            ["Russian"] = "Чертеж: большая батарея красных фейерверков",
            ["Spanish"] = "Esquema: ristra de cohetes rojos grandes",
            ["Taiwanese"] = "結構圖 : 大型紅色煙花束",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8881,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21737,
        ["name"] = {
            ["Chinese"] = "结构图：烟花束发射器",
            ["English"] = "Schematic: Cluster Launcher",
            ["French"] = "Schéma : Lanceur de chapelets",
            ["German"] = "Bauplan: Zünder für Raketenbündel",
            ["Korean"] = "설계도: 연발탄 발사대",
            ["Mexican"] = "Esquema: lanzatracas",
            ["Portuguese"] = "Diagrama: Lançador de Salva de Fogos de Artifício",
            ["Russian"] = "Чертеж: пусковая установка для батарей фейерверков",
            ["Spanish"] = "Esquema: lanzacohetes",
            ["Taiwanese"] = "結構圖 : 煙花束發射器",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8882,
        },
    },
    {
        ["holiday"] = 327,
        ["id"] = 21738,
        ["name"] = {
            ["Chinese"] = "结构图：烟花发射器",
            ["English"] = "Schematic: Firework Launcher",
            ["French"] = "Schéma : Lanceur de fusées",
            ["German"] = "Bauplan: Zünder für Feuerwerk",
            ["Korean"] = "설계도: 폭죽 발사대",
            ["Mexican"] = "Esquema: lanzador de fuegos artificiales",
            ["Portuguese"] = "Diagrama: Lançador de Fogos de Artifício",
            ["Russian"] = "Чертеж: пусковая установка для фейерверков",
            ["Spanish"] = "Esquema: lanzacohetes pirotécnico",
            ["Taiwanese"] = "結構圖 : 煙火發射器",
        },
        ["phase"] = 1,
        ["quality"] = "uncommon",
        ["quests"] = {
            8877,
        },
    },
    {
        ["holiday"] = 999999,
        ["id"] = 22729,
        ["name"] = {
            ["Chinese"] = "结构图：蒸汽车控制器",
            ["English"] = "Schematic: Steam Tonk Controller",
            ["French"] = "Schéma : Commande de chariotte à vapeur",
            ["German"] = "Bauplan: Dampfpanzersteuerung",
            ["Korean"] = "설계도: 통통 전차 조종기",
            ["Mexican"] = "Esquema: mando de tonque de vapor",
            ["Portuguese"] = "Diagrama: Controlador de Tonque a Vapor",
            ["Russian"] = "Чертеж: пульт управления паровым танком",
            ["Spanish"] = "Esquema: mando de tanque a vapor",
            ["Taiwanese"] = "設計圖：蒸氣坦克控制器",
        },
        ["phase"] = 6,
        ["quality"] = "common",
        ["quests"] = {
            9249,
        },
    },
}
