TRADE_SKILLS_DATA["levels"]["Engineering"] = {
    {
        ["id"] = 4036,
        ["max_skill"] = 75,
        ["min_skill"] = 0,
        ["min_xp_level"] = 5,
        ["name"] = {
            ["Chinese"] = "工程学 (初级)",
            ["English"] = "Engineering (Apprentice)",
            ["French"] = "Ingénierie (Apprenti)",
            ["German"] = "Ingenieurskunst (Lehrling)",
            ["Korean"] = "기계공학 (초급)",
            ["Mexican"] = "Ingeniería (Aprendiz)",
            ["Portuguese"] = "Engenharia (Aprendiz)",
            ["Russian"] = "Инженерное дело (Ученик)",
            ["Spanish"] = "Ingeniería (Aprendiz)",
            ["Taiwanese"] = "工程學 (學徒)",
        },
        ["phase"] = 1,
        ["rank"] = 1,
        ["trainers"] = {
            ["price"] = 10,
            ["sources"] = {
                1702,
                2857,
                3290,
                3494,
                4586,
                10993,
                11025,
                11026,
                11028,
                11037,
            },
        },
    },
    {
        ["id"] = 4037,
        ["max_skill"] = 150,
        ["min_skill"] = 50,
        ["min_xp_level"] = 10,
        ["name"] = {
            ["Chinese"] = "工程学 (中级)",
            ["English"] = "Engineering (Journeyman)",
            ["French"] = "Ingénierie (Compagnon)",
            ["German"] = "Ingenieurskunst (Geselle)",
            ["Korean"] = "기계공학 (수습)",
            ["Mexican"] = "Ingeniería (Oficial)",
            ["Portuguese"] = "Engenharia (Profissional)",
            ["Russian"] = "Инженерное дело (Подмастерье)",
            ["Spanish"] = "Ingeniería (Oficial)",
            ["Taiwanese"] = "工程學 (熟練工)",
        },
        ["phase"] = 1,
        ["rank"] = 2,
        ["trainers"] = {
            ["price"] = 500,
            ["sources"] = {
                1676,
                3412,
                5518,
                11029,
                11031,
            },
        },
    },
    {
        ["id"] = 4038,
        ["max_skill"] = 225,
        ["min_skill"] = 125,
        ["min_xp_level"] = 20,
        ["name"] = {
            ["Chinese"] = "工程学 (高级)",
            ["English"] = "Engineering (Expert)",
            ["French"] = "Ingénierie (Expert)",
            ["German"] = "Ingenieurskunst (Experte)",
            ["Korean"] = "기계공학 (숙련)",
            ["Mexican"] = "Ingeniería (Experto)",
            ["Portuguese"] = "Engenharia (Perito)",
            ["Russian"] = "Инженерное дело (Умелец)",
            ["Spanish"] = "Ingeniería (Experto)",
            ["Taiwanese"] = "工程學 (專家)",
        },
        ["phase"] = 1,
        ["rank"] = 3,
        ["trainers"] = {
            ["price"] = 5000,
            ["sources"] = {
                5174,
                11017,
            },
        },
    },
    {
        ["id"] = 12656,
        ["max_skill"] = 300,
        ["min_skill"] = 200,
        ["min_xp_level"] = 35,
        ["name"] = {
            ["Chinese"] = "工程学 (大师级)",
            ["English"] = "Engineering (Artisan)",
            ["French"] = "Ingénierie (Artisan)",
            ["German"] = "Ingenieurskunst (Fachmann)",
            ["Korean"] = "기계공학 (전문)",
            ["Mexican"] = "Ingeniería (Artesano)",
            ["Portuguese"] = "Engenharia (Artifice)",
            ["Russian"] = "Инженерное дело (Мастеровой)",
            ["Spanish"] = "Ingeniería (Artesano)",
            ["Taiwanese"] = "工程學 (大工匠)",
        },
        ["phase"] = 1,
        ["rank"] = 4,
        ["trainers"] = {
            ["price"] = 50000,
            ["sources"] = {
                8736,
            },
        },
    },
}
