TRADE_SKILLS_DATA["items"]["Enchanting"] =
    {
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 20,
                    ["min_xp_level"] = 5,
                },
            },
            ["id"] = 6342,
            ["name"] = {
                ["Chinese"] = "公式：附魔胸甲 - 初级法力",
                ["English"] = "Formula: Enchant Chest - Minor Mana",
                ["French"] = "Formule : Enchantement de plastron (Mana mineur)",
                ["German"] = "Formel: Brust - Schwaches Mana",
                ["Korean"] = "주문식: 가슴보호구 마법부여 - 최하급 마나",
                ["Mexican"] = "Fórmula: encantar pechera: maná menor",
                ["Portuguese"] = "Fórmula: Encantamento Menor de Mana - Torso",
                ["Russian"] = "Формула чар для нагрудника: мана I",
                ["Spanish"] = "Fórmula: encantar pechera: maná menor",
                ["Taiwanese"] = "公式：附魔胸甲 - 初級法力",
            },
            ["quality"] = "uncommon",
            ["vendors"] = {
                ["price"] = 300,
                ["sources"] = {
                    1318,
                    3012,
                    3346,
                    4228,
                    4617,
                    5158,
                    5757,
                    5758,
                    15419,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 25,
                    ["min_xp_level"] = 10,
                },
            },
            ["id"] = 6344,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 初级精神",
                ["English"] = "Formula: Enchant Bracer - Minor Spirit",
                ["French"] = "Formule : Enchantement de bracelets (Esprit mineur)",
                ["German"] = "Formel: Armschiene - Schwache Willenskraft",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 최하급 정신력",
                ["Mexican"] = "Fórmula: encantar brazales: espíritu menor",
                ["Portuguese"] = "Fórmula: Encantamento Menor de Espírito - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: дух I",
                ["Spanish"] = "Fórmula: encantar brazal: espíritu menor",
                ["Taiwanese"] = "公式：附魔護腕 - 初級精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 6346,
            ["name"] = {
                ["Chinese"] = "公式：附魔胸甲 - 次级法力",
                ["English"] = "Formula: Enchant Chest - Lesser Mana",
                ["French"] = "Formule : Enchantement de plastron (Mana inférieur)",
                ["German"] = "Formel: Brust - Geringes Mana",
                ["Korean"] = "주문식: 가슴보호구 마법부여 - 하급 마나",
                ["Mexican"] = "Fórmula: encantar pechera: maná inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Mana - Torso",
                ["Russian"] = "Формула чар для нагрудника: мана II",
                ["Spanish"] = "Fórmula: encantar pechera: maná inferior",
                ["Taiwanese"] = "公式：附魔胸甲 - 次級法力",
            },
            ["quality"] = "uncommon",
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    3346,
                    5757,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 25,
                    ["min_xp_level"] = 10,
                },
            },
            ["id"] = 6347,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 初级力量",
                ["English"] = "Formula: Enchant Bracer - Minor Strength",
                ["French"] = "Formule : Enchantement de bracelets (Force mineure)",
                ["German"] = "Formel: Armschiene - Schwache Stärke",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 최하급 힘",
                ["Mexican"] = "Fórmula: encantar brazales: fuerza menor",
                ["Portuguese"] = "Fórmula: Encantamento Menor de Força - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: сила I",
                ["Spanish"] = "Fórmula: encantar brazal: fuerza menor",
                ["Taiwanese"] = "公式：附魔護腕 - 初級力量",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 25,
                    ["min_xp_level"] = 10,
                },
            },
            ["id"] = 6348,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 初级屠兽",
                ["English"] = "Formula: Enchant Weapon - Minor Beastslayer",
                ["French"] = "Formule : Enchantement d'arme (Tueur de bête mineur)",
                ["German"] = "Formel: Waffe - Schwacher Wildtiertöter",
                ["Korean"] = "주문식: 한손 무기 마법부여 - 야수 사냥",
                ["Mexican"] = "Fórmula: encantar arma: Destripadora de bestias menor",
                ["Portuguese"] = "Fórmula: Encantamento Menor de Matador de Feras - Arma",
                ["Russian"] = "Формула чар для оружия: зверобой I",
                ["Spanish"] = "Fórmula: encantar arma: bestiacida menor",
                ["Taiwanese"] = "公式：附魔武器 - 初級屠獸",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 6349,
            ["name"] = {
                ["Chinese"] = "公式：附魔双手武器 - 次级智力",
                ["English"] = "Formula: Enchant 2H Weapon - Lesser Intellect",
                ["French"] = "Formule : Enchantement d'arme 2M (Intelligence inférieure)",
                ["German"] = "Formel: Zweihandwaffe - Geringe Intelligenz",
                ["Korean"] = "주문식: 양손 무기 마법부여 - 하급 지능",
                ["Mexican"] = "Fórmula: encantar arma de 2M: intelecto inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Intelecto - Arma de 2M",
                ["Russian"] = "Формула чар для двуручного оружия: интеллект I",
                ["Spanish"] = "Fórmula: encantar arma de 2M: intelecto inferior",
                ["Taiwanese"] = "公式：附魔雙手武器 - 次級智力",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 500,
                ["sources"] = {
                    3012,
                    3346,
                    5158,
                    5758,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 30,
                    ["min_xp_level"] = 15,
                },
            },
            ["id"] = 6375,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 次级精神",
                ["English"] = "Formula: Enchant Bracer - Lesser Spirit",
                ["French"] = "Formule : Enchantement de bracelet (Esprit inférieur)",
                ["German"] = "Formel: Armschiene - Geringe Willenskraft",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 하급 정신력",
                ["Mexican"] = "Fórmula: encantar brazales: espíritu inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Espírito - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: дух II",
                ["Spanish"] = "Fórmula: encantar brazal: espíritu inferior",
                ["Taiwanese"] = "公式：附魔護腕 - 次級精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 6377,
            ["name"] = {
                ["Chinese"] = "公式：附魔靴子 - 初级敏捷",
                ["English"] = "Formula: Enchant Boots - Minor Agility",
                ["French"] = "Formule : Bottes enchantées (Agilité mineure)",
                ["German"] = "Formel: Stiefel - Schwache Beweglichkeit",
                ["Korean"] = "주문식: 장화 마법부여 - 최하급 민첩성",
                ["Mexican"] = "Fórmula: encantar botas: agilidad menor",
                ["Portuguese"] = "Fórmula: Encantamento Menor de Agilidade - Botas",
                ["Russian"] = "Формула чар для обуви: ловкость I",
                ["Spanish"] = "Fórmula: encantar botas: agilidad menor",
                ["Taiwanese"] = "公式：附魔靴子 - 初級敏捷",
            },
            ["quality"] = "uncommon",
            ["vendors"] = {
                ["price"] = 1000,
                ["sources"] = {
                    3012,
                    3537,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 30,
                    ["min_xp_level"] = 15,
                },
            },
            ["id"] = 11038,
            ["name"] = {
                ["Chinese"] = "公式：附魔双手武器 - 次级精神",
                ["English"] = "Formula: Enchant 2H Weapon - Lesser Spirit",
                ["French"] = "Formule : Enchantement d'arme 2M (Esprit inférieur)",
                ["German"] = "Formel: Zweihandwaffe - Geringe Willenskraft",
                ["Korean"] = "주문식: 양손 무기 마법부여 - 하급 정신력",
                ["Mexican"] = "Fórmula: encantar arma de 2M: espíritu inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Espírito - Arma de 2M",
                ["Russian"] = "Формула чар для двуручного оружия: дух I",
                ["Spanish"] = "Fórmula: encantar arma de 2M: espíritu inferior",
                ["Taiwanese"] = "公式：附魔雙手武器 - 次級精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 30,
                    ["min_xp_level"] = 15,
                },
            },
            ["id"] = 11039,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 初级敏捷",
                ["English"] = "Formula: Enchant Cloak - Minor Agility",
                ["French"] = "Formule : Enchantement de cape (Agilité mineure)",
                ["German"] = "Formel: Umhang - Schwache Beweglichkeit",
                ["Korean"] = "주문식: 망토 마법부여 - 최하급 민첩성",
                ["Mexican"] = "Fórmula: encantar capa: agilidad menor",
                ["Portuguese"] = "Fórmula: Encantamento Menor de Agilidade - Manto",
                ["Russian"] = "Формула чар для плаща: ловкость I",
                ["Spanish"] = "Fórmula: encantar capa: agilidad menor",
                ["Taiwanese"] = "公式：附魔披風 - 初級敏捷",
            },
            ["quality"] = "uncommon",
            ["vendors"] = {
                ["price"] = 800,
                ["sources"] = {
                    3954,
                    12043,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 30,
                    ["min_xp_level"] = 15,
                },
            },
            ["id"] = 11081,
            ["name"] = {
                ["Chinese"] = "公式：附魔盾牌 - 次级防护",
                ["English"] = "Formula: Enchant Shield - Lesser Protection",
                ["French"] = "Formule : Enchantement de bouclier (Protection inférieure)",
                ["German"] = "Formel: Schild - Geringer Schutz",
                ["Korean"] = "주문식: 방패 마법부여 - 하급 보호",
                ["Mexican"] = "Fórmula: encantar escudo: protección inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Proteção - Escudo",
                ["Russian"] = "Формула чар для щита: броня",
                ["Spanish"] = "Fórmula: encantar escudo: protección inferior",
                ["Taiwanese"] = "公式：附魔盾牌 - 次級防護",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 35,
                    ["min_xp_level"] = 20,
                },
            },
            ["id"] = 11098,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 抵抗次级暗影",
                ["English"] = "Formula: Enchant Cloak - Lesser Shadow Resistance",
                ["French"] = "Formule : Enchantement de cape (Résistance aux ténèbres inférieure)",
                ["German"] = "Formel: Umhang - Geringer Schattenwiderstand",
                ["Korean"] = "주문식: 망토 마법부여 - 하급 암흑 저항",
                ["Mexican"] = "Fórmula: encantar capa: Resistencia a las Sombras inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Resistência à Sombra - Manto",
                ["Russian"] = "Формула чар для плаща: сопротивление темной магии I",
                ["Spanish"] = "Fórmula: encantar capa: resistencia inferior a las Sombras",
                ["Taiwanese"] = "公式：附魔披風 - 抵抗次級暗影",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 11101,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 次级力量",
                ["English"] = "Formula: Enchant Bracer - Lesser Strength",
                ["French"] = "Formule : Enchantement de bracelets (Force inférieure)",
                ["German"] = "Formel: Armschiene - Geringe Stärke",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 하급 힘",
                ["Mexican"] = "Fórmula: encantar brazales: fuerza inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Força - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: сила II",
                ["Spanish"] = "Fórmula: encantar brazal: fuerza inferior",
                ["Taiwanese"] = "公式：附魔護腕 - 次級力量",
            },
            ["quality"] = "uncommon",
            ["vendors"] = {
                ["price"] = 2500,
                ["sources"] = {
                    3954,
                    12043,
                },
            },
        },
        {
            ["drops"] = {
                ["sources"] = {
                    1051,
                    1052,
                    1053,
                    1054,
                    1364,
                },
            },
            ["id"] = 11150,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 采矿",
                ["English"] = "Formula: Enchant Gloves - Mining",
                ["French"] = "Formule : Enchantement de gants (Minage)",
                ["German"] = "Formel: Handschuhe - Bergbau",
                ["Korean"] = "주문식: 장갑 마법부여 - 채광",
                ["Mexican"] = "Fórmula: encantar guantes: minería",
                ["Portuguese"] = "Fórmula: Encantamento de Mineração - Luvas",
                ["Russian"] = "Формула чар для перчаток: горное дело I",
                ["Spanish"] = "Fórmula: encantar guantes: minería",
                ["Taiwanese"] = "公式：附魔手套 - 採礦",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    3834,
                    3919,
                    4028,
                    4029,
                    4030,
                },
            },
            ["id"] = 11151,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 采药",
                ["English"] = "Formula: Enchant Gloves - Herbalism",
                ["French"] = "Formule : Enchantement de gants (Herboristerie)",
                ["German"] = "Formel: Handschuhe - Kräuterkunde",
                ["Korean"] = "주문식: 장갑 마법부여 - 약초 채집",
                ["Mexican"] = "Fórmula: encantar guantes: herboristería",
                ["Portuguese"] = "Fórmula: Encantamento de Herborismo - Luvas",
                ["Russian"] = "Формула чар для перчаток: травничество I",
                ["Spanish"] = "Fórmula: encantar guantes: herboristería",
                ["Taiwanese"] = "公式：附魔手套 - 採藥",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    2374,
                    2375,
                    2376,
                    2377,
                    14276,
                },
            },
            ["id"] = 11152,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 钓鱼",
                ["English"] = "Formula: Enchant Gloves - Fishing",
                ["French"] = "Formule : Enchantement de gants (Pêche)",
                ["German"] = "Formel: Handschuhe - Angeln",
                ["Korean"] = "주문식: 장갑 마법부여 - 낚시",
                ["Mexican"] = "Fórmula: encantar guantes: pesca",
                ["Portuguese"] = "Fórmula: Encantamento de Pescaria - Luvas",
                ["Russian"] = "Формула чар для перчаток: рыбная ловля",
                ["Spanish"] = "Fórmula: encantar guantes: pesca",
                ["Taiwanese"] = "公式：附魔手套 - 釣魚",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 11163,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 次级偏斜",
                ["English"] = "Formula: Enchant Bracer - Lesser Deflection",
                ["French"] = "Formule : Enchantement de bracelets (Déviation inférieure)",
                ["German"] = "Formel: Armschiene - Geringe Abwehr",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 하급 회피",
                ["Mexican"] = "Fórmula: encantar brazal: desvío inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Deflexão - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: отражение II",
                ["Spanish"] = "Fórmula: encantar brazal: desvío inferior",
                ["Taiwanese"] = "公式：附魔護腕 - 次級偏斜",
            },
            ["quality"] = "uncommon",
            ["vendors"] = {
                ["price"] = 3000,
                ["sources"] = {
                    2381,
                    2821,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 40,
                    ["min_xp_level"] = 25,
                },
            },
            ["id"] = 11164,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 次级屠兽",
                ["English"] = "Formula: Enchant Weapon - Lesser Beastslayer",
                ["French"] = "Formule : Enchantement d'arme (Tueur de bête inférieur)",
                ["German"] = "Formel: Waffe - Geringer Wildtiertöter",
                ["Korean"] = "주문식: 무기 마법부여 - 하급 야수 사냥",
                ["Mexican"] = "Fórmula: encantar arma: Destripadora de bestias inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Matador de Feras - Arma",
                ["Russian"] = "Формула чар для оружия: зверобой II",
                ["Spanish"] = "Fórmula: encantar arma: bestiacida inferior",
                ["Taiwanese"] = "公式：附魔武器 - 次級屠獸",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 40,
                    ["min_xp_level"] = 25,
                },
            },
            ["id"] = 11165,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 次级元素杀手",
                ["English"] = "Formula: Enchant Weapon - Lesser Elemental Slayer",
                ["French"] = "Formule : Enchantement d'arme (Tueur d'élémentaire inférieur)",
                ["German"] = "Formel: Waffe - Geringer Elementartöter",
                ["Korean"] = "주문식: 무기 마법부여 - 하급 정령 사냥",
                ["Mexican"] = "Fórmula: encantar arma: mataelementales inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Matador de Elementais - Arma",
                ["Russian"] = "Формула чар для оружия: начинающий убийца элементалей",
                ["Spanish"] = "Fórmula: encantar arma: mataelementales inferior",
                ["Taiwanese"] = "公式：附魔武器 - 次級元素殺手",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    2556,
                    2557,
                    2558,
                    2606,
                },
            },
            ["id"] = 11166,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 剥皮",
                ["English"] = "Formula: Enchant Gloves - Skinning",
                ["French"] = "Formule : Enchantement de gants (Dépeçage)",
                ["German"] = "Formel: Handschuhe - Kürschnerei",
                ["Korean"] = "주문식: 장갑 마법부여 - 무두질",
                ["Mexican"] = "Fórmula: encantar guantes: desuello",
                ["Portuguese"] = "Fórmula: Encantamento de Esfolamento - Luvas",
                ["Russian"] = "Формула чар для перчаток: снятие шкур",
                ["Spanish"] = "Fórmula: encantar guantes: desuello",
                ["Taiwanese"] = "公式：附魔手套 - 剝皮",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 45,
                    ["min_xp_level"] = 30,
                },
            },
            ["id"] = 11167,
            ["name"] = {
                ["Chinese"] = "公式：附魔靴子 - 次级精神",
                ["English"] = "Formula: Enchant Boots - Lesser Spirit",
                ["French"] = "Formule : Enchantement de bottes (Esprit inférieur)",
                ["German"] = "Formel: Stiefel - Geringe Willenskraft",
                ["Korean"] = "주문식: 장화 마법부여 - 하급 정신력",
                ["Mexican"] = "Fórmula: encantar botas: espíritu inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Espírito - Botas",
                ["Russian"] = "Формула чар для обуви: дух I",
                ["Spanish"] = "Fórmula: encantar botas: espíritu inferior",
                ["Taiwanese"] = "公式：附魔靴子 - 次級精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 45,
                    ["min_xp_level"] = 30,
                },
            },
            ["id"] = 11168,
            ["name"] = {
                ["Chinese"] = "公式：附魔盾牌 - 次级格挡",
                ["English"] = "Formula: Enchant Shield - Lesser Block",
                ["French"] = "Formule : Enchantement de bouclier (Blocage inférieur)",
                ["German"] = "Formel: Schild - Geringes Blocken",
                ["Korean"] = "주문식: 방패 마법부여 - 하급 방어",
                ["Mexican"] = "Fórmula: encantar escudo: bloqueo inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Bloqueio - Escudo",
                ["Russian"] = "Формула чар для щита: блок I",
                ["Spanish"] = "Fórmula: encantar escudo: bloqueo inferior",
                ["Taiwanese"] = "公式：附魔盾牌 - 次級格擋",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 50,
                    ["min_xp_level"] = 35,
                },
            },
            ["id"] = 11202,
            ["name"] = {
                ["Chinese"] = "公式：附魔盾牌 - 耐力",
                ["English"] = "Formula: Enchant Shield - Stamina",
                ["French"] = "Formule : Enchantement de bouclier (Endurance)",
                ["German"] = "Formel: Schild - Ausdauer",
                ["Korean"] = "주문식: 방패 마법부여 - 체력",
                ["Mexican"] = "Fórmula: encantar escudo: aguante",
                ["Portuguese"] = "Fórmula: Encantamento de Vigor - Escudo",
                ["Russian"] = "Формула чар для щита: выносливость III",
                ["Spanish"] = "Fórmula: encantar escudo: aguante",
                ["Taiwanese"] = "公式：附魔盾牌 - 耐力",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    674,
                },
            },
            ["id"] = 11203,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 高级采矿",
                ["English"] = "Formula: Enchant Gloves - Advanced Mining",
                ["French"] = "Formule : Enchantement de gants (Minage avancé)",
                ["German"] = "Formel: Handschuhe - Hochentwickelter Bergbau",
                ["Korean"] = "주문식: 장갑 마법부여 - 채광 숙련",
                ["Mexican"] = "Fórmula: encantar guantes: minería avanzada",
                ["Portuguese"] = "Fórmula: Encantamento de Mineração Avançada - Luvas",
                ["Russian"] = "Формула чар для перчаток: горное дело II",
                ["Spanish"] = "Fórmula: encantar guantes: minería avanzada",
                ["Taiwanese"] = "公式：附魔手套 - 高級採礦",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 50,
                    ["min_xp_level"] = 35,
                },
            },
            ["id"] = 11204,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 强效精神",
                ["English"] = "Formula: Enchant Bracer - Greater Spirit",
                ["French"] = "Formule : Enchantement de bracelets (Esprit supérieur)",
                ["German"] = "Formel: Armschiene - Große Willenskraft",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 상급 정신력",
                ["Mexican"] = "Fórmula: encantar brazales: espíritu superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Espírito - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: дух IV",
                ["Spanish"] = "Fórmula: encantar brazal: espíritu superior",
                ["Taiwanese"] = "公式：附魔護腕 - 強效精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    764,
                    765,
                    766,
                    1081,
                    14448,
                },
            },
            ["id"] = 11205,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 高级草药学",
                ["English"] = "Formula: Enchant Gloves - Advanced Herbalism",
                ["French"] = "Formule : Enchantement de gants (Herboristerie avancée)",
                ["German"] = "Formel: Handschuhe - Hochentwickelte Kräuterkunde",
                ["Korean"] = "주문식: 장갑 마법부여 - 약초 채집 숙련",
                ["Mexican"] = "Fórmula: encantar guantes: herboristería avanzada",
                ["Portuguese"] = "Fórmula: Encantamento de Herborismo Avançado - Luvas",
                ["Russian"] = "Формула чар для перчаток: травничество II",
                ["Spanish"] = "Fórmula: encantar guantes: herboristería avanzada",
                ["Taiwanese"] = "公式：附魔手套 - 高級草藥學",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    2246,
                    5623,
                    7805,
                },
            },
            ["id"] = 11206,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 次级敏捷",
                ["English"] = "Formula: Enchant Cloak - Lesser Agility",
                ["French"] = "Formule : Enchantement de cape (Agilité inférieure)",
                ["German"] = "Formel: Umhang - Geringe Beweglichkeit",
                ["Korean"] = "주문식: 망토 마법부여 - 하급 민첩성",
                ["Mexican"] = "Fórmula: encantar capa: Agilidad inferior",
                ["Portuguese"] = "Fórmula: Encantamento Inferior de Agilidade - Manto",
                ["Russian"] = "Формула чар для плаща: ловкость II",
                ["Spanish"] = "Fórmula: encantar capa: agilidad inferior",
                ["Taiwanese"] = "公式：附魔披風 - 次級敏捷",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    9024,
                },
            },
            ["id"] = 11207,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 灼热武器",
                ["English"] = "Formula: Enchant Weapon - Fiery Weapon",
                ["French"] = "Formule : Enchantement d'arme (Arme flamboyante)",
                ["German"] = "Formel: Waffe - Feurige Waffe",
                ["Korean"] = "주문식: 무기 마법부여 - 불타는 무기",
                ["Mexican"] = "Fórmula: encantar arma: arma ígnea",
                ["Portuguese"] = "Fórmula: Encantamento de Arma Ígnea - Arma",
                ["Russian"] = "Формула чар для оружия: огненное оружие",
                ["Spanish"] = "Fórmula: encantar arma: arma ígnea",
                ["Taiwanese"] = "公式：附魔武器 - 灼熱武器",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 55,
                    ["min_xp_level"] = 40,
                },
            },
            ["id"] = 11208,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 屠魔",
                ["English"] = "Formula: Enchant Weapon - Demonslaying",
                ["French"] = "Formule : Enchantement d'arme (Tueur de démon)",
                ["German"] = "Formel: Waffe - Dämonentöten",
                ["Korean"] = "주문식: 무기 마법부여 - 악마 사냥",
                ["Mexican"] = "Fórmula: encantar arma: matanza de demonios",
                ["Portuguese"] = "Fórmula: Encantamento de Demonicídio - Arma",
                ["Russian"] = "Формула чар для оружия: истребитель демонов",
                ["Spanish"] = "Fórmula: encantar arma: matanza de demonios",
                ["Taiwanese"] = "公式：附魔武器 - 屠魔",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 11223,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 偏斜",
                ["English"] = "Formula: Enchant Bracer - Deflection",
                ["French"] = "Formule : Enchantement de bracelets (Déviation)",
                ["German"] = "Formel: Armschiene - Abwehr",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 회피",
                ["Mexican"] = "Fórmula: encantar brazal: desvío",
                ["Portuguese"] = "Fórmula: Encantamento de Deflexão - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: отражение III",
                ["Spanish"] = "Fórmula: encantar brazal: desvío",
                ["Taiwanese"] = "公式：附魔護腕 - 偏斜",
            },
            ["quality"] = "uncommon",
            ["vendors"] = {
                ["price"] = 5800,
                ["sources"] = {
                    989,
                    4229,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 55,
                    ["min_xp_level"] = 40,
                },
            },
            ["id"] = 11224,
            ["name"] = {
                ["Chinese"] = "公式：附魔盾牌 - 冰霜反射",
                ["English"] = "Formula: Enchant Shield - Frost Resistance",
                ["French"] = "Formule : Enchantement de bouclier (Résistance au givre)",
                ["German"] = "Formel: Schild - Frostwiderstand",
                ["Korean"] = "주문식: 방패 마법부여 - 냉기 저항",
                ["Mexican"] = "Fórmula: encantar escudo: Resistencia a la Escarcha",
                ["Portuguese"] = "Fórmula: Encantamento de Resistência ao Gelo - Escudo",
                ["Russian"] = "Формула чар для щита: сопротивление льду",
                ["Spanish"] = "Fórmula: encantar escudo: resistencia a Escarcha",
                ["Taiwanese"] = "公式：附魔盾牌 - 冰霜反射",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 55,
                    ["min_xp_level"] = 40,
                },
            },
            ["id"] = 11225,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 强效耐力",
                ["English"] = "Formula: Enchant Bracer - Greater Stamina",
                ["French"] = "Formule : Enchantement de bracelets (Endurance supérieure)",
                ["German"] = "Formel: Armschiene - Große Ausdauer",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 상급 체력",
                ["Mexican"] = "Fórmula: encantar brazales: aguante superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Vigor - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: выносливость IV",
                ["Spanish"] = "Fórmula: encantar brazal: aguante superior",
                ["Taiwanese"] = "公式：附魔護腕 - 強效耐力",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 55,
                    ["min_xp_level"] = 40,
                },
            },
            ["id"] = 11226,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 骑乘技能",
                ["English"] = "Formula: Enchant Gloves - Riding Skill",
                ["French"] = "Formule : Enchantement de gants (Equitation)",
                ["German"] = "Formel: Handschuhe - Reitfertigkeit",
                ["Korean"] = "주문식: 장갑 마법부여 - 숙련된 조련술",
                ["Mexican"] = "Fórmula: encantar guantes: equitación",
                ["Portuguese"] = "Fórmula: Encantamento de Perícia de Montaria - Luvas",
                ["Russian"] = "Формула чар для перчаток: верховая езда",
                ["Spanish"] = "Fórmula: encantar guantes: equitación",
                ["Taiwanese"] = "公式：附魔手套 - 騎乘技能",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    9025,
                },
            },
            ["id"] = 11813,
            ["name"] = {
                ["Chinese"] = "公式：浓烟山脉之心",
                ["English"] = "Formula: Smoking Heart of the Mountain",
                ["French"] = "Formule : Coeur fumant de la montagne",
                ["German"] = "Formel: Rauchendes Herz des Berges",
                ["Korean"] = "주문식: 연기나는 산의 정수",
                ["Mexican"] = "Fórmula: Corazón humeante de la montaña",
                ["Portuguese"] = "Fórmula: Coração Fumegante da Montanha",
                ["Russian"] = "Формула: дымящееся сердце горы",
                ["Spanish"] = "Fórmula: corazón humeante de la montaña",
                ["Taiwanese"] = "公式：濃煙山脈之心",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    2642,
                },
            },
            ["id"] = 16214,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 强效智力",
                ["English"] = "Formula: Enchant Bracer - Greater Intellect",
                ["French"] = "Formule : Enchantement de bracelets (Intelligence supérieure)",
                ["German"] = "Formel: Armschiene - Große Intelligenz",
                ["Korean"] = "주문식: 팔보호구 마법부여 - 상급 지능",
                ["Mexican"] = "Fórmula: encantar brazales: Intelecto superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Intelecto - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: интеллект III",
                ["Spanish"] = "Fórmula: encantar brazal: intelecto superior",
                ["Taiwanese"] = "公式：附魔護腕 - 強效智力",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 60,
                    ["min_xp_level"] = 45,
                },
            },
            ["id"] = 16215,
            ["name"] = {
                ["Chinese"] = "公式：附魔靴子 - 强效耐力",
                ["English"] = "Formula: Enchant Boots - Greater Stamina",
                ["French"] = "Formule : Enchantement de bottes (Endurance supérieure)",
                ["German"] = "Formel: Stiefel - Große Ausdauer",
                ["Korean"] = "주문식: 장화 마법부여 - 상급 체력",
                ["Mexican"] = "Fórmula: encantar botas: aguante superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Vigor - Botas",
                ["Russian"] = "Формула чар для обуви: выносливость IV",
                ["Spanish"] = "Fórmula: encantar botas: aguante superior",
                ["Taiwanese"] = "公式：附魔靴子 - 強效耐力",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    5259,
                },
            },
            ["id"] = 16216,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 强效抗性",
                ["English"] = "Formula: Enchant Cloak - Greater Resistance",
                ["French"] = "Formule : Enchantement de cape (Résistance supérieure)",
                ["German"] = "Formel: Umhang - Großer Widerstand",
                ["Korean"] = "주문식: 망토 마법부여 - 상급 저항",
                ["Mexican"] = "Fórmula: encantar capa: resistencia superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Resistência - Manto",
                ["Russian"] = "Формула чар для плаща: сопротивление III",
                ["Spanish"] = "Fórmula: encantar capa: resistencia superior",
                ["Taiwanese"] = "公式：附魔披風 - 強效抗性",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 16217,
            ["name"] = {
                ["Chinese"] = "公式：附魔盾牌 - 强效耐力",
                ["English"] = "Formula: Enchant Shield - Greater Stamina",
                ["French"] = "Formule : Enchantement de bouclier (Endurance supérieure)",
                ["German"] = "Formel: Schild - Große Ausdauer",
                ["Korean"] = "주문식: 방패 마법부여 - 상급 체력",
                ["Mexican"] = "Fórmula: encantar escudo: aguante superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Vigor - Escudo",
                ["Russian"] = "Формула чар для щита: выносливость IV",
                ["Spanish"] = "Fórmula: encantar escudo: aguante superior",
                ["Taiwanese"] = "公式：附魔盾牌 - 強效耐力",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 12000,
                ["sources"] = {
                    4229,
                    4561,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 60,
                    ["min_xp_level"] = 45,
                },
            },
            ["id"] = 16218,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 超强精神",
                ["English"] = "Formula: Enchant Bracer - Superior Spirit",
                ["French"] = "Formule : Enchantement de bracelets (Esprit excellent)",
                ["German"] = "Formel: Armschiene - Überragende Willenskraft",
                ["Korean"] = "주문식: 팔보호구 마법부여 - 최상급 정신력",
                ["Mexican"] = "Fórmula: encantar brazales: espíritu excelente",
                ["Portuguese"] = "Fórmula: Encantamento Superior de Espírito - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: дух V",
                ["Spanish"] = "Fórmula: encantar brazal: espíritu excelente",
                ["Taiwanese"] = "公式：附魔護腕 - 超強精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    6201,
                },
            },
            ["id"] = 16219,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 强效敏捷",
                ["English"] = "Formula: Enchant Gloves - Greater Agility",
                ["French"] = "Formule : Enchantement de gants (Agilité supérieure)",
                ["German"] = "Formel: Handschuhe - Große Beweglichkeit",
                ["Korean"] = "주문식: 장갑 마법부여 - 상급 민첩",
                ["Mexican"] = "Fórmula: encantar guantes: agilidad superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Agilidade - Luvas",
                ["Russian"] = "Формула чар для перчаток: ловкость II",
                ["Spanish"] = "Fórmula: encantar guantes: agilidad superior",
                ["Taiwanese"] = "公式：附魔手套 - 強效敏捷",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 60,
                    ["min_xp_level"] = 45,
                },
            },
            ["id"] = 16220,
            ["name"] = {
                ["Chinese"] = "公式：附魔靴子 - 精神",
                ["English"] = "Formula: Enchant Boots - Spirit",
                ["French"] = "Formule : Enchantement de bottes (Esprit)",
                ["German"] = "Formel: Stiefel - Willenskraft",
                ["Korean"] = "주문식: 장화 마법부여 - 정신력",
                ["Mexican"] = "Fórmula: encantar botas: espíritu",
                ["Portuguese"] = "Fórmula: Encantamento de Espírito - Botas",
                ["Russian"] = "Формула чар для обуви: дух II",
                ["Spanish"] = "Fórmula: encantar botas: espíritu",
                ["Taiwanese"] = "公式：附魔靴子 - 精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 16221,
            ["name"] = {
                ["Chinese"] = "公式：附魔胸甲 - 极效生命",
                ["English"] = "Formula: Enchant Chest - Major Health",
                ["French"] = "Formule : Enchantement de plastron (Santé majeure)",
                ["German"] = "Formel: Brust - Erhebliche Gesundheit",
                ["Korean"] = "주문식: 가슴보호구 마법부여 - 일급 생명력",
                ["Mexican"] = "Fórmula: encantar pechera: salud sublime",
                ["Portuguese"] = "Fórmula: Encantamento Elevado de Vida - Torso",
                ["Russian"] = "Формула чар для нагрудника: здоровье VI",
                ["Spanish"] = "Fórmula: encantar pechera: salud sublime",
                ["Taiwanese"] = "公式：附魔胸甲 - 極效生命",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 16000,
                ["sources"] = {
                    11189,
                },
            },
        },
        {
            ["drops"] = {
                ["sources"] = {
                    9447,
                },
            },
            ["id"] = 16222,
            ["name"] = {
                ["Chinese"] = "公式：附魔盾牌 - 超强精神",
                ["English"] = "Formula: Enchant Shield - Superior Spirit",
                ["French"] = "Formule : Enchantement de bouclier (Esprit excellent)",
                ["German"] = "Formel: Schild - Erhebliche Willenskraft",
                ["Korean"] = "주문식: 방패 마법부여 - 최상급 정신력",
                ["Mexican"] = "Fórmula: encantar escudo: espíritu excelente",
                ["Portuguese"] = "Fórmula: Encantamento Superior de Espírito - Escudo",
                ["Russian"] = "Формула чар для щита: дух IV",
                ["Spanish"] = "Fórmula: encantar escudo: espíritu excelente",
                ["Taiwanese"] = "公式：附魔盾牌 - 超強精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    7524,
                },
            },
            ["id"] = 16223,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 冰寒",
                ["English"] = "Formula: Enchant Weapon - Icy Chill",
                ["French"] = "Formule : Enchantement d'arme (Frisson glacial)",
                ["German"] = "Formel: Waffe - Eisiger Hauch",
                ["Korean"] = "주문식: 무기 마법부여 - 빙결",
                ["Mexican"] = "Fórmula: encantar arma: escalofrío gélido",
                ["Portuguese"] = "Fórmula: Encantamento do Arrepio Gélido - Arma",
                ["Russian"] = "Формула чар для оружия: леденящая стужа",
                ["Spanish"] = "Fórmula: encantar arma: escalofrío gélido",
                ["Taiwanese"] = "公式：附魔武器 - 冰寒",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 16224,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 超强防御",
                ["English"] = "Formula: Enchant Cloak - Superior Defense",
                ["French"] = "Formule : Enchantement de cape (Défense excellent)",
                ["German"] = "Formel: Umhang - Überragende Verteidigung",
                ["Korean"] = "주문식: 망토 마법부여 - 최상급 보호",
                ["Mexican"] = "Fórmula: encantar capa: defensa excelente",
                ["Portuguese"] = "Fórmula: Encantamento Superior de Defesa - Manto",
                ["Russian"] = "Формула чар для плаща: защита III",
                ["Spanish"] = "Fórmula: encantar capa: defensa excelente",
                ["Taiwanese"] = "公式：附魔披風 - 超強防禦",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 20000,
                ["sources"] = {
                    12022,
                },
            },
        },
        {
            ["drops"] = {
                ["sources"] = {
                    9452,
                },
            },
            ["id"] = 16242,
            ["name"] = {
                ["Chinese"] = "公式：附魔胸甲 - 极效法力",
                ["English"] = "Formula: Enchant Chest - Major Mana",
                ["French"] = "Formule : Enchantement de plastron (Mana majeur)",
                ["German"] = "Formel: Brust - Erhebliches Mana",
                ["Korean"] = "주문식: 가슴보호구 마법부여 - 일급 마나",
                ["Mexican"] = "Fórmula: encantar pechera: maná sublime",
                ["Portuguese"] = "Fórmula: Encantamento Elevado de Mana - Torso",
                ["Russian"] = "Формула чар для нагрудника: мана VI",
                ["Spanish"] = "Fórmula: encantar pechera: maná sublime",
                ["Taiwanese"] = "公式：附魔胸甲 - 極效法力",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 16243,
            ["name"] = {
                ["Chinese"] = "公式：符文奥金棒",
                ["English"] = "Formula: Runed Arcanite Rod",
                ["French"] = "Formule : Bâtonnet runique en arcanite",
                ["German"] = "Formel: Runenverzierte Arkanitrute",
                ["Korean"] = "주문식: 룬문자 아케이나이트 마법막대",
                ["Mexican"] = "Fórmula: vara rúnica de arcanita",
                ["Portuguese"] = "Fórmula: Bastão Rúnico de Arcanita",
                ["Russian"] = "Формула: рунный арканитовый жезл",
                ["Spanish"] = "Fórmula: vara arcanita con runas",
                ["Taiwanese"] = "公式：符文奧金棒",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 22000,
                ["sources"] = {
                    12022,
                },
            },
        },
        {
            ["drops"] = {
                ["sources"] = {
                    9198,
                },
            },
            ["id"] = 16244,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 强效力量",
                ["English"] = "Formula: Enchant Gloves - Greater Strength",
                ["French"] = "Formule : Enchantement de gants (Force supérieure)",
                ["German"] = "Formel: Handschuhe - Große Stärke",
                ["Korean"] = "주문식: 장갑 마법부여 - 상급 힘",
                ["Mexican"] = "Fórmula: encantar guantes: fuerza superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Força - Luvas",
                ["Russian"] = "Формула чар для перчаток: сила II",
                ["Spanish"] = "Fórmula: encantar guantes: fuerza superior",
                ["Taiwanese"] = "公式：附魔手套 - 強效力量",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 63,
                    ["min_xp_level"] = 50,
                },
            },
            ["id"] = 16245,
            ["name"] = {
                ["Chinese"] = "公式：附魔靴子 - 强效敏捷",
                ["English"] = "Formula: Enchant Boots - Greater Agility",
                ["French"] = "Formule : Enchantement de bottes (Agilité supérieure)",
                ["German"] = "Formel: Stiefel - Große Beweglichkeit",
                ["Korean"] = "주문식: 장화 마법부여 - 상급 민첩",
                ["Mexican"] = "Fórmula: encantar botas: agilidad superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Agilidade - Botas",
                ["Russian"] = "Формула чар для обуви: ловкость IV",
                ["Spanish"] = "Fórmula: encantar botas: agilidad superior",
                ["Taiwanese"] = "公式：附魔靴子 - 強效敏捷",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    7372,
                },
            },
            ["id"] = 16246,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 超强力量",
                ["English"] = "Formula: Enchant Bracer - Superior Strength",
                ["French"] = "Formule : Enchantement de bracelet (Force excellente)",
                ["German"] = "Formel: Armschiene - Überragende Stärke",
                ["Korean"] = "주문식: 팔보호구 마법부여 - 최상급 힘",
                ["Mexican"] = "Fórmula: encantar brazales: fuerza excelente",
                ["Portuguese"] = "Fórmula: Encantamento Superior de Força - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: сила V",
                ["Spanish"] = "Fórmula: encantar brazal: fuerza excelente",
                ["Taiwanese"] = "公式：附魔護腕 - 超強力量",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    10317,
                },
            },
            ["id"] = 16247,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 超强冲击",
                ["English"] = "Formula: Enchant 2H Weapon - Superior Impact",
                ["French"] = "Formule : Enchantement d'arme 2M - Impact excellent",
                ["German"] = "Formel: Zweihandwaffe - Überragender Einschlag",
                ["Korean"] = "주문식: 양손 무기 마법부여 - 최상급 충격",
                ["Mexican"] = "Fórmula: encantar arma de 2M: impacto excelente",
                ["Portuguese"] = "Fórmula: Encantamento Superior de Impacto - Arma de 2M",
                ["Russian"] = "Формула чар для двуручного оружия: импульс V",
                ["Spanish"] = "Fórmula: encantar arma de 2M: impacto excelente",
                ["Taiwanese"] = "公式：附魔武器 - 超強衝擊",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    10398,
                },
            },
            ["id"] = 16248,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 邪恶",
                ["English"] = "Formula: Enchant Weapon - Unholy",
                ["French"] = "Formule : Enchantement d'arme (Impie)",
                ["German"] = "Formel: Waffe - Unheilig",
                ["Korean"] = "주문식: 무기 마법부여 - 부정의 무기",
                ["Mexican"] = "Fórmula: encantar arma: profano",
                ["Portuguese"] = "Fórmula: Encantamento Profano - Arma",
                ["Russian"] = "Формула чар для оружия: нечестивое оружие",
                ["Spanish"] = "Fórmula: encantar arma: profano",
                ["Taiwanese"] = "公式：附魔武器 - 邪惡",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    10422,
                },
            },
            ["id"] = 16249,
            ["name"] = {
                ["Chinese"] = "公式：附魔双手武器 - 极效智力",
                ["English"] = "Formula: Enchant 2H Weapon - Major Intellect",
                ["French"] = "Formule : Enchantement d'arme 2M (Intelligence majeure)",
                ["German"] = "Formel: Zweihandwaffe - Erhebliche Intelligenz",
                ["Korean"] = "주문식: 양손 무기 마법부여 - 일급 지능",
                ["Mexican"] = "Fórmula: encantar arma de 2M: intelecto sublime",
                ["Portuguese"] = "Fórmula: Encantamento Elevado de Intelecto - Arma de 2M",
                ["Russian"] = "Формула чар для двуручного оружия: интеллект II",
                ["Spanish"] = "Fórmula: encantar arma de 2M: intelecto sublime",
                ["Taiwanese"] = "公式：附魔雙手武器 - 極效智力",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    9216,
                },
            },
            ["id"] = 16250,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 超强打击",
                ["English"] = "Formula: Enchant Weapon - Superior Striking",
                ["French"] = "Formule : Enchantement d'arme (Frappe excellente)",
                ["German"] = "Formel: Waffe - Überragendes Schlagen",
                ["Korean"] = "주문식: 무기 마법부여 - 최상급 공격력",
                ["Mexican"] = "Fórmula: encantar arma: golpes excelentes",
                ["Portuguese"] = "Fórmula: Encantamento Superior de Ataque - Arma",
                ["Russian"] = "Формула чар для оружия: удар V",
                ["Spanish"] = "Fórmula: encantar arma: golpes excelentes",
                ["Taiwanese"] = "公式：附魔武器 - 超強打擊",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 63,
                    ["min_xp_level"] = 55,
                },
            },
            ["id"] = 16251,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 超强耐力",
                ["English"] = "Formula: Enchant Bracer - Superior Stamina",
                ["French"] = "Formule : Enchantement de bracelets (Endurance excellente)",
                ["German"] = "Formel: Armschiene - Überragende Ausdauer",
                ["Korean"] = "주문식: 팔보호구 마법부여 - 최상급 체력",
                ["Mexican"] = "Fórmula: encantar brazales: aguante excelente",
                ["Portuguese"] = "Fórmula: Encantamento Superior de Vigor - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: выносливость V",
                ["Spanish"] = "Fórmula: encantar brazal: aguante excelente",
                ["Taiwanese"] = "公式：附魔護腕 - 超強耐力",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    4494,
                    9451,
                },
            },
            ["id"] = 16252,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 十字军",
                ["English"] = "Formula: Enchant Weapon - Crusader",
                ["French"] = "Formule : Enchantement d'arme (Croisé)",
                ["German"] = "Formel: Waffe - Kreuzfahrer",
                ["Korean"] = "주문식: 무기 마법부여 - 성전사",
                ["Mexican"] = "Fórmula: encantar arma: cruzado",
                ["Portuguese"] = "Fórmula: Encantamento do Cruzado - Arma",
                ["Russian"] = "Формула чар для оружия: рыцарь",
                ["Spanish"] = "Fórmula: encantar arma: cruzado",
                ["Taiwanese"] = "公式：附魔武器 - 十字軍",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 63,
                    ["min_xp_level"] = 60,
                },
            },
            ["id"] = 16253,
            ["name"] = {
                ["Chinese"] = "公式：附魔胸甲 - 强效属性",
                ["English"] = "Formula: Enchant Chest - Greater Stats",
                ["French"] = "Formule : Enchantement de plastron (Caractéristiques supérieures)",
                ["German"] = "Formel: Brust - Große Werte",
                ["Korean"] = "주문식: 가슴보호구 마법부여 - 상급 능력치",
                ["Mexican"] = "Fórmula: encantar pechera: estadísticas superiores",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Atributos - Torso",
                ["Russian"] = "Формула чар для нагрудника: все характеристики IV",
                ["Spanish"] = "Fórmula: encantar pechera: estadística superior",
                ["Taiwanese"] = "公式：附魔胸甲 - 強效屬性",
            },
            ["quality"] = "uncommon",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    10499,
                },
            },
            ["id"] = 16254,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 生命偷取",
                ["English"] = "Formula: Enchant Weapon - Lifestealing",
                ["French"] = "Formule : Enchantement d'arme (Vol de vie)",
                ["German"] = "Formel: Waffe - Lebensdiebstahl",
                ["Korean"] = "주문식: 무기 마법부여 - 생명력 흡수",
                ["Mexican"] = "Fórmula: encantar arma: robo de vida",
                ["Portuguese"] = "Fórmula: Encantamento de Roubo de Vida - Arma",
                ["Russian"] = "Формула чар для оружия: похищение жизни",
                ["Spanish"] = "Fórmula: encantar arma: robo de vida",
                ["Taiwanese"] = "公式：附魔武器 - 生命偷取",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    10469,
                },
            },
            ["id"] = 16255,
            ["name"] = {
                ["Chinese"] = "公式：附魔双手武器 - 极效精神",
                ["English"] = "Formula: Enchant 2H Weapon - Major Spirit",
                ["French"] = "Formule : Enchantement d'arme 2M (Esprit majeur)",
                ["German"] = "Formel: Zweihandwaffe - Erhebliche Willenskraft",
                ["Korean"] = "주문식: 양손 무기 마법부여 - 일급 정신력",
                ["Mexican"] = "Fórmula: encantar arma de 2M: espíritu sublime",
                ["Portuguese"] = "Fórmula: Encantamento Elevado de Espírito - Arma de 2M",
                ["Russian"] = "Формула чар для двуручного оружия: дух II",
                ["Spanish"] = "Fórmula: encantar arma de 2M: espíritu sublime",
                ["Taiwanese"] = "公式：附魔雙手武器 - 極效精神",
            },
            ["quality"] = "uncommon",
        },
        {
            ["holiday"] = 141,
            ["id"] = 17725,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 寒冬之力",
                ["English"] = "Formula: Enchant Weapon - Winter's Might",
                ["French"] = "Formule : Enchantement d'arme (Puissance de l'hiver)",
                ["German"] = "Formel: Waffe - Wintermacht",
                ["Korean"] = "주문식: 무기 마법부여 - 한겨울 추위",
                ["Mexican"] = "Fórmula: encantar arma: poderío del invierno",
                ["Portuguese"] = "Fórmula: Encantamento de Poder do Inverno - Arma",
                ["Russian"] = "Формула чар для оружия: могущество зимы",
                ["Spanish"] = "Fórmula: encantar arma: poderío del invierno",
                ["Taiwanese"] = "公式：附魔武器 - 寒冬之力",
            },
            ["quality"] = "uncommon",
            ["quests"] = {
                8769,
            },
        },
        {
            ["drops"] = {
                ["sources"] = {
                    11982,
                    11988,
                    12056,
                    12057,
                    12118,
                    12259,
                    12264,
                },
            },
            ["id"] = 18259,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 法术能量",
                ["English"] = "Formula: Enchant Weapon - Spell Power",
                ["French"] = "Formule : Enchantement d'arme (Puissance de sort)",
                ["German"] = "Formel: Waffe - Zauberkraft",
                ["Korean"] = "주문식: 무기 마법부여 - 주문 강화",
                ["Mexican"] = "Fórmula: encantar arma: poder de hechizos",
                ["Portuguese"] = "Fórmula: Encantamento de Poder Mágico - Arma",
                ["Russian"] = "Формула чар для оружия: сила заклинаний I",
                ["Spanish"] = "Fórmula: encantar arma: poder de hechizos",
                ["Taiwanese"] = "公式：附魔武器 - 法術能量",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    11982,
                    11988,
                    12056,
                    12057,
                    12118,
                    12259,
                    12264,
                },
            },
            ["id"] = 18260,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 治疗能力",
                ["English"] = "Formula: Enchant Weapon - Healing Power",
                ["French"] = "Formule : Enchantement d'arme (Pouvoir de guérison)",
                ["German"] = "Formel: Waffe - Heilkraft",
                ["Korean"] = "주문식: 무기 마법부여 - 치유 강화",
                ["Mexican"] = "Fórmula: encantar arma: poder de sanación",
                ["Portuguese"] = "Fórmula: Encantamento de Poder de Cura - Arma",
                ["Russian"] = "Формула чар для оружия: целительная сила",
                ["Spanish"] = "Fórmula: encantar arma: poder de curación",
                ["Taiwanese"] = "公式：附魔武器 - 治療能量",
            },
            ["quality"] = "rare",
        },
        {
            ["id"] = 19444,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 力量",
                ["English"] = "Formula: Enchant Weapon - Strength",
                ["French"] = "Formule : Enchantement d'arme (Force)",
                ["German"] = "Formel: Waffe - Stärke",
                ["Korean"] = "주문식: 무기 마법부여 - 힘",
                ["Mexican"] = "Fórmula: encantar arma: fuerza",
                ["Portuguese"] = "Fórmula: Encantamento de Força - Arma",
                ["Russian"] = "Формула чар для оружия: сила",
                ["Spanish"] = "Fórmula: encantar arma: fuerza",
                ["Taiwanese"] = "公式：附魔武器 - 力量",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 59,
                ["level_id"] = 5,
            },
            ["vendors"] = {
                ["price"] = 30000,
                ["sources"] = {
                    12944,
                },
            },
        },
        {
            ["id"] = 19445,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 敏捷",
                ["English"] = "Formula: Enchant Weapon - Agility",
                ["French"] = "Formule : Enchantement d'arme (Agilité)",
                ["German"] = "Formel: Waffe - Beweglichkeit",
                ["Korean"] = "주문식: 무기 마법부여 - 민첩성",
                ["Mexican"] = "Fórmula: encantar arma: agilidad",
                ["Portuguese"] = "Fórmula: Encantamento de Agilidade – Arma",
                ["Russian"] = "Формула чар для оружия: ловкость I",
                ["Spanish"] = "Fórmula: encantar arma: agilidad",
                ["Taiwanese"] = "公式：附魔武器 - 敏捷",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 576,
                ["level_id"] = 6,
            },
            ["vendors"] = {
                ["price"] = 30000,
                ["sources"] = {
                    11557,
                },
            },
        },
        {
            ["id"] = 19446,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 法力回复",
                ["English"] = "Formula: Enchant Bracer - Mana Regeneration",
                ["French"] = "Formule : Enchantement de bracelets (Régénération de mana)",
                ["German"] = "Formel: Armschiene - Manaregeneration",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 마나 재생",
                ["Mexican"] = "Fórmula: encantar brazales: regeneración de maná",
                ["Portuguese"] = "Fórmula: Encantamento de Regeneração de Mana - Braçadeiras",
                ["Russian"] = "Формула чар для наручей: восполнение маны",
                ["Spanish"] = "Fórmula: encantar brazal: regeneración de maná",
                ["Taiwanese"] = "公式：附魔護腕 - 法力回復",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 529,
                ["level_id"] = 6,
            },
            ["vendors"] = {
                ["price"] = 30000,
                ["sources"] = {
                    10856,
                    10857,
                    11536,
                },
            },
        },
        {
            ["id"] = 19447,
            ["name"] = {
                ["Chinese"] = "公式：附魔护腕 - 治疗",
                ["English"] = "Formula: Enchant Bracer - Healing",
                ["French"] = "Formule : Enchantement de bracelets (Soin)",
                ["German"] = "Formel: Armschiene - Heilung",
                ["Korean"] = "주문식: 손목보호구 마법부여 - 치유 강화",
                ["Mexican"] = "Fórmula: encantar brazal: sanación",
                ["Portuguese"] = "Fórmula: Encantamento de Cura - Braçadeiras",
                ["Russian"] = "Формула чар для браслетов: лечение",
                ["Spanish"] = "Fórmula: encantar brazal: curación",
                ["Taiwanese"] = "公式：附魔護腕 - 治療",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 529,
                ["level_id"] = 7,
            },
            ["vendors"] = {
                ["price"] = 60000,
                ["sources"] = {
                    10856,
                    10857,
                    11536,
                },
            },
        },
        {
            ["id"] = 19448,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 强效精神",
                ["English"] = "Formula: Enchant Weapon - Mighty Spirit",
                ["French"] = "Formule : Enchantement d'arme (Esprit renforcé)",
                ["German"] = "Formel: Waffe - Mächtige Willenskraft",
                ["Korean"] = "주문식: 무기 마법부여 - 강한 정신력",
                ["Mexican"] = "Fórmula: encantar arma: espíritu poderoso",
                ["Portuguese"] = "Fórmula: Encantamento Potente de Espírito - Arma",
                ["Russian"] = "Формула чар для оружия: могучий дух",
                ["Spanish"] = "Fórmula: encantar arma: espíritu poderoso",
                ["Taiwanese"] = "公式：附魔武器 - 強效精神",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 59,
                ["level_id"] = 6,
            },
            ["vendors"] = {
                ["price"] = 80000,
                ["sources"] = {
                    12944,
                },
            },
        },
        {
            ["id"] = 19449,
            ["name"] = {
                ["Chinese"] = "公式：附魔武器 - 强效智力",
                ["English"] = "Formula: Enchant Weapon - Mighty Intellect",
                ["French"] = "Formule : Enchantement d'arme (Intelligence renforcée)",
                ["German"] = "Formel: Waffe - Mächtige Intelligenz",
                ["Korean"] = "주문식: 무기 마법부여 - 뛰어난 지능",
                ["Mexican"] = "Fórmula: encantar arma: intelecto poderoso",
                ["Portuguese"] = "Fórmula: Encantamento Potente de Intelecto - Arma",
                ["Russian"] = "Формула чар для оружия: могучий интеллект",
                ["Spanish"] = "Fórmula: encantar arma: intelecto poderoso",
                ["Taiwanese"] = "公式：附魔武器 - 強效智力",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 59,
                ["level_id"] = 7,
            },
            ["vendors"] = {
                ["price"] = 100000,
                ["sources"] = {
                    12944,
                },
            },
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15275,
                    15276,
                },
            },
            ["id"] = 20726,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 威胁",
                ["English"] = "Formula: Enchant Gloves - Threat",
                ["French"] = "Formule : Enchantement de gants (Menace)",
                ["German"] = "Formel: Handschuhe - Bedrohung",
                ["Korean"] = "주문식: 장갑 마법부여 - 위협",
                ["Mexican"] = "Fórmula: encantar guantes: amenaza",
                ["Portuguese"] = "Fórmula: Encantamento de Ameaça - Luvas",
                ["Russian"] = "Формула чар для перчаток: угроза",
                ["Spanish"] = "Fórmula: encantar guantes: amenaza",
                ["Taiwanese"] = "公式：附魔手套 - 威脅",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15263,
                    15299,
                    15339,
                    15340,
                    15341,
                    15348,
                    15369,
                    15370,
                    15509,
                    15510,
                    15511,
                    15516,
                    15543,
                    15544,
                },
            },
            ["id"] = 20727,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 暗影能量",
                ["English"] = "Formula: Enchant Gloves - Shadow Power",
                ["French"] = "Formule : Enchantement de gants (Puissance de l'ombre)",
                ["German"] = "Formel: Handschuhe - Schattenmacht",
                ["Korean"] = "주문식: 장갑 마법부여 - 암흑 마법 강화",
                ["Mexican"] = "Fórmula: encantar guantes: Poder de las Sombras",
                ["Portuguese"] = "Fórmula: Encantamento de Poder Sombrio - Luvas",
                ["Russian"] = "Формула чар для перчаток: сила темной магии",
                ["Spanish"] = "Fórmula: encantar guantes: poder de las Sombras",
                ["Taiwanese"] = "公式：附魔手套 - 暗影能量",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15263,
                    15299,
                    15339,
                    15340,
                    15341,
                    15348,
                    15369,
                    15370,
                    15509,
                    15510,
                    15511,
                    15516,
                    15543,
                    15544,
                },
            },
            ["id"] = 20728,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 冰霜能量",
                ["English"] = "Formula: Enchant Gloves - Frost Power",
                ["French"] = "Formule : Enchantement de gants (Puissance du givre)",
                ["German"] = "Formel: Handschuhe - Frostmacht",
                ["Korean"] = "주문식: 장갑 마법부여 - 냉기 마법 강화",
                ["Mexican"] = "Fórmula: encantar guantes: Poder de Escarcha",
                ["Portuguese"] = "Fórmula: Encantamento de Poder Gélido - Luvas",
                ["Russian"] = "Формула чар для перчаток: сила льда",
                ["Spanish"] = "Fórmula: encantar guantes: poder de Escarcha",
                ["Taiwanese"] = "公式：附魔手套 - 冰霜能量",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15263,
                    15299,
                    15339,
                    15340,
                    15341,
                    15348,
                    15369,
                    15370,
                    15509,
                    15510,
                    15511,
                    15516,
                    15543,
                    15544,
                },
            },
            ["id"] = 20729,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 火焰能量",
                ["English"] = "Formula: Enchant Gloves - Fire Power",
                ["French"] = "Formule : Enchantement de gants (Puissance du feu)",
                ["German"] = "Formel: Handschuhe - Feuermacht",
                ["Korean"] = "주문식: 장갑 마법부여 - 화염 마법 강화",
                ["Mexican"] = "Fórmula: encantar guantes: Poder de Fuego",
                ["Portuguese"] = "Fórmula: Encantamento de Poder Ígneo - Luvas",
                ["Russian"] = "Формула чар для перчаток: сила огня",
                ["Spanish"] = "Fórmula: encantar guantes: poder de Fuego",
                ["Taiwanese"] = "公式：附魔手套 - 火焰能量",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15263,
                    15299,
                    15339,
                    15340,
                    15341,
                    15348,
                    15369,
                    15370,
                    15509,
                    15510,
                    15511,
                    15516,
                    15543,
                    15544,
                },
            },
            ["id"] = 20730,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 治疗能量",
                ["English"] = "Formula: Enchant Gloves - Healing Power",
                ["French"] = "Formule : Enchantement de gants (Pouvoir de guérison)",
                ["German"] = "Formel: Handschuhe - Heilkraft",
                ["Korean"] = "주문식: 장갑 마법부여 - 치유 마법 강화",
                ["Mexican"] = "Fórmula: encantar guantes: poder de sanación",
                ["Portuguese"] = "Fórmula: Encantamento de Poder de Cura - Luvas",
                ["Russian"] = "Формула чар для перчаток: целительная сила",
                ["Spanish"] = "Fórmula: encantar guantes: poder de curación",
                ["Taiwanese"] = "公式：附魔手套 - 治療能量",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15263,
                    15299,
                    15339,
                    15340,
                    15341,
                    15348,
                    15369,
                    15370,
                    15509,
                    15510,
                    15511,
                    15516,
                    15543,
                    15544,
                },
            },
            ["id"] = 20731,
            ["name"] = {
                ["Chinese"] = "公式：附魔手套 - 超强敏捷",
                ["English"] = "Formula: Enchant Gloves - Superior Agility",
                ["French"] = "Formule : Enchantement de gants - Agilité excellente",
                ["German"] = "Formel: Handschuhe - Überragende Beweglichkeit",
                ["Korean"] = "주문식: 장갑 마법부여 - 최상급 민첩",
                ["Mexican"] = "Fórmula: encantar guantes: agilidad excelente",
                ["Portuguese"] = "Fórmula: Encantamento Superior de Agilidade - Luvas",
                ["Russian"] = "Формула чар для перчаток: ловкость III",
                ["Spanish"] = "Fórmula: encantar guantes: agilidad excelente",
                ["Taiwanese"] = "公式：附魔手套 - 超強敏捷",
            },
            ["quality"] = "rare",
        },
        {
            ["id"] = 20732,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 强效火焰抗性",
                ["English"] = "Formula: Enchant Cloak - Greater Fire Resistance",
                ["French"] = "Formule : Enchantement de cape (Résistance au feu supérieure)",
                ["German"] = "Formel: Umhang - Großer Feuerwiderstand",
                ["Korean"] = "주문식: 망토 마법부여 - 상급 화염 저항력",
                ["Mexican"] = "Fórmula: encantar capa: Resistencia al Fuego superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Resistência ao Fogo - Manto",
                ["Russian"] = "Формула чар для плаща: сопротивление огню III",
                ["Spanish"] = "Fórmula: encantar capa: resistencia superior a Fuego",
                ["Taiwanese"] = "公式：附魔披風 - 強效火焰抗性",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 609,
                ["level_id"] = 5,
            },
            ["vendors"] = {
                ["price"] = 100000,
                ["sources"] = {
                    15419,
                },
            },
        },
        {
            ["id"] = 20733,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 强效自然抗性",
                ["English"] = "Formula: Enchant Cloak - Greater Nature Resistance",
                ["French"] = "Formule : Enchantement de cape (Résistance à la nature supérieure)",
                ["German"] = "Formel: Umhang - Großer Naturwiderstand",
                ["Korean"] = "주문식: 망토 마법부여 - 상급 자연 저항력",
                ["Mexican"] = "Fórmula: encantar capa: resistencia a la Naturaleza superior",
                ["Portuguese"] = "Fórmula: Encantamento Maior de Resistência à Natureza - Manto",
                ["Russian"] = "Формула чар для плаща: сопротивление силам природы I",
                ["Spanish"] = "Fórmula: encantar capa: resistencia superior a Naturaleza",
                ["Taiwanese"] = "公式：附魔披風 - 強效自然抗性",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 609,
                ["level_id"] = 6,
            },
            ["vendors"] = {
                ["price"] = 100000,
                ["sources"] = {
                    15419,
                },
            },
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15263,
                    15299,
                    15339,
                    15340,
                    15341,
                    15348,
                    15369,
                    15370,
                    15509,
                    15510,
                    15511,
                    15516,
                    15543,
                    15544,
                },
            },
            ["id"] = 20734,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 潜行",
                ["English"] = "Formula: Enchant Cloak - Stealth",
                ["French"] = "Formule : Enchantement de cape (Camouflage)",
                ["German"] = "Formel: Umhang - Verstohlenheit",
                ["Korean"] = "주문식: 망토 마법부여 - 은신",
                ["Mexican"] = "Fórmula: encantar capa: sigilo",
                ["Portuguese"] = "Fórmula: Encantamento de Furtividade - Manto",
                ["Russian"] = "Формула чар для плаща: незаметность",
                ["Spanish"] = "Fórmula: encantar capa: sigilo",
                ["Taiwanese"] = "公式：附魔披風 - 潛行",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15275,
                    15276,
                },
            },
            ["id"] = 20735,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 狡诈",
                ["English"] = "Formula: Enchant Cloak - Subtlety",
                ["French"] = "Formule : Enchantement de cape (Discrétion)",
                ["German"] = "Formel: Umhang - Feingefühl",
                ["Korean"] = "주문식: 망토 마법부여 - 미묘함",
                ["Mexican"] = "Fórmula: encantar capa: sutileza",
                ["Portuguese"] = "Fórmula: Encantamento de Sutileza - Manto",
                ["Russian"] = "Формула чар для плаща: скрытность",
                ["Spanish"] = "Fórmula: encantar capa: sutileza",
                ["Taiwanese"] = "公式：附魔披風 - 狡詐",
            },
            ["quality"] = "rare",
        },
        {
            ["drops"] = {
                ["sources"] = {
                    15263,
                    15299,
                    15339,
                    15340,
                    15341,
                    15348,
                    15369,
                    15370,
                    15509,
                    15510,
                    15511,
                    15516,
                    15543,
                    15544,
                },
            },
            ["id"] = 20736,
            ["name"] = {
                ["Chinese"] = "公式：附魔披风 - 躲闪",
                ["English"] = "Formula: Enchant Cloak - Dodge",
                ["French"] = "Formule : Enchantement de cape (Esquive)",
                ["German"] = "Formel: Umhang - Ausweichen",
                ["Korean"] = "주문식: 망토 마법부여 - 회피",
                ["Mexican"] = "Fórmula: encantar capa: esquivar",
                ["Portuguese"] = "Fórmula: Encantamento de Esquiva - Manto",
                ["Russian"] = "Формула чар для плаща: уклонение",
                ["Spanish"] = "Fórmula: encantar capa: esquivar",
                ["Taiwanese"] = "公式：附魔披風 - 躲閃",
            },
            ["quality"] = "rare",
        },
        {
            ["id"] = 20752,
            ["name"] = {
                ["Chinese"] = "公式：初级法力之油",
                ["English"] = "Formula: Minor Mana Oil",
                ["French"] = "Formule : Huile de mana mineure",
                ["German"] = "Formel: Schwaches Manaöl",
                ["Korean"] = "주문식: 최하급 마나 오일",
                ["Mexican"] = "Fórmula: aceite de maná menor",
                ["Portuguese"] = "Fórmula: Óleo Menor de Mana",
                ["Russian"] = "Формула: слабое масло маны",
                ["Spanish"] = "Fórmula: aceite de maná menor",
                ["Taiwanese"] = "公式：初級法力之油",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 3000,
                ["sources"] = {
                    1318,
                    3012,
                    3346,
                    4228,
                    4617,
                    5158,
                    5757,
                    5758,
                    15419,
                },
            },
        },
        {
            ["id"] = 20753,
            ["name"] = {
                ["Chinese"] = "公式：次级巫师之油",
                ["English"] = "Formula: Lesser Wizard Oil",
                ["French"] = "Formule : Huile de sorcier inférieure",
                ["German"] = "Formel: Geringes Zauberöl",
                ["Korean"] = "주문식: 하급 마술사 오일",
                ["Mexican"] = "Fórmula: aceite de zahorí inferior",
                ["Portuguese"] = "Fórmula: Óleo Inferior de Teurgo",
                ["Russian"] = "Формула: простое волшебное масло",
                ["Spanish"] = "Fórmula: aceite de zahorí inferior",
                ["Taiwanese"] = "公式：次級巫師之油",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 4000,
                ["sources"] = {
                    1318,
                    3012,
                    3346,
                    4228,
                    4617,
                    5158,
                    5757,
                    5758,
                    15419,
                },
            },
        },
        {
            ["id"] = 20754,
            ["name"] = {
                ["Chinese"] = "公式：次级法力之油",
                ["English"] = "Formula: Lesser Mana Oil",
                ["French"] = "Formule : Huile de mana inférieure",
                ["German"] = "Formel: Geringes Manaöl",
                ["Korean"] = "주문식: 하급 마나 오일",
                ["Mexican"] = "Fórmula: aceite de maná inferior",
                ["Portuguese"] = "Fórmula: Óleo Inferior de Mana",
                ["Russian"] = "Формула: простое масло маны",
                ["Spanish"] = "Fórmula: aceite de maná inferior",
                ["Taiwanese"] = "公式：次級法力之油",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 10000,
                ["sources"] = {
                    15419,
                },
            },
        },
        {
            ["id"] = 20755,
            ["name"] = {
                ["Chinese"] = "公式：巫师之油",
                ["English"] = "Formula: Wizard Oil",
                ["French"] = "Formule : Huile de sorcier",
                ["German"] = "Formel: Zauberöl",
                ["Korean"] = "주문식: 마술사 오일",
                ["Mexican"] = "Fórmula: aceite de zahorí",
                ["Portuguese"] = "Fórmula: Óleo de Teurgo",
                ["Russian"] = "Формула: волшебное масло",
                ["Spanish"] = "Fórmula: aceite de zahorí",
                ["Taiwanese"] = "公式：巫師之油",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 20000,
                ["sources"] = {
                    15419,
                },
            },
        },
        {
            ["id"] = 20756,
            ["name"] = {
                ["Chinese"] = "公式：卓越巫师之油",
                ["English"] = "Formula: Brilliant Wizard Oil",
                ["French"] = "Formule : Huile de sorcier brillante",
                ["German"] = "Formel: Hervorragendes Zauberöl",
                ["Korean"] = "주문식: 반짝이는 마술사 오일",
                ["Mexican"] = "Fórmula: aceite de zahorí luminoso",
                ["Portuguese"] = "Fórmula: Óleo Brilhante de Teurgo",
                ["Russian"] = "Формула: сверкающее волшебное масло",
                ["Spanish"] = "Fórmula: aceite de zahorí luminoso",
                ["Taiwanese"] = "公式：卓越巫師之油",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 270,
                ["level_id"] = 6,
            },
            ["vendors"] = {
                ["price"] = 40000,
                ["sources"] = {
                    14921,
                },
            },
        },
        {
            ["id"] = 20757,
            ["name"] = {
                ["Chinese"] = "公式：卓越法力之油",
                ["English"] = "Formula: Brilliant Mana Oil",
                ["French"] = "Formule : Huile de mana brillante",
                ["German"] = "Formel: Hervorragendes Manaöl",
                ["Korean"] = "주문식: 반짝이는 마나 오일",
                ["Mexican"] = "Fórmula: aceite de maná luminoso",
                ["Portuguese"] = "Fórmula: Óleo Brilhante de Mana",
                ["Russian"] = "Формула: сверкающее масло маны",
                ["Spanish"] = "Fórmula: aceite de maná luminoso",
                ["Taiwanese"] = "公式：卓越法力之油",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 270,
                ["level_id"] = 5,
            },
            ["vendors"] = {
                ["price"] = 40000,
                ["sources"] = {
                    14921,
                },
            },
        },
        {
            ["id"] = 20758,
            ["name"] = {
                ["Chinese"] = "公式：初级巫师之油",
                ["English"] = "Formula: Minor Wizard Oil",
                ["French"] = "Formule : Huile de sorcier mineure",
                ["German"] = "Formel: Schwaches Zauberöl",
                ["Korean"] = "주문식: 최하급 마술사 오일",
                ["Mexican"] = "Fórmula: aceite de zahorí menor",
                ["Portuguese"] = "Fórmula: Óleo Menor de Teurgo",
                ["Russian"] = "Формула: слабое волшебное масло",
                ["Spanish"] = "Fórmula: aceite de zahorí menor",
                ["Taiwanese"] = "公式：初級巫師之油",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 500,
                ["sources"] = {
                    1318,
                    3012,
                    3346,
                    4228,
                    4617,
                    5158,
                    5757,
                    5758,
                    15419,
                },
            },
        },
        {
            ["id"] = 22392,
            ["name"] = {
                ["Chinese"] = "公式：附魔双手武器 - 敏捷",
                ["English"] = "Formula: Enchant 2H Weapon - Agility",
                ["French"] = "Formule : Enchantd'arme 2M - Agilité",
                ["German"] = "Formel: Zweihandwaffe - Beweglichkeit",
                ["Korean"] = "주문식: 양손 무기 마법부여 - 민첩성",
                ["Mexican"] = "Fórmula: encantar arma de 2M: agilidad",
                ["Portuguese"] = "Fórmula: Encantamento de Agilidade – Arma de 2M",
                ["Russian"] = "Формула чар для двуручного оружия: ловкость",
                ["Spanish"] = "Fórmula: encantar arma de 2M: agilidad",
                ["Taiwanese"] = "公式：附魔雙手武器 - 敏捷",
            },
            ["quality"] = "common",
            ["reputation"] = {
                ["faction_id"] = 576,
                ["level_id"] = 5,
            },
            ["vendors"] = {
                ["price"] = 25000,
                ["sources"] = {
                    11557,
                },
            },
        },
    }
