TRADE_SKILLS_DATA["levels"]["Enchanting"] = {
    {
        ["id"] = 7411,
        ["max_skill"] = 75,
        ["min_skill"] = 0,
        ["min_xp_level"] = 5,
        ["name"] = {
            ["Chinese"] = "附魔 (初级)",
            ["English"] = "Enchanting (Apprentice)",
            ["French"] = "Enchantement (Apprenti)",
            ["German"] = "Verzauberkunst (Lehrling)",
            ["Korean"] = "마법부여 (초급)",
            ["Mexican"] = "Encantamiento (Aprendiz)",
            ["Portuguese"] = "Encantamento (Aprendiz)",
            ["Russian"] = "Наложение чар (Ученик)",
            ["Spanish"] = "Encantamiento (Aprendiz)",
            ["Taiwanese"] = "附魔 (學徒)",
        },
        ["phase"] = 1,
        ["rank"] = 1,
        ["trainers"] = {
            ["price"] = 10,
            ["sources"] = {
                3606,
                5695,
                11065,
                11066,
                11067,
                11068,
                11070,
                11071,
            },
        },
    },
    {
        ["id"] = 7412,
        ["max_skill"] = 150,
        ["min_skill"] = 50,
        ["min_xp_level"] = 10,
        ["name"] = {
            ["Chinese"] = "附魔 (中级)",
            ["English"] = "Enchanting (Journeyman)",
            ["French"] = "Enchantement (Compagnon)",
            ["German"] = "Verzauberkunst (Geselle)",
            ["Korean"] = "마법부여 (수습)",
            ["Mexican"] = "Encantamiento (Oficial)",
            ["Portuguese"] = "Encantamento (Profissional)",
            ["Russian"] = "Наложение чар (Подмастерье)",
            ["Spanish"] = "Encantamiento (Oficial)",
            ["Taiwanese"] = "附魔 (熟練工)",
        },
        ["phase"] = 1,
        ["rank"] = 2,
        ["trainers"] = {
            ["price"] = 500,
            ["sources"] = {
                1317,
                3011,
                3345,
                4213,
                4616,
                5157,
                7949,
            },
        },
    },
    {
        ["id"] = 7413,
        ["max_skill"] = 225,
        ["min_skill"] = 125,
        ["min_xp_level"] = 20,
        ["name"] = {
            ["Chinese"] = "附魔 (高级)",
            ["English"] = "Enchanting (Expert)",
            ["French"] = "Enchantement (Expert)",
            ["German"] = "Verzauberkunst (Experte)",
            ["Korean"] = "마법부여 (숙련)",
            ["Mexican"] = "Encantamiento (Experto)",
            ["Portuguese"] = "Encantamento (Perito)",
            ["Russian"] = "Наложение чар (Умелец)",
            ["Spanish"] = "Encantamiento (Experto)",
            ["Taiwanese"] = "附魔 (專家)",
        },
        ["phase"] = 1,
        ["rank"] = 3,
        ["trainers"] = {
            ["price"] = 5000,
            ["sources"] = {
                11072,
                11074,
            },
        },
    },
    {
        ["id"] = 13920,
        ["max_skill"] = 300,
        ["min_skill"] = 200,
        ["min_xp_level"] = 35,
        ["name"] = {
            ["Chinese"] = "附魔 (大师级)",
            ["English"] = "Enchanting (Artisan)",
            ["French"] = "Enchantement (Artisan)",
            ["German"] = "Verzauberkunst (Fachmann)",
            ["Korean"] = "마법부여 (전문)",
            ["Mexican"] = "Encantamiento (Artesano)",
            ["Portuguese"] = "Encantamento (Artifice)",
            ["Russian"] = "Наложение чар (Мастеровой)",
            ["Spanish"] = "Encantamiento (Artesano)",
            ["Taiwanese"] = "附魔 (大工匠)",
        },
        ["phase"] = 1,
        ["rank"] = 4,
        ["trainers"] = {
            ["price"] = 50000,
            ["sources"] = {
                11073,
            },
        },
    },
}
