TRADE_SKILLS_DATA["items"]["Cooking"] =
    {
        {
            ["id"] = 728,
            ["name"] = {
                ["Chinese"] = "食谱：杂味炖肉",
                ["English"] = "Recipe: Westfall Stew",
                ["French"] = "Recette : Ragoût de la marche de l'Ouest",
                ["German"] = "Rezept: Westfall-Eintopf",
                ["Korean"] = "조리법: 서부정통 스튜",
                ["Mexican"] = "Receta: estofado de los Páramos de Poniente",
                ["Portuguese"] = "Receita: Ensopado de Cerro Oeste",
                ["Russian"] = "Рецепт: похлебка Западного Края",
                ["Spanish"] = "Receta: estofado de Páramos de Poniente",
                ["Taiwanese"] = "食譜：雜味燉肉",
            },
            ["quality"] = "common",
            ["quests"] = {
                38,
            },
            ["vendors"] = {
                ["price"] = 200,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 2697,
            ["name"] = {
                ["Chinese"] = "食谱：猪肝馅饼",
                ["English"] = "Recipe: Goretusk Liver Pie",
                ["French"] = "Recette : Tourte au foie de Broche-tripes",
                ["German"] = "Rezept: Pastete aus Geiferzahnleber",
                ["Korean"] = "조리법: 뿔엄니멧돼지 간 파이",
                ["Mexican"] = "Receta: pastel de hígado de Dentosangre",
                ["Portuguese"] = "Receita: Empadão de Fígado de Goretusco",
                ["Russian"] = "Рецепт: пирожок из печени жутеклыка",
                ["Spanish"] = "Receta: tarta de hígado de Dentosangre",
                ["Taiwanese"] = "食譜：豬肝餡餅",
            },
            ["quality"] = "common",
            ["quests"] = {
                22,
            },
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 20,
                    ["min_xp_level"] = 10,
                },
            },
            ["id"] = 2698,
            ["name"] = {
                ["Chinese"] = "食谱：煮蟹爪",
                ["English"] = "Recipe: Cooked Crab Claw",
                ["French"] = "Recette : Pince de crabe farcie",
                ["German"] = "Rezept: Gekochte Krebsschere",
                ["Korean"] = "조리법: 집게발 요리",
                ["Mexican"] = "Receta: pinza de cangrejo cocida",
                ["Portuguese"] = "Receita: Pinça de Caranguejo Cozida",
                ["Russian"] = "Рецепт: вареная клешня краба",
                ["Spanish"] = "Receta: pinza de cangrejo cocida",
                ["Taiwanese"] = "食譜：煮蟹爪",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 2699,
            ["name"] = {
                ["Chinese"] = "食谱：赤脊山炖肉",
                ["English"] = "Recipe: Redridge Goulash",
                ["French"] = "Recette : Goulash des Carmines",
                ["German"] = "Rezept: Rotkammgulasch",
                ["Korean"] = "조리법: 붉은마루산 굴라시 스튜",
                ["Mexican"] = "Receta: estofado Crestagrana",
                ["Portuguese"] = "Receita: Gulache de Cristarrubra",
                ["Russian"] = "Рецепт: гуляш по-красногорски",
                ["Spanish"] = "Receta: estofado Crestagrana",
                ["Taiwanese"] = "食譜：赤脊山燉肉",
            },
            ["quality"] = "common",
            ["quests"] = {
                92,
            },
            ["vendors"] = {
                ["price"] = 800,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 25,
                    ["min_xp_level"] = 10,
                },
            },
            ["id"] = 2700,
            ["name"] = {
                ["Chinese"] = "食谱：多汁猪排",
                ["English"] = "Recipe: Succulent Pork Ribs",
                ["French"] = "Recette : Côtes de porc aux herbes",
                ["German"] = "Rezept: Saftige Schweinerippchen",
                ["Korean"] = "조리법: 육즙이 많은 돼지 갈비",
                ["Mexican"] = "Receta: costillas de cerdo suculentas",
                ["Portuguese"] = "Receita: Costelinhas Suínas Suculentas",
                ["Russian"] = "Рецепт: сочные свиные ребрышки",
                ["Spanish"] = "Receta: costillas de cerdo suculentas",
                ["Taiwanese"] = "食譜：多汁豬排",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 2701,
            ["name"] = {
                ["Chinese"] = "食谱：干烤狼肉串",
                ["English"] = "Recipe: Seasoned Wolf Kabob",
                ["French"] = "Recette : Kébab de loup assaisonné",
                ["German"] = "Rezept: Gewürzter Wolfskebab",
                ["Korean"] = "조리법: 양념 늑대 케밥",
                ["Mexican"] = "Receta: kebab de lobo sazonado",
                ["Portuguese"] = "Receita: Kebab Temperado de Lobo",
                ["Russian"] = "Рецепт: приправленная котлета из волчатины",
                ["Spanish"] = "Receta: kebab de lobo salpimentado",
                ["Taiwanese"] = "食譜：乾烤狼肉串",
            },
            ["quality"] = "common",
            ["quests"] = {
                90,
            },
            ["vendors"] = {
                ["price"] = 1600,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 2889,
            ["name"] = {
                ["Chinese"] = "食谱：啤酒烤猪排",
                ["English"] = "Recipe: Beer Basted Boar Ribs",
                ["French"] = "Recette : Côtes de sanglier à la bière",
                ["German"] = "Rezept: Eberrippchen in Biersauce",
                ["Korean"] = "조리법: 맥주로 양념한 멧돼지 갈비",
                ["Mexican"] = "Receta: costillas de jabalí a la cerveza",
                ["Portuguese"] = "Receita: Costelinhas de Javali na Cerveja",
                ["Russian"] = "Рецепт: кабаньи ребрышки в пиве",
                ["Spanish"] = "Receta: costillas de jabalí a la cerveza",
                ["Taiwanese"] = "食譜：啤酒烤豬排",
            },
            ["quality"] = "common",
            ["quests"] = {
                384,
            },
            ["vendors"] = {
                ["price"] = 240,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 3678,
            ["name"] = {
                ["Chinese"] = "食谱：鳄鱼煎排",
                ["English"] = "Recipe: Crocolisk Steak",
                ["French"] = "Recette : Steak de crocilisque",
                ["German"] = "Rezept: Krokiliskensteak",
                ["Korean"] = "조리법: 악어 스테이크",
                ["Mexican"] = "Receta: filete de crocolisco",
                ["Portuguese"] = "Receita: Bife de Crocolisco",
                ["Russian"] = "Рецепт: стейк из кроколиска",
                ["Spanish"] = "Receta: chuleta de crocolisco",
                ["Taiwanese"] = "食譜：鱷魚煎排",
            },
            ["quality"] = "common",
            ["quests"] = {
                385,
            },
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 3679,
            ["name"] = {
                ["Chinese"] = "食谱：血肠",
                ["English"] = "Recipe: Blood Sausage",
                ["French"] = "Recette : Boudin",
                ["German"] = "Rezept: Blutwurst",
                ["Korean"] = "조리법: 선지 소시지",
                ["Mexican"] = "Receta: morcilla",
                ["Portuguese"] = "Receita: Chouriço",
                ["Russian"] = "Рецепт: кровяная колбаса",
                ["Spanish"] = "Receta: morcilla",
                ["Taiwanese"] = "食譜：血腸",
            },
            ["quality"] = "common",
            ["quests"] = {
                418,
            },
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 3680,
            ["name"] = {
                ["Chinese"] = "食谱：鱼人鳍汤",
                ["English"] = "Recipe: Murloc Fin Soup",
                ["French"] = "Recette : Soupe aux ailerons de murloc",
                ["German"] = "Rezept: Murlocflossensuppe",
                ["Korean"] = "조리법: 멀록 지느러미 수프",
                ["Mexican"] = "Receta: sopa de aleta de múrloc",
                ["Portuguese"] = "Receita: Sopa de Barbatana de Murloc",
                ["Russian"] = "Рецепт: суп из плавников мурлока",
                ["Spanish"] = "Receta: sopa de aleta de múrloc",
                ["Taiwanese"] = "食譜：魚人鰭湯",
            },
            ["quality"] = "common",
            ["quests"] = {
                127,
            },
            ["vendors"] = {
                ["price"] = 1600,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 3681,
            ["name"] = {
                ["Chinese"] = "食谱：鳄鱼浓汤",
                ["English"] = "Recipe: Crocolisk Gumbo",
                ["French"] = "Recette : Gombo de crocilisque",
                ["German"] = "Rezept: Krokiliskengumbo",
                ["Korean"] = "조리법: 악어 검보 스튜",
                ["Mexican"] = "Receta: potaje de crocolisco",
                ["Portuguese"] = "Receita: Bobó de Crocolisco",
                ["Russian"] = "Рецепт: суп из кроколиска",
                ["Spanish"] = "Receta: potaje de crocolisco",
                ["Taiwanese"] = "食譜：鱷魚濃湯",
            },
            ["quality"] = "common",
            ["quests"] = {
                471,
            },
            ["vendors"] = {
                ["price"] = 1600,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 3682,
            ["name"] = {
                ["Chinese"] = "食谱：美味煎蛋卷",
                ["English"] = "Recipe: Curiously Tasty Omelet",
                ["French"] = "Recette : Omelette au goût étrange",
                ["German"] = "Rezept: Seltsam schmeckendes Omelett",
                ["Korean"] = "조리법: 진기한 맛의 오믈렛",
                ["Mexican"] = "Receta: tortilla con un sabor curioso",
                ["Portuguese"] = "Receita: Omelete Curiosamente Saboroso",
                ["Russian"] = "Рецепт: невероятно вкусный омлет",
                ["Spanish"] = "Receta: tortilla con un sabor curioso",
                ["Taiwanese"] = "食譜：美味煎蛋捲",
            },
            ["quality"] = "common",
            ["quests"] = {
                296,
            },
            ["vendors"] = {
                ["price"] = 1600,
                ["sources"] = {
                    340,
                    1148,
                    2821,
                },
            },
        },
        {
            ["id"] = 3683,
            ["name"] = {
                ["Chinese"] = "食谱：蜘蛛蛋糕",
                ["English"] = "Recipe: Gooey Spider Cake",
                ["French"] = "Recette : Tourte d'araignée fondante",
                ["German"] = "Rezept: Klebriger Spinnenkuchen",
                ["Korean"] = "조리법: 쫄깃쫄깃한 거미 케이크",
                ["Mexican"] = "Receta: pastel de araña pegajosa",
                ["Portuguese"] = "Receita: Bolo de Aranha Pegajoso",
                ["Russian"] = "Рецепт: пирожок из паучатины",
                ["Spanish"] = "Receta: pastel de araña pegajosa",
                ["Taiwanese"] = "食譜：蜘蛛蛋糕",
            },
            ["quality"] = "common",
            ["quests"] = {
                93,
            },
            ["vendors"] = {
                ["price"] = 1600,
                ["sources"] = {
                    340,
                },
            },
        },
        {
            ["id"] = 3734,
            ["name"] = {
                ["Chinese"] = "食谱：烤熊排",
                ["English"] = "Recipe: Big Bear Steak",
                ["French"] = "Recette : Steak de grand ours",
                ["German"] = "Rezept: Großes Bärensteak",
                ["Korean"] = "조리법: 큰 곰 스테이크",
                ["Mexican"] = "Receta: chuleta de oso grande",
                ["Portuguese"] = "Receita: Filé de Ursão",
                ["Russian"] = "Рецепт: стейк из мяса большого медведя",
                ["Spanish"] = "Receta: chuleta de oso grande",
                ["Taiwanese"] = "食譜：烤熊排",
            },
            ["quality"] = "common",
            ["quests"] = {
                498,
            },
            ["vendors"] = {
                ["price"] = 1600,
                ["sources"] = {
                    3960,
                    12246,
                },
            },
        },
        {
            ["id"] = 3735,
            ["name"] = {
                ["Chinese"] = "食谱：烤狮排",
                ["English"] = "Recipe: Hot Lion Chops",
                ["French"] = "Recette : Côtelettes de lion épicées",
                ["German"] = "Rezept: Scharfe Löwenkoteletts",
                ["Korean"] = "조리법: 매운 사자 고기",
                ["Mexican"] = "Receta: chuletillas de león picantes",
                ["Portuguese"] = "Receita: Costeletas Picantes de Leão",
                ["Russian"] = "Рецепт: острая отбивная из мяса льва",
                ["Spanish"] = "Receta: chuletas de león picantes",
                ["Taiwanese"] = "食譜：烤獅排",
            },
            ["quality"] = "common",
            ["quests"] = {
                501,
            },
            ["vendors"] = {
                ["price"] = 1800,
                ["sources"] = {
                    3489,
                    12245,
                },
            },
        },
        {
            ["id"] = 3736,
            ["name"] = {
                ["Chinese"] = "食谱：香烤狮肉",
                ["English"] = "Recipe: Tasty Lion Steak",
                ["French"] = "Recette : Délicieux steak de lion",
                ["German"] = "Rezept: Schmackhaftes Löwensteak",
                ["Korean"] = "조리법: 맛있는 사자 스테이크",
                ["Mexican"] = "Receta: filete de león sabroso",
                ["Portuguese"] = "Receita: Bife Saboroso de Leão",
                ["Russian"] = "Рецепт: сочный стейк из мяса льва",
                ["Spanish"] = "Receta: filete de león sabroso",
                ["Taiwanese"] = "食譜：香烤獅肉",
            },
            ["quality"] = "common",
            ["quests"] = {
                564,
            },
        },
        {
            ["id"] = 3737,
            ["name"] = {
                ["Chinese"] = "食谱：海龟汤",
                ["English"] = "Recipe: Soothing Turtle Bisque",
                ["French"] = "Recette : Bisque de tortue apaisante",
                ["German"] = "Rezept: Milde Schildkrötensuppe",
                ["Korean"] = "조리법: 독특한 거북 비스크",
                ["Mexican"] = "Receta: sopa de tortuga reconfortante",
                ["Portuguese"] = "Receita: Caldo Reconfortante de Tartaruga",
                ["Russian"] = "Рецепт: нежный черепаховый суп",
                ["Spanish"] = "Receta: sopa de tortuga reconfortante",
                ["Taiwanese"] = "食譜：海龜湯",
            },
            ["quality"] = "common",
            ["quests"] = {
                555,
                7321,
            },
        },
        {
            ["id"] = 4609,
            ["name"] = {
                ["Chinese"] = "食谱：烧烤秃鹰翅膀",
                ["English"] = "Recipe: Barbecued Buzzard Wing",
                ["French"] = "Recette : Aile de busard grillée",
                ["German"] = "Rezept: Gegrillter Bussardflügel",
                ["Korean"] = "조리법: 대머리수리 날개 구이",
                ["Mexican"] = "Receta: ala de águila ratonera a la parrilla",
                ["Portuguese"] = "Receita: Asa de Urubu Grelhada",
                ["Russian"] = "Рецепт: жареное крыло канюка",
                ["Spanish"] = "Receta: ala de águila ratonera a la parrilla",
                ["Taiwanese"] = "食譜：燒烤禿鷹翅膀",
            },
            ["quality"] = "common",
            ["quests"] = {
                703,
            },
            ["vendors"] = {
                ["price"] = 1000,
                ["sources"] = {
                    2814,
                    12246,
                },
            },
        },
        {
            ["id"] = 5482,
            ["name"] = {
                ["Chinese"] = "食谱：卡多雷蜘蛛烤肉",
                ["English"] = "Recipe: Kaldorei Spider Kabob",
                ["French"] = "Recette : Kébab d'araignée kaldorei",
                ["German"] = "Rezept: Kaldorei-Spinnenkebab",
                ["Korean"] = "조리법: 나이트 엘프 거미 케밥",
                ["Mexican"] = "Receta: kebab de araña kaldorei",
                ["Portuguese"] = "Receita: Kebab Kaldorei de Aranha",
                ["Russian"] = "Рецепт: кальдорайский шашлык из паука",
                ["Spanish"] = "Receta: kebab de araña Kaldorei",
                ["Taiwanese"] = "食譜：卡多雷蜘蛛烤肉",
            },
            ["quality"] = "common",
            ["quests"] = {
                4161,
            },
        },
        {
            ["id"] = 5483,
            ["name"] = {
                ["Chinese"] = "食谱：蝎肉大餐",
                ["English"] = "Recipe: Scorpid Surprise",
                ["French"] = "Recette : Surprise du scorpide",
                ["German"] = "Rezept: Skorpid Surprise",
                ["Korean"] = "조리법: 전갈 별미",
                ["Mexican"] = "Receta: sorpresa de escórpido",
                ["Portuguese"] = "Receita: Escondidinho de Escorpídeo",
                ["Russian"] = "Рецепт: десерт из скорпида",
                ["Spanish"] = "Receta: sorpresa de escórpido",
                ["Taiwanese"] = "食譜：蠍肉大餐",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 140,
                ["sources"] = {
                    3881,
                },
            },
        },
        {
            ["id"] = 5484,
            ["name"] = {
                ["Chinese"] = "食谱：炒科多肉",
                ["English"] = "Recipe: Roasted Kodo Meat",
                ["French"] = "Recette : Viande de kodo rôtie",
                ["German"] = "Rezept: Geröstetes Kodofleisch",
                ["Korean"] = "조리법: 코도 숯불구이",
                ["Mexican"] = "Receta: carne de kodo asada",
                ["Portuguese"] = "Receita: Carne Assada de Kodo",
                ["Russian"] = "Рецепт: жареное мясо кодо",
                ["Spanish"] = "Receta: carne de kodo asado",
                ["Taiwanese"] = "食譜：炒科多肉",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 240,
                ["sources"] = {
                    3081,
                },
            },
        },
        {
            ["id"] = 5485,
            ["name"] = {
                ["Chinese"] = "食谱：狂鱼肉片",
                ["English"] = "Recipe: Fillet of Frenzy",
                ["French"] = "Recette : Filet de furie",
                ["German"] = "Rezept: Frenzyfilet",
                ["Korean"] = "조리법: 프렌지 휠레",
                ["Mexican"] = "Receta: filete de pez furia",
                ["Portuguese"] = "Receita: Filé de Farnesim",
                ["Russian"] = "Рецепт: филе бешенки",
                ["Spanish"] = "Receta: filete de furia",
                ["Taiwanese"] = "食譜：狂魚肉片",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    4200,
                },
            },
        },
        {
            ["id"] = 5486,
            ["name"] = {
                ["Chinese"] = "食谱：炖陆行鸟",
                ["English"] = "Recipe: Strider Stew",
                ["French"] = "Recette : Brouet de trotteur",
                ["German"] = "Rezept: Schreitereintopf",
                ["Korean"] = "조리법: 타조 스튜",
                ["Mexican"] = "Receta: estofado de zancudo",
                ["Portuguese"] = "Receita: Ensopado de Moa",
                ["Russian"] = "Рецепт: похлебка из долгонога",
                ["Spanish"] = "Receta: estofado de zancudo",
                ["Taiwanese"] = "食譜：燉陸行鳥",
            },
            ["quality"] = "common",
            ["quests"] = {
                2178,
            },
            ["vendors"] = {
                ["price"] = 440,
                ["sources"] = {
                    3482,
                },
            },
        },
        {
            ["id"] = 5487,
            ["name"] = {
                ["Chinese"] = "食谱：掘地鼠炖肉",
                ["English"] = "Recipe: Dig Rat Stew",
                ["French"] = "Recette : Brouet de rat",
                ["German"] = "Rezept: Grubenratteneintopf",
                ["Korean"] = "조리법: 들쥐 스튜",
                ["Mexican"] = "Receta: estofado de ratas de madriguera",
                ["Portuguese"] = "Receita: Ensopado de Ratoupeira",
                ["Russian"] = "Рецепт: похлебка из пещерной крысы",
                ["Spanish"] = "Receta: estofado de ratas de excavación",
                ["Taiwanese"] = "食譜：掘地鼠燉肉",
            },
            ["quality"] = "common",
            ["quests"] = {
                862,
            },
        },
        {
            ["id"] = 5488,
            ["name"] = {
                ["Chinese"] = "食谱：脆炸蜥蜴尾",
                ["English"] = "Recipe: Crispy Lizard Tail",
                ["French"] = "Recette : Queue de lézard croquante",
                ["German"] = "Rezept: Knuspriger Donnerechsenschwanz",
                ["Korean"] = "조리법: 바삭바삭한 도마뱀 꼬리",
                ["Mexican"] = "Receta: cola de lagarto crujiente",
                ["Portuguese"] = "Receita: Rabo de Lagarto Crocante",
                ["Russian"] = "Рецепт: хрустящий хвост ящерицы",
                ["Spanish"] = "Receta: cola de lagarto crujiente",
                ["Taiwanese"] = "食譜：脆炸蜥蜴尾",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    3482,
                },
            },
        },
        {
            ["id"] = 5489,
            ["name"] = {
                ["Chinese"] = "食谱：瘦鹿肉",
                ["English"] = "Recipe: Lean Venison",
                ["French"] = "Recette : Venaison dégraissée",
                ["German"] = "Rezept: Mageres Wildbret",
                ["Korean"] = "조리법: 사슴 살코기 구이",
                ["Mexican"] = "Receta: venado magro",
                ["Portuguese"] = "Receita: Carne Magra de Caça",
                ["Russian"] = "Рецепт: постная оленина",
                ["Spanish"] = "Receta: venado magro",
                ["Taiwanese"] = "食譜：瘦鹿肉",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 1200,
                ["sources"] = {
                    3960,
                    12245,
                },
            },
        },
        {
            ["id"] = 5528,
            ["name"] = {
                ["Chinese"] = "食谱：杂烩蚌肉",
                ["English"] = "Recipe: Clam Chowder",
                ["French"] = "Recette : Soupe de palourdes",
                ["German"] = "Rezept: Muschelsuppe",
                ["Korean"] = "조리법: 조개 수프",
                ["Mexican"] = "Receta: sopa de almejas",
                ["Portuguese"] = "Receita: Ensopado de Marisco",
                ["Russian"] = "Рецепт: похлебка из моллюсков",
                ["Spanish"] = "Receta: sopa de almejas",
                ["Taiwanese"] = "食譜：雜燴蚌肉",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 800,
                ["sources"] = {
                    4305,
                    4307,
                },
            },
        },
        {
            ["id"] = 6039,
            ["name"] = {
                ["Chinese"] = "食谱：烤巨蚌",
                ["English"] = "Recipe: Giant Clam Scorcho",
                ["French"] = "Recette : Ardeur de palourde géante",
                ["German"] = "Rezept: Riesenmuschelrisotto",
                ["Korean"] = "조리법: 대합 구이",
                ["Mexican"] = "Receta: almeja gigante a la brasa",
                ["Portuguese"] = "Receita: Torresmo de Marisco Gigante",
                ["Russian"] = "Рецепт: гигантский жареный моллюск",
                ["Spanish"] = "Receta: almeja gigante chamuscada",
                ["Taiwanese"] = "食譜：烤巨蚌",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 5000,
                ["sources"] = {
                    2664,
                },
            },
        },
        {
            ["id"] = 6325,
            ["name"] = {
                ["Chinese"] = "食谱：美味小鱼",
                ["English"] = "Recipe: Brilliant Smallfish",
                ["French"] = "Recette : Goujon brillant",
                ["German"] = "Rezept: Glänzender Kleinfisch",
                ["Korean"] = "조리법: 비단잉어 구이",
                ["Mexican"] = "Receta: pececito luminoso",
                ["Portuguese"] = "Receita: Peixinho Brilhante",
                ["Russian"] = "Рецепт: блестящая рыбка",
                ["Spanish"] = "Receta: pececito luminoso",
                ["Taiwanese"] = "食譜：美味小魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 40,
                ["sources"] = {
                    66,
                    1684,
                    3029,
                    3550,
                    4265,
                    4574,
                    5494,
                    5940,
                    8508,
                },
            },
        },
        {
            ["id"] = 6326,
            ["name"] = {
                ["Chinese"] = "食谱：滑皮鲭鱼",
                ["English"] = "Recipe: Slitherskin Mackerel",
                ["French"] = "Recette : Maquereau ombré",
                ["German"] = "Rezept: Glitschhautmakrele",
                ["Korean"] = "조리법: 줄무늬고등어 구이",
                ["Mexican"] = "Receta: caballa de piel escurridiza",
                ["Portuguese"] = "Receita: Cavala Deslizapele",
                ["Russian"] = "Рецепт: скользкая скумбрия",
                ["Spanish"] = "Receta: caballa suave",
                ["Taiwanese"] = "食譜：滑皮鯖魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 40,
                ["sources"] = {
                    3550,
                    4305,
                    5162,
                    5942,
                    10118,
                },
            },
        },
        {
            ["id"] = 6328,
            ["name"] = {
                ["Chinese"] = "食谱：长嘴泥鳅",
                ["English"] = "Recipe: Longjaw Mud Snapper",
                ["French"] = "Recette : Lutjan à longue mâchoire",
                ["German"] = "Rezept: Langzahniger Matschschnapper",
                ["Korean"] = "조리법: 긴주둥이진흙퉁돔 구이",
                ["Mexican"] = "Receta: pargo de lodo boquilargo",
                ["Portuguese"] = "Receita: Pargo-da-lama Bocalonga",
                ["Russian"] = "Рецепт: илистый луциан",
                ["Spanish"] = "Receta: pargo de lodo boquilargo",
                ["Taiwanese"] = "食譜：長嘴泥鰍",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    66,
                    1684,
                    3027,
                    4265,
                    4574,
                    5162,
                    5748,
                    5940,
                },
            },
        },
        {
            ["id"] = 6329,
            ["name"] = {
                ["Chinese"] = "食谱：洛克湖狂鱼",
                ["English"] = "Recipe: Loch Frenzy Delight",
                ["French"] = "Recette : Délice de furie du loch",
                ["German"] = "Rezept: Lochfrenzy Supreme",
                ["Korean"] = "조리법: 호수프렌지 별미",
                ["Mexican"] = "Receta: delicia de furia de Loch Modan",
                ["Portuguese"] = "Receita: Delícia de Farnesim Lacustre",
                ["Russian"] = "Рецепт: деликатес из бешенки",
                ["Spanish"] = "Receta: delicia de furia de Loch Modan",
                ["Taiwanese"] = "食譜：洛克湖狂魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    1684,
                },
            },
        },
        {
            ["id"] = 6330,
            ["name"] = {
                ["Chinese"] = "食谱：刺须鲶鱼",
                ["English"] = "Recipe: Bristle Whisker Catfish",
                ["French"] = "Recette : Poisson-chat moustachu",
                ["German"] = "Rezept: Stoppelfühlerwels",
                ["Korean"] = "조리법: 표범메기 구이",
                ["Mexican"] = "Receta: siluro mostacherizo",
                ["Portuguese"] = "Receita: Bagre de Bigode Cerdoso",
                ["Russian"] = "Рецепт: зубатка ощетиненная",
                ["Spanish"] = "Receta: siluro mostacherizo",
                ["Taiwanese"] = "食譜：刺鬚鯰魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 1200,
                ["sources"] = {
                    2383,
                    2397,
                    3027,
                    3029,
                    3497,
                    4553,
                    5494,
                },
            },
        },
        {
            ["id"] = 6368,
            ["name"] = {
                ["Chinese"] = "食谱：彩鳍鱼",
                ["English"] = "Recipe: Rainbow Fin Albacore",
                ["French"] = "Recette : Thon arc-en-ciel",
                ["German"] = "Rezept: Regenbogenflossenthunfisch",
                ["Korean"] = "조리법: 무지개날개다랑어 구이",
                ["Mexican"] = "Receta: atún blanco arco iris",
                ["Portuguese"] = "Receita: Albacora Arco-íris",
                ["Russian"] = "Рецепт: радужный тунец",
                ["Spanish"] = "Receta: atún blanco arco iris",
                ["Taiwanese"] = "食譜：彩鰭魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 400,
                ["sources"] = {
                    3178,
                    3333,
                    3497,
                    4305,
                    4307,
                    4553,
                    5494,
                    5748,
                    5942,
                    10118,
                },
            },
        },
        {
            ["id"] = 6369,
            ["name"] = {
                ["Chinese"] = "食谱：石鳞鳕鱼",
                ["English"] = "Recipe: Rockscale Cod",
                ["French"] = "Recette : Morue rochécaille",
                ["German"] = "Rezept: Steinschuppenkabeljau",
                ["Korean"] = "조리법: 돌비늘대구 구이",
                ["Mexican"] = "Receta: bacalao piedrescama",
                ["Portuguese"] = "Receita: Bacalhau Escama-de-pedra",
                ["Russian"] = "Рецепт: каменношкурая треска",
                ["Spanish"] = "Receta: bacalao Piedrescama",
                ["Taiwanese"] = "食譜：石鱗鱈魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 2200,
                ["sources"] = {
                    2383,
                    2664,
                    3178,
                    3333,
                    4307,
                    4574,
                    5162,
                    12033,
                    12962,
                },
            },
        },
        {
            ["drops"] = {
                ["range"] = {
                    ["max_xp_level"] = 25,
                    ["min_xp_level"] = 10,
                },
            },
            ["id"] = 6661,
            ["name"] = {
                ["Chinese"] = "食谱：美味风蛇",
                ["English"] = "Recipe: Savory Deviate Delight",
                ["French"] = "Recette : Délice de déviant",
                ["German"] = "Rezept: Pikantes Deviat-Supreme",
                ["Korean"] = "조리법: 돌연변이 물고기 별미",
                ["Mexican"] = "Receta: delicia de pez descarriado sabrosa",
                ["Portuguese"] = "Receita: Delícia de Peixe Anormal",
                ["Russian"] = "Рецепт: загадочное острое лакомство",
                ["Spanish"] = "Receta: delicia desviada sabrosa",
                ["Taiwanese"] = "食譜：美味風蛇",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 6892,
            ["name"] = {
                ["Chinese"] = "食谱：熏熊肉",
                ["English"] = "Recipe: Smoked Bear Meat",
                ["French"] = "Recette : Viande d'ours fumée",
                ["German"] = "Rezept: Geräuchertes Bärenfleisch",
                ["Korean"] = "조리법: 곰고기 숯불구이",
                ["Mexican"] = "Receta: carne de oso ahumada",
                ["Portuguese"] = "Receita: Carne de Urso Defumada",
                ["Russian"] = "Рецепт: копченая медвежатина",
                ["Spanish"] = "Receta: carne de oso ahumado",
                ["Taiwanese"] = "食譜：燻熊肉",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 248,
                ["sources"] = {
                    1465,
                    3556,
                },
            },
        },
        {
            ["id"] = 12226,
            ["name"] = {
                ["Chinese"] = "食谱：香脆蝙蝠翅",
                ["English"] = "Recipe: Crispy Bat Wing",
                ["French"] = "Recette : Aile de chauve-souris croustillante",
                ["German"] = "Rezept: Knuspriger Fledermausflügel",
                ["Korean"] = "조리법: 바삭바삭한 박쥐 날개",
                ["Mexican"] = "Receta: ala de murciélago crujiente",
                ["Portuguese"] = "Receita: Asa de Morcego Crocante",
                ["Russian"] = "Рецепт: хрустящее крылышко летучей мыши",
                ["Spanish"] = "Receta: ala de murciélago crujiente",
                ["Taiwanese"] = "食譜：香脆蝙蝠翅",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 24,
                ["sources"] = {
                    2118,
                },
            },
        },
        {
            ["id"] = 12227,
            ["name"] = {
                ["Chinese"] = "食谱：瘦狼排",
                ["English"] = "Recipe: Lean Wolf Steak",
                ["French"] = "Recette : Steak de loup",
                ["German"] = "Rezept: Mageres Wolfsteak",
                ["Korean"] = "조리법: 늑대 살코기 스테이크",
                ["Mexican"] = "Receta: filete de lobo magro",
                ["Portuguese"] = "Receita: Filé de Lobo Magro",
                ["Russian"] = "Рецепт: постный стейк из волчатины",
                ["Spanish"] = "Receta: chuleta de lobo magro",
                ["Taiwanese"] = "食譜：瘦狼排",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 1600,
                ["sources"] = {
                    12246,
                },
            },
        },
        {
            ["id"] = 12228,
            ["name"] = {
                ["Chinese"] = "食谱：烤迅猛龙肉",
                ["English"] = "Recipe: Roast Raptor",
                ["French"] = "Recette : Rôti de raptor",
                ["German"] = "Rezept: Gerösteter Raptor",
                ["Korean"] = "조리법: 랩터 숯불구이",
                ["Mexican"] = "Receta: raptor asado",
                ["Portuguese"] = "Receita: Raptor Assado",
                ["Russian"] = "Рецепт: жареный ящер",
                ["Spanish"] = "Receta: raptor asado",
                ["Taiwanese"] = "食譜：烤迅猛龍肉",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 5000,
                ["sources"] = {
                    734,
                    1148,
                    2810,
                    2821,
                    4879,
                    4897,
                    12245,
                },
            },
        },
        {
            ["id"] = 12229,
            ["name"] = {
                ["Chinese"] = "食谱：热狼排",
                ["English"] = "Recipe: Hot Wolf Ribs",
                ["French"] = "Recette : Côtes de loup épicées",
                ["German"] = "Rezept: Scharfe Wolfrippchen",
                ["Korean"] = "조리법: 늑대 양념 갈비",
                ["Mexican"] = "Receta: costillas de lobo picantes",
                ["Portuguese"] = "Receita: Costelinhas Picantes de Lobo",
                ["Russian"] = "Рецепт: острая волчья грудинка",
                ["Spanish"] = "Receta: costillas de lobo picantes",
                ["Taiwanese"] = "食譜：熱狼排",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 5000,
                ["sources"] = {
                    7947,
                    8145,
                    12246,
                },
            },
        },
        {
            ["id"] = 12231,
            ["name"] = {
                ["Chinese"] = "食谱：丛林大杂烩",
                ["English"] = "Recipe: Jungle Stew",
                ["French"] = "Recette : Ragoût de la jungle",
                ["German"] = "Rezept: Dschungeleintopf",
                ["Korean"] = "조리법: 밀림 스튜",
                ["Mexican"] = "Receta: estofado de la selva",
                ["Portuguese"] = "Receita: Ensopado da Selva",
                ["Russian"] = "Рецепт: похлебка \"Джунгли\"",
                ["Spanish"] = "Receta: estofado de la selva",
                ["Taiwanese"] = "食譜：叢林大雜燴",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 3000,
                ["sources"] = {
                    734,
                    1148,
                    12245,
                },
            },
        },
        {
            ["id"] = 12232,
            ["name"] = {
                ["Chinese"] = "食谱：腐肉大餐",
                ["English"] = "Recipe: Carrion Surprise",
                ["French"] = "Recette : Tourte surprise",
                ["German"] = "Rezept: Aas Surprise",
                ["Korean"] = "조리법: 고기말이 별미",
                ["Mexican"] = "Receta: sorpresa de carroña",
                ["Portuguese"] = "Receita: Escondidinho de Carniceiro",
                ["Russian"] = "Рецепт: десерт из мертвечины",
                ["Spanish"] = "Receta: sorpresa de carroñero",
                ["Taiwanese"] = "食譜：腐肉大餐",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 5000,
                ["sources"] = {
                    989,
                    4879,
                    9636,
                    12245,
                },
            },
        },
        {
            ["id"] = 12233,
            ["name"] = {
                ["Chinese"] = "食谱：神秘杂烩",
                ["English"] = "Recipe: Mystery Stew",
                ["French"] = "Recette : Ragoût mystère",
                ["German"] = "Rezept: Eigenartiger Eintopf",
                ["Korean"] = "조리법: 신비의 스튜",
                ["Mexican"] = "Receta: estofado misterioso",
                ["Portuguese"] = "Receita: Ensopado Misterioso",
                ["Russian"] = "Рецепт: загадочная похлебка",
                ["Spanish"] = "Receta: estofado misterioso",
                ["Taiwanese"] = "食譜：神秘雜燴",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 3000,
                ["sources"] = {
                    4897,
                    8150,
                    12246,
                },
            },
        },
        {
            ["id"] = 12239,
            ["name"] = {
                ["Chinese"] = "食谱：龙息红椒",
                ["English"] = "Recipe: Dragonbreath Chili",
                ["French"] = "Recette : Chili de souffle de dragon",
                ["German"] = "Rezept: Drachenodemchili",
                ["Korean"] = "조리법: 용숨결 칠리",
                ["Mexican"] = "Receta: ají aliento de dragón",
                ["Portuguese"] = "Receita: Chili Bafo de Dragão",
                ["Russian"] = "Рецепт: мясо в соусе \"Дыхание дракона\"",
                ["Spanish"] = "Receta: ají aliento de dragón",
                ["Taiwanese"] = "食譜：龍息紅椒",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 7000,
                ["sources"] = {
                    4879,
                    4897,
                    12246,
                },
            },
        },
        {
            ["id"] = 12240,
            ["name"] = {
                ["Chinese"] = "食谱：科多肉杂烩",
                ["English"] = "Recipe: Heavy Kodo Stew",
                ["French"] = "Recette : Ragoût épais de kodo",
                ["German"] = "Rezept: Schwerer Kodoeintopf",
                ["Korean"] = "조리법: 코도 고기 스튜",
                ["Mexican"] = "Receta: estofado de kodo pesado",
                ["Portuguese"] = "Receita: Ensopado Grosso de Kodo",
                ["Russian"] = "Рецепт: сытная похлебка из кодо",
                ["Spanish"] = "Receta: estofado de kodo pesado",
                ["Taiwanese"] = "食譜：科多肉雜燴",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 7000,
                ["sources"] = {
                    8150,
                    9636,
                    12245,
                },
            },
        },
        {
            ["id"] = 13939,
            ["name"] = {
                ["Chinese"] = "食谱：斑点黄尾鱼",
                ["English"] = "Recipe: Spotted Yellowtail",
                ["French"] = "Recette : Jaune-queue tacheté",
                ["German"] = "Rezept: Tüpfelgelbschwanz",
                ["Korean"] = "조리법: 점박이놀래기 구이",
                ["Mexican"] = "Receta: serviola moteada",
                ["Portuguese"] = "Receita: Rabo-amarelo Mosqueado",
                ["Russian"] = "Рецепт: пятнистый желтохвост",
                ["Spanish"] = "Receta: serviola moteada",
                ["Taiwanese"] = "食譜：斑點黃尾魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 16000,
                ["sources"] = {
                    8137,
                },
            },
        },
        {
            ["id"] = 13940,
            ["name"] = {
                ["Chinese"] = "食谱：煮熟的光滑大鱼",
                ["English"] = "Recipe: Cooked Glossy Mightfish",
                ["French"] = "Recette : Barracuda luisant cuit",
                ["German"] = "Rezept: Gekochter glänzender Machtfisch",
                ["Korean"] = "조리법: 빛깔좋은 망둥어 요리",
                ["Mexican"] = "Receta: vigorpez lustroso cocido",
                ["Portuguese"] = "Receita: Parrudo Lustroso Cozido",
                ["Russian"] = "Рецепт: мощь-рыба в кляре",
                ["Spanish"] = "Receta: vigorpez lustroso cocido",
                ["Taiwanese"] = "食譜：煮熟的光滑大魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 16000,
                ["sources"] = {
                    2664,
                },
            },
        },
        {
            ["id"] = 13941,
            ["name"] = {
                ["Chinese"] = "食谱：油炸红腮鱼",
                ["English"] = "Recipe: Filet of Redgill",
                ["French"] = "Recette : Filet de rouget",
                ["German"] = "Rezept: Rotkiemenfilet",
                ["Korean"] = "조리법: 붉은퉁돔 통구이",
                ["Mexican"] = "Receta: filete de branquirrojo",
                ["Portuguese"] = "Receita: Filé de Vermelhão",
                ["Russian"] = "Рецепт: филе красноперки",
                ["Spanish"] = "Receta: filete de branquirrojo",
                ["Taiwanese"] = "食譜：油炸紅腮魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 16000,
                ["sources"] = {
                    2664,
                },
            },
        },
        {
            ["id"] = 13942,
            ["name"] = {
                ["Chinese"] = "食谱：烤鱿鱼",
                ["English"] = "Recipe: Grilled Squid",
                ["French"] = "Recette : Calmar grillé",
                ["German"] = "Rezept: Gegrillter Kalmar",
                ["Korean"] = "조리법: 오징어 구이",
                ["Mexican"] = "Receta: calamar a la parrilla",
                ["Portuguese"] = "Receita: Lula Grelhada",
                ["Russian"] = "Рецепт: жареный кальмар",
                ["Spanish"] = "Receta: calamar a la parrilla",
                ["Taiwanese"] = "食譜：烤魷魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 16000,
                ["sources"] = {
                    8137,
                },
            },
        },
        {
            ["id"] = 13943,
            ["name"] = {
                ["Chinese"] = "食谱：烟熏鲈鱼",
                ["English"] = "Recipe: Hot Smoked Bass",
                ["French"] = "Recette : Perche fumée",
                ["German"] = "Rezept: Scharfer geräucherter Barsch",
                ["Korean"] = "조리법: 농어 훈제",
                ["Mexican"] = "Receta: lubina ahumada picante",
                ["Portuguese"] = "Receita: Robalo Defumado Picante",
                ["Russian"] = "Рецепт: острый копченый окунь",
                ["Spanish"] = "Receta: lubina ahumada caliente",
                ["Taiwanese"] = "食譜：煙燻鱸魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 16000,
                ["sources"] = {
                    2664,
                },
            },
        },
        {
            ["id"] = 13945,
            ["name"] = {
                ["Chinese"] = "食谱：夜鳞鱼汤",
                ["English"] = "Recipe: Nightfin Soup",
                ["French"] = "Recette : Soupe de lutjan nagenuit",
                ["German"] = "Rezept: Nachtflossensuppe",
                ["Korean"] = "조리법: 밤비늘퉁돔 수프",
                ["Mexican"] = "Receta: sopa de pargo nocturno",
                ["Portuguese"] = "Receita: Sopa de Pinoturno",
                ["Russian"] = "Рецепт: суп из ночницы",
                ["Spanish"] = "Receta: sopa de aleta nocturna",
                ["Taiwanese"] = "食譜：夜鱗魚湯",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 20000,
                ["sources"] = {
                    8137,
                },
            },
        },
        {
            ["id"] = 13946,
            ["name"] = {
                ["Chinese"] = "食谱：水煮阳鳞鲑鱼",
                ["English"] = "Recipe: Poached Sunscale Salmon",
                ["French"] = "Recette : Saumon solécaille poché",
                ["German"] = "Rezept: Gedünsteter Sonnenschuppenlachs",
                ["Korean"] = "조리법: 삶은 해비늘연어",
                ["Mexican"] = "Receta: salmón escama de sol pochado",
                ["Portuguese"] = "Receita: Salmão Helióscamo Poché",
                ["Russian"] = "Рецепт: вареный радужный лосось",
                ["Spanish"] = "Receta: salmón escama de sol pochado",
                ["Taiwanese"] = "食譜：水煮陽鱗鮭魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 20000,
                ["sources"] = {
                    8137,
                },
            },
        },
        {
            ["id"] = 13947,
            ["name"] = {
                ["Chinese"] = "食谱：炖龙虾",
                ["English"] = "Recipe: Lobster Stew",
                ["French"] = "Recette : Ragoût de homard",
                ["German"] = "Rezept: Hummereintopf",
                ["Korean"] = "조리법: 랍스터 스튜",
                ["Mexican"] = "Receta: estofado de langosta",
                ["Portuguese"] = "Receita: Ensopado de Lagosta",
                ["Russian"] = "Рецепт: похлебка из омаров",
                ["Spanish"] = "Receta: estofado de langosta",
                ["Taiwanese"] = "食譜：燉龍蝦",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 20000,
                ["sources"] = {
                    7947,
                    8145,
                },
            },
        },
        {
            ["id"] = 13948,
            ["name"] = {
                ["Chinese"] = "食谱：大鱼片",
                ["English"] = "Recipe: Mightfish Steak",
                ["French"] = "Recette : Steak de barracuda",
                ["German"] = "Rezept: Machtfischsteak",
                ["Korean"] = "조리법: 망둥어 스테이크",
                ["Mexican"] = "Receta: filete de vigorpez",
                ["Portuguese"] = "Receita: Filé de Parrudo",
                ["Russian"] = "Рецепт: стейк из мощь-рыбы",
                ["Spanish"] = "Receta: filete de vigorpez",
                ["Taiwanese"] = "食譜：大魚片",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 20000,
                ["sources"] = {
                    7947,
                    8145,
                },
            },
        },
        {
            ["id"] = 13949,
            ["name"] = {
                ["Chinese"] = "食谱：烤鲑鱼",
                ["English"] = "Recipe: Baked Salmon",
                ["French"] = "Recette : Pain de saumon",
                ["German"] = "Rezept: Gebackener Lachs",
                ["Korean"] = "조리법: 훈제 연어",
                ["Mexican"] = "Receta: salmón al horno",
                ["Portuguese"] = "Receita: Salmão Assado",
                ["Russian"] = "Рецепт: запеченный лосось",
                ["Spanish"] = "Receta: salmón al horno",
                ["Taiwanese"] = "食譜：烤鮭魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 20000,
                ["sources"] = {
                    7947,
                    8145,
                },
            },
        },
        {
            ["id"] = 16072,
            ["name"] = {
                ["Chinese"] = "中级烹饪教材",
                ["English"] = "Expert Cookbook",
                ["French"] = "Livre de cuisine pour expert",
                ["German"] = "Expertenkochbuch",
                ["Korean"] = "고급 요리책",
                ["Mexican"] = "Libro de cocina para expertos",
                ["Portuguese"] = "Livro de Receitas de Perito",
                ["Russian"] = "Поваренная книга умельца",
                ["Spanish"] = "Libro de cocina para expertos",
                ["Taiwanese"] = "高級烹飪教材",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 10000,
                ["sources"] = {
                    3955,
                    12033,
                },
            },
        },
        {
            ["id"] = 16110,
            ["name"] = {
                ["Chinese"] = "食谱：超级煎蛋卷",
                ["English"] = "Recipe: Monster Omelet",
                ["French"] = "Recette : Omelette monstrueuse",
                ["German"] = "Rezept: Monsteromelett",
                ["Korean"] = "조리법: 괴물 오믈렛",
                ["Mexican"] = "Receta: tortilla gigante",
                ["Portuguese"] = "Receita: Omelete Monstro",
                ["Russian"] = "Рецепт: чудовищный омлет",
                ["Spanish"] = "Receta: tortilla de monstruo",
                ["Taiwanese"] = "食譜：超級煎蛋捲",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 12000,
                ["sources"] = {
                    2803,
                    2806,
                    11187,
                },
            },
        },
        {
            ["id"] = 16111,
            ["name"] = {
                ["Chinese"] = "食谱：辣椒蟹肉",
                ["English"] = "Recipe: Spiced Chili Crab",
                ["French"] = "Recette : Chili de crabe épicé",
                ["German"] = "Rezept: Gewürzter Chilikrebs",
                ["Korean"] = "조리법: 매콤한 칠리 크랩",
                ["Mexican"] = "Receta: chili de cangrejo especiado",
                ["Portuguese"] = "Receita: Chili Temperado de Caranguejo",
                ["Russian"] = "Рецепт: острое крабовое чили",
                ["Spanish"] = "Receta: chili de cangrejo especiado",
                ["Taiwanese"] = "食譜：辣椒蟹肉",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 12000,
                ["sources"] = {
                    989,
                    1149,
                    4305,
                },
            },
        },
        {
            ["id"] = 16767,
            ["name"] = {
                ["Chinese"] = "食谱：安德麦蚌肉杂烩",
                ["English"] = "Recipe: Undermine Clam Chowder",
                ["French"] = "Recette : Soupe de palourdes d'Undermine",
                ["German"] = "Rezept: Undermine-Muschelsuppe",
                ["Korean"] = "조리법: 지하광산 조개 수프",
                ["Mexican"] = "Receta: sopa de almejas de Minahonda",
                ["Portuguese"] = "Receita: Ensopado de Marisco Inframina",
                ["Russian"] = "Рецепт: шахтерская похлебка из моллюсков",
                ["Spanish"] = "Receta: sopa de almejas de Villabajo",
                ["Taiwanese"] = "食譜：安德麥蚌肉雜燴",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 3000,
                ["sources"] = {
                    8139,
                },
            },
        },
        {
            ["id"] = 17062,
            ["name"] = {
                ["Chinese"] = "食谱：银头鲑鱼",
                ["English"] = "Recipe: Mithril Head Trout",
                ["French"] = "Recette : Truite tête-mithril",
                ["German"] = "Rezept: Mithrilkopfforelle",
                ["Korean"] = "조리법: 미스릴송어 구이",
                ["Mexican"] = "Receta: trucha cabeza de mitril",
                ["Portuguese"] = "Receita: Truta Cabeça-de-mithril",
                ["Russian"] = "Рецепт: мифрилоголовая форель",
                ["Spanish"] = "Receta: trucha de cabeza de mitril",
                ["Taiwanese"] = "食譜：銀頭鮭魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 2200,
                ["sources"] = {
                    2383,
                    2664,
                    3178,
                    3333,
                    4307,
                    4574,
                    5162,
                    12033,
                    12962,
                },
            },
        },
        {
            ["holiday"] = 141,
            ["id"] = 17200,
            ["name"] = {
                ["Chinese"] = "食谱：小姜饼",
                ["English"] = "Recipe: Gingerbread Cookie",
                ["French"] = "Recette : Biscuit de pain d'épice",
                ["German"] = "Rezept: Lebkuchen",
                ["Korean"] = "조리법: 생강 과자빵",
                ["Mexican"] = "Receta: galleta de jengibre",
                ["Portuguese"] = "Receita: Biscoito de Gengibre",
                ["Russian"] = "Рецепт: имбирное печенье",
                ["Spanish"] = "Receta: galleta de jengibre",
                ["Taiwanese"] = "食譜：小薑餅",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 24,
                ["sources"] = {
                    13420,
                    13429,
                    13432,
                    13433,
                    13435,
                },
            },
        },
        {
            ["holiday"] = 141,
            ["id"] = 17201,
            ["name"] = {
                ["Chinese"] = "食谱：蛋奶酒",
                ["English"] = "Recipe: Egg Nog",
                ["French"] = "Recette : Lait de poule",
                ["German"] = "Rezept: Eierflip",
                ["Korean"] = "조리법: 에그노그",
                ["Mexican"] = "Receta: ponche de huevo",
                ["Portuguese"] = "Receita: Gemada",
                ["Russian"] = "Рецепт: гоголь-моголь",
                ["Spanish"] = "Receta: ponche de huevo",
                ["Taiwanese"] = "食譜：蛋奶酒",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 240,
                ["sources"] = {
                    13420,
                    13429,
                    13432,
                    13433,
                    13435,
                },
            },
        },
        {
            ["id"] = 18046,
            ["name"] = {
                ["Chinese"] = "食谱：嫩狼肉排",
                ["English"] = "Recipe: Tender Wolf Steak",
                ["French"] = "Recette : Steak de loup tendre",
                ["German"] = "Rezept: Zartes Wolfsteak",
                ["Korean"] = "조리법: 연한 늑대 스테이크",
                ["Mexican"] = "Receta: chuleta de lobo tierno",
                ["Portuguese"] = "Receita: Filé Macio de Lobo",
                ["Russian"] = "Рецепт: сочный стейк из волчатины",
                ["Spanish"] = "Receta: chuleta de lobo tierno",
                ["Taiwanese"] = "食譜：嫩狼肉排",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 12000,
                ["sources"] = {
                    4782,
                    7733,
                    8125,
                },
            },
        },
        {
            ["id"] = 18160,
            ["name"] = {
                ["Chinese"] = "食谱：菊花茶",
                ["English"] = "Recipe: Thistle Tea",
                ["French"] = "Recette : Thé de chardon",
                ["German"] = "Rezept: Disteltee",
                ["Korean"] = "조리법: 엉겅퀴 차",
                ["Mexican"] = "Receta: té de cardo",
                ["Portuguese"] = "Receita: Chá de Cardo",
                ["Russian"] = "Рецепт: артишоковый чай",
                ["Spanish"] = "Receta: té de cardo",
                ["Taiwanese"] = "食譜：菊花茶",
            },
            ["quality"] = "uncommon",
            ["quests"] = {
                2359,
                2478,
            },
            ["vendors"] = {
                ["price"] = 200,
                ["sources"] = {
                    6779,
                },
            },
        },
        {
            ["drops"] = {
                ["sources"] = {
                    14354,
                },
            },
            ["id"] = 18267,
            ["name"] = {
                ["Chinese"] = "食谱：洛恩塔姆薯块",
                ["English"] = "Recipe: Runn Tum Tuber Surprise",
                ["French"] = "Recette : Courante-surprise",
                ["German"] = "Rezept: Runn Tum Knolle Surprise",
                ["Korean"] = "조리법: 룬툼 줄기 별미",
                ["Mexican"] = "Receta: sorpresa de tubérculo runtún",
                ["Portuguese"] = "Receita: Escondidinho de Batata Rataplã",
                ["Russian"] = "Рецепт: десерт из корня Рун-Тум",
                ["Spanish"] = "Receta: sorpresa de tubérculo runtún",
                ["Taiwanese"] = "食譜：洛恩塔姆薯塊",
            },
            ["quality"] = "uncommon",
        },
        {
            ["id"] = 20075,
            ["name"] = {
                ["Chinese"] = "食谱：鳄鱼炖肉",
                ["English"] = "Recipe: Heavy Crocolisk Stew",
                ["French"] = "Recette : Ragoût épais de crocilisque",
                ["German"] = "Rezept: Schwerer Krokiliskeneintopf",
                ["Korean"] = "조리법: 푸짐한 악어 스튜",
                ["Mexican"] = "Receta: estofado de crocolisco pesado",
                ["Portuguese"] = "Receita: Ensopado Grosso de Crocolisco",
                ["Russian"] = "Рецепт: сытная похлебка из кроколиска",
                ["Spanish"] = "Receta: estofado de crocolisco pesado",
                ["Taiwanese"] = "食譜：鱷魚燉肉",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 2000,
                ["sources"] = {
                    4879,
                },
            },
        },
        {
            ["id"] = 21025,
            ["name"] = {
                ["Chinese"] = "食谱：迪尔格的超美味奇美拉肉片",
                ["English"] = "Recipe: Dirge's Kickin' Chimaerok Chops",
                ["French"] = "Recette : Pyro-côtelettes de chimaerok à la Dirge",
                ["German"] = "Rezept: Dirges abgefahrene Chimaerokkoteletts",
                ["Korean"] = "조리법: 더지의 기똥찬 키메로크 찹스테이크",
                ["Mexican"] = "Receta: fabulosas chuletillas de quimerok de Dirge",
                ["Portuguese"] = "Receita: Costeletas Sinistronas de Quiméroco do Funesto",
                ["Russian"] = "Рецепт: отпадные химеровые отбивные Могиля",
                ["Spanish"] = "Receta: pinchos quimerok potentes de Dirge",
                ["Taiwanese"] = "食譜：迪爾格的超美味奇美拉肉片",
            },
            ["quality"] = "epic",
            ["quests"] = {
                8586,
            },
        },
        {
            ["id"] = 21099,
            ["name"] = {
                ["Chinese"] = "食谱：烤鼠尾鱼",
                ["English"] = "Recipe: Smoked Sagefish",
                ["French"] = "Recette : Sagerelle fumée",
                ["German"] = "Rezept: Geräucherter Weisenfisch",
                ["Korean"] = "조리법: 훈제 총명어",
                ["Mexican"] = "Receta: sabiola ahumada",
                ["Portuguese"] = "Receita: Sabichão Defumado",
                ["Russian"] = "Рецепт: копченый шалфокунь",
                ["Spanish"] = "Receta: sabiola ahumada",
                ["Taiwanese"] = "食譜：烤鼠尾魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 500,
                ["sources"] = {
                    2381,
                    2397,
                    2664,
                    3027,
                    3085,
                    3400,
                    4223,
                    4265,
                    4553,
                    5160,
                    5483,
                    8307,
                    12033,
                    14738,
                },
            },
        },
        {
            ["id"] = 21219,
            ["name"] = {
                ["Chinese"] = "食谱：美味鼠尾鱼",
                ["English"] = "Recipe: Sagefish Delight",
                ["French"] = "Recette : Délice de sagerelle",
                ["German"] = "Rezept: Weisenfisch Supreme",
                ["Korean"] = "조리법: 총명어 별미",
                ["Mexican"] = "Receta: delicia de sabiola",
                ["Portuguese"] = "Receita: Delícia de Sabichão",
                ["Russian"] = "Рецепт: деликатес из шалфокуня",
                ["Spanish"] = "Receta: delicia de sabiolas",
                ["Taiwanese"] = "食譜：美味鼠尾魚",
            },
            ["quality"] = "common",
            ["vendors"] = {
                ["price"] = 5000,
                ["sources"] = {
                    2381,
                    2397,
                    2664,
                    3027,
                    3085,
                    3400,
                    4223,
                    4265,
                    4553,
                    5160,
                    5483,
                    8307,
                    12033,
                    14738,
                },
            },
        },
    }
