TRADE_SKILLS_DATA["levels"]["Cooking"] =
    {
        {
            ["id"] = 2550,
            ["max_skill"] = 75,
            ["min_skill"] = 0,
            ["min_xp_level"] = 1,
            ["name"] = {
                ["Chinese"] = "烹饪 (初级)",
                ["English"] = "Cooking (Apprentice)",
                ["French"] = "Cuisine (Apprenti)",
                ["German"] = "Kochkunst (Lehrling)",
                ["Korean"] = "요리 (초급)",
                ["Mexican"] = "Cocina (Aprendiz)",
                ["Portuguese"] = "Culinária (Aprendiz)",
                ["Russian"] = "Кулинария (Ученик)",
                ["Spanish"] = "Cocina (Aprendiz)",
                ["Taiwanese"] = "烹飪 (學徒)",
            },
            ["rank"] = 1,
            ["trainers"] = {
                ["price"] = 100,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 3102,
            ["max_skill"] = 150,
            ["min_skill"] = 50,
            ["min_xp_level"] = 1,
            ["name"] = {
                ["Chinese"] = "烹饪 (中级)",
                ["English"] = "Cooking (Journeyman)",
                ["French"] = "Cuisine (Compagnon)",
                ["German"] = "Kochkunst (Geselle)",
                ["Korean"] = "요리 (수습)",
                ["Mexican"] = "Cocina (Oficial)",
                ["Portuguese"] = "Culinária (Profissional)",
                ["Russian"] = "Кулинария (Подмастерье)",
                ["Spanish"] = "Cocina (Oficial)",
                ["Taiwanese"] = "烹飪 (熟練工)",
            },
            ["rank"] = 2,
            ["trainers"] = {
                ["price"] = 500,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 3413,
            ["items"] = {
                16072,
            },
            ["max_skill"] = 225,
            ["min_skill"] = 125,
            ["min_xp_level"] = 1,
            ["name"] = {
                ["Chinese"] = "烹饪 (高级)",
                ["English"] = "Cooking (Expert)",
                ["French"] = "Cuisine (Expert)",
                ["German"] = "Kochkunst (Experte)",
                ["Korean"] = "요리 (숙련)",
                ["Mexican"] = "Cocina (Experto)",
                ["Portuguese"] = "Culinária (Perito)",
                ["Russian"] = "Кулинария (Умелец)",
                ["Spanish"] = "Cocina (Experto)",
                ["Taiwanese"] = "烹飪 (專家)",
            },
            ["rank"] = 3,
        },
        {
            ["id"] = 18260,
            ["max_skill"] = 300,
            ["min_skill"] = 225,
            ["min_xp_level"] = 35,
            ["name"] = {
                ["Chinese"] = "烹饪 (大师级)",
                ["English"] = "Cooking (Artisan)",
                ["French"] = "Cuisine (Artisan)",
                ["German"] = "Kochkunst (Fachmann)",
                ["Korean"] = "요리 (전문)",
                ["Mexican"] = "Cocina (Artesano)",
                ["Portuguese"] = "Culinária (Artifice)",
                ["Russian"] = "Кулинария (Мастеровой)",
                ["Spanish"] = "Cocina (Artesano)",
                ["Taiwanese"] = "烹飪 (大工匠)",
            },
            ["quests"] = {
                6610,
            },
            ["rank"] = 4,
        },
    }
