TRADE_SKILLS_DATA["skills"]["Cooking"] =
    {
        {
            ["id"] = 2538,
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "烧烤狼肉",
                ["English"] = "Charred Wolf Meat",
                ["French"] = "Viande de loup grillée",
                ["German"] = "Verkohltes Wolfsfleisch",
                ["Korean"] = "까맣게 탄 늑대 고기",
                ["Mexican"] = "Carne de lobo carbonizada",
                ["Portuguese"] = "Carne Tostada de Lobo",
                ["Russian"] = "Рецепт волчатины на углях",
                ["Spanish"] = "Carne de lobo carbonizada",
                ["Taiwanese"] = "燒烤狼肉",
            },
            ["special_action"] = "auto learned",
        },
        {
            ["id"] = 2539,
            ["min_skill"] = 10,
            ["name"] = {
                ["Chinese"] = "香辣狼肉",
                ["English"] = "Spiced Wolf Meat",
                ["French"] = "Viande de loup épicée",
                ["German"] = "Gewürztes Wolfsfleisch",
                ["Korean"] = "늑대 양념 구이",
                ["Mexican"] = "Carne de lobo especiada",
                ["Portuguese"] = "Carne Temperada de Lobo",
                ["Russian"] = "Рецепт волчатины с пряностями",
                ["Spanish"] = "Carne de lobo picante",
                ["Taiwanese"] = "香辣狼肉",
            },
            ["trainers"] = {
                ["price"] = 50,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 2540,
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "烤野猪肉",
                ["English"] = "Roasted Boar Meat",
                ["French"] = "Viande de sanglier rôtie",
                ["German"] = "Geröstetes Eberfleisch",
                ["Korean"] = "멧돼지 숯불구이",
                ["Mexican"] = "Carne de jabalí asada",
                ["Portuguese"] = "Carne Assada de Porco",
                ["Russian"] = "Рецепт жареной кабанятины",
                ["Spanish"] = "Carne de jabalí a la brasa",
                ["Taiwanese"] = "烤野豬肉",
            },
            ["special_action"] = "auto learned",
        },
        {
            ["id"] = 2541,
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "山狗肉排",
                ["English"] = "Coyote Steak",
                ["French"] = "Steak de coyote",
                ["German"] = "Kojotensteak",
                ["Korean"] = "코요테 스테이크",
                ["Mexican"] = "Filete de coyote",
                ["Portuguese"] = "Bife de Coiote",
                ["Russian"] = "Рецепт стейка из койота",
                ["Spanish"] = "Chuleta de coyote",
                ["Taiwanese"] = "山狗肉排",
            },
            ["trainers"] = {
                ["price"] = 100,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 2542,
            ["items"] = {
                2697,
            },
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "猪肝馅饼",
                ["English"] = "Goretusk Liver Pie",
                ["French"] = "Tourte au foie de Broche-tripes",
                ["German"] = "Pastete aus Geiferzahnleber",
                ["Korean"] = "뿔엄니멧돼지 간 파이",
                ["Mexican"] = "Pastel de hígado de Dentosangre",
                ["Portuguese"] = "Empadão de Fígado de Goretusco",
                ["Russian"] = "Рецепт пирожка из печени жутеклыка",
                ["Spanish"] = "Pastel de hígado de dentosangre",
                ["Taiwanese"] = "豬肝餡餅",
            },
        },
        {
            ["id"] = 2543,
            ["items"] = {
                728,
            },
            ["min_skill"] = 75,
            ["name"] = {
                ["Chinese"] = "杂味炖肉",
                ["English"] = "Westfall Stew",
                ["French"] = "Ragoût de la marche de l'Ouest",
                ["German"] = "Westfall-Eintopf",
                ["Korean"] = "서부정통 스튜",
                ["Mexican"] = "Estofado de los Páramos de Poniente",
                ["Portuguese"] = "Ensopado de Cerro Oeste",
                ["Russian"] = "Рецепт похлебки Западного Края",
                ["Spanish"] = "Estofado de Páramos de Poniente",
                ["Taiwanese"] = "雜味燉肉",
            },
        },
        {
            ["id"] = 2544,
            ["min_skill"] = 75,
            ["name"] = {
                ["Chinese"] = "蟹肉蛋糕",
                ["English"] = "Crab Cake",
                ["French"] = "Beignet de crabe",
                ["German"] = "Krebsküchlein",
                ["Korean"] = "게살 케이크",
                ["Mexican"] = "Pastel de cangrejo",
                ["Portuguese"] = "Bolinho de Caranguejo",
                ["Russian"] = "Рецепт пирожка с мясом краба",
                ["Spanish"] = "Pastel de cangrejo",
                ["Taiwanese"] = "蟹肉蛋糕",
            },
            ["trainers"] = {
                ["price"] = 200,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 2545,
            ["items"] = {
                2698,
            },
            ["min_skill"] = 85,
            ["name"] = {
                ["Chinese"] = "煮蟹爪",
                ["English"] = "Cooked Crab Claw",
                ["French"] = "Pince de crabe farcie",
                ["German"] = "Gekochte Krebsschere",
                ["Korean"] = "집게발 요리",
                ["Mexican"] = "Pinza de cangrejo cocida",
                ["Portuguese"] = "Pinça de Caranguejo Cozida",
                ["Russian"] = "Рецепт вареной клешни краба",
                ["Spanish"] = "Tenaza de cangrejo cocinada",
                ["Taiwanese"] = "煮蟹爪",
            },
        },
        {
            ["id"] = 2546,
            ["min_skill"] = 80,
            ["name"] = {
                ["Chinese"] = "猪肉干",
                ["English"] = "Dry Pork Ribs",
                ["French"] = "Côtes de porc séchées",
                ["German"] = "Trockene Schweinerippchen",
                ["Korean"] = "말린 돼지 갈비",
                ["Mexican"] = "Costillas de cerdo secas",
                ["Portuguese"] = "Costelinhas Suínas Ressecadas",
                ["Russian"] = "Рецепт сушеных свиных ребрышек",
                ["Spanish"] = "Costillas de cerdo secas",
                ["Taiwanese"] = "豬肉乾",
            },
            ["trainers"] = {
                ["price"] = 150,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 2547,
            ["items"] = {
                2699,
            },
            ["min_skill"] = 100,
            ["name"] = {
                ["Chinese"] = "赤脊山炖肉",
                ["English"] = "Redridge Goulash",
                ["French"] = "Goulash des Carmines",
                ["German"] = "Rotkammgulasch",
                ["Korean"] = "붉은마루산 굴라시 스튜",
                ["Mexican"] = "Estofado Crestagrana",
                ["Portuguese"] = "Gulache de Cristarrubra",
                ["Russian"] = "Рецепт гуляша по-красногорски",
                ["Spanish"] = "Estofado de Crestagrana",
                ["Taiwanese"] = "赤脊山燉肉",
            },
        },
        {
            ["id"] = 2548,
            ["items"] = {
                2700,
            },
            ["min_skill"] = 110,
            ["name"] = {
                ["Chinese"] = "多汁猪排",
                ["English"] = "Succulent Pork Ribs",
                ["French"] = "Côtes de porc aux herbes",
                ["German"] = "Saftige Schweinerippchen",
                ["Korean"] = "육즙이 많은 돼지 갈비",
                ["Mexican"] = "Costillas de cerdo suculentas",
                ["Portuguese"] = "Costelinhas Suínas Suculentas",
                ["Russian"] = "Рецепт сочных свиных ребрышек",
                ["Spanish"] = "Costilletas de cerdo suculentas",
                ["Taiwanese"] = "多汁豬排",
            },
        },
        {
            ["id"] = 2549,
            ["items"] = {
                2701,
            },
            ["min_skill"] = 100,
            ["name"] = {
                ["Chinese"] = "干烤狼肉串",
                ["English"] = "Seasoned Wolf Kabob",
                ["French"] = "Kébab de loup assaisonné",
                ["German"] = "Gewürzter Wolfskebab",
                ["Korean"] = "양념 늑대 케밥",
                ["Mexican"] = "Kebab de lobo sazonado",
                ["Portuguese"] = "Kebab Temperado de Lobo",
                ["Russian"] = "Рецепт приправленной котлеты из волчатины",
                ["Spanish"] = "Kebab de lobo sazonado",
                ["Taiwanese"] = "乾烤狼肉串",
            },
        },
        {
            ["id"] = 2795,
            ["items"] = {
                2889,
            },
            ["min_skill"] = 25,
            ["name"] = {
                ["Chinese"] = "啤酒烤猪排",
                ["English"] = "Beer Basted Boar Ribs",
                ["French"] = "Côtes de sanglier à la bière",
                ["German"] = "Eberrippchen in Biersauce",
                ["Korean"] = "맥주로 양념한 멧돼지 갈비",
                ["Mexican"] = "Costillas de jabalí a la cerveza",
                ["Portuguese"] = "Costelinhas de Javali na Cerveja",
                ["Russian"] = "Кабаньи ребрышки в пиве",
                ["Spanish"] = "Costillas de jabalí rociadas con cerveza",
                ["Taiwanese"] = "啤酒烤豬排",
            },
        },
        {
            ["id"] = 3370,
            ["items"] = {
                3678,
            },
            ["min_skill"] = 80,
            ["name"] = {
                ["Chinese"] = "鳄鱼肉排",
                ["English"] = "Crocolisk Steak",
                ["French"] = "Steak de crocilisque",
                ["German"] = "Krokiliskensteak",
                ["Korean"] = "악어 스테이크",
                ["Mexican"] = "Filete de crocolisco",
                ["Portuguese"] = "Bife de Crocolisco",
                ["Russian"] = "Рецепт стейка из кроколиска",
                ["Spanish"] = "Filete de crocolisco",
                ["Taiwanese"] = "鱷魚肉排",
            },
        },
        {
            ["id"] = 3371,
            ["items"] = {
                3679,
            },
            ["min_skill"] = 60,
            ["name"] = {
                ["Chinese"] = "血肠",
                ["English"] = "Blood Sausage",
                ["French"] = "Boudin",
                ["German"] = "Blutwurst",
                ["Korean"] = "선지 소시지",
                ["Mexican"] = "Morcilla",
                ["Portuguese"] = "Chouriço",
                ["Russian"] = "Рецепт кровяной колбасы",
                ["Spanish"] = "Salchicha de sangre",
                ["Taiwanese"] = "血腸",
            },
        },
        {
            ["id"] = 3372,
            ["items"] = {
                3680,
            },
            ["min_skill"] = 90,
            ["name"] = {
                ["Chinese"] = "鱼人鳍汤",
                ["English"] = "Murloc Fin Soup",
                ["French"] = "Soupe aux ailerons de murloc",
                ["German"] = "Murlocflossensuppe",
                ["Korean"] = "멀록 지느러미 수프",
                ["Mexican"] = "Sopa de aleta de múrloc",
                ["Portuguese"] = "Sopa de Barbatana de Murloc",
                ["Russian"] = "Рецепт супа из плавников морлока",
                ["Spanish"] = "Sopa de aleta de múrloc",
                ["Taiwanese"] = "魚人鰭湯",
            },
        },
        {
            ["id"] = 3373,
            ["items"] = {
                3681,
            },
            ["min_skill"] = 120,
            ["name"] = {
                ["Chinese"] = "鳄鱼浓汤",
                ["English"] = "Crocolisk Gumbo",
                ["French"] = "Gombo de crocilisque",
                ["German"] = "Krokiliskengumbo",
                ["Korean"] = "악어 검보 스튜",
                ["Mexican"] = "Potaje de crocolisco",
                ["Portuguese"] = "Bobó de Crocolisco",
                ["Russian"] = "Рецепт супа из кроколиска",
                ["Spanish"] = "Sopa de crocolisco",
                ["Taiwanese"] = "鱷魚濃湯",
            },
        },
        {
            ["id"] = 3376,
            ["items"] = {
                3682,
            },
            ["min_skill"] = 130,
            ["name"] = {
                ["Chinese"] = "美味煎蛋卷",
                ["English"] = "Curiously Tasty Omelet",
                ["French"] = "Omelette au goût étrange",
                ["German"] = "Seltsam schmeckendes Omelett",
                ["Korean"] = "진기한 맛의 오믈렛",
                ["Mexican"] = "Tortilla con un sabor curioso",
                ["Portuguese"] = "Omelete Curiosamente Saboroso",
                ["Russian"] = "Рецепт невероятно вкусного омлета",
                ["Spanish"] = "Omelet curiosamente sabroso",
                ["Taiwanese"] = "美味煎蛋捲",
            },
        },
        {
            ["id"] = 3377,
            ["items"] = {
                3683,
            },
            ["min_skill"] = 110,
            ["name"] = {
                ["Chinese"] = "蜘蛛蛋糕",
                ["English"] = "Gooey Spider Cake",
                ["French"] = "Tourte d'araignée fondante",
                ["German"] = "Klebriger Spinnenkuchen",
                ["Korean"] = "쫄깃쫄깃한 거미 케이크",
                ["Mexican"] = "Pastel de araña pegajosa",
                ["Portuguese"] = "Bolo de Aranha Pegajoso",
                ["Russian"] = "Рецепт пирожка из паучатины",
                ["Spanish"] = "Pastel pegajoso de araña",
                ["Taiwanese"] = "蜘蛛蛋糕",
            },
        },
        {
            ["id"] = 3397,
            ["items"] = {
                3734,
            },
            ["min_skill"] = 110,
            ["name"] = {
                ["Chinese"] = "大块的熊排",
                ["English"] = "Big Bear Steak",
                ["French"] = "Steak de grand ours",
                ["German"] = "Großes Bärensteak",
                ["Korean"] = "큰 곰 스테이크",
                ["Mexican"] = "Chuleta de oso grande",
                ["Portuguese"] = "Filé de Ursão",
                ["Russian"] = "Рецепт стейка из мяса большого медведя",
                ["Spanish"] = "Chuleta grande de oso",
                ["Taiwanese"] = "大塊的熊排",
            },
        },
        {
            ["id"] = 3398,
            ["items"] = {
                3735,
            },
            ["min_skill"] = 125,
            ["name"] = {
                ["Chinese"] = "烤狮排",
                ["English"] = "Hot Lion Chops",
                ["French"] = "Côtelettes de lion épicées",
                ["German"] = "Scharfe Löwenkoteletts",
                ["Korean"] = "매운 사자 고기",
                ["Mexican"] = "Chuletillas de león picantes",
                ["Portuguese"] = "Costeletas Picantes de Leão",
                ["Russian"] = "Рецепт острой отбивной из львятины",
                ["Spanish"] = "Pinchos de león cocidas",
                ["Taiwanese"] = "烤獅排",
            },
        },
        {
            ["id"] = 3399,
            ["items"] = {
                3736,
            },
            ["min_skill"] = 150,
            ["name"] = {
                ["Chinese"] = "香烤狮肉",
                ["English"] = "Tasty Lion Steak",
                ["French"] = "Délicieux steak de lion",
                ["German"] = "Schmackhaftes Löwensteak",
                ["Korean"] = "맛있는 사자 스테이크",
                ["Mexican"] = "Filete de león sabroso",
                ["Portuguese"] = "Bife Saboroso de Leão",
                ["Russian"] = "Рецепт стейка из львятины",
                ["Spanish"] = "Chuletón de león suculento",
                ["Taiwanese"] = "香烤獅肉",
            },
        },
        {
            ["id"] = 3400,
            ["items"] = {
                3737,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "海龟汤",
                ["English"] = "Soothing Turtle Bisque",
                ["French"] = "Bisque de tortue apaisante",
                ["German"] = "Milde Schildkrötensuppe",
                ["Korean"] = "독특한 거북이 비스크",
                ["Mexican"] = "Sopa de tortuga reconfortante",
                ["Portuguese"] = "Caldo Reconfortante de Tartaruga",
                ["Russian"] = "Рецепт нежного черепахового супа",
                ["Spanish"] = "Sopa balsámica de tortuga",
                ["Taiwanese"] = "海龜湯",
            },
        },
        {
            ["id"] = 4094,
            ["items"] = {
                4609,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "烧烤秃鹰翅膀",
                ["English"] = "Barbecued Buzzard Wing",
                ["French"] = "Aile de busard grillée",
                ["German"] = "Gegrillter Bussardflügel",
                ["Korean"] = "대머리수리 날개 구이",
                ["Mexican"] = "Ala de águila ratonera a la parrilla",
                ["Portuguese"] = "Asa de Urubu Grelhada",
                ["Russian"] = "Рецепт жареного крыла канюка",
                ["Spanish"] = "Alas de águila ratonera a la parrilla",
                ["Taiwanese"] = "燒烤禿鷹翅膀",
            },
        },
        {
            ["id"] = 6412,
            ["items"] = {
                5482,
            },
            ["min_skill"] = 10,
            ["name"] = {
                ["Chinese"] = "卡多雷蜘蛛烤肉",
                ["English"] = "Kaldorei Spider Kabob",
                ["French"] = "Kébab d'araignée kaldorei",
                ["German"] = "Kaldorei-Spinnenkebab",
                ["Korean"] = "나이트 엘프 거미 케밥",
                ["Mexican"] = "Kebab de araña kaldorei",
                ["Portuguese"] = "Kebab Kaldorei de Aranha",
                ["Russian"] = "Рецепт кальдорейского шашлыка из паука",
                ["Spanish"] = "Kebab de araña Kaldorei",
                ["Taiwanese"] = "卡多雷蜘蛛烤肉",
            },
        },
        {
            ["id"] = 6413,
            ["items"] = {
                5483,
            },
            ["min_skill"] = 20,
            ["name"] = {
                ["Chinese"] = "蝎肉大餐",
                ["English"] = "Scorpid Surprise",
                ["French"] = "Surprise du scorpide",
                ["German"] = "Skorpid Surprise",
                ["Korean"] = "전갈 별미",
                ["Mexican"] = "Sorpresa de escórpido",
                ["Portuguese"] = "Escondidinho de Escorpídeo",
                ["Russian"] = "Рецепт десерта из скорпида",
                ["Spanish"] = "Sorpresa de escórpido",
                ["Taiwanese"] = "蠍肉大餐",
            },
        },
        {
            ["id"] = 6414,
            ["items"] = {
                5484,
            },
            ["min_skill"] = 35,
            ["name"] = {
                ["Chinese"] = "烤科多肉",
                ["English"] = "Roasted Kodo Meat",
                ["French"] = "Viande de kodo rôtie",
                ["German"] = "Geröstetes Kodofleisch",
                ["Korean"] = "코도 숯불구이",
                ["Mexican"] = "Carne de kodo asada",
                ["Portuguese"] = "Carne Assada de Kodo",
                ["Russian"] = "Рецепт жареного мяса кодо",
                ["Spanish"] = "Carne de kodo a la brasa",
                ["Taiwanese"] = "烤科多肉",
            },
        },
        {
            ["id"] = 6415,
            ["items"] = {
                5485,
            },
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "狂鱼肉片",
                ["English"] = "Fillet of Frenzy",
                ["French"] = "Filet de furie",
                ["German"] = "Frenzyfilet",
                ["Korean"] = "프렌지 휠레",
                ["Mexican"] = "Filete de pez furia",
                ["Portuguese"] = "Filé de Farnesim",
                ["Russian"] = "Рецепт филе бешенки",
                ["Spanish"] = "Filete de merluza",
                ["Taiwanese"] = "狂魚肉片",
            },
        },
        {
            ["id"] = 6416,
            ["items"] = {
                5486,
            },
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "炖陆行鸟",
                ["English"] = "Strider Stew",
                ["French"] = "Brouet de trotteur",
                ["German"] = "Schreitereintopf",
                ["Korean"] = "타조 스튜",
                ["Mexican"] = "Estofado de zancudo",
                ["Portuguese"] = "Ensopado de Moa",
                ["Russian"] = "Рецепт похлебки из долгонога",
                ["Spanish"] = "Estofado de zancudo",
                ["Taiwanese"] = "燉陸行鳥",
            },
        },
        {
            ["id"] = 6417,
            ["items"] = {
                5487,
            },
            ["min_skill"] = 90,
            ["name"] = {
                ["Chinese"] = "掘地鼠炖肉",
                ["English"] = "Dig Rat Stew",
                ["French"] = "Brouet de rat",
                ["German"] = "Grubenratteneintopf",
                ["Korean"] = "들쥐 스튜",
                ["Mexican"] = "Estofado de ratas de madriguera",
                ["Portuguese"] = "Ensopado de Ratoupeira",
                ["Russian"] = "Рецепт похлебки из пещерной крысы",
                ["Spanish"] = "Estofado de ratas de excavación",
                ["Taiwanese"] = "掘地鼠燉肉",
            },
        },
        {
            ["id"] = 6418,
            ["items"] = {
                5488,
            },
            ["min_skill"] = 100,
            ["name"] = {
                ["Chinese"] = "脆炸蜥蜴尾",
                ["English"] = "Crispy Lizard Tail",
                ["French"] = "Queue de lézard croquante",
                ["German"] = "Knuspriger Donnerechsenschwanz",
                ["Korean"] = "바삭바삭한 도마뱀 꼬리",
                ["Mexican"] = "Cola de lagarto crujiente",
                ["Portuguese"] = "Rabo de Lagarto Crocante",
                ["Russian"] = "Рецепт хрустящего хвоста ящерицы",
                ["Spanish"] = "Cola crocante de lagarto",
                ["Taiwanese"] = "脆炸蜥蜴尾",
            },
        },
        {
            ["id"] = 6419,
            ["items"] = {
                5489,
            },
            ["min_skill"] = 110,
            ["name"] = {
                ["Chinese"] = "瘦鹿肉",
                ["English"] = "Lean Venison",
                ["French"] = "Venaison dégraissée",
                ["German"] = "Mageres Wildbret",
                ["Korean"] = "사슴 살코기 구이",
                ["Mexican"] = "Venado magro",
                ["Portuguese"] = "Carne Magra de Caça",
                ["Russian"] = "Рецепт постной оленины",
                ["Spanish"] = "Venison magro",
                ["Taiwanese"] = "瘦鹿肉",
            },
        },
        {
            ["id"] = 6499,
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "水煮蚌肉",
                ["English"] = "Boiled Clams",
                ["French"] = "Palourdes bouillies",
                ["German"] = "Gekochte Muscheln",
                ["Korean"] = "삶은 조개",
                ["Mexican"] = "Almejas hervidas",
                ["Portuguese"] = "Mariscos Fervidos",
                ["Russian"] = "Рецепт отварных мидий",
                ["Spanish"] = "Almejas hervidas",
                ["Taiwanese"] = "水煮蚌肉",
            },
            ["trainers"] = {
                ["price"] = 100,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 6500,
            ["min_skill"] = 125,
            ["name"] = {
                ["Chinese"] = "地精芥末蘸蚌肉",
                ["English"] = "Goblin Deviled Clams",
                ["French"] = "Palourdes gobelines",
                ["German"] = "Scharfe Muscheln nach Goblin-Art",
                ["Korean"] = "고블린식 매운 조개 요리",
                ["Mexican"] = "Almejas picantes a la goblin",
                ["Portuguese"] = "Marisco à la Goblin",
                ["Russian"] = "Рецепт мидий по-гоблински",
                ["Spanish"] = "Almejas purificadas a la goblin",
                ["Taiwanese"] = "哥布林芥末蘸蚌肉",
            },
            ["trainers"] = {
                ["price"] = 300,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 6501,
            ["items"] = {
                5528,
            },
            ["min_skill"] = 90,
            ["name"] = {
                ["Chinese"] = "杂烩蚌肉",
                ["English"] = "Clam Chowder",
                ["French"] = "Soupe de palourdes",
                ["German"] = "Muschelsuppe",
                ["Korean"] = "조개 수프",
                ["Mexican"] = "Sopa de almejas",
                ["Portuguese"] = "Ensopado de Marisco",
                ["Russian"] = "Рецепт похлебки из моллюсков",
                ["Spanish"] = "Guiso de almejas",
                ["Taiwanese"] = "雜燴蚌肉",
            },
        },
        {
            ["id"] = 7213,
            ["items"] = {
                6039,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "烧烤巨蚌",
                ["English"] = "Giant Clam Scorcho",
                ["French"] = "Ardeur de palourde géante",
                ["German"] = "Riesenmuschelrisotto",
                ["Korean"] = "대합 구이",
                ["Mexican"] = "Almeja gigante a la brasa",
                ["Portuguese"] = "Torresmo de Marisco Gigante",
                ["Russian"] = "Рецепт гигантского жареного моллюска",
                ["Spanish"] = "Almeja gigante a la brasa",
                ["Taiwanese"] = "燒烤巨蚌",
            },
        },
        {
            ["id"] = 7751,
            ["items"] = {
                6325,
            },
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "美味小鱼",
                ["English"] = "Brilliant Smallfish",
                ["French"] = "Goujon brillant",
                ["German"] = "Glänzender Kleinfisch",
                ["Korean"] = "비단잉어 구이",
                ["Mexican"] = "Pececito luminoso",
                ["Portuguese"] = "Peixinho Brilhante",
                ["Russian"] = "Рецепт блестящей рыбки",
                ["Spanish"] = "Pececito brillante",
                ["Taiwanese"] = "美味小魚",
            },
        },
        {
            ["id"] = 7752,
            ["items"] = {
                6326,
            },
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "滑皮鲭鱼",
                ["English"] = "Slitherskin Mackerel",
                ["French"] = "Maquereau ombré",
                ["German"] = "Glitschhautmakrele",
                ["Korean"] = "줄무늬고등어 구이",
                ["Mexican"] = "Caballa de piel escurridiza",
                ["Portuguese"] = "Cavala Deslizapele",
                ["Russian"] = "Рецепт скользкой скумбрии",
                ["Spanish"] = "Caba de piel deslizante",
                ["Taiwanese"] = "滑皮鯖魚",
            },
        },
        {
            ["id"] = 7753,
            ["items"] = {
                6328,
            },
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "长嘴泥鳅",
                ["English"] = "Longjaw Mud Snapper",
                ["French"] = "Lutjan à longue mâchoire",
                ["German"] = "Langzahniger Matschschnapper",
                ["Korean"] = "긴주둥이진흙퉁돔 구이",
                ["Mexican"] = "Pargo de lodo boquilargo",
                ["Portuguese"] = "Pargo-da-lama Bocalonga",
                ["Russian"] = "Рецепт илистого луциана",
                ["Spanish"] = "Faucelarga muerdebarros",
                ["Taiwanese"] = "長嘴泥鰍",
            },
        },
        {
            ["id"] = 7754,
            ["items"] = {
                6329,
            },
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "洛克湖狂鱼",
                ["English"] = "Loch Frenzy Delight",
                ["French"] = "Délice de furie du loch",
                ["German"] = "Lochfrenzy Supreme",
                ["Korean"] = "호수프렌지 별미",
                ["Mexican"] = "Delicia de furia del Loch Modan",
                ["Portuguese"] = "Delícia de Farnesim Lacustre",
                ["Russian"] = "Рецепт деликатеса из бешенки",
                ["Spanish"] = "Delicia de merluza del Loch",
                ["Taiwanese"] = "洛克湖狂魚",
            },
        },
        {
            ["id"] = 7755,
            ["items"] = {
                6330,
            },
            ["min_skill"] = 100,
            ["name"] = {
                ["Chinese"] = "刺须鲶鱼",
                ["English"] = "Bristle Whisker Catfish",
                ["French"] = "Poisson-chat moustachu",
                ["German"] = "Stoppelfühlerwels",
                ["Korean"] = "표범메기 구이",
                ["Mexican"] = "Siluro mostacherizo",
                ["Portuguese"] = "Bagre de Suíças Cerdosas",
                ["Russian"] = "Рецепт зубатки ощетиненной",
                ["Spanish"] = "Siluro mostacherizo",
                ["Taiwanese"] = "刺鬚鯰魚",
            },
        },
        {
            ["id"] = 7827,
            ["items"] = {
                6368,
            },
            ["min_skill"] = 50,
            ["name"] = {
                ["Chinese"] = "彩鳍鱼",
                ["English"] = "Rainbow Fin Albacore",
                ["French"] = "Thon arc-en-ciel",
                ["German"] = "Regenbogenflossenthunfisch",
                ["Korean"] = "무지개날개다랑어 구이",
                ["Mexican"] = "Atún blanco arco iris",
                ["Portuguese"] = "Albacora Arco-íris",
                ["Russian"] = "Рецепт радужного тунца",
                ["Spanish"] = "Atún blanco arcoiris",
                ["Taiwanese"] = "彩鰭魚",
            },
        },
        {
            ["id"] = 7828,
            ["items"] = {
                6369,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "石鳞鳕鱼",
                ["English"] = "Rockscale Cod",
                ["French"] = "Morue rochécaille",
                ["German"] = "Steinschuppenkabeljau",
                ["Korean"] = "돌비늘대구 구이",
                ["Mexican"] = "Bacalao piedrescama",
                ["Portuguese"] = "Bacalhau Escama-de-pedra",
                ["Russian"] = "Рецепт каменношкурой трески",
                ["Spanish"] = "Bacalao de escamas de piedra",
                ["Taiwanese"] = "石鱗鱈魚",
            },
        },
        {
            ["id"] = 8238,
            ["items"] = {
                6661,
            },
            ["min_skill"] = 85,
            ["name"] = {
                ["Chinese"] = "美味风蛇",
                ["English"] = "Savory Deviate Delight",
                ["French"] = "Délice de déviant",
                ["German"] = "Pikantes Deviat-Supreme",
                ["Korean"] = "돌연변이 물고기 별미",
                ["Mexican"] = "Delicia de pez descarriado sabrosa",
                ["Portuguese"] = "Delícia de Peixe Anormal",
                ["Russian"] = "Рецепт необычного десерта с чабером",
                ["Spanish"] = "Delicia sobrosa retorcida",
                ["Taiwanese"] = "美味風蛇",
            },
        },
        {
            ["id"] = 8604,
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "草药烘蛋",
                ["English"] = "Herb Baked Egg",
                ["French"] = "Oeufs aux herbes",
                ["German"] = "Kräutergebackenes Ei",
                ["Korean"] = "알 약초구이",
                ["Mexican"] = "Huevo a las finas hierbas",
                ["Portuguese"] = "Ovo Assado com Ervas",
                ["Russian"] = "Рецепт яйца с травами",
                ["Spanish"] = "Huevo cocido con hierbas",
                ["Taiwanese"] = "草藥烘蛋",
            },
            ["special_action"] = "auto learned",
        },
        {
            ["id"] = 8607,
            ["items"] = {
                6892,
            },
            ["min_skill"] = 40,
            ["name"] = {
                ["Chinese"] = "熏熊肉",
                ["English"] = "Smoked Bear Meat",
                ["French"] = "Viande d'ours fumée",
                ["German"] = "Geräuchertes Bärenfleisch",
                ["Korean"] = "곰고기 숯불구이",
                ["Mexican"] = "Carne de oso ahumada",
                ["Portuguese"] = "Carne de Urso Defumada",
                ["Russian"] = "Рецепт копченой медвежатины",
                ["Spanish"] = "Carne de oso",
                ["Taiwanese"] = "燻熊肉",
            },
        },
        {
            ["classes"] = {
                "rogue",
            },
            ["id"] = 9513,
            ["items"] = {
                18160,
            },
            ["min_skill"] = 60,
            ["name"] = {
                ["Chinese"] = "菊花茶",
                ["English"] = "Thistle Tea",
                ["French"] = "Thé de chardon",
                ["German"] = "Disteltee",
                ["Korean"] = "엉겅퀴 차",
                ["Mexican"] = "Té de cardo",
                ["Portuguese"] = "Chá de Cardo",
                ["Russian"] = "Рецепт артишокового чая",
                ["Spanish"] = "Te de cardo",
                ["Taiwanese"] = "菊花茶",
            },
        },
        {
            ["id"] = 13028,
            ["min_skill"] = 125,
            ["name"] = {
                ["Chinese"] = "金棘茶",
                ["English"] = "Goldthorn Tea",
                ["French"] = "Thé de dorépine",
                ["German"] = "Golddorntee",
                ["Korean"] = "황금가시 차",
                ["Mexican"] = "Té de espina de oro",
                ["Portuguese"] = "Chá de Espinheira-dourada",
                ["Russian"] = "Рецепт чая из златошипа",
                ["Spanish"] = "Té espina de oro",
                ["Taiwanese"] = "金棘茶",
            },
            ["trainers"] = {
                ["price"] = 0,
                ["sources"] = {
                    8696,
                },
            },
        },
        {
            ["id"] = 15853,
            ["items"] = {
                12227,
            },
            ["min_skill"] = 125,
            ["name"] = {
                ["Chinese"] = "瘦狼排",
                ["English"] = "Lean Wolf Steak",
                ["French"] = "Steak de loup",
                ["German"] = "Mageres Wolfsteak",
                ["Korean"] = "늑대 살코기 스테이크",
                ["Mexican"] = "Filete de lobo magro",
                ["Portuguese"] = "Filé de Lobo Magro",
                ["Russian"] = "Рецепт постного стейка из волчатины",
                ["Spanish"] = "Filete de lobo magro",
                ["Taiwanese"] = "瘦狼排",
            },
        },
        {
            ["id"] = 15855,
            ["items"] = {
                12228,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "烤迅猛龙肉",
                ["English"] = "Roast Raptor",
                ["French"] = "Rôti de raptor",
                ["German"] = "Gerösteter Raptor",
                ["Korean"] = "랩터 숯불구이",
                ["Mexican"] = "Raptor asado",
                ["Portuguese"] = "Raptor Assado",
                ["Russian"] = "Рецепт жареного ящера",
                ["Spanish"] = "Raptor a la brasa",
                ["Taiwanese"] = "烤迅猛龍肉",
            },
        },
        {
            ["id"] = 15856,
            ["items"] = {
                12229,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "热狼排",
                ["English"] = "Hot Wolf Ribs",
                ["French"] = "Côtes de loup épicées",
                ["German"] = "Scharfe Wolfrippchen",
                ["Korean"] = "늑대 양념 갈비",
                ["Mexican"] = "Costillas de lobo picantes",
                ["Portuguese"] = "Costelinhas Picantes de Lobo",
                ["Russian"] = "Рецепт острой волчьей грудинки",
                ["Spanish"] = "Costillas de lobo cocidas",
                ["Taiwanese"] = "熱狼排",
            },
        },
        {
            ["id"] = 15861,
            ["items"] = {
                12231,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "丛林大杂烩",
                ["English"] = "Jungle Stew",
                ["French"] = "Ragoût de la jungle",
                ["German"] = "Dschungeleintopf",
                ["Korean"] = "밀림 스튜",
                ["Mexican"] = "Estofado de la selva",
                ["Portuguese"] = "Ensopado da Selva",
                ["Russian"] = "Рецепт похлебки \"Джунгли\"",
                ["Spanish"] = "Estofado de la selva",
                ["Taiwanese"] = "叢林大雜燴",
            },
        },
        {
            ["id"] = 15863,
            ["items"] = {
                12232,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "腐肉大餐",
                ["English"] = "Carrion Surprise",
                ["French"] = "Tourte surprise",
                ["German"] = "Aas Surprise",
                ["Korean"] = "고기말이 별미",
                ["Mexican"] = "Sorpresa de carroña",
                ["Portuguese"] = "Escondidinho de Carniceiro",
                ["Russian"] = "Рецепт десерта из мертвечины",
                ["Spanish"] = "Sorpresa de carroña",
                ["Taiwanese"] = "腐肉大餐",
            },
        },
        {
            ["id"] = 15865,
            ["items"] = {
                12233,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "神秘杂烩",
                ["English"] = "Mystery Stew",
                ["French"] = "Ragoût mystère",
                ["German"] = "Eigenartiger Eintopf",
                ["Korean"] = "신비의 스튜",
                ["Mexican"] = "Estofado misterioso",
                ["Portuguese"] = "Ensopado Misterioso",
                ["Russian"] = "Рецепт загадочной похлебки",
                ["Spanish"] = "Guisado misterioso",
                ["Taiwanese"] = "神秘雜燴",
            },
        },
        {
            ["id"] = 15906,
            ["items"] = {
                12239,
            },
            ["min_skill"] = 200,
            ["name"] = {
                ["Chinese"] = "龙息红椒",
                ["English"] = "Dragonbreath Chili",
                ["French"] = "Chili de souffle de dragon",
                ["German"] = "Drachenodemchili",
                ["Korean"] = "용숨결 칠리",
                ["Mexican"] = "Ají aliento de dragón",
                ["Portuguese"] = "Chili Bafo de Dragão",
                ["Russian"] = "Рецепт мяса в соусе \"Дыхание дракона\"",
                ["Spanish"] = "Chili de aliento de dragón",
                ["Taiwanese"] = "龍息紅椒",
            },
        },
        {
            ["id"] = 15910,
            ["items"] = {
                12240,
            },
            ["min_skill"] = 200,
            ["name"] = {
                ["Chinese"] = "科多肉杂烩",
                ["English"] = "Heavy Kodo Stew",
                ["French"] = "Ragoût épais de kodo",
                ["German"] = "Schwerer Kodoeintopf",
                ["Korean"] = "코도 고기 스튜",
                ["Mexican"] = "Estofado de kodo pesado",
                ["Portuguese"] = "Ensopado Grosso de Kodo",
                ["Russian"] = "Сытная похлебка из кодо",
                ["Spanish"] = "Estofado pesado de kodo",
                ["Taiwanese"] = "科多肉雜燴",
            },
        },
        {
            ["id"] = 15915,
            ["items"] = {
                16111,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "辣椒蟹肉",
                ["English"] = "Spiced Chili Crab",
                ["French"] = "Chili de crabe épicé",
                ["German"] = "Gewürzter Chilikrebs",
                ["Korean"] = "매콤한 칠리 크랩",
                ["Mexican"] = "Chili de cangrejo especiado",
                ["Portuguese"] = "Chili Temperado de Caranguejo",
                ["Russian"] = "Рецепт краба под соусом чили",
                ["Spanish"] = "cangrejo al chili picante",
                ["Taiwanese"] = "辣椒蟹肉",
            },
        },
        {
            ["id"] = 15933,
            ["items"] = {
                16110,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "超级煎蛋卷",
                ["English"] = "Monster Omelet",
                ["French"] = "Omelette monstrueuse",
                ["German"] = "Monsteromelett",
                ["Korean"] = "괴물 오믈렛",
                ["Mexican"] = "Tortilla gigante",
                ["Portuguese"] = "Omelete Monstro",
                ["Russian"] = "Рецепт омлета с монстрятиной",
                ["Spanish"] = "Mezcolanza de mosntruo",
                ["Taiwanese"] = "超級煎蛋捲",
            },
        },
        {
            ["id"] = 15935,
            ["items"] = {
                12226,
            },
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "香脆蝙蝠翅",
                ["English"] = "Crispy Bat Wing",
                ["French"] = "Aile de chauve-souris croustillante",
                ["German"] = "Knuspriger Fledermausflügel",
                ["Korean"] = "바삭바삭한 박쥐 날개",
                ["Mexican"] = "Ala de murciélago crujiente",
                ["Portuguese"] = "Asa de Morcego Crocante",
                ["Russian"] = "Рецепт хрустящего крылышка летучей мыши",
                ["Spanish"] = "Ala crocante de murciélago",
                ["Taiwanese"] = "香脆蝙蝠翅",
            },
        },
        {
            ["id"] = 18238,
            ["items"] = {
                13939,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "斑点黄尾鱼",
                ["English"] = "Spotted Yellowtail",
                ["French"] = "Jaune-queue tacheté",
                ["German"] = "Tüpfelgelbschwanz",
                ["Korean"] = "점박이놀래기 구이",
                ["Mexican"] = "Serviola moteada",
                ["Portuguese"] = "Rabo-amarelo Mosqueado",
                ["Russian"] = "Рецепт пятнистого желтохвоста",
                ["Spanish"] = "Serviola moteada",
                ["Taiwanese"] = "斑點黃尾魚",
            },
        },
        {
            ["id"] = 18239,
            ["items"] = {
                13940,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "煮熟的光滑大鱼",
                ["English"] = "Cooked Glossy Mightfish",
                ["French"] = "Barracuda luisant cuit",
                ["German"] = "Gekochter glänzender Machtfisch",
                ["Korean"] = "빛깔좋은 망둥어 요리",
                ["Mexican"] = "Vigorpez lustroso cocido",
                ["Portuguese"] = "Parrudo Lustroso Cozido",
                ["Russian"] = "Рецепт мощь-рыбы в кляре",
                ["Spanish"] = "Vigorpez brilloso cocinado",
                ["Taiwanese"] = "煮熟的光滑大魚",
            },
        },
        {
            ["id"] = 18240,
            ["items"] = {
                13942,
            },
            ["min_skill"] = 240,
            ["name"] = {
                ["Chinese"] = "烤鱿鱼",
                ["English"] = "Grilled Squid",
                ["French"] = "Calmar grillé",
                ["German"] = "Gegrillter Kalmar",
                ["Korean"] = "오징어 구이",
                ["Mexican"] = "Calamar a la parrilla",
                ["Portuguese"] = "Lula Grelhada",
                ["Russian"] = "Рецепт жареного кальмара",
                ["Spanish"] = "Calamar asado",
                ["Taiwanese"] = "烤魷魚",
            },
        },
        {
            ["id"] = 18241,
            ["items"] = {
                13941,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "油炸红腮鱼",
                ["English"] = "Filet of Redgill",
                ["French"] = "Filet de rouget",
                ["German"] = "Rotkiemenfilet",
                ["Korean"] = "붉은퉁돔 통구이",
                ["Mexican"] = "Filete de branquirrojo",
                ["Portuguese"] = "Filé de Vermelhão",
                ["Russian"] = "Рецепт филе красноперки",
                ["Spanish"] = "Filete de Agallarroja",
                ["Taiwanese"] = "油炸紅腮魚",
            },
        },
        {
            ["id"] = 18242,
            ["items"] = {
                13943,
            },
            ["min_skill"] = 240,
            ["name"] = {
                ["Chinese"] = "烟熏鲈鱼",
                ["English"] = "Hot Smoked Bass",
                ["French"] = "Perche fumée",
                ["German"] = "Scharfer geräucherter Barsch",
                ["Korean"] = "농어 훈제",
                ["Mexican"] = "Lubina ahumada picante",
                ["Portuguese"] = "Robalo Defumado Picante",
                ["Russian"] = "Рецепт окуня горячего копчения",
                ["Spanish"] = "Perca ahumada",
                ["Taiwanese"] = "煙燻鱸魚",
            },
        },
        {
            ["id"] = 18243,
            ["items"] = {
                13945,
            },
            ["min_skill"] = 250,
            ["name"] = {
                ["Chinese"] = "夜鳞鱼汤",
                ["English"] = "Nightfin Soup",
                ["French"] = "Soupe de lutjan nagenuit",
                ["German"] = "Nachtflossensuppe",
                ["Korean"] = "밤비늘퉁돔 수프",
                ["Mexican"] = "Sopa de pargo nocturno",
                ["Portuguese"] = "Sopa de Pinoturno",
                ["Russian"] = "Рецепт супа из ночницы",
                ["Spanish"] = "Sopa de aletoche",
                ["Taiwanese"] = "夜鱗魚湯",
            },
        },
        {
            ["id"] = 18244,
            ["items"] = {
                13946,
            },
            ["min_skill"] = 250,
            ["name"] = {
                ["Chinese"] = "水煮阳鳞鲑鱼",
                ["English"] = "Poached Sunscale Salmon",
                ["French"] = "Saumon solécaille poché",
                ["German"] = "Gedünsteter Sonnenschuppenlachs",
                ["Korean"] = "삶은 해비늘연어",
                ["Mexican"] = "Salmón Solescama pochado",
                ["Portuguese"] = "Salmão Helióscamo Poché",
                ["Russian"] = "Рецепт вареного радужного лосося",
                ["Spanish"] = "Salmón solescamas salvaje",
                ["Taiwanese"] = "水煮陽鱗鮭魚",
            },
        },
        {
            ["id"] = 18245,
            ["items"] = {
                13947,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "炖龙虾",
                ["English"] = "Lobster Stew",
                ["French"] = "Ragoût de homard",
                ["German"] = "Hummereintopf",
                ["Korean"] = "랍스터 스튜",
                ["Mexican"] = "Estofado de langosta",
                ["Portuguese"] = "Ensopado de Lagosta",
                ["Russian"] = "Рецепт похлебки из омаров",
                ["Spanish"] = "Estofado de langosta",
                ["Taiwanese"] = "燉龍蝦",
            },
        },
        {
            ["id"] = 18246,
            ["items"] = {
                13948,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "大鱼片",
                ["English"] = "Mightfish Steak",
                ["French"] = "Steak de barracuda",
                ["German"] = "Machtfischsteak",
                ["Korean"] = "망둥어 스테이크",
                ["Mexican"] = "Filete de vigorpez",
                ["Portuguese"] = "Filé de Parrudo",
                ["Russian"] = "Рецепт стейка из мощь-рыбы",
                ["Spanish"] = "Filete de vigorpez",
                ["Taiwanese"] = "大魚片",
            },
        },
        {
            ["id"] = 18247,
            ["items"] = {
                13949,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "烤鲑鱼",
                ["English"] = "Baked Salmon",
                ["French"] = "Pain de saumon",
                ["German"] = "Gebackener Lachs",
                ["Korean"] = "훈제 연어",
                ["Mexican"] = "Salmón al horno",
                ["Portuguese"] = "Salmão Assado",
                ["Russian"] = "Рецепт запеченного лосося",
                ["Spanish"] = "Salmón al horno",
                ["Taiwanese"] = "烤鮭魚",
            },
        },
        {
            ["id"] = 20626,
            ["items"] = {
                16767,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "安德麦蚌肉杂烩",
                ["English"] = "Undermine Clam Chowder",
                ["French"] = "Soupe de palourdes d'Undermine",
                ["German"] = "Undermine-Muschelsuppe",
                ["Korean"] = "지하광산 조개 수프",
                ["Mexican"] = "Sopa de almejas de Minahonda",
                ["Portuguese"] = "Ensopado de Marisco Inframina",
                ["Russian"] = "Рецепт шахтерской похлебки из моллюсков",
                ["Spanish"] = "Sopa de almejas debilitadora",
                ["Taiwanese"] = "安德麥蚌肉雜燴",
            },
        },
        {
            ["id"] = 20916,
            ["items"] = {
                17062,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "银头鲑鱼",
                ["English"] = "Mithril Headed Trout",
                ["French"] = "Truite tête-mithril",
                ["German"] = "Mithrilkopfforelle",
                ["Korean"] = "미스릴송어 구이",
                ["Mexican"] = "Trucha cabeza de mitril",
                ["Portuguese"] = "Truta Cabeça-de-mithril",
                ["Russian"] = "Рецепт мифрилоголовой форели",
                ["Spanish"] = "Trucha cabeza de mitril",
                ["Taiwanese"] = "銀頭鮭魚",
            },
        },
        {
            ["id"] = 21143,
            ["items"] = {
                17200,
            },
            ["min_skill"] = 1,
            ["name"] = {
                ["Chinese"] = "姜饼",
                ["English"] = "Gingerbread Cookie",
                ["French"] = "Biscuit au pain d'épices",
                ["German"] = "Lebkuchen",
                ["Korean"] = "생강 과자빵",
                ["Mexican"] = "Galleta de jengibre",
                ["Portuguese"] = "Biscoito de Gengibre",
                ["Russian"] = "Рецепт имбирного пряника",
                ["Spanish"] = "Galleta de jengibre",
                ["Taiwanese"] = "薑餅",
            },
        },
        {
            ["id"] = 21144,
            ["items"] = {
                17201,
            },
            ["min_skill"] = 35,
            ["name"] = {
                ["Chinese"] = "蛋奶酒",
                ["English"] = "Egg Nog",
                ["French"] = "Lait de poule",
                ["German"] = "Eierflip",
                ["Korean"] = "에그노그",
                ["Mexican"] = "Ponche de huevo",
                ["Portuguese"] = "Gemada",
                ["Russian"] = "Рецепт гоголя-моголя",
                ["Spanish"] = "Huevo cocido",
                ["Taiwanese"] = "蛋奶酒",
            },
        },
        {
            ["id"] = 21175,
            ["min_skill"] = 200,
            ["name"] = {
                ["Chinese"] = "蜘蛛肉肠",
                ["English"] = "Spider Sausage",
                ["French"] = "Saucisse d'araignée",
                ["German"] = "Spinnenwurst",
                ["Korean"] = "거미 소시지",
                ["Mexican"] = "Salchicha de araña",
                ["Portuguese"] = "Linguiça de Aranha",
                ["Russian"] = "Рецепт паучьей колбаски",
                ["Spanish"] = "Salchicha de araña",
                ["Taiwanese"] = "蜘蛛肉腸",
            },
            ["trainers"] = {
                ["price"] = 4000,
                ["sources"] = {
                    1355,
                    1382,
                    1430,
                    1699,
                    3026,
                    3067,
                    3087,
                    3399,
                    4210,
                    4552,
                    5159,
                    5482,
                    6286,
                    8306,
                },
            },
        },
        {
            ["id"] = 22480,
            ["items"] = {
                18046,
            },
            ["min_skill"] = 225,
            ["name"] = {
                ["Chinese"] = "嫩狼肉排",
                ["English"] = "Tender Wolf Steak",
                ["French"] = "Steak de loup tendre",
                ["German"] = "Zartes Wolfsteak",
                ["Korean"] = "연한 늑대 스테이크",
                ["Mexican"] = "Chuleta de lobo tierno",
                ["Portuguese"] = "Filé Macio de Lobo",
                ["Russian"] = "Рецепт сочного стейка из волчатины",
                ["Spanish"] = "Chuletón de lobo tierno",
                ["Taiwanese"] = "嫩狼肉排",
            },
        },
        {
            ["id"] = 22761,
            ["items"] = {
                18267,
            },
            ["min_skill"] = 275,
            ["name"] = {
                ["Chinese"] = "洛恩塔姆薯块",
                ["English"] = "Runn Tum Tuber Surprise",
                ["French"] = "Courante-surprise",
                ["German"] = "Runn Tum Knolle Surprise",
                ["Korean"] = "룬툼 줄기 별미",
                ["Mexican"] = "Sorpresa de tubérculo runtún",
                ["Portuguese"] = "Escondidinho de Batata Rataplã",
                ["Russian"] = "Рецепт десерта из корня Рун-Тум",
                ["Spanish"] = "Sorpresa de tubérculo Runn Tum",
                ["Taiwanese"] = "洛恩塔姆薯塊",
            },
        },
        {
            ["id"] = 24418,
            ["items"] = {
                20075,
            },
            ["min_skill"] = 150,
            ["name"] = {
                ["Chinese"] = "鳄鱼炖肉",
                ["English"] = "Heavy Crocolisk Stew",
                ["French"] = "Ragoût épais de crocilisque",
                ["German"] = "Schwerer Krokiliskeneintopf",
                ["Korean"] = "푸짐한 악어 스튜",
                ["Mexican"] = "Estofado de crocolisco pesado",
                ["Portuguese"] = "Ensopado Grosso de Crocolisco",
                ["Russian"] = "Рецепт сытной похлебки из кроколиска",
                ["Spanish"] = "Guiso de crocolisco",
                ["Taiwanese"] = "鱷魚燉肉",
            },
        },
        {
            ["id"] = 24801,
            ["min_skill"] = 285,
            ["name"] = {
                ["Chinese"] = "沙漠肉丸子",
                ["English"] = "Smoked Desert Dumplings",
                ["French"] = "Boulettes fumées du désert",
                ["German"] = "Geräucherte Wüstenknödel",
                ["Korean"] = "훈제 사막 경단",
                ["Mexican"] = "Albóndigas del desierto ahumadas",
                ["Portuguese"] = "Bolinhos Defumados do Deserto",
                ["Russian"] = "Рецепт копченых пустынных клецок",
                ["Spanish"] = "Torrijas al horno del desierto",
                ["Taiwanese"] = "沙漠肉丸子",
            },
            ["quests"] = {
                8313,
            },
        },
        {
            ["id"] = 25659,
            ["items"] = {
                21025,
            },
            ["min_skill"] = 300,
            ["name"] = {
                ["Chinese"] = "迪尔格的超美味奇美拉肉片",
                ["English"] = "Dirge's Kickin' Chimaerok Chops",
                ["French"] = "Pyro-côtelettes de chimaerok à la Dirge",
                ["German"] = "Dirges abgefahrene Chimearokkoteletts",
                ["Korean"] = "더지의 기똥찬 키메로크 찹스테이크",
                ["Mexican"] = "Fabulosas chuletillas de quimerok de Dirge",
                ["Portuguese"] = "Costeletas Sinistronas de Quiméroco do Funesto",
                ["Russian"] = "Рецепт отпадных химеровых отбивных Дирга",
                ["Spanish"] = "Fabulosas chuletas quiméricas de Cantofúnebre",
                ["Taiwanese"] = "迪爾格的超美味奇美拉肉片",
            },
        },
        {
            ["id"] = 25704,
            ["items"] = {
                21099,
            },
            ["min_skill"] = 80,
            ["name"] = {
                ["Chinese"] = "烤鼠尾鱼",
                ["English"] = "Smoked Sagefish",
                ["French"] = "Sagerelle fumée",
                ["German"] = "Geräucherter Weisenfisch",
                ["Korean"] = "훈제 총명어",
                ["Mexican"] = "Sabiola ahumada",
                ["Portuguese"] = "Sabichão Defumado",
                ["Russian"] = "Рецепт копченого шалфокуня",
                ["Spanish"] = "Sabiola ahumada",
                ["Taiwanese"] = "烤鼠尾魚",
            },
        },
        {
            ["id"] = 25954,
            ["items"] = {
                21219,
            },
            ["min_skill"] = 175,
            ["name"] = {
                ["Chinese"] = "美味鼠尾鱼",
                ["English"] = "Sagefish Delight",
                ["French"] = "Délice de sagerelle",
                ["German"] = "Weisenfisch Supreme",
                ["Korean"] = "총명어 별미",
                ["Mexican"] = "Delicia de sabiola",
                ["Portuguese"] = "Delícia de Sabichão",
                ["Russian"] = "Рецепт деликатесного шалфокуня",
                ["Spanish"] = "Delicia de sabiola",
                ["Taiwanese"] = "美味鼠尾魚",
            },
        },
    }
