TRADE_SKILLS_DATA["levels"]["Tailoring"] =
    {
        {
            ["id"] = 3908,
            ["max_skill"] = 75,
            ["min_skill"] = 0,
            ["min_xp_level"] = 5,
            ["name"] = {
                ["Chinese"] = "裁缝 (初级)",
                ["English"] = "Tailoring (Apprentice)",
                ["French"] = "Couture (Apprenti)",
                ["German"] = "Schneiderei (Lehrling)",
                ["Korean"] = "재봉술 (초급)",
                ["Mexican"] = "Costura (Aprendiz)",
                ["Portuguese"] = "Alfaiataria (Aprendiz)",
                ["Russian"] = "Портняжное дело (Ученик)",
                ["Spanish"] = "Sastrería (Aprendiz)",
                ["Taiwanese"] = "裁縫 (學徒)",
            },
            ["phase"] = 1,
            ["rank"] = 1,
            ["trainers"] = {
                ["price"] = 10,
                ["sources"] = {
                    1103,
                    1300,
                    1703,
                    2855,
                    3484,
                    3523,
                    4193,
                    11048,
                    11050,
                    11051,
                },
            },
        },
        {
            ["id"] = 3909,
            ["max_skill"] = 150,
            ["min_skill"] = 50,
            ["min_xp_level"] = 10,
            ["name"] = {
                ["Chinese"] = "裁缝 (中级)",
                ["English"] = "Tailoring (Journeyman)",
                ["French"] = "Couture (Compagnon)",
                ["German"] = "Schneiderei (Geselle)",
                ["Korean"] = "재봉술 (수습)",
                ["Mexican"] = "Costura (Oficial)",
                ["Portuguese"] = "Alfaiataria (Profissional)",
                ["Russian"] = "Портняжное дело (Подмастерье)",
                ["Spanish"] = "Sastrería (Oficial)",
                ["Taiwanese"] = "裁縫 (熟練工)",
            },
            ["phase"] = 1,
            ["rank"] = 2,
            ["trainers"] = {
                ["price"] = 500,
                ["sources"] = {
                    2627,
                    3004,
                    3363,
                    3704,
                    4159,
                    5153,
                    5567,
                    11049,
                },
            },
        },
        {
            ["id"] = 3910,
            ["max_skill"] = 225,
            ["min_skill"] = 125,
            ["min_xp_level"] = 20,
            ["name"] = {
                ["Chinese"] = "裁缝 (高级)",
                ["English"] = "Tailoring (Expert)",
                ["French"] = "Couture (Expert)",
                ["German"] = "Schneiderei (Experte)",
                ["Korean"] = "재봉술 (숙련)",
                ["Mexican"] = "Costura (Experto)",
                ["Portuguese"] = "Alfaiataria (Perito)",
                ["Russian"] = "Портняжное дело (Умелец)",
                ["Spanish"] = "Sastrería (Experto)",
                ["Taiwanese"] = "裁縫 (專家)",
            },
            ["phase"] = 1,
            ["rank"] = 3,
            ["trainers"] = {
                ["price"] = 5000,
                ["sources"] = {
                    1346,
                    4576,
                },
            },
        },
        {
            ["id"] = 12180,
            ["max_skill"] = 300,
            ["min_skill"] = 200,
            ["min_xp_level"] = 35,
            ["name"] = {
                ["Chinese"] = "裁缝 (大师级)",
                ["English"] = "Tailoring (Artisan)",
                ["French"] = "Couture (Artisan)",
                ["German"] = "Schneiderei (Fachmann)",
                ["Korean"] = "재봉술 (전문)",
                ["Mexican"] = "Costura (Artesano)",
                ["Portuguese"] = "Alfaiataria (Artifice)",
                ["Russian"] = "Портняжное дело (Мастеровой)",
                ["Spanish"] = "Sastrería (Artesano)",
                ["Taiwanese"] = "裁縫 (大工匠)",
            },
            ["phase"] = 1,
            ["rank"] = 4,
            ["trainers"] = {
                ["price"] = 50000,
                ["sources"] = {
                    2399,
                    11052,
                    11557,
                },
            },
        },
    }
